Repository Homebrew/homebrew-core, pull requests merged in 2018-05, with the labels that each got.

#27318 pmd 6.3.0
  Formula/pmd.rb
Labels: java

#26731 travis.yml: generate `brew info` JSON.
  .travis.yml
Labels: in progress

#24474 Adding new formula nifi-registry for Apache NiFi Registry 0.1.0
  Formula/nifi-registry.rb
Labels: new formula, ready to merge

#28313 avian: coexist with JDK 9
  Formula/avian.rb
Labels: java

#28314 drip: require Java 8 specifically
  Formula/drip.rb
Labels: java

#28315 aws-apigateway-importer: require Java 8 specifically
  Formula/aws-apigateway-importer.rb
Labels: java

#28316 gssh: require Java 8 specifically
  Formula/gssh.rb
Labels: java

#28317 henplus: require Java 8 exactly
  Formula/henplus.rb
Labels: java

#28318 hexgui: require Java 8 exactly
  Formula/hexgui.rb
Labels: java

#28319 lcm: require Java 8 specifically
  Formula/lcm.rb
Labels: java

#28320 mysql-cluster: require Java 8 specifically
  Formula/mysql-cluster.rb
Labels: java

#28321 pillar: use Java 8 specifically
  Formula/pillar.rb
Labels: java

#28322 voldemort: use Java 8 specifically
  Formula/voldemort.rb
Labels: java

#28323 wartremover: use Java 8 specifically
  Formula/wartremover.rb
Labels: java

#28248 taskell 1.2.5 (new formula)
  Formula/taskell.rb
Labels: haskell, new formula

#27756 circleci 0.0.4705-deba4df (new formula)
  Formula/circleci.rb
Labels: new formula

#28342 apache-flink 1.5.0
  Formula/apache-flink.rb
Labels: java

#28500 darcs: depend on ghc at build time
  Formula/darcs.rb
Labels: audit failure
