Repository Homebrew/homebrew-core, pull requests merged in 2018-09, with the labels that each got.

#31822 'source-hightlight' needs C++11.
  Formula/source-highlight.rb
Labels: 10.7

#31844 `graphite2` needs C++11.
  Formula/graphite2.rb
Labels: 10.7

#31845 cmake: Fix for macOS Lion
  Formula/cmake.rb
Labels: 10.7, build failure

#31816 Make curl compile with Lion.
  Formula/curl.rb
Labels: 10.7

#32096 vfuse 2.0.6 (new formula)
  Formula/vfuse.rb
Labels: new formula

#32266 wine: no devel or head on High Sierra and Mojave
  Formula/wine.rb
Labels: maintainer feedback, xcode10

#32399 Grakn 1.4.0 Revision 1 - updating the SHA to match the re-uploaded zip
  Formula/grakn.rb
Labels: checksum mismatch

#32416 submarine: delete
  Formula/submarine.rb
Labels: marked for removal/rejection

#32524 redis@2.8: delete
  Formula/redis@2.8.rb
  formula_renames.json
Labels: maintainer feedback, marked for removal/rejection

#32553 bundletool 0.6.0 (new formula)
  Formula/bundletool.rb
Labels: new formula
