Repository Homebrew/homebrew-core, pull requests merged in 2018-10, with the labels that each got.

#30366 stanford-corenlp 3.9.1 (new formula)
  Formula/stanford-corenlp.rb
Labels: new formula

#31891 makensis: pass compiler as SCons arguments
  Formula/makensis.rb
Labels: almost there

#32565 qt@5.5: delete
  Aliases/qt@5.11
  Formula/qt@5.5.rb
  formula_renames.json
Labels: marked for removal/rejection

#32763 solr 6.6.5
  Formula/solr@6.6.rb
Labels: legacy, new formula

#33179 datomic: remove as not open source.
  Formula/datomic.rb
Labels: marked for removal/rejection

#33278 corebird: delete
  Formula/corebird.rb
Labels: marked for removal/rejection

#33382 Influxdb 1.6.4
  Formula/influxdb.rb
Labels: checksum mismatch

#32396 logstash: move config files into etc
  Formula/logstash.rb
Labels: ready to merge
