Repository Homebrew/homebrew-core, pull requests merged in 2019-09, with the labels that each got.

#42727 nudoku: switch to head do block
  Formula/nudoku.rb
Labels: ready to merge

#43838 sbt 1.3.0
  Formula/sbt.rb
Labels: ready to merge

#43826 presto 0.225
  Formula/presto.rb
Labels: ready to merge

#42892 kontena: delete
  Formula/kontena.rb
Labels: marked for removal/rejection

#43097 Formula taisei should be a Cask
  Formula/taisei.rb
Labels: marked for removal/rejection

#43530 pgbouncer fixes
  Formula/pgbouncer.rb
Labels: ready to merge

#44303 exult: remove link from caveats
  Formula/exult.rb
Labels: ready to merge

#44581 Update bcel to 6.4.0
  Formula/ant.rb
Labels: upstream issue

#44713 gmp: work around Catalina bug
  Formula/gmp.rb
Labels: 10.15

#44715 gettext: fix build on Catalina
  Formula/gettext.rb
Labels: 10.15

#44711 ammonite-repl 1.7.4
  Formula/ammonite-repl.rb
Labels: ready to merge
