Repository Homebrew/homebrew-core, pull requests merged in 2019-01, with the labels that each got.

#35679 php@5.6 removal due to EOL
  Formula/php@5.6.rb
  formula_renames.json
Labels: marked for removal/rejection, php

#36051 Remove hyper.rb from Formula
  Formula/hyper.rb
Labels: marked for removal/rejection

#35914 Update desc of binutils to note missing tools
  Formula/binutils.rb
Labels: maintainer feedback

#36082 improve instructions in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: almost there

#36345 kustomize: add head
  Formula/kustomize.rb
Labels: ready to merge

#36353 Update git-quick-stats.rb
  Formula/git-quick-stats.rb
Labels: ready to merge

#35854 monero: add plist to start/stop daemon with brew services
  Formula/monero.rb
Labels: ready to merge

#36016 bundletool 0.8.0
  Formula/bundletool.rb
Labels: test failure

#36254 bash-completion@2: add info on how to support existing v1 completions
  Formula/bash-completion@2.rb
Labels: ready to merge
