Repository Homebrew/homebrew-core, pull requests merged in 2019-02, with the labels that each got.

#36752 apache-opennlp 1.9.1
  Formula/apache-opennlp.rb
Labels: ready to merge

#31532 Cassandra-reaper 1.3.0 (new formula)
  Formula/cassandra-reaper.rb
Labels: new formula, ready to merge

#36376 Update graphite2 to reference src dir in cmake
  Formula/graphite2.rb
Labels: ready to merge

#36747 phpmd 2.6.0 (new formula)
  Formula/phpmd.rb
Labels: almost there, new formula

#35994 fff 1.0 (New Formula)
  Formula/fff.rb
Labels: new formula, ready to merge

#36247 signal-cli 0.6.2 (new formula)
  Formula/signal-cli.rb
Labels: new formula

#36306 swagger2markup-cli 1.3.3 (new formula)
  Formula/swagger2markup-cli.rb
Labels: new formula, ready to merge

#36828 Deploy formulae.brew.sh changes with Actions
  .github/formulae.brew.sh.workflow
Labels: do not merge

#36965 xcodegen: Add head
  Formula/xcodegen.rb
Labels: ready to merge

#36960 Update main.workflow
  .github/formulae.brew.sh.workflow
  .github/main.workflow
  .github/main.workflow.sh
Labels: do not merge

#37057 ballerina 0.990.3
  Formula/ballerina.rb
Labels: ready to merge

#37049 allure 2.10.0
  Formula/allure.rb
Labels: test failure

#37260 bee 1.64
  Formula/bee.rb
Labels: test failure

#37365 libccd: use new option to enable double precision
  Formula/libccd.rb
Labels: ready to merge

#37371 fix mu --HEAD install
  Formula/mu.rb
Labels: ready to merge
