Repository Homebrew/homebrew-core, pull requests merged in 2019-11, with the labels that each got.

#46055 exploitdb 2019-11-01
  Formula/exploitdb.rb
Labels: ready to merge

#46099 exploitdb 2019-11-02
  Formula/exploitdb.rb
Labels: ready to merge

#46119 bdsup2sub: delete
  Formula/bdsup2sub.rb
Labels: marked for removal/rejection

#46121 aiccu: delete
  Formula/aiccu.rb
Labels: marked for removal/rejection

#46222 gmtl: delete
  Formula/gmtl.rb
Labels: marked for removal/rejection

#46338 mariadb@10.0: removed due to EOL
  Formula/mariadb@10.0.rb
  formula_renames.json
Labels: marked for removal/rejection

#46354 mysql@5.5: removed due to EOL
  Formula/mysql@5.5.rb
  formula_renames.json
Labels: marked for removal/rejection, ready to merge

#46499 dita-ot 3.4
  Formula/dita-ot.rb
Labels: ready to merge

#46539 pound: delete
  Formula/pound.rb
Labels: marked for removal/rejection

#46608 Update pygments homepage url and head url
  Formula/pygments.rb
Labels: ready to merge

#46641 embulk 0.9.20
  Formula/embulk.rb
Labels: ready to merge

#46645 dependency-check 5.2.4
  Formula/dependency-check.rb
Labels: ready to merge

#46701 paket 5.233.0
  Formula/paket.rb
Labels: ready to merge

#46693 exploitdb 2019-11-13
  Formula/exploitdb.rb
Labels: ready to merge

#46711 hana: delete
  Formula/hana.rb
Labels: marked for removal/rejection

#46660 cockroach: delete
  Formula/cockroach.rb
Labels: maintainer feedback, marked for removal/rejection, ready to merge

#46801 llvm@4: delete
  Formula/llvm@4.rb
Labels: marked for removal/rejection, ready to merge

#46875 ruby@2.0: delete
  Formula/ruby@2.0.rb
Labels: marked for removal/rejection

#46924 grib-api: delete
  Formula/grib-api.rb
Labels: marked for removal/rejection

#46876 Remove OpenSSL 1.0
  Aliases/openssl@1.0
  Formula/openssl.rb
Labels: maintainer feedback, marked for removal/rejection

#47034 Aliases: add openssl
  Aliases/openssl
Labels: maintainer feedback

#47095 eccodes: remove conflict_with deleted formula
  Formula/eccodes.rb
Labels: ready to merge

#47209 php-cs-fixer 2.16.1
  Formula/php-cs-fixer.rb
Labels: ready to merge

#47221 paket 5.238.1
  Formula/paket.rb
Labels: ready to merge

#47256 pianod: restore HTTPS
  Formula/pianod.rb
Labels: ready to merge

#47253 vert.x 3.8.4
  Formula/vert.x.rb
Labels: ready to merge

#47257 ballerina 1.0.4
  Formula/ballerina.rb
Labels: ready to merge

#47316 exploitdb 2019-11-29
  Formula/exploitdb.rb
Labels: ready to merge
