Repository Homebrew/homebrew-core, pull requests merged in 2019-06, with the labels that each got.

#39895 Fix issue with PG upgrade command when `initdb` fails
  cmd/brew-postgresql-upgrade-database.rb
Labels: maintainer feedback

#40877 paket 5.210.1
  Formula/paket.rb
Labels: CI-requeued

#40966 meson: fix detection of Xcode 11 compilers
  Formula/meson.rb
Labels: ready to merge

#41051 commandbox 4.7.0
  Formula/commandbox.rb
Labels: needs response
