Repository Homebrew/homebrew-core, pull requests merged in 2020-12, with the labels that each got.

#65917 .github/workflows/stale.yml: Don't re-run on forks.
  .github/workflows/stale.yml
Labels: CI-syntax-only, automerge-skip

#65981 phpunit 9.4.4
  Formula/phpunit.rb
Labels: bottle unneeded, php

#66001 django-completion 3.1.4
  Formula/django-completion.rb
Labels: bottle unneeded

#66000 astrometry-net: add livecheck
  Formula/astrometry-net.rb
Labels: CI-syntax-only, livecheck, python

#66008 jenkins 2.269
  Formula/jenkins.rb
Labels: bottle unneeded, java

#65861 workflows/scheduled-triage: add lock and support request actions
  .github/support.yml
  .github/workflows/scheduled-triage.yml
Labels: automerge-skip

#66023 sqlmap 1.4.12
  Formula/sqlmap.rb
Labels: bottle unneeded, deprecated license

#66035 flank: add livecheck
  Formula/flank.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck

#66050 docker-completion 19.03.14
  Formula/docker-completion.rb
Labels: bottle unneeded

#66028 workflows/scheduled-triage: update job name
  .github/workflows/scheduled-triage.yml
Labels: CI-syntax-only, automerge-skip

#66075 jenkins-lts 2.263.1
  Formula/jenkins-lts.rb
Labels: bottle unneeded, java

#66085 libtirpc 1.3.1
  Formula/libtirpc.rb
Labels: bottle unneeded, linux-only

#66078 flank 20.12.0
  Formula/flank.rb
Labels: bottle unneeded, java

#66133 kubecm: update homepage
  Formula/kubecm.rb
Labels: go

#66131 throttle contentful-cli updates
  audit_exceptions/throttled_formulae.json
Labels: automerge-skip

#66161 latex2rtf: update livecheck
  Formula/latex2rtf.rb
Labels: CI-syntax-only, livecheck

#66179 mosquitto: switch to use download page
  Formula/mosquitto.rb
Labels: CI-syntax-only, livecheck

#66229 metabase 0.37.3
  Formula/metabase.rb
Labels: bottle unneeded, java, nodejs

#66230 exploitdb 2020-12-04
  Formula/exploitdb.rb
Labels: bottle unneeded

#66245 questdb 5.0.5
  Formula/questdb.rb
Labels: bottle unneeded, java

#66247 dispatch-build-bottle.yml: add ARM PATH
  .github/workflows/dispatch-build-bottle.yml
Labels: automerge-skip

#66250 tests.yml: add ARM PATH
  .github/workflows/tests.yml
Labels: automerge-skip

#66290 tests.yml: force vendored Ruby on Catalina
  .github/workflows/tests.yml
Labels: automerge-skip

#66295 dispatch-build-bottle.yml: set HOMEBREW_CHANGE_ARCH_TO_ARM
  .github/workflows/dispatch-build-bottle.yml
Labels: automerge-skip

#66286 rustup-init: update homepage
  Formula/rustup-init.rb
Labels: CI-syntax-only, rust

#66282 exploitdb 2020-12-05
  Formula/exploitdb.rb
Labels: bottle unneeded

#66259 flyway 7.3.1
  Formula/flyway.rb
Labels: bottle unneeded, java

#66261 liquibase 4.2.1
  Formula/liquibase.rb
Labels: bottle unneeded, java

#66267 ktlint 0.40.0
  Formula/ktlint.rb
Labels: bottle unneeded, java

#66330 dog: add linux-only dependencies
  Formula/dog.rb
Labels: CI-syntax-only, linux to homebrew-core, rust

#66324 jack: add livecheck
  Formula/jack.rb
Labels: CI-syntax-only, livecheck, python

#66319 hledger: update livecheck
  Formula/hledger.rb
Labels: CI-syntax-only, haskell, livecheck

#66342 hledger: update livecheck
  Formula/hledger.rb
Labels: CI-syntax-only, haskell, livecheck

#66334 plantuml 1.2020.22
  Formula/plantuml.rb
Labels: bottle unneeded, java

#66351 cask 0.8.5
  Formula/cask.rb
Labels: bottle unneeded, license

#65444 geos fix mac os arm compile
  Formula/geos.rb
Labels: missing license, python

#66309 sdhash: disable formula
  Formula/sdhash.rb
Labels: formula disabled, missing license

#66347 md: fix build under Xcode 12
  Formula/md.rb
Labels: formula disabled, missing license

#66375 cdparanoia: add linux-only patch
  Formula/cdparanoia.rb
Labels: linux to homebrew-core, missing license

#66248 config.yml: Change reference `brew cask`
  .github/ISSUE_TEMPLATE/config.yml
Labels: automerge-skip

#66400 Revert "tests.yml: force vendored Ruby on Catalina"
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, do not merge

#66377 php-cs-fixer 2.16.8
  Formula/php-cs-fixer.rb
Labels: bottle unneeded, php

#66379 workflows/tests: fix CI-syntax-only label detection
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip

#66408 workflows/tests: don't check labels on push events
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip

#66427 cups: add linux-only dependency
  Formula/cups.rb
Labels: CI-syntax-only, linux to homebrew-core

#66439 Re-add Catalina workaround
  .github/workflows/tests.yml
Labels: automerge-skip

#66452 clojure 1.10.1.754
  Formula/clojure.rb
Labels: bottle unneeded, java, ruby

#66451 apache-flink 1.12.0
  Formula/apache-flink.rb
Labels: bottle unneeded, java

#66454 gping: add regex for livecheck
  Formula/gping.rb
Labels: CI-syntax-only, livecheck, rust

#66436 php-cs-fixer 2.17.0
  Formula/php-cs-fixer.rb
Labels: bottle unneeded, php

#66480 php-cs-fixer 2.17.1
  Formula/php-cs-fixer.rb
Labels: bottle unneeded, php

#66490 rocksdb: add linux-only changes
  Formula/rocksdb.rb
Labels: deprecated license, linux to homebrew-core

#66492 cpr: make test flags portable, align them with linux
  Formula/cpr.rb
Labels: linux to homebrew-core

#66503 jruby 9.2.14.0
  Formula/jruby.rb
Labels: bottle unneeded, java

#66431 activemq: keep linux bin files on linux
  Formula/activemq.rb
Labels: bottle unneeded, java, linux to homebrew-core

#66528 picard-tools 2.23.9
  Formula/picard-tools.rb
Labels: bottle unneeded, java

#66536 kotlin 1.4.21
  Formula/kotlin.rb
Labels: bottle unneeded, java

#66543 zlib: add head
  Formula/zlib.rb
Labels: CI-syntax-only

#66550 exploitdb 2020-12-09
  Formula/exploitdb.rb
Labels: bottle unneeded

#66563 gping: add comment before livecheck block
  Formula/gping.rb
Labels: CI-syntax-only, livecheck, rust

#66564 s3ql: add deprecation date
  Formula/s3ql.rb
Labels: CI-syntax-only, deprecated license, formula deprecated, python

#66567 sonarqube 8.6.0.39681
  Formula/sonarqube.rb
Labels: bottle unneeded, java

#66595 tcl-tk: add linux-only dependency
  Formula/tcl-tk.rb
Labels: CI-syntax-only, linux to homebrew-core

#66581 bind: disable linux caps on linux
  Formula/bind.rb
Labels: linux to homebrew-core, python

#66593 closure-compiler 20201207
  Formula/closure-compiler.rb
Labels: bottle unneeded, java

#66607 winetricks 20201206
  Formula/winetricks.rb
Labels: bottle unneeded

#66610 liquibase 4.2.2
  Formula/liquibase.rb
Labels: bottle unneeded, java

#66624 ruby-build 20201210
  Formula/ruby-build.rb
Labels: bottle unneeded

#66620 zpaq: update test file's sha
  Formula/zpaq.rb
Labels: license

#66643 lua@5.3: fix livecheck
  Formula/lua@5.3.rb
Labels: legacy

#66649 dispatch-build-bottle.yml: set HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK
  .github/workflows/dispatch-build-bottle.yml
Labels: automerge-skip

#66413 workflows/tests-linux: respect CI-syntax-only
  .github/workflows/tests-linux.yml
Labels: CI-syntax-only, automerge-skip

#66414 ladspa-sdk: add livecheck
  Formula/ladspa-sdk.rb
Labels: CI-syntax-only, bottle unneeded, linux-only, livecheck

#66659 sshtrix: add livecheck
  Formula/sshtrix.rb
Labels: CI-syntax-only, deprecated license, livecheck

#66660 lua@5.3: update livecheck regex
  Formula/lua@5.3.rb
Labels: CI-syntax-only, legacy, livecheck

#66666 cdo: add livecheck
  Formula/cdo.rb
Labels: CI-syntax-only, livecheck

#66665 kerl 2.0.2
  Formula/kerl.rb
Labels: bottle unneeded

#66667 readline: fix livecheck
  Formula/readline.rb
Labels: CI-syntax-only, livecheck

#66668 bash: fix livecheck
  Formula/bash.rb
Labels: CI-syntax-only, livecheck

#66675 puzzles: update livecheck
  Formula/puzzles.rb
Labels: CI-syntax-only, livecheck, missing license

#66676 exploitdb 2020-12-10
  Formula/exploitdb.rb
Labels: bottle unneeded

#66690 docfx 2.56.6
  Formula/docfx.rb
Labels: bottle unneeded

#66430 hardlink: add linux-only dependency
  Formula/hardlink.rb
Labels: linux to homebrew-core, missing license

#66719 exploitdb 2020-12-11
  Formula/exploitdb.rb
Labels: bottle unneeded

#66700 gcore: disable, remove dead urls
  Formula/gcore.rb
Labels: formula disabled

#65324 pike: depend on jpeg for linux
  Formula/pike.rb
Labels: linux to homebrew-core

#66771 gopls: add livecheck
  Formula/gopls.rb
Labels: CI-syntax-only, go, livecheck

#66781 open-ocd: update livecheck
  Formula/open-ocd.rb
Labels: CI-syntax-only, deprecated license, livecheck

#66782 ipv6toolkit: add livecheck
  Formula/ipv6toolkit.rb
Labels: CI-syntax-only, livecheck

#66795 phpstan 0.12.60
  Formula/phpstan.rb
Labels: bottle unneeded, php

#66797 datetime-fortran: make test flags work on both mac and linux
  Formula/datetime-fortran.rb
Labels: linux to homebrew-core

#66799 gauche: update livecheck
  Formula/gauche.rb
Labels: CI-syntax-only, livecheck, missing license

#66798 dbhash: make test work on linux
  Formula/dbhash.rb
Labels: linux to homebrew-core

#66801 depqbf: install shared library on linux too
  Formula/depqbf.rb
Labels: linux to homebrew-core

#66802 dive: add linux-only dependencies
  Formula/dive.rb
Labels: go, linux to homebrew-core

#66803 djview: split install for mac and linux, add license
  Formula/djview4.rb
Labels: linux to homebrew-core

#66806 xplanet: enable aqua only on macOS, add license
  Formula/xplanet.rb
Labels: linux to homebrew-core

#66807 glade: align formula with linux version
  Formula/glade.rb
Labels: linux to homebrew-core

#66804 gtksourceview4: align test with linux
  Formula/gtksourceview4.rb
Labels: linux to homebrew-core

#66825 wren: add livecheck
  Formula/wren.rb
Labels: CI-syntax-only, livecheck

#66842 phpstan 0.12.61
  Formula/phpstan.rb
Labels: bottle unneeded, php

#66850 phpstan 0.12.62
  Formula/phpstan.rb
Labels: bottle unneeded, php

#66865 icon: add livecheck
  Formula/icon.rb
Labels: CI-syntax-only, livecheck, missing license

#66867 mmctl: add livecheck
  Formula/mmctl.rb
Labels: CI-syntax-only, go, livecheck

#66883 vips: add livecheck
  Formula/vips.rb
Labels: CI-syntax-only, livecheck

#66884 phoronix-test-suite: add livecheck
  Formula/phoronix-test-suite.rb
Labels: CI-syntax-only, bottle unneeded, livecheck

#60732 apache-drill 1.18.0
  Formula/apache-drill.rb
Labels: CI-requeued, bottle unneeded, java, ready to merge

#66885 plantuml 1.2020.23
  Formula/plantuml.rb
Labels: bottle unneeded, java

#66876 inxi: update license
  Formula/inxi.rb
Labels: CI-syntax-only, bottle unneeded, license

#66168 python@3.9: add linux-only changes
  Formula/python@3.9.rb
Labels: linux to homebrew-core

#66911 gettext: add --with-included-gettext only on macOS
  Formula/gettext.rb
Labels: CI-syntax-only, linux to homebrew-core

#66601 ampl-mp: add linux changes
  Formula/ampl-mp.rb
Labels: audit failure, linux to homebrew-core

#66949 workflows/tests-linux: build from source.
  .github/workflows/tests-linux.yml
Labels: CI-syntax-only, automerge-skip

#66887 redsocks: disable
  Formula/redsocks.rb
Labels: CI-syntax-only, formula disabled

#66956 tests-linux.yml: do not cat non-existing file
  .github/workflows/tests-linux.yml
Labels: automerge-skip

#65300 wayland (new formula)
  .github/workflows/tests-linux.yml
  Formula/wayland.rb
Labels: automerge-skip, linux to homebrew-core, linux-only, new formula

#66994 mysql@5.6: update livecheck
  Formula/mysql@5.6.rb
Labels: CI-syntax-only, legacy, livecheck

#66995 mysql@5.7: update livecheck
  Formula/mysql@5.7.rb
Labels: CI-syntax-only, deprecated license, legacy, livecheck

#66996 mysql: update livecheck
  Formula/mysql.rb
Labels: CI-syntax-only, deprecated license, livecheck

#66997 jetty/jetty-runner: update livecheck
  Formula/jetty-runner.rb
  Formula/jetty.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck

#66983 jenkins 2.271
  Formula/jenkins.rb
Labels: bottle unneeded, java

#67005 vcprompt: add livecheck
  Formula/vcprompt.rb
Labels: CI-syntax-only, livecheck

#66961 forego: fix build with go 1.16 (HEAD)
  Formula/forego.rb
Labels: go

#66924 strace 5.10
  Formula/strace.rb
Labels: bottle unneeded, linux-only

#66941 rm-improved: update test
  Formula/rm-improved.rb
Labels: rust

#62087 libxml++: add license
  Formula/libxml++.rb
Labels: CI-syntax-only

#66982 alsa-lib 1.2.4
  Formula/alsa-lib.rb
Labels: bottle unneeded, linux-only

#67017 libaio 0.3.112
  Formula/libaio.rb
Labels: bottle unneeded, linux-only

#67028 teleport: update livecheck
  Formula/teleport.rb
Labels: CI-syntax-only, go, livecheck

#66962 krb5: add Linux-only dependency
  Formula/krb5.rb
Labels: CI-syntax-only, linux to homebrew-core

#67068 clojure 1.10.1.763
  Formula/clojure.rb
Labels: bottle unneeded, java, ruby

#67061 php-cs-fixer 2.17.2
  Formula/php-cs-fixer.rb
Labels: CI-requeued, bottle unneeded, php

#67043 deno: revert revision bump
  Formula/deno.rb
Labels: rust

#67151 carton: add livecheck
  Formula/carton.rb
Labels: CI-syntax-only, livecheck, perl

#67076 wayland-protocols (new formula)
  .github/workflows/tests-linux.yml
  Formula/wayland-protocols.rb
Labels: automerge-skip, linux to homebrew-core

#67100 flyway 7.3.2
  Formula/flyway.rb
Labels: bottle unneeded, java

#67054 dlite: disable
  Formula/dlite.rb
Labels: formula disabled, go

#66829 imgur-screenshot 2.0.0
  Formula/imgur-screenshot.rb
Labels: bottle unneeded

#67155 docker-machine-driver-xhyve: deprecate
  Formula/docker-machine-driver-xhyve.rb
Labels: formula deprecated, go

#67133 presto 0.245
  Formula/prestodb.rb
Labels: bottle unneeded, java

#67139 signal-cli 0.7.0
  Formula/signal-cli.rb
Labels: bottle unneeded, java

#67136 sbt 1.4.5
  Formula/sbt.rb
Labels: bottle unneeded, java

#67152 allure 2.13.8
  Formula/allure.rb
Labels: bottle unneeded, java

#67168 pandoc: update license
  Formula/pandoc.rb
Labels: CI-syntax-only, haskell

#67198 rtags: add livecheck
  Formula/rtags.rb
Labels: CI-syntax-only, deprecated license, livecheck

#67199 pugixml: add livecheck
  Formula/pugixml.rb
Labels: CI-syntax-only, livecheck

#67174 exploitdb 2020-12-18
  Formula/exploitdb.rb
Labels: bottle unneeded

#67225 libvnc: add livecheck
  Formula/libvnc.rb
Labels: CI-syntax-only, livecheck

#67229 texmath: correct license
  Formula/texmath.rb
Labels: CI-syntax-only, haskell, license

#67209 cython: add license
  Formula/cython.rb
Labels: CI-syntax-only, license, python
