Repository Homebrew/homebrew-core, pull requests merged in 2020-03, with the labels that each got.

#50866 php: add head
  Formula/php.rb
Labels: ready to merge

#50874 jetty 9.4.27.v20200227 version update
  Formula/jetty.rb
Labels: ready to merge

#50971 docfx 2.49
  Formula/docfx.rb
Labels: hackillinois2020

#50965 duply 2.2.2
  Formula/duply.rb
Labels: hackillinois2020

#50943 calabash 1.1.30-99
  Formula/calabash.rb
Labels: hackillinois2020

#50963 checkstyle 8.30
  Formula/checkstyle.rb
Labels: hackillinois2020

#50984 css-crush 3.0.1
  Formula/css-crush.rb
Labels: hackillinois2020

#50983 z 1.11
  Formula/z.rb
Labels: hackillinois2020

#50973 closure-compiler 20200224
  Formula/closure-compiler.rb
Labels: hackillinois2020

#50944 format-udf 1.8.0
  Formula/format-udf.rb
Labels: hackillinois2020

#50912 git-quick-stats 2.0.15
  Formula/git-quick-stats.rb
Labels: hackillinois2020, ready to merge

#51022 wiremock-standalone 2.26.2
  Formula/wiremock-standalone.rb
Labels: ready to merge

#50881 deno: document that it does not build with Python 3
  Formula/deno.rb
Labels: python

#51013 scons: use rewrite_python_shebang function
  Formula/scons.rb
Labels: python

#50828 cless: delete
  Formula/cless.rb
Labels: marked for removal/rejection

#50831 arx: delete
  Formula/arx-libertatis.rb
  Formula/arx.rb
  Formula/rnv.rb
Labels: marked for removal/rejection

#50857 wu: delete formula
  Formula/wu.rb
Labels: marked for removal/rejection

#50910 git-filter-repo 2.25.0
  Formula/git-filter-repo.rb
Labels: hackillinois2020, ready to merge

#51067 kerl 1.8.7
  Formula/kerl.rb
Labels: ready to merge

#51075 stgit: use stable release download url
  Formula/stgit.rb
Labels: checksum mismatch

#51122 cppcheck: use python@3.8 for test
  Formula/cppcheck.rb
Labels: python

#50878 rethinkdb: document that it does not build with Python 3
  Formula/rethinkdb.rb
Labels: python

#51006 PyPy development is now on Heptapod.
  Formula/pypy.rb
  Formula/pypy3.rb
Labels: ready to merge

#50936 blazegraph 2.1.5
  Formula/blazegraph.rb
Labels: hackillinois2020, ready to merge

#51310 youtube-dl 2020.03.08
  Formula/youtube-dl.rb
Labels: ready to merge

#51304 libcerf: add head
  Formula/libcerf.rb
Labels: ready to merge

#51354 upgrading to confluent-platform-5.4.1
  Formula/confluent-platform.rb
Labels: ready to merge

#51385 elasticsearch 6.8.7
  Formula/elasticsearch.rb
Labels: ready to merge

#51393 groovy 3.0.2
  Formula/groovy.rb
Labels: ready to merge

#51395 jruby 9.2.11.0
  Formula/jruby.rb
Labels: ready to merge

#51394 groovysdk 3.0.2
  Formula/groovysdk.rb
Labels: ready to merge

#51373 quex: Document that it does not work with Python 3
  Formula/quex.rb
Labels: python

#51374 unicorn: Document that it does not work with Python 3
  Formula/unicorn.rb
Labels: python

#51634 netdata: Adds missing log/netdata directory
  Formula/netdata.rb
Labels: ready to merge

#51649 fantom 1.0.74 - fix to download from GitHub
  Formula/fantom.rb
Labels: ready to merge

#50989 hapi-fhir-cli 4.2.0
  Formula/hapi-fhir-cli.rb
Labels: build failure, hackillinois2020, upstream issue

#51267 fop: fix and update hyphenation data
  Formula/fop.rb
Labels: ready to merge

#51779 pushpin: use python@3.8
  Formula/pushpin.rb
Labels: python

#51781 node-build 4.8.0
  Formula/node-build.rb
Labels: ready to merge

#50688 remove apache-zeppelin
  Formula/apache-zeppelin.rb
Labels: marked for removal/rejection, ready to merge

#51933 docfx 2.51
  Formula/docfx.rb
Labels: ready to merge

#51979 phpmyadmin 5.0.2
  Formula/phpmyadmin.rb
Labels: ready to merge

#52048 viewvc: document that package depends on Python 2
  Formula/viewvc.rb
Labels: python

#52123 exploitdb 2020-03-25
  Formula/exploitdb.rb
Labels: ready to merge

#52100 solr 8.5.0
  Aliases/solr@8.5
  Formula/solr.rb
Labels: ready to merge

#52152 workflows/tests: don't fail fast
  .github/workflows/tests.yml
Labels: ready to merge

#52157 volt: remove GOPATH, add patch for Go 1.14
  Formula/volt.rb
Labels: ready to merge

#52159 jenkins-lts 2.204.6
  Formula/jenkins-lts.rb
Labels: ready to merge

#52139 syncthing-inotify: delete
  Formula/syncthing-inotify.rb
Labels: marked for removal/rejection

#52209 openapi-generator 4.3.0
  Formula/openapi-generator.rb
Labels: ready to merge

#52273 fish: Only apply patch on non-HEAD installs
  Formula/fish.rb
Labels: ready to merge

#52242 wtf 20200326
  Formula/wtf.rb
Labels: ready to merge

#52243 bundletool 0.13.4
  Formula/bundletool.rb
Labels: ready to merge

#52313 exploitdb 2020-03-29
  Formula/exploitdb.rb
Labels: ready to merge

#52312 lsyncd: support 10.15.4+
  Formula/lsyncd.rb
Labels: ready to merge

#52369 glib: fix inreplace
  Formula/glib.rb
Labels: ready to merge

#52353 apache-geode 1.12.0
  Formula/apache-geode.rb
Labels: ready to merge

#52355 bee 1.76
  Formula/bee.rb
Labels: ready to merge
