Repository Homebrew/homebrew-core, pull requests merged in 2020-05, with the labels that each got.

#54070 libfido2: make test more robust
  Formula/libfido2.rb
Labels: ready to merge

#54195 mesa: migrate to python@3.8
  Formula/mesa.rb
Labels: python-3.8-migration

#54218 phpstan 0.12.20
  Formula/phpstan.rb
Labels: ready to merge

#54226 iso-codes: migrate to python@3.8
  Formula/iso-codes.rb
Labels: python-3.8-migration

#54242 grc: migrate to python@3.8
  Formula/grc.rb
Labels: python-3.8-migration

#53224 leakcanary-shark 2.2 (new formula)
  Formula/leakcanary-shark.rb
Labels: new formula, ready to merge

#54324 workflows: dismiss reviews if bottle publish failed
  .github/workflows/publish-commit-bottles.yml
Labels: do not merge, maintainer feedback

#54340 aurora-cli: disable
  Formula/aurora-cli.rb
Labels: marked for removal/rejection, python-3.8-migration

#54441 salt: does not support Python 3.8
  Formula/salt.rb
Labels: python-3.8-migration

#54451 gwt 2.9.0
  Formula/gwt.rb
Labels: maintainer feedback

#54736 spirv-tools: migrate to python@3.8
  Formula/spirv-tools.rb
Labels: python-3.8-migration

#54753 llnode: migrate to python@3.8
  Formula/llnode.rb
Labels: python-3.8-migration

#54771 ghc@8.8: migrate to python@3.8
  Formula/ghc@8.8.rb
Labels: python-3.8-migration

#54595 aacgain: add livecheck block
  Formula/aacgain.rb
Labels: livecheck

#54597 imap-uw: add livecheck block
  Formula/imap-uw.rb
Labels: livecheck

#54668 gradio: deprecate formula
  Formula/gradio.rb
Labels: marked for removal/rejection, python-3.8-migration

#54958 cqlkit 0.3.1 (new formula)
  Formula/cqlkit.rb
Labels: java, new formula

#55500 cake 0.38.0
  Formula/cake.rb
Labels: prerelease
