Repository Homebrew/homebrew-core, pull requests merged in 2020-06, with the labels that each got.

#55349 rethinkdb: replace download server url
  Formula/rethinkdb.rb
Labels: almost there

#55881 haskell-stack: add linux dependency and resource
  Formula/haskell-stack.rb
Labels: linux to homebrew-core

#56695 tnftp: add linux-only dependency
  Formula/tnftp.rb
Labels: linux to homebrew-core

#56697 check: gawk is a runtime dependency
  Formula/check.rb
Labels: linux to homebrew-core

#56741 tnftp: add linux-only dependency
  Formula/tnftp.rb
Labels: linux to homebrew-core

#56783 flank 20.06.2 (new formula)
  Formula/flank.rb
Labels: java, new formula, ready to merge

#56831 composer 1.10.8
  Formula/composer.rb
Labels: ready to merge

#56849 apr: apply upstream patch to fix macOS 11 compile
  Formula/apr.rb
Labels: 11.0

#56992 neo4j 4.1.0
  Formula/neo4j.rb
Labels: ready to merge

#56999 crowdin 3.1.15
  Formula/crowdin.rb
Labels: ready to merge
