Repository Homebrew/homebrew-core, pull requests merged in 2020-07, with the labels that each got.

#57429 workflows: use more Homebrew actions
  .github/workflows/publish-commit-bottles.yml
Labels: do not merge

#57425 python@3.8: add arm64 compatibility patches
  Formula/python@3.8.rb
Labels: 11.0

#57419 pcre2: Only enabled JIT on x86_64 as workaround to ARM crash.
  Formula/pcre2.rb
Labels: 11.0

#57410 pcre: Made JIT require x86_64 for now.
  Formula/pcre.rb
Labels: 11.0

#57502 libinfinity: disable
  Formula/libinfinity.rb
Labels: formula disabled

#57501 gobby: disable
  Formula/gobby.rb
Labels: formula disabled

#57315 Get GMP building on Apple Silicon
  Formula/gmp.rb
Labels: 11.0

#57557 workflows: set dispatch type to 'Publish *'
  .github/workflows/publish-commit-bottles.yml
Labels: do not merge

#57572 Patch carthage for Swift 5.3 (pre-release)
  Formula/carthage.rb
Labels: 11.0

#57494 cargo-completion: delete
  Formula/cargo-completion.rb
Labels: marked for removal/rejection

#57627 aacgain: update livecheck regex
  Formula/aacgain.rb
Labels: livecheck

#57125 Switch Consul back to -dev mode
  Formula/consul.rb
Labels: almost there

#57664 redis: Update to support macOS 11
  Formula/redis.rb
Labels: 11.0

#57830 osi 0.108.6 (new formula)
  Formula/osi.rb
Labels: new formula

#58133 apache-flink 1.11.0
  Formula/apache-flink.rb
Labels: needs response

#58092 libffi: fix build on Apple Silicon
  Formula/libffi.rb
Labels: 11.0

#58191 krb5: add a fix for broken configure test
  Formula/krb5.rb
Labels: 11.0

#57455 Fix for nettle on Apple Silicon
  Formula/nettle.rb
Labels: 11.0

#58278 mas: fix build on Apple Silicon
  Formula/mas.rb
Labels: 11.0

#58334 librdkafka: depend on python@3.8 for build
  Formula/librdkafka.rb
Labels: linux to homebrew-core

#58320 igv 2.8.7
  Formula/igv.rb
Labels: CI-requeued

#58317 geoserver 2.17.2
  Formula/geoserver.rb
Labels: CI-requeued

#58483 llvm: skip OpenMP on Apple Silicon
  Formula/llvm.rb
Labels: 11.0

#58688 workflows: pr-automerge correct tap
  .github/workflows/scheduled.yml
Labels: do not merge

#56746 aws-google-auth: add linux-only resources
  Formula/aws-google-auth.rb
Labels: linux to homebrew-core

#58710 workflows: add more on-schedule workflows
  .github/workflows/autocancel.yml
  .github/workflows/autolabel.yml
  .github/workflows/autopublish.yml
Labels: do not merge

#58725 workflows: use workflow_dispatch for publishing workflow
  .github/workflows/publish-commit-bottles.yml
Labels: do not merge

#57817 doxygen: uses flex from macOS
  Formula/doxygen.rb
Labels: linux to homebrew-core

#58737 exploitdb 2020-07-28
  Formula/exploitdb.rb
Labels: bottle unneeded

#58753 jenkins 2.250
  Formula/jenkins.rb
Labels: bottle unneeded

#58755 audiofile: align test with Linux test
  Formula/audiofile.rb
Labels: linux to homebrew-core

#58760 vsts-cli: deprecate
  Formula/vsts-cli.rb
Labels: formula deprecated

#58752 workflows: tighten regexes for labelling
  .github/workflows/autolabel.yml
Labels: do not merge

#58802 workflows: don't checkout whole repo on upload
  .github/workflows/publish-commit-bottles.yml
Labels: do not merge

#58790 jenkins-lts 2.235.3
  Formula/jenkins-lts.rb
Labels: bottle unneeded

#58799 wtf 20200728
  Formula/wtf.rb
Labels: bottle unneeded

#58815 sonarqube-lts 7.9.4
  Formula/sonarqube-lts.rb
Labels: bottle unneeded

#58829 exploitdb 2020-07-29
  Formula/exploitdb.rb
Labels: bottle unneeded

#58717 yafc: Fix test server
  Formula/yafc.rb
Labels: CI-requeued

#56262 pg_top: update homepage
  Formula/pg_top.rb
Labels: maintainer feedback

#58720 dps8m: Fix test/audit
  Formula/dps8m.rb
Labels: CI-requeued

#58855 Revert "workflows/autolabel: add gopath deprecation"
  .github/workflows/autolabel.yml
Labels: do not merge

#58863 basex 9.4.1
  Formula/basex.rb
Labels: bottle unneeded

#58889 metabase 0.36.1
  Formula/metabase.rb
Labels: bottle unneeded
