Repository Homebrew/homebrew-core, pull requests merged in 2020-10, with the labels that each got.

#61914 liquibase 4.1.0
  Formula/liquibase.rb
Labels: bottle unneeded

#61910 jenkins 2.259
  Formula/jenkins.rb
Labels: bottle unneeded, java

#60739 apache-drill: update livecheck
  Formula/apache-drill.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck

#61929 picard-tools 2.23.6
  Formula/picard-tools.rb
Labels: bottle unneeded, java

#61930 nifi 1.12.1
  Formula/nifi.rb
Labels: bottle unneeded, java

#61920 ant 1.10.9
  Formula/ant.rb
Labels: bottle unneeded, java

#61925 neo4j 4.1.3
  Formula/neo4j.rb
Labels: bottle unneeded, deprecated license, java

#61986 closure-compiler 20200927
  Formula/closure-compiler.rb
Labels: bottle unneeded, java

#61989 carla: update license
  Formula/carla.rb
Labels: CI-syntax-only, python

#61993 geoserver 2.18.0
  Formula/geoserver.rb
Labels: bottle unneeded, missing license

#61992 s3-backer: update license
  Formula/s3-backer.rb
Labels: CI-syntax-only

#61991 jetty: add license
  Formula/jetty.rb
Labels: CI-syntax-only, almost there, bottle unneeded, java

#61985 apibuilder-cli 0.1.41
  Formula/apibuilder-cli.rb
Labels: bottle unneeded

#62006 nexus 2.14.19-01
  Formula/nexus.rb
Labels: bottle unneeded

#62015 workflows: permit extra pr-pull args
  .github/workflows/publish-commit-bottles.yml
Labels: needs response

#62026 exploitdb 2020-10-03
  Formula/exploitdb.rb
Labels: bottle unneeded

#62029 gobject-introspection: update homepage
  Formula/gobject-introspection.rb
Labels: CI-syntax-only, python

#62037 tinc: add license
  Formula/tinc.rb
Labels: CI-syntax-only

#62053 gammu: update license
  Formula/gammu.rb
Labels: CI-syntax-only

#61988 confluent-platform: disable due to OSI license issue
  Formula/confluent-platform.rb
Labels: CI-syntax-only, bottle unneeded, formula disabled, java, maintainer feedback, missing license

#62076 sonar-scanner 4.5.0.2216
  Formula/sonar-scanner.rb
Labels: bottle unneeded

#62085 dhall: add license
  Formula/dhall.rb
Labels: CI-syntax-only, haskell

#62086 claws-mail: add license
  Formula/claws-mail.rb
Labels: CI-syntax-only, ready to merge

#62096 ruby-build 20201005
  Formula/ruby-build.rb
Labels: bottle unneeded

#62097 cppcheck: update license
  Formula/cppcheck.rb
Labels: CI-syntax-only, python

#62104 freexl: fix test
  Formula/freexl.rb
Labels: missing license

#62106 z: add license
  Formula/z.rb
Labels: bottle unneeded

#62089 libice: depend on libx11 for test
  Formula/libice.rb
Labels: linux to homebrew-core

#62121 legit: remove explicit version
  Formula/legit.rb
Labels: CI-syntax-only, python

#62127 workflows: trigger cancelling on pull_request_target
  .github/workflows/cancel-previous-runs.yml
Labels: CI-syntax-only, do not merge

#62032 Remove livecheck blocks for deprecated formulae
  Formula/akka.rb
  Formula/archey.rb
  Formula/erlang@20.rb
  Formula/helm@2.rb
  Formula/ooniprobe.rb
  Formula/opencv@2.rb
  Formula/vsts-cli.rb
Labels: CI-syntax-only, formula deprecated, livecheck

#62138 rabbitmq 3.8.9
  Formula/rabbitmq.rb
Labels: bottle unneeded, python

#62155 babl: update license
  Formula/babl.rb
Labels: CI-syntax-only

#62145 libxres: align test with linuxbrew-core
  Formula/libxres.rb
Labels: linux to homebrew-core

#62144 libxmu: align test with linuxbrew-core
  Formula/libxmu.rb
Labels: linux to homebrew-core

#62142 libxcomposite: align test with linuxbrew-core
  Formula/libxcomposite.rb
Labels: linux to homebrew-core

#62164 lynis 3.0.1
  Formula/lynis.rb
Labels: bottle unneeded

#62174 skaffold: update homepage
  Formula/skaffold.rb
Labels: go

#62176 exploitdb 2020-10-06
  Formula/exploitdb.rb
Labels: bottle unneeded

#62196 gradle-profiler 0.15.0
  Formula/gradle-profiler.rb
Labels: bottle unneeded, java

#62105 wxpython: add license + update homepage
  Formula/wxpython.rb
Labels: CI-syntax-only, python

#62233 ydiff: migrate to python@3.9
  Formula/ydiff.rb
Labels: bottle unneeded, python, python-3.9-migration

#62200 helm@2: add deprecation date, restore livecheck
  Formula/helm@2.rb
Labels: CI-syntax-only, formula deprecated, go, legacy, livecheck

#62157 mkvtoolnix: specify name of renamed development branch for HEAD
  Formula/mkvtoolnix.rb
Labels: ruby

#62421 ssh-audit: migrate to python@3.9
  Formula/ssh-audit.rb
Labels: bottle unneeded, python, python-3.9-migration

#60907 abyss: update license
  Formula/abyss.rb
Labels: CI-syntax-only

#62173 sdl2: remove patch which has already been merged
  Formula/sdl2.rb
Labels: missing license

#62556 languagetool 5.1
  Formula/languagetool.rb
Labels: bottle unneeded, java, missing license

#62579 sslyze: fix license
  Formula/sslyze.rb
Labels: license, python

#62586 metabase 0.36.7
  Formula/metabase.rb
Labels: bottle unneeded, java, nodejs

#62591 exploitdb 2020-10-09
  Formula/exploitdb.rb
Labels: bottle unneeded

#62602 awscli: remove pyinstaller
  Formula/awscli.rb
Labels: python

#62601 prestosql 344
  Formula/prestosql.rb
Labels: bottle unneeded, java

#62599 phpmyadmin 5.0.3
  Formula/phpmyadmin.rb
Labels: bottle unneeded, missing license, php

#62598 tomcat@8 8.5.59
  Formula/tomcat@8.rb
Labels: bottle unneeded, java, legacy

#62597 tomcat 9.0.39
  Formula/tomcat.rb
Labels: bottle unneeded, java

#62595 languagetool 5.1.2
  Formula/languagetool.rb
Labels: bottle unneeded, java, missing license

#62607 xtrans: add missing test dependency
  Formula/xtrans.rb
Labels: linux to homebrew-core

#62608 libxshmfence: add missing test dependency
  Formula/libxshmfence.rb
Labels: linux to homebrew-core

#62609 structurizr-cli 1.4.5
  Formula/structurizr-cli.rb
Labels: bottle unneeded, java

#62612 code-server: add linux-only dependencies
  Formula/code-server.rb
Labels: linux to homebrew-core, nodejs, python

#62611 cairo: add linux-only dependencies
  Formula/cairo.rb
Labels: deprecated license, linux to homebrew-core

#62613 fmsx: add linux-only dependencies
  Formula/fmsx.rb
Labels: linux to homebrew-core, missing license

#62615 get-flash-videos: add linux-only resources
  Formula/get-flash-videos.rb
Labels: linux to homebrew-core

#62616 get_iplayer: add linux-only resources
  Formula/get_iplayer.rb
Labels: deprecated license, linux to homebrew-core, perl

#62618 gprof2dot: add linux-only dependency
  Formula/gprof2dot.rb
Labels: deprecated license, linux to homebrew-core, python

#62610 exploitdb 2020-10-10
  Formula/exploitdb.rb
Labels: bottle unneeded

#62214 libpciaccess (new formula)
  .github/workflows/tests-linux.yml
  Formula/libpciaccess.rb
Labels: do not merge, linux to homebrew-core, new formula

#62637 closure-compiler 20201006
  Formula/closure-compiler.rb
Labels: bottle unneeded, java

#62664 Update tagline/description for Xonsh
  Formula/xonsh.rb
Labels: CI-syntax-only, python

#62638 cypher-shell 4.1.2
  Formula/cypher-shell.rb
Labels: bottle unneeded, deprecated license, java

#62669 nanorc 2020.10.10
  Formula/nanorc.rb
Labels: bottle unneeded, deprecated license

#62665 inform6: add license
  Formula/inform6.rb
Labels: CI-syntax-only, license

#62684 get-flash-videos: fix test
  Formula/get-flash-videos.rb
Labels: bottle unneeded

#57558 workflows: add new dispatch-build-bottle workflow
  .github/workflows/dispatch-build-bottle.yml
Labels: CI-syntax-only, do not merge, in progress

#62683 phpunit 9.4.1
  Formula/phpunit.rb
Labels: bottle unneeded, php

#62713 wtf 20201005
  Formula/wtf.rb
Labels: bottle unneeded

#62716 calabash 1.2.5-100
  Formula/calabash.rb
Labels: bottle unneeded, deprecated license

#62732 uhd: add license
  Formula/uhd.rb
Labels: CI-syntax-only, python

#62737 llvm: fix typo
  Formula/llvm.rb
Labels: CI-syntax-only, python

#62752 swaks 20201010.0
  Formula/swaks.rb
Labels: bottle unneeded, missing license

#62756 phpstan 0.12.49
  Formula/phpstan.rb
Labels: bottle unneeded, php

#62755 plantuml 1.2020.19
  Formula/plantuml.rb
Labels: bottle unneeded, java

#62770 root: use ninja instead of make
  Formula/root.rb
Labels: python

#62781 miniserve: require rust only at build-time
  Formula/miniserve.rb
Labels: rust

#62799 workflows: always --autosquash on green PRs
  .github/workflows/autopublish.yml
Labels: automerge-skip, do not merge

#62839 cksfv: update license
  Formula/cksfv.rb
Labels: CI-syntax-only, license

#62841 dos2unix: add license
  Formula/dos2unix.rb
Labels: CI-syntax-only, license

#62840 cproto: add license
  Formula/cproto.rb
Labels: CI-syntax-only, license

#62842 freediameter: add license
  Formula/freediameter.rb
Labels: CI-syntax-only, license

#62829 libid3tag: add linux-only dependencies and patch
  Formula/libid3tag.rb
Labels: linux to homebrew-core, missing license

#62830 mikutter: depend on terminal-notifier only on mac
  Formula/mikutter.rb
Labels: linux to homebrew-core, ruby

#62831 mycli: add linux-only dependency
  Formula/mycli.rb
Labels: linux to homebrew-core, missing license, python

#62833 ripgrep-all: use zip for test
  Formula/ripgrep-all.rb
Labels: deprecated license, linux to homebrew-core, rust

#62834 rex: add linux-only dependency
  Formula/rex.rb
Labels: linux to homebrew-core, missing license, perl

#62891 tee-clc 14.135.0
  Formula/tee-clc.rb
Labels: bottle unneeded, java

#62890 signal-cli 0.6.11
  Formula/signal-cli.rb
Labels: bottle unneeded, java

#62807 picard-tools 2.23.7
  Formula/picard-tools.rb
Labels: CI-requeued, bottle unneeded, java

#62879 flyway 7.0.3
  Formula/flyway.rb
Labels: CI-requeued, bottle unneeded, java

#62883 gradle 6.7
  Formula/gradle.rb
Labels: CI-requeued, bottle unneeded, java

#62899 picard-tools 2.23.8
  Formula/picard-tools.rb
Labels: bottle unneeded, java

#62895 crystal: split mac and linux resource
  Formula/crystal.rb
Labels: linux to homebrew-core

#62912 workflows: move uploading stuff to separate job
  .github/workflows/dispatch-build-bottle.yml
Labels: CI-syntax-only, do not merge

#62913 exploitdb 2020-10-15
  Formula/exploitdb.rb
Labels: bottle unneeded

#62947 bnd 5.2.0
  Formula/bnd.rb
Labels: bottle unneeded, missing license

#62946 phpmyadmin 5.0.4
  Formula/phpmyadmin.rb
Labels: bottle unneeded, missing license, php

#62952 clojure 1.10.1.716
  Formula/clojure.rb
Labels: bottle unneeded, java, ruby

#62944 jenkins 2.262
  Formula/jenkins.rb
Labels: bottle unneeded, java

#62955 ssh-audit: add man page
  Formula/ssh-audit.rb
Labels: bottle unneeded, python

#62938 bundletool 1.3.0
  Formula/bundletool.rb
Labels: bottle unneeded, java

#62936 httpstat 1.3.0
  Formula/httpstat.rb
Labels: CI-requeued, bottle unneeded

#62917 languagetool 5.1.3
  Formula/languagetool.rb
Labels: CI-requeued, bottle unneeded, java

#62970 exploitdb 2020-10-16
  Formula/exploitdb.rb
Labels: bottle unneeded

#62652 libdrm (new formula)
  .github/workflows/tests-linux.yml
  Formula/libdrm.rb
Labels: linux to homebrew-core

#63000 flyway 7.0.4
  Formula/flyway.rb
Labels: bottle unneeded, java

#63011 exploitdb 2020-10-17
  Formula/exploitdb.rb
Labels: bottle unneeded

#63037 swaks 20201014.0
  Formula/swaks.rb
Labels: bottle unneeded, missing license

#63067 swaks: add license
  Formula/swaks.rb
Labels: CI-syntax-only, bottle unneeded, license

#63014 device-mapper (new formula)
  .github/workflows/tests-linux.yml
  Formula/device-mapper.rb
Labels: automerge-skip, linux to homebrew-core, new formula

#63077 meson-internal: remove
  Formula/meson-internal.rb
Labels: marked for removal/rejection, python

#63052 tfsec: fix test resource sha
  Formula/tfsec.rb
Labels: go

#63095 phpunit 9.4.2
  Formula/phpunit.rb
Labels: bottle unneeded, php

#63112 artifactory 6.23.0
  Formula/artifactory.rb
Labels: bottle unneeded, java, missing license

#63132 sbt 1.4.1
  Formula/sbt.rb
Labels: bottle unneeded, java

#63150 tbb: update homepage
  Formula/tbb.rb
Labels: CI-syntax-only, python

#63151 libpqxx: update hompage
  Formula/libpqxx.rb
  Formula/libpqxx@6.rb
Labels: CI-syntax-only, python

#63153 k3d: update homepage
  Formula/k3d.rb
Labels: CI-syntax-only, go

#63136 ace: add livecheck
  Formula/ace.rb
Labels: CI-syntax-only, livecheck

#63145 kaitai-struct-compiler 0.9
  Formula/kaitai-struct-compiler.rb
Labels: bottle unneeded, java

#63180 jenkins 2.263
  Formula/jenkins.rb
Labels: bottle unneeded, java

#63191 lizard-analyzer: add license
  Formula/lizard-analyzer.rb
Labels: CI-syntax-only, python

#63192 kerl 2.0.1
  Formula/kerl.rb
Labels: bottle unneeded

#63227 zbar: update livecheck regex
  Formula/zbar.rb
Labels: CI-syntax-only, livecheck

#63232 embulk: update livecheck
  Formula/embulk.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck

#63233 zint: update livecheck regex
  Formula/zint.rb
Labels: CI-syntax-only, livecheck

#63234 apache-drill: update livecheck regex
  Formula/apache-drill.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck

#63225 libsndfile: update homepage and livecheck block
  Formula/libsndfile.rb
Labels: CI-syntax-only, livecheck

#63252 exploitdb 2020-10-21
  Formula/exploitdb.rb
Labels: bottle unneeded

#63270 paket 5.250.0
  Formula/paket.rb
Labels: bottle unneeded

#63273 pandocomatic: update license
  Formula/pandocomatic.rb
Labels: CI-syntax-only, license, ruby

#63280 tfsec: add livecheck
  Formula/tfsec.rb
Labels: CI-syntax-only, go, livecheck

#63293 openjdk@8: remove hack for binary bootstrap URL
  Formula/openjdk@8.rb
Labels: CI-syntax-only, legacy

#63297 tfsec: update livecheck
  Formula/tfsec.rb
Labels: CI-syntax-only, go, livecheck

#62908 sbcl: split bootstrap binary resources for linux and mac
  Formula/sbcl.rb
Labels: linux to homebrew-core

#63310 jetty 9.4.33.v20201020
  Formula/jetty.rb
Labels: bottle unneeded, java

#63317 woboq_codebrowser: Remove
  Formula/woboq_codebrowser.rb
Labels: marked for removal/rejection

#63312 jetty-runner 9.4.33.v20201020
  Formula/jetty-runner.rb
Labels: bottle unneeded, java

#63326 exploitdb 2020-10-22
  Formula/exploitdb.rb
Labels: bottle unneeded

#63337 php-code-sniffer 3.5.7
  Formula/php-code-sniffer.rb
Labels: bottle unneeded

#63340 llvm@6: Remove
  Formula/llvm@6.rb
Labels: legacy, marked for removal/rejection
