Repository Homebrew/homebrew-core, pull requests merged in 2020-09, with the labels that each got.

#60444 pmd 6.27.0
  Formula/pmd.rb
Labels: bottle unneeded, java

#60458 node-build 4.9.5
  Formula/node-build.rb
Labels: bottle unneeded

#60452 closure-compiler 20200830
  Formula/closure-compiler.rb
Labels: bottle unneeded, java

#60478 cmd: cleanup commands.
  cmd/aspell-dictionaries.rb
  cmd/postgresql-upgrade-database.rb
Labels: CI-syntax-only

#56515 clang-format@8: add botle for version 8 (head is 10)
  Aliases/clang-format@10
  Formula/clang-format@8.rb
Labels: new formula

#60483 django-completion 3.1.1
  Formula/django-completion.rb
Labels: bottle unneeded

#60482 exploitdb 2020-09-01
  Formula/exploitdb.rb
Labels: bottle unneeded

#60486 jenkins 2.255
  Formula/jenkins.rb
Labels: bottle unneeded, java

#60477 gitleaks: set version properly
  Formula/gitleaks.rb
Labels: go

#60489 grakn 1.8.2
  Formula/grakn.rb
Labels: bottle unneeded, java

#60491 crowdin 3.2.2
  Formula/crowdin.rb
Labels: bottle unneeded, java

#60529 ISSUE_TEMPLATE: direct people to GitHub Discussions
  .github/ISSUE_TEMPLATE/config.yml
Labels: CI-syntax-only

#60530 phpstan 0.12.41
  Formula/phpstan.rb
Labels: bottle unneeded, php

#60536 questdb 5.0.3
  Formula/questdb.rb
Labels: bottle unneeded, java

#60570 rhino 1.7.13
  Formula/rhino.rb
Labels: bottle unneeded

#60545 phpstan 0.12.42
  Formula/phpstan.rb
Labels: bottle unneeded, php

#60386 easyengine 4.1.4
  Formula/easyengine.rb
Labels: bottle unneeded, php, test failure

#60594 nodeenv 1.5.0
  Formula/nodeenv.rb
Labels: bottle unneeded

#60615 logstash 7.9.1
  Formula/logstash.rb
Labels: bottle unneeded, java

#60613 exploitdb 2020-09-03
  Formula/exploitdb.rb
Labels: bottle unneeded

#60631 solr 8.6.2
  Formula/solr.rb
Labels: bottle unneeded, java

#60627 rabbitmq 3.8.8
  Formula/rabbitmq.rb
Labels: bottle unneeded, python

#60227 i2p 0.9.47
  Formula/i2p.rb
Labels: bottle unneeded, java, missing license

#60664 jmxterm 1.0.2
  Formula/jmxterm.rb
Labels: bottle unneeded, java

#60695 exploitdb 2020-09-05
  Formula/exploitdb.rb
Labels: bottle unneeded

#60042 fox: add license
  Formula/fox.rb
Labels: CI-syntax-only

#60702 dashing: fix test
  Formula/dashing.rb
Labels: go

#60735 tokei: add livecheck
  Formula/tokei.rb
Labels: CI-syntax-only, rust

#60729 Ant: use Ivy 2.5.0 as specified in libraries.properties
  Formula/ant.rb
Labels: bottle unneeded, java

#60749 bsdiff: improve homepage url to avoid an insecure redirect
  Formula/bsdiff.rb
Labels: CI-syntax-only

#60751 dependency-check 6.0.0
  Formula/dependency-check.rb
Labels: bottle unneeded, java

#60789 exploitdb 2020-09-08
  Formula/exploitdb.rb
Labels: bottle unneeded

#60792 jenkins 2.256
  Formula/jenkins.rb
Labels: bottle unneeded, java

#60793 asdf 0.8.0
  Formula/asdf.rb
Labels: bottle unneeded

#60807 composer 1.10.12
  Formula/composer.rb
Labels: bottle unneeded, missing license

#60817 detekt 1.13.0
  Formula/detekt.rb
Labels: bottle unneeded, java

#60827 phpmd 2.9.0
  Formula/phpmd.rb
Labels: bottle unneeded

#60828 airshare: add license
  Formula/airshare.rb
Labels: CI-syntax-only, python

#60834 composer 1.10.13
  Formula/composer.rb
Labels: bottle unneeded, missing license

#60815 composer: add license
  Formula/composer.rb
Labels: CI-syntax-only, bottle unneeded

#60845 exploitdb 2020-09-09
  Formula/exploitdb.rb
Labels: bottle unneeded

#60821 openfst: add livecheck
  Formula/openfst.rb
Labels: CI-syntax-only, livecheck

#60830 aalib: add license
  Formula/aalib.rb
Labels: CI-syntax-only

#60829 aacgain: add license
  Formula/aacgain.rb
Labels: CI-syntax-only

#60832 a2ps: update license
  Formula/a2ps.rb
Labels: CI-syntax-only

#60887 jenkins-lts 2.249.1
  Formula/jenkins-lts.rb
Labels: bottle unneeded, java

#60892 repo 2.9
  Formula/repo.rb
Labels: bottle unneeded

#60895 riemann 0.3.6
  Formula/riemann.rb
Labels: bottle unneeded

#60885 picard-tools 2.23.4
  Formula/picard-tools.rb
Labels: bottle unneeded, java

#60939 snapcraft: update license
  Formula/snapcraft.rb
Labels: python

#60936 exploitdb 2020-09-10
  Formula/exploitdb.rb
Labels: bottle unneeded

#60944 fix nushell HEAD builds
  Formula/nushell.rb
Labels: rust

#60935 embulk 0.10.15
  Formula/embulk.rb
Labels: bottle unneeded, java

#60959 hello: update license
  Formula/hello.rb
Labels: CI-syntax-only

#60958 update kotlin from 1.4.0 to 1.4.10
  Formula/kotlin.rb
Labels: bottle unneeded

#60961 ppsspp: fix license
  Formula/ppsspp.rb
Labels: CI-syntax-only

#59734 ghc: update cabal-install version for head build
  Formula/ghc.rb
Labels: python, stale

#60932 asciidoctorj 2.4.1
  Formula/asciidoctorj.rb
Labels: bottle unneeded, java

#60982 exploitdb 2020-09-11
  Formula/exploitdb.rb
Labels: bottle unneeded

#61000 wgetpaste 2.30
  Formula/wgetpaste.rb
Labels: bottle unneeded

#60990 caddy: add resume flag
  Formula/caddy.rb
Labels: go

#60942 alsa-lib 1.2.1.2 (new formula)
  .github/workflows/tests-linux.yml
  Formula/alsa-lib.rb
Labels: linux to homebrew-core, new formula

#61014 phpunit 9.3.10
  Formula/phpunit.rb
Labels: bottle unneeded, php

#61016 exploitdb 2020-09-12
  Formula/exploitdb.rb
Labels: bottle unneeded

#61018 checkstyle 8.36.1
  Formula/checkstyle.rb
Labels: bottle unneeded, java

#61084 dependency-check 6.0.1
  Formula/dependency-check.rb
Labels: bottle unneeded, java

#61085 parallel: update livecheck url and regex
  Formula/parallel.rb
Labels: CI-syntax-only, livecheck

#60943 ladspa-sdk 1.15 (new formula)
  .github/workflows/tests-linux.yml
  Formula/ladspa-sdk.rb
Labels: linux to homebrew-core, new formula

#61093 youtube-dl 2020.09.14
  Formula/youtube-dl.rb
Labels: bottle unneeded

#60784 couchdb: add caveats for 3.x: requires pw before startup
  Formula/couchdb.rb
Labels: CI-syntax-only

#61196 metabase 0.36.6
  Formula/metabase.rb
Labels: bottle unneeded, java, nodejs

#61228 vert.x 3.9.3
  Formula/vert.x.rb
Labels: bottle unneeded, java

#61211 wiremock-standalone 2.27.2
  Formula/wiremock-standalone.rb
Labels: bottle unneeded, java

#61255 tomcat-native: fix mirror url
  Formula/tomcat-native.rb
Labels: java

#61249 docker-compose-completion 1.27.3
  Formula/docker-compose-completion.rb
Labels: bottle unneeded

#61275 grakn 1.8.3
  Formula/grakn.rb
Labels: bottle unneeded, java

#61278 docker-completion 19.03.13
  Formula/docker-completion.rb
Labels: bottle unneeded

#61203 libseccomp 2.5.0
  Formula/libseccomp.rb
Labels: bottle unneeded

#61288 dasm: update license
  Formula/dasm.rb
Labels: CI-syntax-only

#61301 bash-preexec 0.4.1
  Formula/bash-preexec.rb
Labels: bottle unneeded

#61372 exploitdb 2020-09-19
  Formula/exploitdb.rb
Labels: bottle unneeded

#60289 flank 20.08.4
  Formula/flank.rb
Labels: bottle unneeded, java, ready to merge

#61398 plantuml 1.2020.17
  Formula/plantuml.rb
Labels: bottle unneeded, java

#61378 flank 20.09.2
  Formula/flank.rb
Labels: bottle unneeded, java

#61410 phpstan 0.12.43
  Formula/phpstan.rb
Labels: bottle unneeded, php

#61411 sonarqube 8.4.2.36762
  Formula/sonarqube.rb
Labels: bottle unneeded, java

#61434 youtube-dl 2020.09.20
  Formula/youtube-dl.rb
Labels: bottle unneeded

#61439 libsoxr: fix test for gcc
  Formula/libsoxr.rb
Labels: bottle unneeded

#61480 ocamlsdl: disable
  Formula/ocamlsdl.rb
Labels: formula disabled, ocaml

#61526 exploitdb 2020-09-22
  Formula/exploitdb.rb
Labels: bottle unneeded

#61532 jenkins 2.258
  Formula/jenkins.rb
Labels: bottle unneeded, java

#61349 cjdns: update license
  Formula/cjdns.rb
Labels: CI-syntax-only, nodejs

#61551 vivid: fix bottle commit (2a73560) code style issue
  Formula/vivid.rb
Labels: CI-syntax-only, rust

#61565 easyengine 4.1.5
  Formula/easyengine.rb
Labels: bottle unneeded, php

#61579 phpmd 2.9.1
  Formula/phpmd.rb
Labels: bottle unneeded

#61591 phpunit 9.3.11
  Formula/phpunit.rb
Labels: bottle unneeded, php

#61613 phpstan 0.12.44
  Formula/phpstan.rb
Labels: bottle unneeded, php

#61615 docker-compose-completion 1.27.4
  Formula/docker-compose-completion.rb
Labels: bottle unneeded

#61627 cddlib: update license
  Formula/cddlib.rb
Labels: CI-syntax-only

#61628 scamper: update license
  Formula/scamper.rb
Labels: CI-syntax-only

#61649 ruby-build 20200926
  Formula/ruby-build.rb
Labels: bottle unneeded

#61662 exploitdb 2020-09-26
  Formula/exploitdb.rb
Labels: bottle unneeded

#61665 phpstan 0.12.45
  Formula/phpstan.rb
Labels: bottle unneeded, php

#61696 dependency-check 6.0.2
  Formula/dependency-check.rb
Labels: bottle unneeded, java

#61673 spotbugs 4.1.3
  Formula/spotbugs.rb
Labels: bottle unneeded, java

#61683 neo4j 4.1.2
  Formula/neo4j.rb
Labels: bottle unneeded, deprecated license, java

#61698 idnits 2.16.05
  Formula/idnits.rb
Labels: bottle unneeded, missing license

#61705 idnits: update license
  Formula/idnits.rb
Labels: CI-syntax-only, bottle unneeded

#61725 phpstan 0.12.46
  Formula/phpstan.rb
Labels: bottle unneeded, php

#61710 libaio (new formula)
  .github/workflows/tests-linux.yml
  Formula/libaio.rb
Labels: linux to homebrew-core, new formula

#61708 libnfnetlink (new formula)
  .github/workflows/tests-linux.yml
  Formula/libnfnetlink.rb
Labels: linux to homebrew-core, new formula

#61729 libxmlsec1: depend on xcode for mac only
  Formula/libxmlsec1.rb
Labels: linux to homebrew-core

#61731 libmnl (new formula)
  .github/workflows/tests-linux.yml
  Formula/libmnl.rb
Labels: linux to homebrew-core

#61732 libnetfilter-queue (new formula)
  .github/workflows/tests-linux.yml
  Formula/libnetfilter-queue.rb
Labels: bottle unneeded, linux to homebrew-core, new formula

#61755 clojure 1.10.1.697
  Formula/clojure.rb
Labels: bottle unneeded, java, ruby

#61763 crowdin 3.3.0
  Formula/crowdin.rb
Labels: bottle unneeded, java

#61791 ssh audit 2.3.0
  Formula/ssh-audit.rb
Labels: bottle unneeded, python
