Repository Homebrew/homebrew-core, pull requests merged in 2020-04, with the labels that each got.

#52366 monit: Add plist according to the official wiki.
  Formula/monit.rb
Labels: ready to merge

#52241 semtag (new formula)
  Formula/semtag.rb
Labels: new formula

#52414 sbt 1.3.9
  Formula/sbt.rb
Labels: ready to merge

#52423 inxi 3.0.38 (new formula)
  Formula/inxi.rb
Labels: new formula, ready to merge

#52572 openssh: fix broken link
  Formula/openssh.rb
Labels: ready to merge

#52594 logstash 7.6.2
  Formula/logstash.rb
Labels: ready to merge

#52658 ssh-copy-id: provided by macOS.
  Formula/ssh-copy-id.rb
Labels: ready to merge

#52668 exploitdb 2020-04-07
  Formula/exploitdb.rb
Labels: ready to merge

#52587 emacs-dracula 1.7.0 (new formula)
  Formula/emacs-dracula.rb
Labels: new formula

#52703 detekt 1.7.4
  Formula/detekt.rb
Labels: ready to merge

#52593 Use free_port instead of predefined in test
  Formula/algernon.rb
  Formula/anycable-go.rb
  Formula/app-engine-python.rb
  Formula/appium.rb
  Formula/armor.rb
  Formula/asio.rb
  Formula/caddy.rb
  Formula/carrot2.rb
  Formula/chronograf.rb
  Formula/cosi.rb
  Formula/couchdb.rb
  Formula/cppcms.rb
  Formula/envconsul.rb
  Formula/fortio.rb
  Formula/gnirehtet.rb
  Formula/h2o.rb
  Formula/icecast.rb
  Formula/jenkins-lts.rb
  Formula/jenkins.rb
  Formula/jetty-runner.rb
  Formula/leaps.rb
  Formula/mpd.rb
  Formula/mysql.rb
  Formula/mysql@5.6.rb
  Formula/mysql@5.7.rb
  Formula/nanomsg.rb
  Formula/nng.rb
  Formula/openssh.rb
  Formula/polynote.rb
  Formula/postgrest.rb
  Formula/privoxy.rb
  Formula/selenium-server-standalone.rb
  Formula/serve.rb
  Formula/serveit.rb
  Formula/shadowsocks-libev.rb
  Formula/tinyproxy.rb
  Formula/webdis.rb
  Formula/webfs.rb
  Formula/websocketd.rb
Labels: do not merge

#52711 repo 2.5
  Formula/repo.rb
Labels: ready to merge

#52575 grails 4.0.3
  Formula/grails.rb
Labels: ready to merge

#52585 workflows: post comment on pr-publish failure
  .github/workflows/publish-commit-bottles.yml
Labels: ready to merge

#52618 Moco 1.1.0
  Formula/moco.rb
Labels: ready to merge

#52786 composer 1.10.4
  Formula/composer.rb
Labels: ready to merge

#52785 tomcat 9.0.34
  Formula/tomcat.rb
Labels: ready to merge

#52796 Liquibase 3.8.9
  Formula/liquibase.rb
Labels: ready to merge

#52838 jetty 9.4.28.v20200408
  Formula/jetty.rb
Labels: ready to merge

#52860 compcert: remove formula
  Formula/compcert.rb
Labels: marked for removal/rejection

#53025 atlassian-cli 9.2.0
  Formula/atlassian-cli.rb
Labels: ready to merge

#52956 polynote 0.3.6
  Formula/polynote.rb
Labels: ready to merge

#53092 gitversion: downgrade, use mono.
  Formula/gitversion.rb
Labels: ready to merge

#53144 exploitdb 2020-04-14
  Formula/exploitdb.rb
Labels: ready to merge

#53156 artifactory 6.19.0
  Formula/artifactory.rb
Labels: ready to merge

#53179 Suggest the correct path in zsh-completions caveats
  Formula/zsh-completions.rb
Labels: ready to merge

#53249 ballerina 1.2.2
  Formula/ballerina.rb
Labels: ready to merge

#52642 zurl: use python@3.8 for test
  Formula/zurl.rb
Labels: python-3.8-migration

#52996 embulk: add note for 0.10.x release
  Formula/embulk.rb
Labels: ready to merge

#51502 open-completion 1.0.4
  Formula/open-completion.rb
Labels: ready to merge

#53434 phpunit 9.1.2
  Formula/phpunit.rb
Labels: ready to merge

#53556 Aliases: add vimcat
  Aliases/vimcat
Labels: ready to merge

#53555 phpunit 9.1.3
  Formula/phpunit.rb
Labels: ready to merge

#53719 rswift 5.2.0
  Formula/rswift.rb
Labels: ready to merge

#53678 vips: uses zlib from macos
  Formula/vips.rb
Labels: ready to merge

#53770 workflows/tests: move tap_syntax checks to hosted workers.
  .github/workflows/tests.yml
Labels: do not merge

#54049 wtf 20200429
  Formula/wtf.rb
Labels: ready to merge
