Repository Homebrew/homebrew-core, pull requests merged in 2020-02, with the labels that each got.

#49555 par: fix URLs, add mirror
  Formula/par.rb
Labels: ready to merge

#49693 euler-py: update test
  Formula/euler-py.rb
Labels: ready to merge

#48981 pdftk-java 3.0.9
  Formula/pdftk-java.rb
Labels: ready to merge

#49707 mldonkey: remove formula
  Formula/mldonkey.rb
  Formula/ocaml.rb
Labels: marked for removal/rejection

#49745 fstar: remove formula
  Formula/fstar.rb
Labels: marked for removal/rejection, ready to merge

#49785 exploitdb 2020-02-04
  Formula/exploitdb.rb
Labels: ready to merge

#46435 allure: depend on openjdk
  Formula/allure.rb
Labels: openjdk-migration, ready to merge

#46436 ammonite-repl: depend on openjdk
  Formula/ammonite-repl.rb
Labels: openjdk-migration, ready to merge

#46437 ant: depend on openjdk
  Formula/ant.rb
Labels: openjdk-migration, ready to merge

#46439 antlr: depend on openjdk
  Formula/antlr.rb
  Formula/antlr@2.rb
Labels: openjdk-migration, ready to merge

#46440 apache-archiva: depend on openjdk
  Formula/apache-archiva.rb
Labels: openjdk-migration, ready to merge

#46450 artifactory: depend on openjdk
  Formula/artifactory.rb
Labels: openjdk-migration, ready to merge

#49742 activemq: depend on openjdk
  Formula/activemq.rb
Labels: openjdk-migration, ready to merge

#49814 yarn 1.22.0
  Formula/yarn.rb
Labels: ready to merge

#46448 apollo: depend on openjdk
  Formula/apollo.rb
Labels: openjdk-migration, ready to merge

#46445 apache-forrest: depend on openjdk
  Formula/apache-forrest.rb
Labels: openjdk-migration, ready to merge

#49846 libphonenumber: remove Java dependency
  Formula/libphonenumber.rb
Labels: ready to merge

#49847 spotbugs: depend on openjdk@12
  Formula/spotbugs.rb
Labels: openjdk-migration, ready to merge

#49848 golo: depend on openjdk@12
  Formula/golo.rb
Labels: openjdk-migration, ready to merge

#49904 hapi-fhir-cli: depend on openjdk
  Formula/hapi-fhir-cli.rb
Labels: openjdk-migration, ready to merge

#49843 openjdk: missing revision bumps
  Formula/activemq.rb
  Formula/allure.rb
  Formula/ammonite-repl.rb
  Formula/ant.rb
  Formula/antlr.rb
  Formula/antlr@2.rb
  Formula/apache-archiva.rb
  Formula/artifactory.rb
Labels: openjdk-migration, ready to merge

#49951 closure-compiler 20200204
  Formula/closure-compiler.rb
Labels: ready to merge

#49976 python: don't mention python@2 formula in caveats
  Formula/python.rb
Labels: ready to merge

#49907 nesc: depend on openjdk
  Formula/nesc.rb
Labels: openjdk-migration, ready to merge

#50035 zeek: add mac only dependencies and document Python 2 usage
  Formula/zeek.rb
Labels: python

#49917 i2p: depend on openjdk
  Formula/i2p.rb
Labels: openjdk-migration, ready to merge

#49898 predictionio: fix depends_on :java
  Formula/predictionio.rb
Labels: ready to merge

#50077 node@10: Add comment about Python 3 support
  Formula/node@10.rb
Labels: python

#50095 avro-tools 1.9.2
  Formula/avro-tools.rb
Labels: ready to merge

#50099 docker-completion 19.03.6
  Formula/docker-completion.rb
Labels: ready to merge

#50175 groovy 3.0.0
  Formula/groovy.rb
Labels: ready to merge

#50279 libpqxx: Depend on python@3.8
  Formula/libpqxx.rb
Labels: python

#50290 quicktype: add HEAD
  Formula/quicktype.rb
Labels: ready to merge

#50352 gh: delete
  Formula/gh.rb
Labels: marked for removal/rejection

#50364 plantuml 1.2020.1
  Formula/plantuml.rb
Labels: ready to merge

#50348 paket 5.242.2
  Formula/paket.rb
Labels: ready to merge

#50344 groovysdk 3.0.1
  Formula/groovysdk.rb
Labels: ready to merge

#50370 gpgme: remove Python 2 test
  Formula/gpgme.rb
Labels: python

#50371 zpython: delete
  Formula/zpython.rb
Labels: python

#50454 bedtools: build with Python@3.8
  Formula/bedtools.rb
Labels: python

#50456 anycable-go: add head
  Formula/anycable-go.rb
Labels: ready to merge

#50559 micronaut 1.3.2
  Formula/micronaut.rb
Labels: ready to merge

#50468 workflows: add self-hosted runners
  .github/workflows/build-bottles.yml
Labels: do not merge

#50678 wabt: use Python@3.8 for build
  Formula/wabt.rb
Labels: python

#50693 sk: add fish key bindings
  Formula/sk.rb
Labels: ready to merge

#50759 stop patching paths in solr config files
  Formula/solr.rb
  Formula/solr@7.7.rb
Labels: ready to merge

#50756 neal: delete
  Formula/neal.rb
Labels: marked for removal/rejection

#50739 Nuvie: Add test
  Formula/nuvie.rb
Labels: ready to merge

#50720 Bastet: Add test
  Formula/bastet.rb
Labels: ready to merge

#50796 ctemplate: add test
  Formula/ctemplate.rb
Labels: ready to merge

#50788 xmake: correction in description string
  Formula/xmake.rb
Labels: ready to merge
