Repository Homebrew/homebrew-core, pull requests merged in 2021-05, with the labels that each got.

#76362 sdl2_net: fix build for Linux
  Formula/sdl2_net.rb
Labels: linux to homebrew-core

#76363 morse: disable test on Linux
  Formula/morse.rb
Labels: CI-syntax-only, linux to homebrew-core

#74369 libdrm: add docutils as dependency
  Formula/libdrm.rb
Labels: bottle unneeded, linux-only

#76391 griffon: remove `bottle :unneeded`
  Formula/griffon.rb
Labels: CI-force-arm, formula disabled, missing license

#76433 ecasound: add livecheck
  Formula/ecasound.rb
Labels: CI-syntax-only, livecheck, missing license, no ARM bottle

#76430 stgit: update license
  Formula/stgit.rb
Labels: CI-syntax-only, license, python

#76404 libdrm 2.4.105
  Formula/libdrm.rb
Labels: bottle unneeded, linux-only

#76483 s-nail: add livecheck
  Formula/s-nail.rb
Labels: CI-syntax-only, livecheck, missing license

#76496 wayland-protocols: upstream Linux fix
  Formula/wayland-protocols.rb
Labels: CI-syntax-only, bottle unneeded, linux to homebrew-core, linux-only

#76495 ponyc: upstream Linux fix
  Formula/ponyc.rb
Labels: CI-syntax-only, linux to homebrew-core, no ARM bottle

#76491 libsigc++: upstream Linux fix
  Formula/libsigc++.rb
Labels: CI-syntax-only, linux to homebrew-core

#76489 recutils: upstream Linux fix
  Formula/recutils.rb
Labels: CI-syntax-only, linux to homebrew-core

#76488 ncview: upstream Linux fix
  Formula/ncview.rb
Labels: CI-syntax-only, linux to homebrew-core

#76487 pinentry: upstream Linux fix
  Formula/pinentry.rb
Labels: CI-syntax-only, linux to homebrew-core

#76485 cast: upstream Linux fix
  Formula/castxml.rb
Labels: CI-syntax-only, linux to homebrew-core

#76482 rtags: upstream Linux fix
  Formula/rtags.rb
Labels: CI-syntax-only, linux to homebrew-core

#76481 pipx: add resource for Linux
  Formula/pipx.rb
Labels: CI-syntax-only, linux to homebrew-core, python

#76486 pcsc-lite: upstream Linux fix
  Formula/pcsc-lite.rb
Labels: linux to homebrew-core

#76509 kaitai-struct-compiler: migrate from Bintray
  Formula/kaitai-struct-compiler.rb
Labels: automerge-skip, bottle unneeded, java

#76515 giza: fix test
  Formula/giza.rb
Labels: automerge-skip, bottle unneeded

#76490 libstfl: upstream Linux fix
  Formula/libstfl.rb
Labels: linux to homebrew-core, perl, python, ruby

#76484 talloc: fix test on Linux
  Formula/talloc.rb
Labels: linux to homebrew-core

#76520 libfabric: conflict with `mpich`
  Formula/libfabric.rb
Labels: CI-syntax-only

#76514 gitbucket: fix test hanging
  Formula/gitbucket.rb
Labels: bottle unneeded, java

#76528 openlibm: remove `keg-only`, add license
  Formula/openlibm.rb
Labels: CI-syntax-only, license

#76643 workflows: output `brew bottle` result
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/linux-dispatch-build-bottle.yml
  .github/workflows/tests.yml
Labels: automerge-skip

#76665 rpm: update livecheck
  Formula/rpm.rb
Labels: CI-syntax-only, livecheck, lua, no ARM bottle

#76693 scalastyle: add livecheck
  Formula/scalastyle.rb
Labels: CI-syntax-only, bottle unneeded, livecheck, missing license

#76721 wayland-protocols 1.21
  Formula/wayland-protocols.rb
Labels: bottle unneeded, linux-only

#76746 imagemagick@6: update homepage
  Formula/imagemagick@6.rb
Labels: CI-syntax-only, legacy

#76749 autorest: add `depends_on arch: :x86_64`
  Formula/autorest.rb
Labels: nodejs

#76753 workflows: display and upload logs for Linux builds
  .github/workflows/linux-pr-tests.yml
Labels: automerge-skip

#76741 bash: update livecheck
  Formula/bash.rb
Labels: CI-syntax-only, livecheck

#76807 jolie-1.10 new syntax test
  Formula/jolie.rb
Labels: java

#76853 autoconf@2.13: update license
  Formula/autoconf@2.13.rb
Labels: CI-syntax-only, legacy, license

#76848 sonarqube-lts: update livecheck
  Formula/sonarqube-lts.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck

#76836 openmodelica: fix build with CMake 3.20+
  Formula/openmodelica.rb
Labels: java, no ARM bottle

#76889 imath: remove `conflicts_with`
  Formula/imath.rb
Labels: CI-syntax-only

#76877 exploitdb 2021-05-08
  Formula/exploitdb.rb
Labels: bottle unneeded

#76865 docs: simplify commands to edit formula
  CONTRIBUTING.md
Labels: CI-syntax-only, automerge-skip

#76867 laszip: align test with Linux version
  Formula/laszip.rb
Labels: license, linux to homebrew-core

#76871 alot: align test with Linux version
  Formula/alot.rb
Labels: linux to homebrew-core, python

#76873 jinja2-cli: align test with Linux version
  Formula/jinja2-cli.rb
Labels: linux to homebrew-core, python

#76755 mesa: update livecheck
  Formula/mesa.rb
Labels: CI-syntax-only, livecheck

#76876 gradle-profiler: update for gradle 7.0
  Formula/gradle-profiler.rb
Labels: bottle unneeded, java

#76891 zeek: use a test fixture instead of downloading one
  Formula/zeek.rb
Labels: automerge-skip, bottle unneeded, python

#76913 device-mapper 2.03.12
  Formula/device-mapper.rb
Labels: bottle unneeded, linux-only

#76945 libdivecomputer: update head
  Formula/libdivecomputer.rb
Labels: CI-syntax-only

#76875 workflows: set `HOMEBREW_RELOCATE_RPATHS`
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip

#76966 haskell-stack: add comment for install constraint
  Formula/haskell-stack.rb
Labels: CI-syntax-only, haskell, no ARM bottle

#76974 gitbucket: avoid shell metacharacters
  Formula/gitbucket.rb
Labels: automerge-skip, bottle unneeded, java

#76981 signal-cli: cleanup
  Formula/signal-cli.rb
Labels: java, no ARM bottle

#76984 openblas: scope patch to stable
  Formula/openblas.rb
Labels: CI-syntax-only

#76995 etcd: set ETCD_UNSUPPORTED_ARCH for Arm64, because while it builds on…
  Formula/etcd.rb
Labels: CI-force-arm, go, no ARM bottle

#77096 exploitdb 2021-05-11
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#77104 libtirpc 1.3.2
  Formula/libtirpc.rb
Labels: bottle unneeded, bump-formula-pr, linux-only

#77108 mesa: support new default branch
  Formula/mesa.rb
Labels: CI-syntax-only

#77118 phpstan 0.12.87
  Formula/phpstan.rb
Labels: bottle unneeded, bump-formula-pr, php

#77120 exploitdb 2021-05-12
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#77129 lynis 3.0.4
  Formula/lynis.rb
Labels: bottle unneeded, bump-formula-pr

#77117 exim: update livecheck
  Formula/exim.rb
Labels: CI-syntax-only, livecheck

#77159 mvnvm 1.0.15
  Formula/mvnvm.rb
Labels: bottle unneeded, bump-formula-pr, java

#77136 nanomsgxx: align test with Linux version
  Formula/nanomsgxx.rb
Labels: linux to homebrew-core

#77137 mjpegtools: add license
  Formula/mjpegtools.rb
Labels: CI-syntax-only, license

#77168 tomcat@9 9.0.46
  Formula/tomcat@9.rb
Labels: bottle unneeded, bump-formula-pr, java, legacy

#77170 tomcat 10.0.6
  Formula/tomcat.rb
Labels: bottle unneeded, bump-formula-pr, java

#77171 tomcat@8 8.5.66
  Formula/tomcat@8.rb
Labels: bottle unneeded, bump-formula-pr, java, legacy

#77167 ffmpeg: disable avresample
  Formula/ffmpeg.rb
Labels: automerge-skip, bottle unneeded

#77165 salt: add Linux dependencies
  Formula/salt.rb
Labels: CI-syntax-only, linux to homebrew-core, python

#77164 gnu-time: upstream Linux fix
  Formula/gnu-time.rb
Labels: CI-syntax-only, linux to homebrew-core, ruby

#77163 unpaper: upstream Linux fix
  Formula/unpaper.rb
Labels: CI-syntax-only, linux to homebrew-core

#77162 gtkextra: upstream Linux fix
  Formula/gtkextra.rb
Labels: linux to homebrew-core

#77161 percona-server: add Linux dependencies
  Formula/percona-server.rb
Labels: CI-syntax-only, linux to homebrew-core

#77158 sfml: build on Linux
  Formula/sfml.rb
Labels: linux to homebrew-core

#77157 qcachegrind: upstream Linux fix
  Formula/qcachegrind.rb
Labels: linux to homebrew-core

#77156 libgosu: fix build for Linux
  Formula/libgosu.rb
Labels: linux to homebrew-core

#77154 latexml: upstream Linux fix
  Formula/latexml.rb
Labels: CI-syntax-only, linux to homebrew-core, perl

#77150 fcrackzip: fix build for Linux
  Formula/fcrackzip.rb
Labels: CI-syntax-only, license, linux to homebrew-core

#77151 game-music-emu: fix build for Linux
  Formula/game-music-emu.rb
Labels: license, linux to homebrew-core

#77149 babl: upstream Linux fix
  Formula/babl.rb
Labels: linux to homebrew-core

#77148 abuse: fix build for Linux
  Formula/abuse.rb
Labels: CI-syntax-only, linux to homebrew-core

#77155 handbrake: fix build for Linux
  Formula/handbrake.rb
Labels: CI-syntax-only, linux to homebrew-core, no ARM bottle

#77192 exploitdb 2021-05-13
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#77230 leveldb: set `RPATH` for ARM
  Formula/leveldb.rb
Labels: CI-force-arm, no ARM bottle

#77188 pkg-config: remove `pour_bottle?` block
  Formula/pkg-config.rb
Labels: CI-syntax-only, automerge-skip, bottle unneeded

#77241 ngircd: add livecheck
  Formula/ngircd.rb
Labels: CI-syntax-only, livecheck, no ARM bottle

#77244 ADIOS2: New FindPython.cmake
  Formula/adios2.rb
Labels: python

#77276 guile: switch to "main" branch
  Formula/guile.rb
Labels: CI-syntax-only

#77029 telegraf: fix v1.18.2 source tarball sha256 hash
  Formula/telegraf.rb
Labels: go

#77293 exploitdb 2021-05-14
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#77286 questdb 6.0.1
  Formula/questdb.rb
Labels: bottle unneeded, java

#77346 kind: fix test, use `main` branch for `--HEAD`
  Formula/kind.rb
Labels: automerge-skip, bottle unneeded, go

#77306 aws-okta: deprecate
  Formula/aws-okta.rb
Labels: formula deprecated, go

#77352 jbake 2.6.7
  Formula/jbake.rb
Labels: bottle unneeded, bump-formula-pr, java

#77355 exploitdb 2021-05-15
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#77319 sysstat 12.5.3
  Formula/sysstat.rb
Labels: bottle unneeded, bump-formula-pr, linux-only

#77357 plantuml 1.2021.6
  Formula/plantuml.rb
Labels: bottle unneeded, bump-formula-pr, java

#77361 detekt 1.17.0
  Formula/detekt.rb
Labels: bottle unneeded, bump-formula-pr, java

#77363 bowtie2: update license
  Formula/bowtie2.rb
Labels: CI-syntax-only, license, no ARM bottle

#77374 mercury: add livecheck
  Formula/mercury.rb
Labels: CI-syntax-only, java, livecheck, no ARM bottle

#77403 cksfv: add livecheck
  Formula/cksfv.rb
Labels: CI-syntax-only, livecheck

#77418 minizip: update `conflicts_with` and add license
  Formula/minizip.rb
Labels: CI-syntax-only, license

#77451 gnu-chess: update license
  Formula/gnu-chess.rb
Labels: CI-syntax-only, license

#77450 fplll: update license
  Formula/fplll.rb
Labels: CI-syntax-only, license

#76761 workflows/tests: set timeout, fail fast using labels.
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip

#77456 phpstan 0.12.88
  Formula/phpstan.rb
Labels: bottle unneeded, bump-formula-pr, php

#77455 php-code-sniffer: update phpcbf resource
  Formula/php-code-sniffer.rb
Labels: bottle unneeded

#77458 Revert "workflows/tests: set timeout, fail fast using labels."
  .github/workflows/tests.yml
Labels: automerge-skip

#77480 lttng-ust 2.12.2
  Formula/lttng-ust.rb
Labels: bottle unneeded, bump-formula-pr, linux-only

#77482 rogue: fix build for Linux
  Formula/rogue.rb
Labels: CI-syntax-only, linux to homebrew-core, missing license

#77490 fastlane: refactor to use write_env_script
  Formula/fastlane.rb
Labels: ruby

#77493 bluepill: update livecheck
  Formula/bluepill.rb
Labels: CI-syntax-only, livecheck

#77486 pdnsrec: use brew gcc on Linux
  Formula/pdnsrec.rb
Labels: linux to homebrew-core, lua

#77530 exploitdb 2021-05-18
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#77581 libdrm 2.4.106
  Formula/libdrm.rb
Labels: bottle unneeded, bump-formula-pr, linux-only

#77575 rmw: add livecheck
  Formula/rmw.rb
Labels: CI-syntax-only, livecheck

#77607 wp-cli 2.5.0
  Formula/wp-cli.rb
Labels: bottle unneeded

#77614 druid: force stop zookeeper in test
  Formula/druid.rb
Labels: java

#76668 djl-serving: fix sha256 mismatch
  Formula/djl-serving.rb
Labels: bottle unneeded, java

#77647 allure 2.14.0
  Formula/allure.rb
Labels: bottle unneeded, java

#75951 workflows: add workflow to recreate linux self-hosted VM on schedule
  .github/workflows/recreate-runner.yml
Labels: CI-syntax-only, automerge-skip

#76283 wildfly-as 23.0.2
  Formula/wildfly-as.rb
Labels: bottle unneeded, bump-formula-pr, java, ready to merge

#77687 truncate: deprecate
  Formula/truncate.rb
Labels: CI-syntax-only, deprecated license, formula deprecated

#77691 rsstail: deprecate
  Formula/rsstail.rb
Labels: CI-syntax-only, deprecated license, formula deprecated

#77689 httping: deprecate
  Formula/httping.rb
Labels: CI-syntax-only, deprecated license, formula deprecated

#77690 multitail: deprecate
  Formula/multitail.rb
Labels: CI-syntax-only, deprecated license, formula deprecated

#77688 genstats: deprecate
  Formula/genstats.rb
Labels: CI-syntax-only, formula deprecated, missing license

#77692 libdshconfig: add livecheck
  Formula/libdshconfig.rb
Labels: CI-syntax-only, deprecated license, livecheck

#77697 osm: add build date to binary
  Formula/osm.rb
Labels: go

#77698 libdshconfig: update license
  Formula/libdshconfig.rb
Labels: CI-syntax-only, license

#77701 openvdb: update dependency comments
  Formula/openvdb.rb
Labels: CI-syntax-only

#77719 exploitdb 2021-05-21
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#77731 mysql: add Linux dependencies and flags
  Formula/mysql.rb
Labels: CI-syntax-only, linux to homebrew-core

#77746 composer 2.0.14
  Formula/composer.rb
Labels: bottle unneeded

#77774 ptex: add license
  Formula/ptex.rb
Labels: CI-syntax-only, license, no ARM bottle

#77783 open-zwave: add livecheck
  Formula/open-zwave.rb
Labels: CI-syntax-only, deprecated license, livecheck

#77806 ssss: add livecheck
  Formula/ssss.rb
Labels: CI-syntax-only, deprecated license, livecheck

#77835 exploitdb 2021-05-22
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#77838 geoserver 2.19.1
  Formula/geoserver.rb
Labels: bottle unneeded, bump-formula-pr, missing license

#77842 libunwind-headers 201
  Formula/libunwind-headers.rb
Labels: bottle unneeded, bump-formula-pr

#77832 ckan 1.30.2
  Formula/ckan.rb
Labels: bottle unneeded, bump-formula-pr

#77854 yarn: make fsevents test macOS specific
  Formula/yarn.rb
Labels: linux to homebrew-core, nodejs

#77865 open-zwave: update license
  Formula/open-zwave.rb
Labels: CI-syntax-only, license

#77867 detekt 1.17.1
  Formula/detekt.rb
Labels: bottle unneeded, bump-formula-pr, java

#77872 cairomm@1.14: update livecheck
  Formula/cairomm@1.14.rb
Labels: CI-syntax-only, legacy, livecheck

#77888 libserialport: add livecheck
  Formula/libserialport.rb
Labels: CI-syntax-only, deprecated license, livecheck

#77882 plantuml 1.2021.7
  Formula/plantuml.rb
Labels: bottle unneeded, bump-formula-pr, java

#77892 cargo-audit: add livecheck
  Formula/cargo-audit.rb
Labels: CI-syntax-only, livecheck, rust

#77879 ghostscript: build with brewed gcc on Linux
  Formula/ghostscript.rb
Labels: CI-syntax-only, linux to homebrew-core

#77919 exa: fix head completion install
  Formula/exa.rb
Labels: rust
