Repository Homebrew/homebrew-core, pull requests merged in 2021-10, with the labels that each got.

#86224 libgit2: set head default branch to main
  Formula/libgit2.rb
Labels: CI-syntax-only

#86240 mmsrip: add livecheck
  Formula/mmsrip.rb
Labels: livecheck, CI-syntax-only, deprecated license

#86292 brotli: add HTTP mirror
  Formula/brotli.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#86293 gettext: add HTTP mirror
  Formula/gettext.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#86294 libidn2: add HTTP mirror
  Formula/libidn2.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#86295 libssh2: add HTTP mirror
  Formula/libssh2.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#86296 libunistring: add HTTP mirror
  Formula/libunistring.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#86297 openldap: add HTTP mirror
  Formula/openldap.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#86298 openssl@1.1: add HTTP mirror
  Formula/openssl@1.1.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#86299 pkg-config: add HTTP mirror
  Formula/pkg-config.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#86300 rtmpdump: add HTTP mirror
  Formula/rtmpdump.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#86301 zstd: add HTTP mirror
  Formula/zstd.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#86317 cloud-nuke: remove caveats
  Formula/cloud-nuke.rb
Labels: go, CI-syntax-only

#86331 libunwind: add livecheck
  Formula/libunwind.rb
Labels: livecheck, CI-syntax-only, linux-only

#85032 pkg-config: pour bottle only in default prefixes
  Formula/pkg-config.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#86227 zurl: fix build on Linux
  Formula/zurl.rb
Labels: linux to homebrew-core, CI-force-linux, CI-no-fail-fast, CI-no-bottles, no Linux bottle

#86377 uncrustify: move patches for 0.73.0 to formula-patches
  Formula/uncrustify.rb
Labels: CI-no-bottles

#86379 pbc-sig: add livecheck
  Formula/pbc-sig.rb
Labels: livecheck, CI-syntax-only, deprecated license, no Linux bottle

#86380 mesa: remove livecheck
  Formula/mesa.rb
Labels: livecheck, CI-syntax-only

#86383 opentsdb: update livecheck
  Formula/opentsdb.rb
Labels: java, livecheck, formula deprecated, CI-syntax-only, deprecated license, no Linux bottle

#86389 sqoop: remove livecheck
  Formula/sqoop.rb
Labels: java, livecheck, formula deprecated, CI-syntax-only

#86407 bsponmpi: depend on macOS because of Python 2
  Formula/bsponmpi.rb
Labels: formula deprecated, CI-syntax-only, macos-only

#86409 eye-d3: fix build for Linux
  Formula/eye-d3.rb
Labels: python, linux to homebrew-core, CI-force-linux, no Linux bottle

#86417 xpdf: fix build on Linux
  Formula/xpdf.rb
Labels: linux to homebrew-core, CI-force-linux, CI-no-fail-fast, no Linux bottle

#86443 gource: fix build on Linux
  Formula/gource.rb
Labels: linux to homebrew-core, CI-force-linux, CI-no-bottles, no Linux bottle

#84537 dspdfviewer: fix build on Linux and use poppler-qt5
  Formula/dspdfviewer.rb
Labels: in progress, linux to homebrew-core, CI-force-linux, CI-no-fail-fast, no Linux bottle

#86521 psc-package: fix build and use ghc 8.10
  Formula/psc-package.rb
Labels: haskell, linux to homebrew-core, CI-force-arm, CI-force-linux, no Linux bottle

#88322 charge: call `deuniversalize_machos`
  Formula/charge.rb
Labels: nodejs, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88320 enet: patch incorrect -flat_namespace usage
  Formula/enet.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88321 chmlib: patch incorrect -flat_namespace usage
  Formula/chmlib.rb
Labels: deprecated license, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88318 libpgm: patch incorrect -flat_namespace usage
  Formula/libpgm.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88319 dhcping: use HTTPS
  Formula/dhcping.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88314 choose-gui: build a native binary
  Formula/choose-gui.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88313 openfst: patch incorrect -flat_namespace usage
  Formula/openfst.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88312 libdc1394: patch incorrect -flat_namespace usage
  Formula/libdc1394.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88310 h3: fix ARM build
  Formula/h3.rb
Labels: CI-force-arm, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88308 memtester: use HTTPS
  Formula/memtester.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88307 gearman: patch incorrect -flat_namespace usage
  Formula/gearman.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88306 cracklib: patch incorrect -flat_namespace usage
  Formula/cracklib.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88305 mogenerator: build a native binary
  Formula/mogenerator.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88304 sqliteodbc: patch incorrect -flat_namespace usage
  Formula/sqliteodbc.rb
Labels: missing license, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88302 ppl: patch incorrect -flat_namespace usage
  Formula/ppl.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88301 libngspice: patch incorrect -flat_namespace usage
  Formula/libngspice.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88282 isc-dhcp: remove explicitly specified `version`
  Formula/isc-dhcp.rb
Labels: test failure, 12

#88281 crf++: patch incorrect -flat_namespace usage
  Formula/crf++.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88283 userspace-rcu: patch incorrect -flat_namespace usage
  Formula/userspace-rcu.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88284 cmu-sphinxbase: patch incorrect -flat_namespace usage
  Formula/cmu-sphinxbase.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88285 libp11: patch incorrect -flat_namespace usage
  Formula/libp11.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88286 argtable: patch incorrect -flat_namespace usage
  Formula/argtable.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88287 exempi: patch incorrect -flat_namespace usage
  Formula/exempi.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88288 rpcgen: build a native binary
  Formula/rpcgen.rb
Labels: missing license, CI-skip-recursive-dependents, macos-only, CI-skip-dependents, CI-no-bottles

#88290 macosvpn: build a native binary
  Formula/macosvpn.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88292 hexo: call `deuniversalize_machos`
  Formula/hexo.rb
Labels: nodejs, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88293 systemc: patch incorrect -flat_namespace usage
  Formula/systemc.rb
Labels: no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88294 wandio: patch incorrect -flat_namespace usage
  Formula/wandio.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88296 libart: patch incorrect -flat_namespace usage
  Formula/libart.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88297 yaz: patch incorrect -flat_namespace usage
  Formula/yaz.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88311 raptor: patch incorrect -flat_namespace usage
  Formula/raptor.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88289 libcanberra: patch incorrect -flat_namespace usage
  Formula/libcanberra.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88300 libicns: patch incorrect -flat_namespace usage
  Formula/libicns.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88299 libcdio: patch incorrect -flat_namespace usage
  Formula/libcdio.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88298 libdaemon: patch incorrect -flat_namespace usage
  Formula/libdaemon.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88295 libpipeline: use HTTPS for `homepage`
  Formula/libpipeline.rb
Labels: CI-syntax-only, 12

#88349 gopls: update livecheck
  Formula/gopls.rb
Labels: go, livecheck, CI-syntax-only

#88337 libetpan: build native binaries
  Formula/libetpan.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88338 xcproj: build a native binary
  Formula/xcproj.rb
Labels: missing license, CI-skip-recursive-dependents, macos-only, CI-skip-dependents, CI-no-bottles

#88339 swimat: build a native binary
  Formula/swimat.rb
Labels: CI-skip-recursive-dependents, macos-only, CI-skip-dependents, CI-no-bottles

#88340 mjpegtools: patch incorrect -flat_namespace usage
  Formula/mjpegtools.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88341 pgpool-ii: patch incorrect -flat_namespace usage
  Formula/pgpool-ii.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88342 gnu-apl: patch incorrect -flat_namespace usage
  Formula/gnu-apl.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88345 spandsp: patch incorrect -flat_namespace usage
  Formula/spandsp.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88346 atf: patch incorrect -flat_namespace usage
  Formula/atf.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88348 lutok: patch incorrect -flat_namespace usage
  Formula/lutok.rb
Labels: lua, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88347 getmail: use HTTPS
  Formula/getmail.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88351 liboauth: patch incorrect -flat_namespace usage
  Formula/liboauth.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88355 clblas: fix test for ARM
  Formula/clblas.rb
Labels: CI-force-arm, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88359 sword: patch incorrect -flat_namespace usage
  Formula/sword.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88360 liboping: patch incorrect -flat_namespace usage
  Formula/liboping.rb
Labels: perl, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88362 cpptest: patch incorrect -flat_namespace usage
  Formula/cpptest.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88363 dante: patch incorrect -flat_namespace usage
  Formula/dante.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88367 loudmouth: patch incorrect -flat_namespace usage
  Formula/loudmouth.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88368 scamper: patch incorrect -flat_namespace usage
  Formula/scamper.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88369 pbc: patch incorrect -flat_namespace usage
  Formula/pbc.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88371 unittest-cpp: patch incorrect -flat_namespace usage
  Formula/unittest-cpp.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88373 libpano: patch incorrect -flat_namespace usage
  Formula/libpano.rb
Labels: missing license, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88374 primesieve: set `CMAKE_INSTALL_RPATH`
  Formula/primesieve.rb
Labels: CI-force-arm, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88370 configen: build a native binary
  Formula/configen.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88361 gammu: set `CMAKE_INSTALL_RPATH`
  Formula/gammu.rb
Labels: CI-force-arm, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88409 libbinio: patch incorrect -flat_namespace usage
  Formula/libbinio.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88410 imageworsener: patch incorrect -flat_namespace usage
  Formula/imageworsener.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88411 libpcl: patch incorrect -flat_namespace usage
  Formula/libpcl.rb
Labels: deprecated license, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88416 libcsv: patch incorrect -flat_namespace usage
  Formula/libcsv.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88417 gtkextra: patch incorrect -flat_namespace usage
  Formula/gtkextra.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88418 htmlcxx: patch incorrect -flat_namespace usage
  Formula/htmlcxx.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88419 recutils: patch incorrect -flat_namespace usage
  Formula/recutils.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88382 itex2mml: fix livecheck
  Formula/itex2mml.rb
Labels: livecheck, CI-syntax-only, no Linux bottle

#88434 kytea: patch incorrect -flat_namespace usage
  Formula/kytea.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88435 csmith: patch incorrect -flat_namespace usage
  Formula/csmith.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88437 genders: patch incorrect -flat_namespace usage
  Formula/genders.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88440 minetest: update livecheck
  Formula/minetest.rb
Labels: lua, livecheck, CI-syntax-only, no ARM bottle, no Linux bottle

#88450 rhino: update livecheck
  Formula/rhino.rb
Labels: java, livecheck, CI-syntax-only

#88439 libnghttp2: add link_overwrite for Linux
  Formula/libnghttp2.rb
Labels: CI-syntax-only

#88455 libgfshare: patch incorrect -flat_namespace usage
  Formula/libgfshare.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88451 libfishsound: patch incorrect -flat_namespace usage
  Formula/libfishsound.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88453 flickcurl: patch incorrect -flat_namespace usage
  Formula/flickcurl.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88456 psftools: regenerate `configure`
  Formula/psftools.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88449 libcmph: patch incorrect -flat_namespace usage
  Formula/libcmph.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88452 chadwick: patch incorrect -flat_namespace usage
  Formula/chadwick.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88454 owfs: patch incorrect -flat_namespace usage
  Formula/owfs.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88459 shadowenv: fix checksum
  Formula/shadowenv.rb
Labels: rust, CI-no-fail-fast, CI-no-bottles

#88458 wasm-pack: fix checksum
  Formula/wasm-pack.rb
Labels: rust, no ARM bottle, CI-no-fail-fast, CI-no-bottles

#88461 dotenv-linter: fix checksum
  Formula/dotenv-linter.rb
Labels: rust, CI-no-fail-fast, CI-no-bottles

#88466 v8: fix minor typo in comment
  Formula/v8.rb
Labels: CI-syntax-only

#88462 dfc: update homepage and tarball url
  Formula/dfc.rb
Labels: CI-no-bottles
