Repository Homebrew/homebrew-core, pull requests merged in 2021-04, with the labels that each got.

#74297 raptor: add livecheck
  Formula/raptor.rb
Labels: CI-syntax-only, livecheck, missing license

#73929 sqldiff: do not use absolute sqlite3 path in test, fixes test for Linux
  Formula/sqldiff.rb
Labels: linux to homebrew-core

#74327 ncmpcpp: only add -liconv to LDFLAGS on macOS
  Formula/ncmpcpp.rb
Labels: CI-syntax-only, linux to homebrew-core

#74326 mednafen: upstream Linux fix
  Formula/mednafen.rb
Labels: CI-syntax-only, linux to homebrew-core

#74319 ncurses: disable ada
  Formula/ncurses.rb
Labels: CI-syntax-only, linux to homebrew-core

#74325 helm: upstream Linux fix
  Formula/helm.rb
Labels: CI-syntax-only, go, linux to homebrew-core

#74334 pianobar: disable test in Linux CI
  Formula/pianobar.rb
Labels: CI-syntax-only, linux to homebrew-core

#74336 embulk: move from bintray
  Formula/embulk.rb
Labels: bottle unneeded, java

#74340 griffon: disable as unsupported
  Formula/griffon.rb
Labels: bottle unneeded, formula disabled, missing license

#74331 exploitdb 2021-04-01
  Formula/exploitdb.rb
Labels: bottle unneeded

#74330 vagrant-completion 2.2.15
  Formula/vagrant-completion.rb
Labels: bottle unneeded

#74329 libzdb: upstream Linux fixes
  Formula/libzdb.rb
Labels: linux to homebrew-core

#74328 libxc: change order of linker flags in test
  Formula/libxc.rb
Labels: linux to homebrew-core

#74343 hpack: uses zlib from macos
  Formula/hpack.rb
Labels: CI-syntax-only, haskell, linux to homebrew-core, no ARM bottle

#74339 golo: move to eclipse
  Formula/golo.rb
Labels: bottle unneeded, java

#74346 flank 21.04.0
  Formula/flank.rb
Labels: bottle unneeded, java

#74351 scalaenv 0.1.10
  Formula/scalaenv.rb
Labels: bottle unneeded

#74347 flyway 7.7.2
  Formula/flyway.rb
Labels: bottle unneeded, java

#74354 geogram: add livecheck
  Formula/geogram.rb
Labels: CI-syntax-only, livecheck, no ARM bottle

#74367 ncmpcpp: uses curl from macos
  Formula/ncmpcpp.rb
Labels: CI-syntax-only, linux to homebrew-core

#74377 duck: update livecheck
  Formula/duck.rb
Labels: CI-syntax-only, automerge-skip, livecheck

#74324 icu4c: upstream Linux test fix
  Formula/icu4c.rb
Labels: linux to homebrew-core

#74368 workflows: enable commit signing for BrewTestBot
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/linux-dispatch-build-bottle.yml
  .github/workflows/publish-commit-bottles.yml
  .github/workflows/remove-disabled-formulae.yml
Labels: automerge-skip

#74390 workflows: run container as linuxbrew user
  .github/workflows/linux-dispatch-build-bottle.yml
  .github/workflows/linux-pr-tests.yml
Labels: automerge-skip

#74370 quantlib: migrate from Bintray
  Formula/quantlib.rb
Labels: automerge-skip, bottle unneeded

#74423 poppler: only change dylibs on macOS
  Formula/poppler.rb
Labels: CI-syntax-only, linux to homebrew-core

#74417 tccutil: explicitly make macOS only
  Formula/tccutil.rb
Labels: CI-syntax-only, bottle unneeded, linux to homebrew-core

#74422 hackrf: upstream Linux fix
  Formula/hackrf.rb
Labels: linux to homebrew-core

#74421 log4cplus: change linker flag order
  Formula/log4cplus.rb
Labels: linux to homebrew-core

#74416 gengetopt: upstream Linux fix
  Formula/gengetopt.rb
Labels: CI-syntax-only, linux to homebrew-core, missing license

#74415 pumba: upstream test fix for Linux
  Formula/pumba.rb
Labels: go, linux to homebrew-core

#74413 metabase 0.38.3
  Formula/metabase.rb
Labels: bottle unneeded, java, nodejs

#74252 Upload bottles to GitHub Packages
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/publish-commit-bottles.yml
Labels: CI-syntax-only, automerge-skip, do not merge

#74432 hdf5-mpi: add livecheck, license
  Formula/hdf5-mpi.rb
Labels: CI-syntax-only, license, livecheck

#74414 whois: only use libiconv on macOS
  Formula/whois.rb
Labels: linux to homebrew-core

#74449 hdf5: update livecheck
  Formula/hdf5.rb
Labels: CI-syntax-only, livecheck

#74051 scipy: upstream Linux fix
  Formula/scipy.rb
Labels: linux to homebrew-core, python

#74473 bench: upstream Linux fix
  Formula/bench.rb
Labels: CI-syntax-only, haskell, linux to homebrew-core, no ARM bottle

#74471 bluepill: explicitly make macOS only
  Formula/bluepill.rb
Labels: CI-syntax-only, linux to homebrew-core

#74453 libpeas: add -lintl flag only on mac
  Formula/libpeas.rb
Labels: linux to homebrew-core, python

#74452 ldns: add mac-only flags only on mac
  Formula/ldns.rb
Labels: linux to homebrew-core, python

#71854 util-linux: add linux-only dependency, make keg-only only on mac
  Formula/util-linux.rb
Labels: CI-syntax-only, linux to homebrew-core

#74470 navi: upstream Linux fix
  Formula/navi.rb
Labels: CI-syntax-only, linux to homebrew-core, rust

#74412 ldpl: upstream Linux fix
  Formula/ldpl.rb
Labels: CI-syntax-only, linux to homebrew-core

#74468 workflows: set committer for `git-try-push` action
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/linux-dispatch-build-bottle.yml
  .github/workflows/publish-commit-bottles.yml
Labels: automerge-skip

#74438 atlassian-cli: remove
  Aliases/stash-cli
  Formula/atlassian-cli.rb
Labels: CI-syntax-only, automerge-skip, bottle unneeded, java, marked for removal/rejection, missing license

#74487 grepcidr: add livecheck
  Formula/grepcidr.rb
Labels: CI-syntax-only, deprecated license, livecheck

#74492 yadm 3.1.0
  Formula/yadm.rb
Labels: bottle unneeded

#74488 phpstan 0.12.83
  Formula/phpstan.rb
Labels: bottle unneeded, php

#74472 locateme: explicitly make macOS only
  Formula/locateme.rb
Labels: CI-syntax-only, linux to homebrew-core

#74512 plantuml 1.2021.4
  Formula/plantuml.rb
Labels: bottle unneeded, java

#74521 maven 3.8.1
  Aliases/maven@3.8
  Formula/maven.rb
Labels: automerge-skip

#74524 google-java-format 1.10.0
  Formula/google-java-format.rb
Labels: bottle unneeded, java

#74527 sbt 1.5.0
  Formula/sbt.rb
Labels: bottle unneeded, java

#74529 sbtenv 0.0.22
  Formula/sbtenv.rb
Labels: bottle unneeded

#74542 tinycdb: add livecheck
  Formula/tinycdb.rb
Labels: CI-syntax-only, livecheck, missing license

#74536 glyr: upstream Linux fix
  Formula/glyr.rb
Labels: CI-syntax-only, linux to homebrew-core

#74534 x264: change order of linker flags
  Formula/x264.rb
Labels: linux to homebrew-core

#74454 swi-prolog: remove clang paths
  Formula/swi-prolog.rb
Labels: linux to homebrew-core

#74554 ripmime: set -liconv flag only on mac
  Formula/ripmime.rb
Labels: linux to homebrew-core

#74555 pup: fix platform for Linux
  Formula/pup.rb
Labels: go, linux to homebrew-core

#74557 percona-toolkit: always install DBI
  Formula/percona-toolkit.rb
Labels: linux to homebrew-core, perl

#74558 ntl: align test with Linux version
  Formula/ntl.rb
Labels: linux to homebrew-core, missing license

#74564 pup: fix platform for Linux
  Formula/pup.rb
Labels: go, linux to homebrew-core

#74552 sdl_mixer: set cocoa flag only on macOS
  Formula/sdl_mixer.rb
Labels: linux to homebrew-core

#74559 plotutils: depend on libx11/libxaw stack on Linux
  Formula/plotutils.rb
Labels: linux to homebrew-core, missing license

#74566 plotutils: add license
  Formula/plotutils.rb
Labels: CI-syntax-only, license

#74553 rtags: set -lc++abi flag only on macOS
  Formula/rtags.rb
Labels: linux to homebrew-core

#74574 jflex: add livecheck
  Formula/jflex.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck, missing license

#74582 juman: add livecheck
  Formula/juman.rb
Labels: CI-syntax-only, livecheck, missing license

#74583 cln: add livecheck
  Formula/cln.rb
Labels: CI-syntax-only, deprecated license, livecheck, no ARM bottle

#74578 tests.yml: remove spaces in logs/failed bottles directory
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip

#74584 zeek: add a pcap test
  Formula/zeek.rb
Labels: automerge-skip, bottle unneeded, python

#74576 nvm 0.38.0
  Formula/nvm.rb
Labels: bottle unneeded

#74573 ruby-build 20210405
  Formula/ruby-build.rb
Labels: bottle unneeded

#74591 clojure 1.10.3.822
  Formula/clojure.rb
Labels: bottle unneeded, java, ruby

#74556 pueue: tweak test path on Linux to fix test
  Formula/pueue.rb
Labels: linux to homebrew-core, rust

#74535 glui: upstream Linux fix
  Formula/glui.rb
Labels: linux to homebrew-core

#74592 spotify-tui: update test
  Formula/spotify-tui.rb
Labels: automerge-skip, bottle unneeded, rust

#74567 buku: update test
  Formula/buku.rb
Labels: automerge-skip, bottle unneeded, python, rust

#74635 exploitdb 2021-04-06
  Formula/exploitdb.rb
Labels: bottle unneeded

#74632 redshift: upstream Linux fix
  Formula/redshift.rb
Labels: license, linux to homebrew-core

#74673 workflows/triage: update legacy exceptions
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip

#74677 howdoi: update test
  Formula/howdoi.rb
Labels: python

#74633 micropython: upstream Linux fix
  Formula/micropython.rb
Labels: linux to homebrew-core, no ARM bottle, python

#74547 unrtf: set -liconv only on macOS
  Formula/unrtf.rb
Labels: license, linux to homebrew-core

#74711 dwm: add livecheck
  Formula/dwm.rb
Labels: CI-syntax-only, livecheck

#74676 splint: add license
  Formula/splint.rb
Labels: CI-syntax-only, license

#74722 knot: upstream Linux fix
  Formula/knot.rb
Labels: CI-syntax-only, linux to homebrew-core

#74721 eureka: upstream Linux fix
  Formula/eureka.rb
Labels: CI-syntax-only, linux to homebrew-core, rust

#74717 duckscript: upstream Linux fix
  Formula/duckscript.rb
Labels: CI-syntax-only, linux to homebrew-core, rust

#74716 wxmaxima: upstream Linux fix
  Formula/wxmaxima.rb
Labels: CI-syntax-only, linux to homebrew-core

#74715 rtmpdump: upstream Linux fix
  Formula/rtmpdump.rb
Labels: linux to homebrew-core

#74713 libtorrent-rakshasa: upstream Linux fix
  Formula/libtorrent-rakshasa.rb
Labels: CI-syntax-only, license, linux to homebrew-core

#74661 tmux: fix HEAD on Linux
  Formula/tmux.rb
Labels: CI-syntax-only

#74731 exploitdb 2021-04-07
  Formula/exploitdb.rb
Labels: bottle unneeded

#74723 virtuoso: upstream Linux fix
  Formula/virtuoso.rb
Labels: CI-syntax-only, license, linux to homebrew-core, no ARM bottle

#74746 orgalorg: tweak test args
  Formula/orgalorg.rb
Labels: automerge-skip, bottle unneeded, go

#74752 github/workflows: use simpler GitHub Packages `--root-url`.
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/publish-commit-bottles.yml
Labels: CI-syntax-only, automerge-skip

#74750 jenkins 2.287
  Formula/jenkins.rb
Labels: bottle unneeded, java

#74647 Update token usage
  .github/workflows/autopublish.yml
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/linux-dispatch-build-bottle.yml
  .github/workflows/publish-commit-bottles.yml
  .github/workflows/remove-disabled-formulae.yml
  .github/workflows/triage.yml
Labels: automerge-skip

#74757 workflows/publish-commit-bottles: fix token usage
  .github/workflows/publish-commit-bottles.yml
Labels: CI-syntax-only, automerge-skip

#74753 jenkins-lts 2.277.2
  Formula/jenkins-lts.rb
Labels: bottle unneeded, java

#74678 gcc: set mac-only flags and workarounds only on mac
  Formula/gcc.rb
Labels: linux to homebrew-core

#74782 mongo-cxx-driver: fix rpath for ARM
  Formula/mongo-cxx-driver.rb
Labels: CI-force-arm, no ARM bottle

#74720 libusb: upstream Linux fix
  Formula/libusb.rb
Labels: linux to homebrew-core

#74679 llvm: add linux dependencies, set platform-specific flags
  Formula/llvm.rb
Labels: linux to homebrew-core, python

#74795 exploitdb 2021-04-08
  Formula/exploitdb.rb
Labels: bottle unneeded

#74810 curlftps: remove commented out dependency
  Formula/curlftpfs.rb
Labels: CI-syntax-only, missing license

#74815 publish workflows: flip Bintray/GitHub packages logic
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/publish-commit-bottles.yml
Labels: CI-syntax-only, automerge-skip

#74819 flyway 7.7.3
  Formula/flyway.rb
Labels: bottle unneeded, java

#74737 rbspy: update formula's test fixture format
  Formula/rbspy.rb
Labels: rust

#74821 prestodb 0.250
  Formula/prestodb.rb
Labels: bottle unneeded, java

#74847 jpeginfo: add livecheck
  Formula/jpeginfo.rb
Labels: CI-syntax-only, livecheck

#74846 cask 0.8.7
  Formula/cask.rb
Labels: bottle unneeded, test failure

#74865 workflows/publish-commit-bottles: change `pr-pull` token
  .github/workflows/publish-commit-bottles.yml
Labels: automerge-skip

#74883 id3tool: add livecheck
  Formula/id3tool.rb
Labels: CI-syntax-only, livecheck, missing license

#74884 id3tool: add license
  Formula/id3tool.rb
Labels: CI-syntax-only, license

#74896 gradle 7.0
  Formula/gradle.rb
Labels: bottle unneeded, java

#74219 systemd (new formula)
  .github/workflows/linux-pr-tests.yml
  Formula/systemd.rb
Labels: automerge-skip, linux to homebrew-core

#74906 net-tools (new formula)
  .github/workflows/linux-pr-tests.yml
  Formula/net-tools.rb
Labels: automerge-skip, linux to homebrew-core

#74920 kops: update livecheck
  Formula/kops.rb
Labels: CI-syntax-only, go, livecheck

#74924 Fixing homepage of expect
  Formula/expect.rb
Labels: CI-syntax-only

#74925 awscli: Fix test
  Formula/awscli.rb
Labels: python

#74928 formulae*: add linux dependencies
  Formula/freerdp.rb
  Formula/hidapi.rb
  Formula/libfido2.rb
  Formula/openvpn.rb
Labels: CI-syntax-only, linux to homebrew-core

#74469 libedit: upstream Linux fix
  Formula/libedit.rb
Labels: CI-syntax-only, linux to homebrew-core

#74858 monero: add livecheck
  Formula/monero.rb
Labels: CI-syntax-only, do not merge, livecheck

#74927 tendermint: Fix test
  Formula/tendermint.rb
Labels: go

#74636 splint: upstream Linux fix
  Formula/splint.rb
Labels: CI-syntax-only, linux to homebrew-core, ready to merge

#74551 swig: add linux-compatible test
  Formula/swig.rb
Labels: linux to homebrew-core, ruby

#74961 swig: create test.i file for Linux too
  Formula/swig.rb
Labels: linux to homebrew-core, ruby

#74949 gcc@4.9: split args for macOS and Linux
  Formula/gcc@4.9.rb
Labels: formula deprecated, legacy, linux to homebrew-core, missing license

#74965 cimg 2.9.7
  Formula/cimg.rb
Labels: bottle unneeded

#74995 usb.ids 2021.03.31
  Formula/usb.ids.rb
Labels: bottle unneeded

#74964 fibjs: align with linux version
  Formula/fibjs.rb
Labels: linux to homebrew-core, no ARM bottle

#74978 zsh-vi-mode 0.8.2
  Formula/zsh-vi-mode.rb
Labels: bottle unneeded, new formula

#74984 libcdr: add license
  Formula/libcdr.rb
Labels: CI-syntax-only, license, ready to merge

#74976 lcov: update test
  Formula/lcov.rb
Labels: automerge-skip, bottle unneeded, perl

#74986 libva 2.11.0
  Formula/libva.rb
Labels: bottle unneeded, linux-only

#74977 libtensorflow: update test
  Formula/libtensorflow.rb
Labels: automerge-skip, bottle unneeded, no ARM bottle

#75021 github/workflows: remove Bintray upload.
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/linux-dispatch-build-bottle.yml
  .github/workflows/publish-commit-bottles.yml
Labels: CI-syntax-only, automerge-skip

#75036 mysql++: add livecheck
  Formula/mysql++.rb
Labels: CI-syntax-only, livecheck

#75044 workflows: update Big Sur runner labels
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/tests.yml
Labels: automerge-skip

#75049 issue template: remind users to `brew update`
  .github/ISSUE_TEMPLATE/bug.yml
Labels: CI-syntax-only, automerge-skip

#75087 Revert "issue template: remind users to `brew update`"
  .github/ISSUE_TEMPLATE/bug.yml
Labels: CI-syntax-only, automerge-skip

#75024 github/workflows: bottle with `--only-json-tab`
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/linux-dispatch-build-bottle.yml
  .github/workflows/tests.yml
Labels: automerge-skip

#75088 bug.yml: update issue template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: CI-syntax-only, automerge-skip

#75058 libfuse 3.10.3
  Formula/libfuse.rb
Labels: bottle unneeded, linux-only

#75103 librasterlite: add livecheck
  Formula/librasterlite.rb
Labels: CI-syntax-only, livecheck, missing license

#75104 vamp-plugin-sdk: add livecheck
  Formula/vamp-plugin-sdk.rb
Labels: CI-syntax-only, livecheck, missing license
