Repository Homebrew/homebrew-core, pull requests merged in 2021-03, with the labels that each got.

#72189 phpstan 0.12.80
  Formula/phpstan.rb
Labels: bottle unneeded, php

#72226 grc 1.12
  Formula/grc.rb
Labels: bottle unneeded, python

#72232 libomp: update livecheck
  Formula/libomp.rb
Labels: CI-syntax-only, livecheck

#72236 mysql-connector-c++: update livecheck
  Formula/mysql-connector-c++.rb
Labels: CI-syntax-only, livecheck, missing license

#72237 libbluray: update livecheck
  Formula/libbluray.rb
Labels: CI-syntax-only, livecheck

#72241 luajit: update livecheck
  Formula/luajit.rb
Labels: CI-syntax-only, livecheck, no ARM bottle

#72242 rtmpdump: update livecheck
  Formula/rtmpdump.rb
Labels: CI-syntax-only, livecheck

#72261 zmqpp: make test portable, these flags are not needed
  Formula/zmqpp.rb
Labels: linux to homebrew-core

#72272 gdcm: -undefined dynamic_lookup is macOS only
  Formula/gdcm.rb
Labels: linux to homebrew-core, python

#72245 minimal-racket: update livecheck
  Formula/minimal-racket.rb
Labels: CI-syntax-only, livecheck

#72255 step: remove dep build dependency
  Formula/step.rb
Labels: CI-force-arm, go, no ARM bottle

#72310 jenkins 2.282
  Formula/jenkins.rb
Labels: bottle unneeded, java

#72267 ykman: add cflags for linux-only pcsc-lite dependency
  Formula/ykman.rb
Labels: linux to homebrew-core, python

#72264 ykpers: set platform specific backend
  Formula/ykpers.rb
Labels: linux to homebrew-core

#72317 docfx 2.56.7
  Formula/docfx.rb
Labels: bottle unneeded

#72313 libxml2: don't require python at runtime
  Formula/libxml2.rb
Labels: automerge-skip, bottle unneeded

#72270 wallpaper: depends on macos
  Formula/wallpaper.rb
Labels: CI-syntax-only, linux to homebrew-core, swift

#70536 liquidprompt 2.0.2
  Formula/liquidprompt.rb
Labels: bottle unneeded

#72401 ktoblzcheck: fix build for ARM, update license
  Formula/ktoblzcheck.rb
Labels: CI-force-arm, automerge-skip, bottle unneeded, license, no ARM bottle, python

#72404 varnish: update url
  Formula/varnish.rb
Labels: automerge-skip, bottle unneeded

#72419 asdf: disable update command (currently runs git commands inside brew repo)
  Formula/asdf.rb
Labels: bottle unneeded

#72437 sqlmap 1.5.3
  Formula/sqlmap.rb
Labels: bottle unneeded

#72449 petsc: update livecheck
  Formula/petsc.rb
Labels: CI-syntax-only, livecheck

#72421 asdf: update test
  Formula/asdf.rb
Labels: bottle unneeded

#72459 cvs-fast-export: add missing linux dependencies
  Formula/cvs-fast-export.rb
Labels: no ARM bottle

#72462 exploitdb 2021-03-04
  Formula/exploitdb.rb
Labels: bottle unneeded

#72471 rabbitmq-c: aarch64 build fix
  Formula/rabbitmq-c.rb
Labels: CI-force-arm, automerge-skip, bottle unneeded, no ARM bottle

#72468 php@7.4: allow fpm as root for tests
  Formula/php@7.4.rb
Labels: formula deprecated, legacy

#72455 git-tf: deprecate
  Formula/git-tf.rb
Labels: bottle unneeded, formula deprecated, missing license

#72456 tdkjs: deprecate
  Formula/tdkjs.rb
Labels: automerge-skip, bottle unneeded, formula deprecated, nodejs

#72479 buildozer: remove livecheck
  Formula/buildozer.rb
Labels: CI-syntax-only, go, livecheck

#72488 jsonschema2pojo 1.1.0
  Formula/jsonschema2pojo.rb
Labels: bottle unneeded, java

#72487 jruby 9.2.16.0
  Formula/jruby.rb
Labels: bottle unneeded, java

#72533 repo 2.13.2
  Formula/repo.rb
Labels: bottle unneeded, python

#72531 cromwell 58
  Formula/cromwell.rb
Labels: bottle unneeded, java

#72549 exploitdb 2021-03-05
  Formula/exploitdb.rb
Labels: bottle unneeded

#72558 closure-compiler 20210302
  Formula/closure-compiler.rb
Labels: bottle unneeded, java

#72574 metabase 0.38.1
  Formula/metabase.rb
Labels: bottle unneeded, java, nodejs

#72094 go: do not install test/debug files
  Formula/go.rb
Labels: linux to homebrew-core

#72585 fakeroot: add linux-only dependency
  Formula/fakeroot.rb
Labels: CI-syntax-only, deprecated license, linux to homebrew-core

#72588 ftgl: depend on mesa-glu on Linux
  Formula/ftgl.rb
Labels: automerge-skip, bottle unneeded, linux to homebrew-core, missing license

#72587 fontforge: make caveats mac only
  Formula/fontforge.rb
Labels: CI-syntax-only, linux to homebrew-core, missing license, no ARM bottle, python

#72596 bonnie++: fix livecheck
  Formula/bonnie++.rb
Labels: CI-syntax-only, livecheck

#72506 workflows/tests: use HOMEBREW_SIMULATE_MACOS_ON_LINUX
  .github/workflows/tests.yml
Labels: automerge-skip

#72595 rerepro: prefer system gcc on Linux
  Formula/reprepro.rb
Labels: linux to homebrew-core, missing license

#72614 cake 1.1.0
  Formula/cake.rb
Labels: bottle unneeded

#72593 fftw: prefer system gcc on Linux
  Formula/fftw.rb
Labels: linux to homebrew-core

#72609 ckan 1.30.0
  Formula/ckan.rb
Labels: bottle unneeded

#72589 abyss: prefer system gcc on Linux
  Formula/abyss.rb
Labels: linux to homebrew-core

#72632 python@3.7: add Linux build
  Formula/python@3.7.rb
Labels: automerge-skip, bottle unneeded, legacy, no ARM bottle

#72640 stockfish: update livecheck
  Formula/stockfish.rb
Labels: CI-syntax-only, livecheck

#72577 stanford-corenlp 4.2.0
  Formula/stanford-corenlp.rb
Labels: bottle unneeded, java, missing license

#72659 stanford-corenlp: add license
  Formula/stanford-corenlp.rb
Labels: CI-syntax-only, bottle unneeded, java, license

#72664 plantuml 1.2021.2
  Formula/plantuml.rb
Labels: bottle unneeded, java

#72672 stanford-ner-4.2.0
  Formula/stanford-ner.rb
Labels: bottle unneeded, java

#72673 stanford-parser-4.2.0
  Formula/stanford-parser.rb
Labels: bottle unneeded, java

#72697 qcachegrind: update livecheck
  Formula/qcachegrind.rb
Labels: CI-syntax-only, livecheck

#72217 libfuse 3.10.2
  Formula/libfuse.rb
Labels: bottle unneeded, linux-only

#72707 dependecy-check 6.1.2
  Formula/dependency-check.rb
Labels: bottle unneeded, java

#72688 fio: update license
  Formula/fio.rb
Labels: CI-syntax-only, license

#72652 aescrypt: add livecheck block
  Formula/aescrypt.rb
Labels: CI-syntax-only, license, livecheck

#72668 hardlink: fix Linux build and add better test
  Formula/hardlink.rb
Labels: automerge-skip, bottle unneeded, missing license

#72669 various formulae: use `Time` instead of shelling out to `date`
  Formula/ksync.rb
Labels: automerge-skip, bottle unneeded, go

#72671 python@3.8: add Linux build
  Formula/python@3.8.rb
Labels: automerge-skip, bottle unneeded, legacy

#72723 workflows: rename test workflows
  .github/workflows/linux-pr-tests-wheezy.yml
  .github/workflows/linux-pr-tests.yml
  .github/workflows/tests.yml
Labels: automerge-skip

#72729 sbtenv 0.0.18
  Formula/sbtenv.rb
Labels: bottle unneeded

#72734 python@3.8: align test with other versions
  Formula/python@3.8.rb
Labels: CI-syntax-only, legacy

#72736 libressl: postinstall code is mac-only
  Formula/libressl.rb
Labels: linux to homebrew-core

#72738 wolfssl: add mac flag only on macOS
  Formula/wolfssl.rb
Labels: automerge-skip, bottle unneeded, linux to homebrew-core

#72746 cask 0.8.6
  Formula/cask.rb
Labels: bottle unneeded

#72758 phpstan 0.12.81
  Formula/phpstan.rb
Labels: bottle unneeded, php

#72745 bats-core 1.3.0
  Formula/bats-core.rb
Labels: bottle unneeded

#72766 apache-forrest: deprecate
  Formula/apache-forrest.rb
Labels: formula deprecated, java

#72774 spotifyd: fix build for Linux
  Formula/spotifyd.rb
Labels: linux to homebrew-core, no ARM bottle, rust

#72777 gpac: fix build for Linux
  Formula/gpac.rb
Labels: linux to homebrew-core

#72778 libspng: fix build for Linux
  Formula/libspng.rb
Labels: linux to homebrew-core

#72779 feh: fix build for Linux
  Formula/feh.rb
Labels: linux to homebrew-core

#72776 exploitdb 2021-03-09
  Formula/exploitdb.rb
Labels: bottle unneeded

#72785 sbt 1.4.8
  Formula/sbt.rb
Labels: bottle unneeded, java

#72795 jenkins 2.283
  Formula/jenkins.rb
Labels: bottle unneeded, java

#72808 bdw-gc: needs gcc headers for test
  Formula/bdw-gc.rb
Labels: CI-syntax-only, linux to homebrew-core

#72806 ansible@2.9: set mac env variables only on mac
  Formula/ansible@2.9.rb
Labels: legacy, linux to homebrew-core, python

#72805 ansible@2.8: set mac env variables only on mac
  Formula/ansible@2.8.rb
Labels: deprecated license, legacy, linux to homebrew-core, no ARM bottle, python, rust

#72811 botan: let the build script detect the platform and compiler
  Formula/botan.rb
Labels: linux to homebrew-core, python

#72804 ansible: set mac env variables only on mac
  Formula/ansible.rb
Labels: automerge-skip, bottle unneeded, linux to homebrew-core, python, rust

#72815 rancher-cli: update livecheck
  Formula/rancher-cli.rb
Labels: CI-syntax-only, go, livecheck

#72823 wcslib: update livecheck
  Formula/wcslib.rb
Labels: CI-syntax-only, livecheck

#72796 composer: update checksum
  Formula/composer.rb
Labels: bottle unneeded, checksum mismatch

#72818 ruby-build 20210309
  Formula/ruby-build.rb
Labels: bottle unneeded

#72825 percona-xtrabackup: update livecheck
  Formula/percona-xtrabackup.rb
Labels: CI-syntax-only, livecheck, missing license, perl

#72828 jumanpp: update livecheck
  Formula/jumanpp.rb
Labels: CI-syntax-only, livecheck

#72830 highlight: add livecheck
  Formula/highlight.rb
Labels: CI-syntax-only, livecheck, lua

#72843 ffe: update livecheck
  Formula/ffe.rb
Labels: CI-syntax-only, livecheck

#72841 lcs: add livecheck
  Formula/lcs.rb
Labels: CI-syntax-only, deprecated license, livecheck

#72822 lcov: use system gcc on Linux, depend on zlib
  Formula/lcov.rb
Labels: automerge-skip, bottle unneeded, linux to homebrew-core, perl

#72855 bison@2.7: fix build for Linux
  Formula/bison@2.7.rb
Labels: automerge-skip, bottle unneeded, legacy, linux to homebrew-core, missing license

#72862 neon: fix build for Linux
  Formula/neon.rb
Labels: automerge-skip, bottle unneeded, linux to homebrew-core, missing license

#72861 rrdtool: fix build for Linux
  Formula/rrdtool.rb
Labels: automerge-skip, bottle unneeded, deprecated license, linux to homebrew-core

#72858 zsh-navigation-tools: fix build for Linux
  Formula/zsh-navigation-tools.rb
Labels: automerge-skip, bottle unneeded, linux to homebrew-core, missing license

#72857 udunits: fix build for Linux
  Formula/udunits.rb
Labels: automerge-skip, bottle unneeded, linux to homebrew-core, missing license

#72860 terraforming: fix build for Linux
  Formula/terraforming.rb
Labels: automerge-skip, bottle unneeded, linux to homebrew-core, ruby

#72856 pypy3: remove useless (?) code
  Formula/pypy3.rb
Labels: automerge-skip, bottle unneeded

#72839 json_spirit: add livecheck
  Formula/json_spirit.rb
Labels: CI-syntax-only, livecheck

#72837 gnome-autoar: add livecheck
  Formula/gnome-autoar.rb
Labels: CI-syntax-only, livecheck

#72821 opencascade: update homepage, livecheck
  Formula/opencascade.rb
Labels: CI-syntax-only, livecheck

#72807 analog: add -lm flag for Linux and set os specific build targets
  Formula/analog.rb
Labels: linux to homebrew-core, missing license

#72874 exploitdb 2021-03-10
  Formula/exploitdb.rb
Labels: bottle unneeded

#72863 kim-api: fix build for Linux
  Formula/kim-api.rb
Labels: automerge-skip, bottle unneeded, linux to homebrew-core

#72866 neon: add license
  Formula/neon.rb
Labels: CI-syntax-only, license

#72820 libproxy: depend on glib and dbus for Linux
  Formula/libproxy.rb
Labels: CI-syntax-only, linux to homebrew-core, python

#72906 exiv2: fix rpath issue.
  Formula/exiv2.rb
Labels: CI-force-arm, automerge-skip, bottle unneeded, license, no ARM bottle

#72916 php-cs-fixer 2.18.3
  Formula/php-cs-fixer.rb
Labels: bottle unneeded, php

#72803 gromacs: fails with gcc 5 and 6
  Formula/gromacs.rb
Labels: linux to homebrew-core

#72941 lastpass: remove unneeded workaround and fix build on Linux
  Formula/lastpass-cli.rb
Labels: CI-syntax-only, automerge-skip, bottle unneeded, deprecated license

#72945 libvirt: fix build on Linux
  Formula/libvirt.rb
Labels: CI-syntax-only, automerge-skip, bottle unneeded, perl

#72933 volta: fix test issues for Linux
  Formula/volta.rb
Labels: CI-syntax-only, automerge-skip, bottle unneeded, no ARM bottle, rust

#72934 cling: fix build on Linux
  Formula/cling.rb
Labels: CI-syntax-only, automerge-skip, bottle unneeded

#72947 libnfc: fix build for Linux
  Formula/libnfc.rb
Labels: CI-syntax-only, deprecated license, linux to homebrew-core

#72950 urlview: fix for Linux
  Formula/urlview.rb
Labels: CI-syntax-only, linux to homebrew-core

#72952 lmod: fix for Linux
  Formula/lmod.rb
Labels: CI-syntax-only, automerge-skip, bottle unneeded, linux to homebrew-core, lua

#72905 bear: Add dependencies for Linux
  Formula/bear.rb
Labels: automerge-skip, bottle unneeded, python

#72963 volta: use canonical name for openssl
  Formula/volta.rb
Labels: linux to homebrew-core, no ARM bottle, rust

#70424 ethereum: fix build for Linux
  Formula/ethereum.rb
Labels: automerge-skip, bottle unneeded, go, linux to homebrew-core

#72965 exploitdb 2021-03-11
  Formula/exploitdb.rb
Labels: bottle unneeded

#72953 x3270: fix for Linux
  Formula/x3270.rb
Labels: CI-syntax-only, automerge-skip, bottle unneeded, linux to homebrew-core

#72977 python@3.9: fix fragile cellar paths on Linux too
  Formula/python@3.9.rb
Labels: CI-syntax-only, linux to homebrew-core

#72913 aws-google-auth: fix zlib paths for Linux
  Formula/aws-google-auth.rb
Labels: automerge-skip, bottle unneeded, linux to homebrew-core, python, rust

#72992 htpdate: update livecheck
  Formula/htpdate.rb
Labels: CI-syntax-only, livecheck, missing license

#72991 glibmm, atkmm: use brewed gcc on Linux
  Formula/atkmm.rb
  Formula/glibmm.rb
Labels: CI-syntax-only, linux to homebrew-core

#73020 xterm: update license
  Formula/xterm.rb
Labels: CI-syntax-only, license

#73009 grails 4.0.9
  Formula/grails.rb
Labels: bottle unneeded, java

#72914 buku: set expect for Linux
  Formula/buku.rb
Labels: automerge-skip, bottle unneeded, linux to homebrew-core, python, rust

#73037 exploitdb 2021-03-12
  Formula/exploitdb.rb
Labels: bottle unneeded

#73049 antlr 4.9.2
  Formula/antlr.rb
Labels: bottle unneeded, java

#73054 flyway 7.7.0
  Formula/flyway.rb
Labels: bottle unneeded, java

#73055 flank 21.03.1
  Formula/flank.rb
Labels: bottle unneeded, java

#73058 detekt 1.16.0
  Formula/detekt.rb
Labels: bottle unneeded, java

#73024 lensfun: add license
  Formula/lensfun.rb
Labels: CI-syntax-only, license, python, ready to merge

#72984 mmark: use stable resource URL
  Formula/mmark.rb
Labels: automerge-skip, bottle unneeded, go

#73093 ack 3.5.0
  Formula/ack.rb
Labels: bottle unneeded, perl

#73092 libelf: fix build for arm.
  Formula/libelf.rb
Labels: CI-force-arm, automerge-skip, bottle unneeded, no ARM bottle

#73098 exploitdb 2021-03-13
  Formula/exploitdb.rb
Labels: bottle unneeded

#73100 gource: update license
  Formula/gource.rb
Labels: CI-syntax-only, license

#73088 qscintilla2: fix build for Linux
  Formula/qscintilla2.rb
Labels: python

#73122 avrdude: add config.guess/config.sub workaround.
  Formula/avrdude.rb
Labels: CI-force-arm, automerge-skip, bottle unneeded, no ARM bottle

#73145 nspr: update livecheck
  Formula/nspr.rb
Labels: CI-syntax-only, livecheck

#72964 libx11: Fix issue with sed barfing on unicode characters
  Formula/libx11.rb
Labels: automerge-skip, bottle unneeded

#73118 glibc: skip livecheck
  Formula/glibc.rb
Labels: CI-syntax-only, bottle unneeded, linux-only, livecheck

#73109 fontforge: add license
  Formula/fontforge.rb
Labels: CI-syntax-only, license, no ARM bottle, python

#73159 cassandra-reaper: mark as bottle :unneeded
  Formula/cassandra-reaper.rb
Labels: CI-syntax-only, bottle unneeded, java
