Repository Homebrew/homebrew-core, pull requests merged in 2021-01, with the labels that each got.

#68110 checkstyle 8.39
  Formula/checkstyle.rb
Labels: 11-arm, bottle unneeded, java

#68107 artifactory 6.23.7
  Formula/artifactory.rb
Labels: 11-arm, bottle unneeded, java

#68124 ruby@2.5: deprecate
  Formula/ruby@2.5.rb
Labels: formula deprecated, legacy, no ARM bottle

#68120 signal-cli 0.7.2
  Formula/signal-cli.rb
Labels: 11-arm, bottle unneeded, java

#68129 dependency-check 6.0.4
  Formula/dependency-check.rb
Labels: 11-arm, bottle unneeded, java

#68142 flank 21.01.0
  Formula/flank.rb
Labels: bottle unneeded, java

#68154 Remove agda from dependency conflict allowlist
  audit_exceptions/versioned_dependencies_conflicts_allowlist.json
Labels: CI-syntax-only, automerge-skip

#68160 lilv: add livecheck
  Formula/lilv.rb
Labels: CI-syntax-only, livecheck

#68173 alure: remove livecheck
  Formula/alure.rb
Labels: CI-syntax-only, formula disabled, livecheck, missing license

#68174 libav: remove livecheck, add deprecation reference
  Formula/libav.rb
Labels: CI-syntax-only, formula deprecated, livecheck

#68175 openimageio: update livecheck
  Formula/openimageio.rb
Labels: CI-syntax-only, livecheck, no ARM bottle, python

#68176 nexus: update livecheck
  Formula/nexus.rb
Labels: CI-syntax-only, java, livecheck, no ARM bottle

#68178 pstree: add livecheck
  Formula/pstree.rb
Labels: CI-syntax-only, livecheck, missing license, no ARM bottle

#68179 libcanberra: add livecheck
  Formula/libcanberra.rb
Labels: CI-syntax-only, livecheck, missing license

#68180 kaitai-struct-compiler: add livecheck
  Formula/kaitai-struct-compiler.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck

#68181 mandoc: add livecheck
  Formula/mandoc.rb
Labels: CI-syntax-only, livecheck, missing license

#68182 par: add livecheck
  Formula/par.rb
Labels: CI-syntax-only, livecheck, missing license

#68201 pony-stable: deprecate in favor of corral
  Formula/pony-stable.rb
Labels: CI-syntax-only, formula deprecated

#68200 workflows/publish*: cache gems
  .github/workflows/publish-commit-bottles.yml
Labels: CI-syntax-only, automerge-skip

#68228 yaz: add livecheck
  Formula/yaz.rb
Labels: CI-syntax-only, livecheck

#68224 sqlmap 1.5
  Formula/sqlmap.rb
Labels: bottle unneeded, license

#68236 yaz: update livecheck
  Formula/yaz.rb
Labels: CI-syntax-only, livecheck

#68245 lua@5.1: deprecate
  Formula/lua@5.1.rb
Labels: formula deprecated, legacy

#68249 django-completion 3.1.5
  Formula/django-completion.rb
Labels: bottle unneeded

#68263 v2ray: add livecheck
  Formula/v2ray.rb
Labels: CI-syntax-only, go, livecheck, no ARM bottle

#68269 flyway 7.4.0
  Formula/flyway.rb
Labels: bottle unneeded, java

#68266 dyld-headers 832.7.1
  Formula/dyld-headers.rb
Labels: bottle unneeded

#68241 qt@5: create qt@5 alias and update qt alias
  Aliases/qt@5
  formula_renames.json
Labels: automerge-skip

#68185 tgenv 0.0.3 (new formula)
  Formula/tgenv.rb
Labels: bottle unneeded, new formula

#68317 picard-tools 2.24.0
  Formula/picard-tools.rb
Labels: 11-arm, bottle unneeded, java

#68309 squashfs: add livecheck
  Formula/squashfs.rb
Labels: CI-syntax-only, deprecated license, livecheck

#68323 phoronix-test-suite 10.2.0
  Formula/phoronix-test-suite.rb
Labels: bottle unneeded

#68334 exploitdb 2021-01-05
  Formula/exploitdb.rb
Labels: bottle unneeded

#68335 flank 21.01.1
  Formula/flank.rb
Labels: 11-arm, bottle unneeded, java

#68337 jenkins 2.274
  Formula/jenkins.rb
Labels: 11-arm, bottle unneeded, java

#68347 unison: update livecheck
  Formula/unison.rb
Labels: CI-syntax-only, livecheck, no ARM bottle, ocaml

#68349 kubeseal: update livecheck
  Formula/kubeseal.rb
Labels: CI-syntax-only, go, livecheck

#68351 tectonic: add livecheck
  Formula/tectonic.rb
Labels: CI-syntax-only, livecheck, rust

#68189 neovim: add linux-only dependencies, replace shims only on mac
  Formula/neovim.rb
Labels: linux to homebrew-core, lua, no ARM bottle

#67910 macvim: set -fdeclspec only for clang
  Formula/macvim.rb
Labels: linux to homebrew-core, lua, python, ruby, upstream issue

#68374 exploitdb 2021-01-06
  Formula/exploitdb.rb
Labels: bottle unneeded

#68373 crowdin 3.5.2
  Formula/crowdin.rb
Labels: bottle unneeded, java

#68371 atlassian-cli 9.5.0
  Formula/atlassian-cli.rb
Labels: bottle unneeded, java, missing license

#68391 antlr 4.9.1
  Formula/antlr.rb
Labels: bottle unneeded, java

#68397 ruby: add ruby@2 ruby@3 aliases
  Aliases/ruby@2
  Aliases/ruby@3
Labels: CI-syntax-only, automerge-skip

#68394 structurizr-cli 1.7.0
  Formula/structurizr-cli.rb
Labels: bottle unneeded, java

#68403 phpstan 0.12.65
  Formula/phpstan.rb
Labels: bottle unneeded, php

#67898 weechat: set -fdeclspec only for clang
  Formula/weechat.rb
Labels: linux to homebrew-core, lua, perl, python, ruby

#68436 libmemcached: make test portable (fix for Linux)
  Formula/libmemcached.rb
Labels: linux to homebrew-core, missing license

#68437 libmagic: make test portable (fix for Linux)
  Formula/libmagic.rb
Labels: linux to homebrew-core, missing license

#68449 libbitcoin: fix for Apple Silicon
  Formula/libbitcoin.rb
Labels: CI-force-arm, deprecated license, help wanted, no ARM bottle

#68452 dependency-check v6.0.5
  Formula/dependency-check.rb
Labels: bottle unneeded, java

#68466 scalaenv 0.1.5
  Formula/scalaenv.rb
Labels: bottle unneeded

#68468 basex 9.4.6
  Formula/basex.rb
Labels: bottle unneeded, java

#68420 prestodb 0.245.1
  Formula/prestodb.rb
Labels: bottle unneeded, java

#68489 yadm 3.0.2
  Formula/yadm.rb
Labels: bottle unneeded

#68501 json-glib: set -lintl flag only on mac
  Formula/json-glib.rb
Labels: CI-syntax-only, linux to homebrew-core

#68502 libdazzle: set mac-only flags only on mac
  Formula/libdazzle.rb
Labels: CI-syntax-only, linux to homebrew-core

#68503 libinfinity: set -lintl flag only on mac
  Formula/libinfinity.rb
Labels: CI-syntax-only, deprecated license, formula disabled, linux to homebrew-core

#68505 libxml++: set -lintl flag only on mac
  Formula/libxml++.rb
Labels: CI-syntax-only, linux to homebrew-core

#68509 libxml++3: set -lintl flag only on mac
  Formula/libxml++3.rb
Labels: CI-syntax-only, linux to homebrew-core

#68499 john: set linux target on linux
  Formula/john.rb
Labels: linux to homebrew-core, missing license

#68504 libxc: make test portable (fix for linux)
  Formula/libxc.rb
Labels: linux to homebrew-core

#68500 json-c: make test portable (fix for Linux)
  Formula/json-c.rb
Labels: linux to homebrew-core

#68523 openkim-models: add livecheck
  Formula/openkim-models.rb
Labels: CI-syntax-only, livecheck, missing license, no ARM bottle

#68540 libunwind-headers 200.10
  Formula/libunwind-headers.rb
Labels: bottle unneeded

#68536 bsdmake: add livecheck
  Formula/bsdmake.rb
Labels: CI-syntax-only, livecheck

#68537 libunwind-headers: add livecheck
  Formula/libunwind-headers.rb
Labels: CI-syntax-only, bottle unneeded, livecheck

#68538 mtoc: add livecheck
  Formula/mtoc.rb
Labels: CI-syntax-only, livecheck, missing license

#68539 rpcgen: add livecheck
  Formula/rpcgen.rb
Labels: CI-syntax-only, livecheck, missing license

#68573 dyld-headers: update livecheck
  Formula/dyld-headers.rb
Labels: CI-syntax-only, bottle unneeded, livecheck

#68549 neo4j 4.2.2
  Formula/neo4j.rb
Labels: bottle unneeded, java

#68563 basex: update sha
  Formula/basex.rb
Labels: bottle unneeded, checksum mismatch, java

#68586 alure: remove disable as site is back
  Formula/alure.rb
Labels: CI-syntax-only, livecheck, missing license

#68588 lynis 3.0.3
  Formula/lynis.rb
Labels: bottle unneeded

#68591 sbtenv 0.0.16
  Formula/sbtenv.rb
Labels: bottle unneeded

#68592 gradle 6.8
  Formula/gradle.rb
Labels: bottle unneeded, java

#68595 ghc: update livecheck
  Formula/ghc.rb
Labels: CI-syntax-only, livecheck, no ARM bottle, python

#68596 minio: update livecheck
  Formula/minio.rb
Labels: CI-syntax-only, go, livecheck

#68597 minio-mc: update livecheck
  Formula/minio-mc.rb
Labels: CI-syntax-only, go, livecheck

#68598 lammps: update livecheck
  Formula/lammps.rb
Labels: CI-syntax-only, livecheck, no ARM bottle

#68600 arabica: update livecheck
  Formula/arabica.rb
Labels: CI-syntax-only, livecheck

#68601 re2: add livecheck
  Formula/re2.rb
Labels: CI-syntax-only, livecheck

#68619 yafc: change call to Checksum
  Formula/yafc.rb
Labels: missing license

#68602 yarn: update livecheck
  Formula/yarn.rb
Labels: CI-syntax-only, bottle unneeded, livecheck, maintainer feedback, nodejs

#68622 k3sup: fix typo in livecheck
  Formula/k3sup.rb
Labels: CI-syntax-only, go, livecheck

#68633 closure-compiler 20210106
  Formula/closure-compiler.rb
Labels: 11-arm, bottle unneeded, java

#68643 device-mapper 2.03.11
  Formula/device-mapper.rb
Labels: automerge-skip, bottle unneeded, linux-only

#68637 ballerina 1.2.13
  Formula/ballerina.rb
Labels: 11-arm, bottle unneeded, java

#68644 exploitdb 2021-01-09
  Formula/exploitdb.rb
Labels: bottle unneeded

#68691 hapi-fhir-cli: add livecheck
  Formula/hapi-fhir-cli.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck

#68705 node@10: deprecate
  Formula/node@10.rb
Labels: formula deprecated, legacy, no ARM bottle

#68700 suil: add livecheck
  Formula/suil.rb
Labels: CI-syntax-only, livecheck

#68701 calcurse: add livecheck
  Formula/calcurse.rb
Labels: CI-syntax-only, livecheck

#68704 kubie: add livecheck
  Formula/kubie.rb
Labels: CI-syntax-only, livecheck, no ARM bottle, rust

#68606 orientdb: add livecheck
  Formula/orientdb.rb
Labels: java, livecheck, no ARM bottle

#68699 mda-lv2: add livecheck
  Formula/mda-lv2.rb
Labels: CI-syntax-only, deprecated license, livecheck

#68717 iperf: update livecheck
  Formula/iperf.rb
Labels: CI-syntax-only, livecheck, missing license

#68725 plantuml 1.2021.0
  Formula/plantuml.rb
Labels: bottle unneeded, java

#68682 repo 2.11.1
  Formula/repo.rb
Labels: bottle unneeded, python

#68746 pyside: fix test style
  Formula/pyside.rb
Labels: CI-syntax-only, python

#68747 subversion: always use macOs's perl in the test
  Formula/subversion.rb
Labels: java, perl, python, ruby

#68751 cproto: add livecheck
  Formula/cproto.rb
Labels: CI-syntax-only, livecheck

#68796 flyway 7.5.0
  Formula/flyway.rb
Labels: bottle unneeded, java

#68803 phpstan 0.12.66
  Formula/phpstan.rb
Labels: bottle unneeded, php

#68808 buildkit: use `Utils#git_head`
  Formula/buildkit.rb
Labels: go

#68810 rbenv: use `Utils#git_short_head`
  Formula/rbenv.rb
Labels: ruby

#68821 cromwell 55
  Formula/cromwell.rb
Labels: bottle unneeded, java

#68840 distcc: add livecheck
  Formula/distcc.rb
Labels: CI-syntax-only, livecheck, python

#68850 zenith: add livecheck
  Formula/zenith.rb
Labels: CI-syntax-only, livecheck, no ARM bottle, rust

#68849 vault-cli: add livecheck
  Formula/vault-cli.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck

#68844 forge: add livecheck
  Formula/forge.rb
Labels: CI-syntax-only, livecheck, no ARM bottle

#68854 exploitdb 2021-01-12
  Formula/exploitdb.rb
Labels: bottle unneeded

#68871 fortio: add livecheck
  Formula/fortio.rb
Labels: CI-syntax-only, go, livecheck

#68876 mosquitto: uses libxslt from macos for build
  Formula/mosquitto.rb
Labels: CI-syntax-only, linux to homebrew-core

#68892 scala@2.12 2.12.13
  Formula/scala@2.12.rb
Labels: bottle unneeded, java, legacy

#68860 Update jpeg sha256sum
  Formula/jpeg.rb
Labels: checksum mismatch

#65422 alluxio 2.4.1
  Formula/alluxio.rb
Labels: bottle unneeded, java, license

#68930 osm-pbf: uses zlib from macos
  Formula/osm-pbf.rb
Labels: CI-syntax-only, deprecated license, linux to homebrew-core

#68926 jenkins-lts 2.263.2
  Formula/jenkins-lts.rb
Labels: bottle unneeded, java

#68923 jenkins 2.275
  Formula/jenkins.rb
Labels: bottle unneeded, java

#68931 exploitdb 2021-01-13
  Formula/exploitdb.rb
Labels: bottle unneeded

#68947 jython: update livecheck
  Formula/jython.rb
Labels: CI-syntax-only, livecheck

#68961 inxi 3.2.02-1
  Formula/inxi.rb
Labels: CI-requeued, bottle unneeded

#68911 atkmm@2.28: add livecheck regex
  Formula/atkmm@2.28.rb
Labels: CI-syntax-only, legacy, livecheck

#68977 rbenv: use new `Utils.git_short_head`
  Formula/rbenv.rb
Labels: CI-syntax-only, automerge-skip, ruby

#68809 docker: use `Utils.git_short_head`
  Formula/docker.rb
Labels: automerge-skip, go

#68813 crystal: use `Utils.git_short_head`
  Formula/crystal.rb
Labels: CI-syntax-only, automerge-skip, no ARM bottle

#68975 buildkit: use new `Utils.git_head`
  Formula/buildkit.rb
Labels: automerge-skip, go

#68976 h2spec: use new `Utils.git_short_head`
  Formula/h2spec.rb
Labels: automerge-skip, go

#68982 traefik: update head due to project org update
  Formula/traefik.rb
Labels: CI-syntax-only, go

#68988 gitbucket 4.35.3
  Formula/gitbucket.rb
Labels: bottle unneeded, java

#68986 exploitdb 2021-01-14
  Formula/exploitdb.rb
Labels: bottle unneeded

#69004 phpstan 0.12.67
  Formula/phpstan.rb
Labels: bottle unneeded, php

#69008 arduino-cli: use `Utils.git_head`
  Formula/arduino-cli.rb
Labels: automerge-skip, go, no ARM bottle

#69013 docker: add head
  Formula/docker.rb
Labels: CI-syntax-only, go

#69010 cayley: use `Utils.git_short_head`
  Formula/cayley.rb
Labels: automerge-skip, go

#69012 chezmoi: use `Utils.git_head`
  Formula/chezmoi.rb
Labels: automerge-skip, go

#69011 chart-testing: use `Utils.git_head`
  Formula/chart-testing.rb
Labels: automerge-skip, go, no ARM bottle

#69014 circleci: use `Utils.git_short_head`
  Formula/circleci.rb
Labels: automerge-skip, go, no ARM bottle

#69016 consul-template: use `Utils.git_short_head`
  Formula/consul-template.rb
Labels: automerge-skip, go

#69017 docker-machine-driver-xhyve: use `Utils.git_short_head`
  Formula/docker-machine-driver-xhyve.rb
Labels: automerge-skip, formula deprecated, go

#69007 arangodb: use `Utils.git_head`
  Formula/arangodb.rb
Labels: automerge-skip, go, no ARM bottle, python

#69018 calicoctl: use `Utils.git_short_head`
  Formula/calicoctl.rb
Labels: automerge-skip, go

#68946 openjdk: add ARM version
  Formula/openjdk.rb
Labels: CI-force-arm, no ARM bottle, ready to merge

#68974 icu4c: replace '-' to '.' in livecheck
  Formula/icu4c.rb
Labels: CI-syntax-only, livecheck

#69054 funcoeszz 21.1
  Formula/funcoeszz.rb
Labels: bottle unneeded, missing license

#69029 openjdk: fix version on ARM
  Formula/openjdk.rb
Labels: CI-force-arm, no ARM bottle

#69019 kapacitor: use `Utils.git_head`
  Formula/kapacitor.rb
Labels: automerge-skip, go

#69112 exploitdb 2021-01-15
  Formula/exploitdb.rb
Labels: bottle unneeded
