Repository Homebrew/homebrew-core, pull requests merged in 2021-07, with the labels that each got.

#80335 archi-steam-farm: add livecheck
  Formula/archi-steam-farm.rb
Labels: CI-syntax-only, livecheck, no ARM bottle

#80316 workflows: use system bash to fix post cleanup
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/tests.yml
Labels: CI-force-linux, automerge-skip, do not merge, in progress, workflows

#80363 pcaplusplus: upstream Linux fix
  Formula/pcapplusplus.rb
Labels: linux to homebrew-core

#80387 workflows/triage: restrict self-hosted Linux labelling
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#80406 CODEOWNERS: add me for .github
  CODEOWNERS
Labels: CI-syntax-only, automerge-skip

#80414 scheme48: add livecheck
  Formula/scheme48.rb
Labels: CI-syntax-only, livecheck

#80314 libgit2-glib: m1-support add in rpath to build on Apple Silicon
  Formula/libgit2-glib.rb
Labels: CI-force-arm, deprecated license, no ARM bottle

#80438 gcc@5: add missing version_suffix for Linux
  Formula/gcc@5.rb
Labels: CI-force-linux, legacy, linux to homebrew-core, missing license

#80444 eksctl: update `head` branch
  Formula/eksctl.rb
Labels: CI-syntax-only, go

#80454 bwfmetaedit: add livecheck
  Formula/bwfmetaedit.rb
Labels: CI-syntax-only, livecheck

#80487 workflows: label macos formulae
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#80518 libdrm 2.4.107
  Formula/libdrm.rb
Labels: bottle unneeded, bump-formula-pr, linux-only

#80540 binaryen: specify `main` branch for `head`
  Formula/binaryen.rb
Labels: CI-syntax-only

#80506 ronn: Fix test for Linux
  Formula/ronn.rb
Labels: linux to homebrew-core, ruby

#80541 tree-sitter: skip WASM module build on Linux
  Formula/tree-sitter.rb
Labels: linux to homebrew-core, nodejs, rust

#79727 rust: use system curl only on macOS
  Formula/rust.rb
Labels: linux to homebrew-core

#80249 open-mesh: Add rpath to cmake build. Add rpath to test linking to ma…
  Formula/open-mesh.rb
Labels: CI-force-arm, missing license, no ARM bottle

#80253 pg_top: Add support for Apple Silicon by calling autoreconf -fvi befo…
  Formula/pg_top.rb
Labels: CI-force-arm, missing license, no ARM bottle

#80564 maturin: remove workaround in test
  Formula/maturin.rb
Labels: rust

#80566 mecab-unidic: add livecheck
  Formula/mecab-unidic.rb
Labels: CI-syntax-only, livecheck

#80572 apr: build with autoconf@2.69
  Formula/apr.rb
Labels: CI-force-linux, linux to homebrew-core

#80575 openjpeg: make test portable, align with Linux
  Formula/openjpeg.rb
Labels: CI-force-linux, linux to homebrew-core

#80555 openjdk: ignore missing library
  Formula/openjdk.rb
Labels: CI-force-linux, linux to homebrew-core

#80584 namebench: deprecate
  Formula/namebench.rb
Labels: formula deprecated, macos-only

#80605 groff: Fix build for Linux
  Formula/groff.rb
Labels: CI-force-linux, linux to homebrew-core, perl

#80549 ghc: Fix build for Linux
  Formula/ghc.rb
Labels: CI-force-linux, linux to homebrew-core

#79239 libstfl: upstream additional Linux fixes
  Formula/libstfl.rb
Labels: linux to homebrew-core, perl, ruby, stale

#79468 llvm@8: upstream Linux fixes
  Formula/llvm@8.rb
Labels: legacy, linux to homebrew-core, python

#80609 llvm@8: fix typo
  Formula/llvm@8.rb
Labels: CI-syntax-only, legacy, python

#80606 bdw-gc: fix test for Linux
  Formula/bdw-gc.rb
Labels: CI-force-linux, linux to homebrew-core

#79470 llvm@7: upstream Linux fixes
  Formula/llvm@7.rb
Labels: legacy, linux to homebrew-core, python

#80618 llvm@7: fix typo
  Formula/llvm@7.rb
Labels: CI-syntax-only

#80621 fftw: update urls to https
  Formula/fftw.rb
Labels: CI-syntax-only

#80632 luv: remove explicitly specified version
  Formula/luv.rb
Labels: CI-syntax-only, lua

#80631 ansible@2.8: deprecate
  Formula/ansible@2.8.rb
Labels: CI-syntax-only, formula deprecated, legacy, no ARM bottle, python, rust

#80633 midicsv: add livecheck
  Formula/midicsv.rb
Labels: CI-syntax-only, livecheck, missing license

#80657 maturin: fix test for Linux
  Formula/maturin.rb
Labels: CI-force-linux, rust

#80659 mpi4py: fix test for Linux
  Formula/mpi4py.rb
Labels: CI-force-linux, linux to homebrew-core, missing license, python

#80241 zssh: call autoreconf -fvi before configure, this fixes build issues …
  Formula/zssh.rb
Labels: CI-force-arm, deprecated license

#80708 anyenv: fix test for Linux
  Formula/anyenv.rb
Labels: CI-force-linux, linux to homebrew-core

#79261 hadolint: add env variables for gmp on Linux
  Formula/hadolint.rb
Labels: haskell, linux to homebrew-core, stale

#80735 h2spec: fix description
  Formula/h2spec.rb
Labels: CI-syntax-only, go

#80731 github/workflows/tests: rename pre_tests to check_labels.
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#80744 php: update livecheck
  Formula/php.rb
Labels: CI-syntax-only, livecheck

#80743 php@7.2: use disable instead of deprecate
  Formula/php@7.2.rb
Labels: CI-syntax-only, formula disabled, legacy

#80643 postgresql: fix Linux build with OpenLDAP 2.5
  Formula/postgresql.rb
Labels: CI-force-linux, linux to homebrew-core, perl

#80762 gtk+: fix test for Linux
  Formula/gtk+.rb
Labels: CI-force-linux, linux to homebrew-core

#80761 tokyo-cabinet: fix build for Linux
  Formula/tokyo-cabinet.rb
Labels: CI-syntax-only, license, linux to homebrew-core

#80800 lynx: add zlib dependency for Linux
  Formula/lynx.rb
Labels: CI-force-linux, deprecated license, linux to homebrew-core

#80807 bastet: fix build for Linux and update license
  Formula/bastet.rb
Labels: CI-force-linux, license, linux to homebrew-core

#80808 .github/workflows: use new test-bot features.
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/tests.yml
  .github/workflows/triage.yml
Labels: automerge-skip, workflows

#80844 workflows/tests: fix syntax-only condition
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#80840 cpmtools: add livecheck
  Formula/cpmtools.rb
Labels: CI-syntax-only, livecheck

#80764 libebml: fix build for Linux
  Formula/libebml.rb
Labels: CI-force-linux, linux to homebrew-core, ready to merge

#80766 kakoune: fix build with GCC
  Formula/kakoune.rb
Labels: CI-force-linux, linux to homebrew-core, ready to merge

#80846 libhttpseverywhere: set -lintl only on macOS
  Formula/libhttpseverywhere.rb
Labels: CI-force-linux, linux to homebrew-core

#80769 vcprompt: fix build by using older autconf@2.69
  Formula/vcprompt.rb
Labels: CI-force-linux, linux to homebrew-core, ready to merge

#80768 wp-cli: add php dependency for Linux
  Formula/wp-cli.rb
Labels: CI-force-linux, linux to homebrew-core, php, ready to merge

#80765 pastel: fix build and add head
  Formula/pastel.rb
Labels: CI-force-linux, linux to homebrew-core, ready to merge, rust

#80850 git-extras: fix build for Linux
  Formula/git-extras.rb
Labels: CI-force-linux, linux to homebrew-core

#80872 enscript: fix test issue with double escaped characters
  Formula/enscript.rb
Labels: CI-syntax-only, license

#80881 .github/workflows: add more `concurrency`.
  .github/workflows/autopublish.yml
  .github/workflows/recreate-linux-runners.yml
  .github/workflows/remove-disabled-formulae.yml
  .github/workflows/triage.yml
Labels: automerge-skip, workflows

#80842 earthly: disable
  Formula/earthly.rb
Labels: do not merge, formula disabled, go, maintainer feedback

#80673 lua: add Linux fixes
  Formula/lua.rb
Labels: CI-force-linux, CI-long-timeout, CI-no-fail-fast, linux to homebrew-core

#80886 clusterctl: update livecheck
  Formula/clusterctl.rb
Labels: CI-syntax-only, go, livecheck

#80890 argo: update stable url
  Formula/argo.rb
Labels: CI-syntax-only, go, nodejs

#80895 ruby-completion: add livecheck
  Formula/ruby-completion.rb
Labels: CI-syntax-only, livecheck

#80898 ps2eps: add livecheck
  Formula/ps2eps.rb
Labels: CI-syntax-only, livecheck, missing license

#80899 bnd: add livecheck
  Formula/bnd.rb
Labels: CI-syntax-only, java, livecheck, missing license

#80905 rails-completion: add livecheck
  Formula/rails-completion.rb
Labels: CI-syntax-only, livecheck

#80771 git: fix test for Linux
  Formula/git.rb
Labels: CI-force-linux, linux to homebrew-core, ready to merge

#80921 yank: fix test for Linux
  Formula/yank.rb
Labels: CI-force-linux, linux to homebrew-core

#80931 atlantis: Change `--repo-whitelist` test flag to `--repo-allowlist`
  Formula/atlantis.rb
Labels: go

#80917 nss: fix build on Linux
  Formula/nss.rb
Labels: CI-force-linux, linux to homebrew-core, ready to merge

#80960 monitoring-plugins: add livecheck
  Formula/monitoring-plugins.rb
Labels: CI-syntax-only, livecheck, missing license

#80966 hardlink: add livecheck
  Formula/hardlink.rb
Labels: CI-syntax-only, livecheck, missing license

#80968 nu-smv: add livecheck
  Formula/nu-smv.rb
Labels: CI-syntax-only, livecheck, missing license, no ARM bottle

#80969 libscrypt: fix homepage
  Formula/libscrypt.rb
Labels: CI-force-linux

#80938 aamath: link Homebrew readline on Linux
  Formula/aamath.rb
Labels: CI-force-linux, linux to homebrew-core, ready to merge

#80970 w3m: fix unavailable patches
  Formula/w3m.rb
Labels: CI-force-linux, missing license

#80956 naabu: fix build for Linux
  Formula/naabu.rb
Labels: CI-force-linux, go, linux to homebrew-core

#80954 vbindiff: add license and fix Linux build
  Formula/vbindiff.rb
Labels: CI-force-linux, license, linux to homebrew-core

#80955 pacman4console: fix build for Linux
  Formula/pacman4console.rb
Labels: CI-force-linux, deprecated license, linux to homebrew-core

#80937 caf: fix build for Linux
  Formula/caf.rb
Labels: CI-force-linux, linux to homebrew-core

#80972 terraform@0.11: fix build for Linux
  Formula/terraform@0.11.rb
Labels: CI-force-linux, formula deprecated, go, legacy

#80871 exiftool: use CPAN url and make homepage url mirror
  Formula/exiftool.rb
Labels: CI-force-linux, linux to homebrew-core

#80935 cfengine: fix build for Linux
  Formula/cfengine.rb
Labels: CI-force-linux, linux to homebrew-core

#80984 wdc: fix syntax
  Formula/wdc.rb
Labels: CI-force-linux, missing license

#80983 hidapi: fix test for Linux
  Formula/hidapi.rb
Labels: CI-force-linux

#80973 qdbm: fix build for Linux
  Formula/qdbm.rb
Labels: CI-force-linux, deprecated license

#80974 physfs: fix test for Linux
  Formula/physfs.rb
Labels: CI-force-linux, linux to homebrew-core

#80986 irrlicht: fix test for Linux
  Formula/irrlicht.rb
Labels: CI-force-linux, linux to homebrew-core, missing license

#80990 pumba: fix test for Linux
  Formula/pumba.rb
Labels: CI-force-linux, go, linux to homebrew-core

#80989 libepoxy: fix test for Linux
  Formula/libepoxy.rb
Labels: CI-force-linux, linux to homebrew-core

#80985 gdb: fix build for Linux
  Formula/gdb.rb
Labels: CI-force-linux, linux to homebrew-core, no ARM bottle, python

#80987 fluent-bit: don't install any service on Linux
  Formula/fluent-bit.rb
Labels: CI-force-linux, linux to homebrew-core

#80988 global: needs libtool at runtime on Linux
  Formula/global.rb
Labels: CI-force-linux, linux to homebrew-core, python

#80999 geckodriver: fix test for Linux
  Formula/geckodriver.rb
Labels: CI-force-linux, linux to homebrew-core, rust

#81004 tests: skip unbottled linux reverse dependencies
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#81001 archiver: fix test for linux
  Formula/archiver.rb
Labels: CI-force-linux, go, linux to homebrew-core

#81011 pbzip2: fix build for Linux
  Formula/pbzip2.rb
Labels: CI-force-linux, linux to homebrew-core

#80936 aces_container: fix test for Linux
  Formula/aces_container.rb
Labels: CI-force-linux, linux to homebrew-core, missing license, ready to merge

#81023 blastem: add livecheck
  Formula/blastem.rb
Labels: CI-syntax-only, livecheck, macos-only, no ARM bottle

#81024 blastem: update livecheck
  Formula/blastem.rb
Labels: CI-syntax-only, livecheck, macos-only, no ARM bottle

#81035 lsusb: add `depends_on :macos`
  Formula/lsusb.rb
Labels: CI-syntax-only, macos-only

#81034 afsctool: add `depends_on :macos`
  Formula/afsctool.rb
Labels: CI-syntax-only, deprecated license, macos-only

#81036 neopop-sdl: add livecheck
  Formula/neopop-sdl.rb
Labels: CI-syntax-only, deprecated license, livecheck, no ARM bottle

#81038 freediameter: add livecheck
  Formula/freediameter.rb
Labels: CI-syntax-only, livecheck

#81039 rubberband: update livecheck
  Formula/rubberband.rb
Labels: CI-syntax-only, java, livecheck

#81030 lua@5.1: add linux fixes
  Formula/lua@5.1.rb
Labels: CI-force-linux, formula deprecated, legacy, linux to homebrew-core

#80883 julia: fix build on Linux
  Formula/julia.rb
Labels: CI-force-linux, linux to homebrew-core, no ARM bottle, perl, ready to merge

#81043 dropbear: fix build for Linux
  Formula/dropbear.rb
Labels: CI-force-linux, linux to homebrew-core

#81064 tmuxinator: fix test for Linux
  Formula/tmuxinator.rb
Labels: CI-force-linux, linux to homebrew-core, ruby

#81061 pybind11: fix test for Linux
  Formula/pybind11.rb
Labels: CI-force-linux, linux to homebrew-core, python

#81069 v: fix test for Linux
  Formula/v.rb
Labels: CI-force-linux, linux to homebrew-core, missing license

#81075 Revert "tests: skip unbottled linux reverse dependencies"
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#81065 httpflow: fix build for Linux
  Formula/httpflow.rb
Labels: CI-force-linux, linux to homebrew-core

#81060 pigz: fix test for Linux
  Formula/pigz.rb
Labels: CI-force-linux, linux to homebrew-core

#81067 bitrise: add rsync at runtime for Linux
  Formula/bitrise.rb
Labels: CI-force-linux, go, linux to homebrew-core

#81037 libpqxx: fix build for Linux
  Formula/libpqxx.rb
Labels: CI-force-linux, linux to homebrew-core

#81070 ghc: prevent opportunistic linkage against numa
  Formula/ghc.rb
Labels: CI-build-dependents-from-source, CI-long-timeout, linux to homebrew-core

#81099 otf2bd: add alternate test for Linux
  Formula/otf2bdf.rb
Labels: CI-force-linux, linux to homebrew-core, missing license

#81094 nzbget: fix ncurses paths, disable workaround on Linux
  Formula/nzbget.rb
Labels: CI-force-linux, linux to homebrew-core, no ARM bottle

#81131 mscgen: update to https urls and add license
  Formula/mscgen.rb
Labels: CI-syntax-only, no ARM bottle, ready to merge

#81132 mtools: fix build for Linux
  Formula/mtools.rb
Labels: CI-force-linux, linux to homebrew-core, ready to merge

#81133 sslsplit: fix build for Linux and ARM
  Formula/sslsplit.rb
Labels: CI-force-arm, CI-force-linux, linux to homebrew-core, no ARM bottle, ready to merge

#81136 libsvg: fix test for Linux
  Formula/libsvg.rb
Labels: CI-force-linux, linux to homebrew-core

#81137 abcmidi: fix build for Linux
  Formula/abcmidi.rb
Labels: CI-force-linux, linux to homebrew-core, ready to merge

#81135 lc0: fix build for Linux
  Formula/lc0.rb
Labels: CI-force-linux, linux to homebrew-core

#81152 tfsec: update the organization
  Formula/tfsec.rb
Labels: go

#81156 id3ed: add livecheck
  Formula/id3ed.rb
Labels: CI-syntax-only, deprecated license, livecheck

#81165 bitcoin: update urls to new domain
  Formula/bitcoin.rb
Labels: CI-syntax-only, no ARM bottle

#81161 libnice: fix test for Linux
  Formula/libnice.rb
Labels: CI-force-linux, linux to homebrew-core

#81162 hcxtools: fix build for Linux
  Formula/hcxtools.rb
Labels: CI-force-linux, linux to homebrew-core

#81164 slurm: add ncurses dependency for Linux
  Formula/slurm.rb
Labels: CI-force-linux, license, linux to homebrew-core

#81169 dwarfutils: fix build for Linux
  Formula/dwarfutils.rb
Labels: CI-force-linux, linux to homebrew-core

#81166 avanor: fix build for Linux
  Formula/avanor.rb
Labels: CI-force-linux, license, linux to homebrew-core

#81176 keydb: deps for Linux
  Formula/keydb.rb
Labels: CI-force-linux, no ARM bottle

#81174 screen: fix build from source and update license
  Formula/screen.rb
Labels: CI-force-linux

#81177 libiconv: incorporate Linux
  Formula/libiconv.rb
Labels: CI-force-linux, linux to homebrew-core

#81180 libxdiff: add livecheck
  Formula/libxdiff.rb
Labels: CI-syntax-only, deprecated license, livecheck

#81181 tpp: add livecheck
  Formula/tpp.rb
Labels: CI-syntax-only, livecheck, missing license

#81182 hyperspec: add livecheck
  Formula/hyperspec.rb
Labels: CI-syntax-only, livecheck, missing license

#81183 nicovideo-dl: add livecheck
  Formula/nicovideo-dl.rb
Labels: CI-syntax-only, livecheck, missing license, python

#81185 num-utils: add livecheck
  Formula/num-utils.rb
Labels: CI-syntax-only, livecheck, perl

#81066 jnettop: fix build for Linux
  Formula/jnettop.rb
Labels: CI-force-linux, license, linux to homebrew-core, ready to merge

#81186 rasqal: add livecheck
  Formula/rasqal.rb
Labels: CI-syntax-only, livecheck, missing license

#81187 linklint: add livecheck
  Formula/linklint.rb
Labels: CI-syntax-only, livecheck, missing license

#81189 ceylon: add livecheck
  Formula/ceylon.rb
Labels: CI-syntax-only, java, livecheck, missing license

#81134 libmms: fix build for Linux
  Formula/libmms.rb
Labels: CI-force-linux, license, linux to homebrew-core, ready to merge
