Repository Homebrew/homebrew-core, pull requests merged in 2021-11, with the labels that each got.

#88428 bedops: fix sha256 checksum
  Formula/bedops.rb
Labels: deprecated license, CI-no-fail-fast, CI-no-bottles

#88484 cogl: update homepage and head branch
  Formula/cogl.rb
Labels: CI-no-bottles

#88501 crush-tools: patch incorrect -flat_namespace usage
  Formula/crush-tools.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88503 log4c: patch incorrect -flat_namespace usage
  Formula/log4c.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88505 tracebox: fix ARM build
  Formula/tracebox.rb
Labels: lua, CI-force-arm, no ARM bottle, CI-skip-recursive-dependents, CI-force-linux, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88506 librcsc: patch incorrect -flat_namespace usage
  Formula/librcsc.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88512 libwandevent: patch incorrect -flat_namespace usage
  Formula/libwandevent.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88519 cbc: update livecheck
  Formula/cbc.rb
Labels: livecheck, CI-syntax-only

#88520 cgl: update livecheck
  Formula/cgl.rb
Labels: livecheck, CI-syntax-only

#88524 topgrade: add livecheck
  Formula/topgrade.rb
Labels: rust, livecheck, CI-syntax-only

#88527 watchexec: add livecheck
  Formula/watchexec.rb
Labels: rust, livecheck, CI-syntax-only

#88559 ace: update livecheck
  Formula/ace.rb
Labels: livecheck, CI-syntax-only, no ARM bottle, no Linux bottle

#88572 topgrade: remove livecheck
  Formula/topgrade.rb
Labels: rust, livecheck, CI-syntax-only

#88592 flat_namespace_allowlist: add `blast`
  audit_exceptions/flat_namespace_allowlist.json
Labels: CI-syntax-only, automerge-skip, 12

#88526 clutter: patch incorrect -flat_namespace usage
  Formula/clutter.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88538 heimdal: patch incorrect -flat_namespace usage
  Formula/heimdal.rb
Labels: perl, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88544 cmu-pocketsphinx: patch incorrect -flat_namespace usage
  Formula/cmu-pocketsphinx.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88555 rasqal: patch incorrect -flat_namespace usage
  Formula/rasqal.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88564 fastd: fix meson flags
  Formula/fastd.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88565 gucharmap: patch incorrect -flat_namespace usage
  Formula/gucharmap.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88566 thrax: patch incorrect -flat_namespace usage
  Formula/thrax.rb
Labels: python, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88567 zyre: patch incorrect -flat_namespace usage
  Formula/zyre.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88568 vcdimager: patch incorrect -flat_namespace usage
  Formula/vcdimager.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88330 dovecot: use Homebrew `curl` for `pigeonhole` resource
  Formula/dovecot.rb
Labels: ready to merge, CI-no-fail-fast, CI-no-bottles, 12

#88599 blueutil: build a native binary
  Formula/blueutil.rb
Labels: CI-skip-recursive-dependents, macos-only, CI-skip-dependents, CI-no-bottles

#88601 silk: patch incorrect -flat_namespace usage
  Formula/silk.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88600 profanity: fix ARM build
  Formula/profanity.rb
Labels: CI-force-arm, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88602 ginac: patch incorrect -flat_namespace usage
  Formula/ginac.rb
Labels: python, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88603 dar: patch incorrect -flat_namespace usage
  Formula/dar.rb
Labels: no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88606 urweb: patch incorrect -flat_namespace usage
  Formula/urweb.rb
Labels: missing license, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88607 libsmf: patch incorrect -flat_namespace usage
  Formula/libsmf.rb
Labels: missing license, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88618 opensaml: patch incorrect -flat_namespace usage
  Formula/opensaml.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88619 redland: patch incorrect -flat_namespace usage
  Formula/redland.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88621 clutter-gtk: patch incorrect -flat_namespace usage
  Formula/clutter-gtk.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88632 libgnomecanvas: change homepage url
  Formula/libgnomecanvas.rb
Labels: missing license, CI-syntax-only, no Linux bottle

#88626 libdvdnav: patch incorrect -flat_namespace usage
  Formula/libdvdnav.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88627 libtrace: patch incorrect -flat_namespace usage
  Formula/libtrace.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88554 libgnomecanvas: patch incorrect -flat_namespace usage
  Formula/libgnomecanvas.rb
Labels: audit failure, formula deprecated, missing license, automerge-skip, CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88634 clutter-gst: change homepage url
  Formula/clutter-gst.rb
Labels: missing license, CI-no-bottles, no Linux bottle

#88633 gtksourceviewmm: change homepage url
  Formula/gtksourceviewmm.rb
Labels: CI-no-bottles, no Linux bottle

#88630 lilv: fix homepage url
  Formula/lilv.rb
Labels: CI-no-bottles, no Linux bottle

#88631 sratom: fix homepage url
  Formula/sratom.rb
Labels: CI-no-bottles, no Linux bottle

#88669 tesseract: update head branch
  Formula/tesseract.rb
Labels: CI-syntax-only

#88668 flat_namespace_allowlist: add `libvirt`
  audit_exceptions/flat_namespace_allowlist.json
Labels: CI-syntax-only, automerge-skip

#88705 fastbit: patch incorrect -flat_namespace usage
  Formula/fastbit.rb
Labels: java, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88718 jetty: depend on `x86_64`
  Formula/jetty.rb
Labels: java, CI-syntax-only, no Linux bottle

#88721 watchman: pour bottle only in default prefixes
  Formula/watchman.rb
Labels: python, rust, CI-syntax-only

#88720 jetty: add comment for `x86_64` dependency
  Formula/jetty.rb
Labels: java, CI-syntax-only, no Linux bottle

#88460 pev: fix checksum
  Formula/pev.rb
Labels: CI-no-fail-fast, CI-no-bottles, no Linux bottle

#88717 wildfly-as: depend on `x86_64`
  Formula/wildfly-as.rb
Labels: java, CI-no-bottles, no Linux bottle

#88715 fits: depend on `x86_64`
  Formula/fits.rb
Labels: java, CI-no-bottles, no Linux bottle

#88726 mpd: remove unrecognised option
  Formula/mpd.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88722 libflowmanager: patch incorrect -flat_namespace usage
  Formula/libflowmanager.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88732 aterm: fix URL and deprecate
  Formula/aterm.rb
Labels: formula deprecated, no Linux bottle

#88736 bbftp-client: fix homepage url, add license
  Formula/bbftp-client.rb
Labels: license, CI-no-fail-fast, CI-no-bottles, no Linux bottle

#88810 befunge93: add livecheck
  Formula/befunge93.rb
Labels: livecheck, CI-syntax-only

#88183 flat_namespace_allowlist: add `omniorb`
  audit_exceptions/flat_namespace_allowlist.json
Labels: CI-syntax-only, automerge-skip

#87871 workflows/tests: enable Monterey CI on PRs
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#88823 activemq-cpp: patch incorrect -flat_namespace usage
  Formula/activemq-cpp.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88830 botan: add livecheck
  Formula/botan.rb
Labels: python, livecheck, CI-syntax-only

#88826 subversion: patch incorrect -flat_namespace usage
  Formula/subversion.rb
Labels: java, ruby, perl, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#88831 rinetd: fix `head` URL
  Formula/rinetd.rb
Labels: CI-no-bottles

#88860 zinit: use maintained fork
  Formula/zinit.rb
Labels: CI-no-bottles

#88364 fontconfig: force --disable-docs option
  Formula/fontconfig.rb
Labels: CI-long-timeout, CI-no-fail-fast, CI-no-bottles

#88899 apgdiff: add livecheck
  Formula/apgdiff.rb
Labels: java, livecheck, CI-syntax-only

#88922 tnftpd: fix Linux build
  Formula/tnftpd.rb
Labels: missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#88921 mplayershell: build a native binary
  Formula/mplayershell.rb
Labels: no ARM bottle, CI-skip-recursive-dependents, macos-only, CI-skip-dependents, CI-no-bottles

#88930 bpm-tools: add livecheck
  Formula/bpm-tools.rb
Labels: livecheck, CI-syntax-only, deprecated license

#88947 luabind: changed build command from bjam to b2
  Formula/luabind.rb
Labels: lua, CI-no-fail-fast, CI-no-bottles, no Linux bottle

#88920 flat_namespace_allowlist: add `adios2`
  audit_exceptions/flat_namespace_allowlist.json
Labels: CI-syntax-only, automerge-skip

#88970 shellcheck: update checksum
  Formula/shellcheck.rb
Labels: haskell, checksum mismatch, CI-no-fail-fast, CI-no-bottles

#88925 ocaml: patch incorrect -flat_namespace usage
  Formula/ocaml.rb
Labels: CI-long-timeout, CI-skip-recursive-dependents, CI-skip-dependents, CI-build-dependents-from-source, CI-no-bottles

#88984 ledit: use HTTPS for homepage
  Formula/ledit.rb
Labels: ocaml, CI-syntax-only, no Linux bottle

#89035 cd-discid: add livecheck
  Formula/cd-discid.rb
Labels: livecheck, CI-syntax-only, deprecated license

#89112 idris2: fix HEAD branch name
  Formula/idris2.rb
Labels: CI-syntax-only, no ARM bottle

#89151 ceres-solver: add livecheck
  Formula/ceres-solver.rb
Labels: livecheck, CI-syntax-only

#89192 mapserver: fix ARM build
  Formula/mapserver.rb
Labels: python, no ARM bottle, CI-no-fail-fast, CI-no-bottles, no Linux bottle

#89196 cheops: add livecheck
  Formula/cheops.rb
Labels: livecheck, CI-syntax-only, deprecated license

#89210 gradle: depend on openjdk 17 on all platforms
  Formula/gradle.rb
Labels: java

#89246 Update versioned_dependencies_conflicts_allowlist.json
  audit_exceptions/versioned_dependencies_conflicts_allowlist.json
Labels: CI-syntax-only, automerge-skip

#89268 workflows: use `--skip-online-checks` for bottle jobs
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
Labels: CI-syntax-only, automerge-skip, workflows

#89283 collectd: add livecheck
  Formula/collectd.rb
Labels: livecheck, perl, CI-syntax-only

#89336 crosstool-ng: add livecheck
  Formula/crosstool-ng.rb
Labels: python, livecheck, CI-syntax-only, no Linux bottle

#89327 workflows/triage: label dotnet formula PRs
  .github/workflows/triage.yml
Labels: automerge-skip, workflows

#89350 meilisearch: add livecheck
  Formula/meilisearch.rb
Labels: rust, livecheck, CI-syntax-only

#89371 flat_namespace_allowlist: add bind
  audit_exceptions/flat_namespace_allowlist.json
Labels: CI-syntax-only, automerge-skip

#89368 couchdb: add livecheck
  Formula/couchdb.rb
Labels: livecheck, CI-syntax-only, no ARM bottle, no Linux bottle

#89378 csmith: add livecheck
  Formula/csmith.rb
Labels: livecheck, CI-syntax-only, no Linux bottle

#89379 pybind11: add livecheck
  Formula/pybind11.rb
Labels: livecheck, CI-syntax-only

#89380 postgresql@9.6: remove livecheck
  Formula/postgresql@9.6.rb
Labels: legacy, livecheck, perl, formula deprecated, CI-syntax-only

#89381 libelf: remove livecheck
  Formula/libelf.rb
Labels: livecheck, formula deprecated, CI-syntax-only

#89382 bzrtools: remove livecheck
  Formula/bzrtools.rb
Labels: livecheck, formula deprecated, missing license, CI-syntax-only

#89377 goproxy: fix test
  Formula/goproxy.rb
Labels: go, CI-no-bottles

#89458 stylua 0.11.2
  Formula/stylua.rb
Labels: rust, bump-formula-pr

#89460 shogun: disable due to license
  Formula/shogun.rb
Labels: formula disabled

#89484 qwt-qt5: update livecheck
  Formula/qwt-qt5.rb
Labels: livecheck, CI-syntax-only

#89510 git-revise: Fetch HEAD version from `main` branch
  Formula/git-revise.rb
Labels: python, CI-no-bottles

#89514 cutter: add livecheck
  Formula/cutter.rb
Labels: livecheck, CI-syntax-only, deprecated license, no Linux bottle

#89483 cweb: update livecheck
  Formula/cweb.rb
Labels: livecheck, missing license, CI-syntax-only

#89536 objfw: support head build.
  Formula/objfw.rb
Labels: CI-syntax-only, no Linux bottle

#89519 t-rec: fix test
  Formula/t-rec.rb
Labels: test failure, rust, CI-no-bottles, no Linux bottle

#89572 deheader: add livecheck
  Formula/deheader.rb
Labels: python, livecheck, CI-syntax-only

#89616 funcoeszz: fix test on Linux
  Formula/funcoeszz.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#89620 tests: set timeout via flags only on self-hosted runners
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#89625 readline: improve livecheck
  Formula/readline.rb
Labels: livecheck, CI-syntax-only

#89686 tee-clc: deprecate as unmaintained
  Formula/tee-clc.rb
Labels: java, formula deprecated, CI-no-bottles

#89747 workflows/autobump: fix username setting
  .github/workflows/autobump.yml
Labels: CI-syntax-only, automerge-skip, workflows

#89586 workflows: use `container`
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#89759 workflows/triage: replace JSON with YAML
  .github/workflows/triage.yml
Labels: automerge-skip, workflows

#89489 workflows: update legacy formula exceptions
  .github/workflows/triage.yml
Labels: automerge-skip, workflows

#89871 pyenv-which-ext: test depend on python
  Formula/pyenv-which-ext.rb
Labels: formula deprecated

#88864 maturin: migrate to python@3.10
  Formula/maturin.rb
Labels: rust, CI-no-bottles, python-3.10-migration

#89890 pyenv-which-ext: use /bin/ls for testing
  Formula/pyenv-which-ext.rb
Labels: formula deprecated

#89900 profanity: update `inreplace` comment
  Formula/profanity.rb
Labels: CI-no-bottles

#89836 cuba: disable due to checksum mismatch
  Formula/cuba.rb
Labels: formula disabled, deprecated license, no Linux bottle

#89902 php: remove `glib` dependency
  Formula/php.rb
Labels: CI-no-bottles

#88843 cdparanoia: use brewed curl for URLs
  Formula/cdparanoia.rb
Labels: CI-no-fail-fast, CI-no-bottles, no Linux bottle

#89912 ejabberd: add livecheck
  Formula/ejabberd.rb
Labels: livecheck, CI-syntax-only, no Linux bottle

#89908 php@7.2: remove `glib` dependency
  Formula/php@7.2.rb
Labels: legacy, formula disabled, CI-no-bottles

#89907 php@7.3: remove `glib` dependency
  Formula/php@7.3.rb
Labels: legacy, formula deprecated, no ARM bottle, CI-no-bottles

#89924 gtksourceview5: fix build
  Formula/gtksourceview5.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#89922 csound: fix ARM build
  Formula/csound.rb
Labels: python, java, no ARM bottle, CI-no-bottles, no Linux bottle

#89687 ioke: deprecate
  Formula/ioke.rb
Labels: upstream issue, java, formula deprecated, missing license, CI-no-fail-fast

#89954 open-image-denoise: fix typo
  Formula/open-image-denoise.rb
Labels: CI-syntax-only, no Linux bottle

#89916 ocaml: add `flat_namespace_allowlist` reminder
  Formula/ocaml.rb
Labels: CI-syntax-only, CI-build-dependents-from-source

#89959 enca: add livecheck
  Formula/enca.rb
Labels: livecheck, CI-syntax-only

#88521 openmotif: patch incorrect -flat_namespace usage
  Formula/openmotif.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#89989 openmotif: add Monterey bottles
  Formula/openmotif.rb
Labels: CI-syntax-only

#89990 csound: don't recommend `DYLD_FRAMEWORK_PATH`
  Formula/csound.rb
Labels: python, java, CI-no-bottles, no Linux bottle

#89988 rust: remove MACOSX_DEPLOYMENT_TARGET
  Formula/rust.rb
Labels: CI-long-timeout, CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-build-dependents-from-source, CI-no-bottles

#90011 flat_namespace_allowlist: add `hdf5-mpi`
  audit_exceptions/flat_namespace_allowlist.json
Labels: CI-syntax-only, automerge-skip

#89981 libstfl: deprecate as upstream repo/website is gone
  Formula/libstfl.rb
  Formula/newsboat.rb
Labels: ruby, ready to merge, perl, formula deprecated, CI-syntax-only, automerge-skip

#90043 qt: fix build with assimp 5.1
  Formula/qt.rb
Labels: nodejs, python, perl, CI-long-timeout, CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#90058 ffmpeg2theora: add livecheck
  Formula/ffmpeg2theora.rb
Labels: livecheck, missing license, CI-syntax-only, no Linux bottle

#90091 nginx: fix not running on Mac os
  Formula/nginx.rb
Labels: CI-no-bottles

#90092 pango: fix Meson flags
  Formula/pango.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#89980 civl: re-enable for Linux
  Formula/civl.rb
Labels: java, CI-no-fail-fast

#90137 git-ftp: update license
  Formula/git-ftp.rb
Labels: CI-syntax-only, license

#90135 flvmeta: add livecheck
  Formula/flvmeta.rb
Labels: livecheck, CI-syntax-only, deprecated license

#90140 lolcode: update head, license
  Formula/lolcode.rb
Labels: license, CI-force-linux, CI-no-bottles, no Linux bottle

#90033 chakra: fix build with modern compilers
  Formula/chakra.rb
Labels: no ARM bottle, CI-long-timeout, CI-no-bottles, no Linux bottle

#90145 batik: fix Linux path in test
  Formula/batik.rb
Labels: java, CI-no-bottles

#90183 haskell-language-server: use `ncurses` and `zlib` from macOS
  Formula/haskell-language-server.rb
Labels: haskell, CI-syntax-only

#87302 iozone: use `OS.kernel_name`
  Formula/iozone.rb
Labels: checksum mismatch, CI-no-bottles, no Linux bottle
