Repository Homebrew/homebrew-core, pull requests merged in 2021-02, with the labels that each got.

#70139 digdag 0.10.0
  Formula/digdag.rb
Labels: 11-arm, bottle unneeded, java, missing license

#70146 django-completion 3.1.6
  Formula/django-completion.rb
Labels: bottle unneeded

#70141 digdag: add license
  Formula/digdag.rb
Labels: CI-syntax-only, bottle unneeded, java

#70144 flank 21.02.0
  Formula/flank.rb
Labels: bottle unneeded, java

#70152 dyld-headers 832.7.3
  Formula/dyld-headers.rb
Labels: bottle unneeded

#70156 usb.ids 2021.01.29
  Formula/usb.ids.rb
Labels: bottle unneeded

#70157 grails 4.0.7
  Formula/grails.rb
Labels: bottle unneeded, java

#70165 gawk: update license
  Formula/gawk.rb
Labels: CI-syntax-only

#70171 brew-gem 1.1.0
  Formula/brew-gem.rb
Labels: bottle unneeded

#70172 phpstan 0.12.71
  Formula/phpstan.rb
Labels: bottle unneeded, php

#70190 jumanpp: add livecheck
  Formula/jumanpp.rb
Labels: CI-syntax-only, livecheck, no ARM bottle

#70191 mlpack: add livecheck
  Formula/mlpack.rb
Labels: CI-syntax-only, livecheck, no ARM bottle

#70192 bundler-completion: add livecheck to skip
  Formula/bundler-completion.rb
Labels: CI-syntax-only, bottle unneeded, livecheck

#70195 dnstracer: add livecheck
  Formula/dnstracer.rb
Labels: CI-syntax-only, livecheck, missing license

#70198 docker-completion 19.03.15
  Formula/docker-completion.rb
Labels: bottle unneeded

#70194 sqlmap 1.5.2
  Formula/sqlmap.rb
Labels: bottle unneeded

#70210 exploitdb 2021-02-02
  Formula/exploitdb.rb
Labels: bottle unneeded

#70212 flank: don't set JAVA_HOME in test
  Formula/flank.rb
Labels: bottle unneeded, java

#70213 gcc: improve bugurl style
  Formula/gcc.rb
Labels: CI-syntax-only

#70227 .github/ISSUE_TEMPLATE/bug: use new YAML issue template.
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug.yml
Labels: CI-syntax-only, automerge-skip

#70222 phpunit 9.5.2
  Formula/phpunit.rb
Labels: bottle unneeded, php

#70235 syncthing: update livecheck block
  Formula/syncthing.rb
Labels: CI-syntax-only, go

#70230 sonarqube: depend on openjdk@11
  Formula/sonarqube.rb
Labels: bottle unneeded, java

#70237 scalaenv 0.1.7
  Formula/scalaenv.rb
Labels: bottle unneeded

#70271 predictionio: deprecate
  Formula/predictionio.rb
Labels: bottle unneeded, formula deprecated, java

#70208 plantuml 1.2021.1
  Formula/plantuml.rb
Labels: CI-requeued, bottle unneeded, java

#70275 tomcat 9.0.43
  Formula/tomcat.rb
Labels: bottle unneeded, java

#70282 sonarqube-lts: depend on openjdk@11
  Formula/sonarqube-lts.rb
Labels: bottle unneeded, java

#70287 exploitdb 2021-02-03
  Formula/exploitdb.rb
Labels: bottle unneeded

#70247 dep: set os-specific build target
  Formula/dep.rb
Labels: formula deprecated, go, linux to homebrew-core, no ARM bottle

#70303 audit_exceptions/unstable_allowlist: remove rust
  audit_exceptions/unstable_allowlist.json
Labels: CI-syntax-only, automerge-skip

#70300 vert.x 4.0.1
  Formula/vert.x.rb
Labels: bottle unneeded, java

#70313 kotlin 1.4.30
  Formula/kotlin.rb
Labels: bottle unneeded, java

#70314 picard-tools 2.24.2
  Formula/picard-tools.rb
Labels: bottle unneeded, java

#70337 mysql@5.6: deprecate
  Formula/mysql@5.6.rb
Labels: CI-syntax-only, formula deprecated, legacy, no ARM bottle

#70341 tcpflow: update stable and livecheck
  Formula/tcpflow.rb
Labels: CI-syntax-only, deprecated license, livecheck

#70344 vlang: update livecheck
  Formula/vlang.rb
Labels: CI-syntax-only, livecheck

#70348 msitools: update livecheck
  Formula/msitools.rb
Labels: CI-syntax-only, livecheck

#70360 notifiers: add license
  Formula/notifiers.rb
Labels: CI-syntax-only, license, python, ready to merge

#70334 linkerd: set platform specific build targets
  Formula/linkerd.rb
Labels: go, linux to homebrew-core

#70335 make: define caveats only on mac
  Formula/make.rb
Labels: linux to homebrew-core

#70336 osqp: use shared_library for libqdldl
  Formula/osqp.rb
Labels: linux to homebrew-core

#70340 fish: set sed path only for mac
  Formula/fish.rb
Labels: deprecated license, linux to homebrew-core

#70258 unbound: set expat path for mac and linux
  Formula/unbound.rb
Labels: linux to homebrew-core

#70362 tomcat@8 8.5.63
  Formula/tomcat@8.rb
Labels: bottle unneeded, java, legacy

#70383 wayland 1.19.0
  Formula/wayland.rb
Labels: bottle unneeded, linux-only

#70387 exploitdb 2021-02-04
  Formula/exploitdb.rb
Labels: bottle unneeded

#70420 structurizr-cli 1.8.1
  Formula/structurizr-cli.rb
Labels: bottle unneeded, java

#70423 ccfits: avoid gcc shims on linux
  Formula/ccfits.rb
Labels: linux to homebrew-core, missing license

#70425 gotop: set os-specific paths in test
  Formula/gotop.rb
Labels: go, linux to homebrew-core

#70427 consul: set platform for mac and for linux
  Formula/consul.rb
Labels: go, linux to homebrew-core

#70467 workflows/triage: update no ARM bottle label regex
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip

#70453 closure-compiler 20210202
  Formula/closure-compiler.rb
Labels: bottle unneeded, java

#70455 spotbugs 4.2.1
  Formula/spotbugs.rb
Labels: bottle unneeded, java

#70454 cromwell 56
  Formula/cromwell.rb
Labels: bottle unneeded, java

#70483 ssh-copy-id: backport upstream patch
  Formula/ssh-copy-id.rb
Labels: bottle unneeded

#70490 exploitdb 2021-02-05
  Formula/exploitdb.rb
Labels: bottle unneeded

#70501 hdf5: add license
  Formula/hdf5.rb
Labels: CI-syntax-only, license

#70500 vert.x 4.0.2
  Formula/vert.x.rb
Labels: bottle unneeded, java

#70505 glyr: fix test, update license
  Formula/glyr.rb
Labels: license

#70310 tests: use HOMEBREW_BOOTSNAP.
  .github/workflows/tests.yml
  Formula/citus.rb
  Formula/cstore_fdw.rb
  Formula/ephemeralpg.rb
Labels: automerge-skip

#70513 Revert "tests: use HOMEBREW_BOOTSNAP."
  .github/workflows/tests.yml
  Formula/citus.rb
  Formula/cstore_fdw.rb
  Formula/ephemeralpg.rb
Labels: CI-syntax-only, automerge-skip

#70524 closure-compiler new homepage
  Formula/closure-compiler.rb
Labels: bottle unneeded, java

#70533 git-interactive-rebase-tool: update license
  Formula/git-interactive-rebase-tool.rb
Labels: CI-syntax-only, license, no ARM bottle, rust

#70510 gradle 6.8.2
  Formula/gradle.rb
Labels: bottle unneeded, java

#70541 cern-ndiff: update livecheck
  Formula/cern-ndiff.rb
Labels: CI-syntax-only, livecheck, missing license

#70542 connect: update livecheck
  Formula/connect.rb
Labels: CI-syntax-only, livecheck

#70544 curaengine: update livecheck
  Formula/curaengine.rb
Labels: CI-syntax-only, livecheck

#70545 dust: update livecheck
  Formula/dust.rb
Labels: CI-syntax-only, livecheck, rust

#70546 erlang: update livecheck
  Formula/erlang.rb
Labels: CI-syntax-only, livecheck

#70549 grok: update livecheck
  Formula/grok.rb
Labels: CI-syntax-only, livecheck

#70552 kustomize: update livecheck
  Formula/kustomize.rb
Labels: CI-syntax-only, go, livecheck

#70553 oniguruma: update livecheck
  Formula/oniguruma.rb
Labels: CI-syntax-only, livecheck

#70554 openshift-cli: update livecheck
  Formula/openshift-cli.rb
Labels: CI-syntax-only, go, livecheck

#70555 tidy-html5: update livecheck
  Formula/tidy-html5.rb
Labels: CI-syntax-only, livecheck

#70557 ec2-api-tools: remove livecheck
  Formula/ec2-api-tools.rb
Labels: CI-syntax-only, bottle unneeded, formula deprecated, java, livecheck, missing license

#70559 bagit: update livecheck
  Formula/bagit.rb
Labels: CI-syntax-only, livecheck, python

#70575 gost: fix test
  Formula/gost.rb
Labels: go

#70576 deno: fix pre-Mojave SDK minimum version
  Formula/deno.rb
Labels: CI-syntax-only, rust

#70088 byteman: fix test
  Formula/byteman.rb
Labels: bottle unneeded, java

#70587 byteman: add livecheck
  Formula/byteman.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck

#70588 opensubdiv: add livecheck
  Formula/opensubdiv.rb
Labels: CI-syntax-only, livecheck

#70585 tcpflow: update stable and livecheck
  Formula/tcpflow.rb
Labels: CI-syntax-only, deprecated license, livecheck

#70586 bulk_extractor: update stable and livecheck
  Formula/bulk_extractor.rb
Labels: CI-syntax-only, livecheck

#70604 tfenv 2.2.0
  Formula/tfenv.rb
Labels: bottle unneeded

#70636 phpstan 0.12.73
  Formula/phpstan.rb
Labels: bottle unneeded, php

#70642 cake 1.0.0
  Formula/cake.rb
Labels: bottle unneeded

#70655 dbus: update livecheck
  Formula/dbus.rb
Labels: CI-syntax-only, livecheck, missing license

#70654 arx-libertatis: update license, stable, livecheck
  Formula/arx-libertatis.rb
Labels: CI-syntax-only, license, livecheck

#70656 elinks: update livecheck
  Formula/elinks.rb
Labels: CI-syntax-only, livecheck, missing license

#70658 fastlane: update livecheck
  Formula/fastlane.rb
Labels: CI-syntax-only, livecheck, ruby

#70659 jenkins: update livecheck
  Formula/jenkins.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck

#70660 kubernetes-cli: update livecheck
  Formula/kubernetes-cli.rb
Labels: CI-syntax-only, go, livecheck, no ARM bottle

#70661 languagetool: update livecheck
  Formula/languagetool.rb
Labels: CI-syntax-only, java, livecheck, no ARM bottle

#70662 latexml: update livecheck
  Formula/latexml.rb
Labels: CI-syntax-only, livecheck, perl

#70663 metabase: update livecheck
  Formula/metabase.rb
Labels: CI-syntax-only, bottle unneeded, java, livecheck, nodejs

#70674 log4cxx: remove O2 reference (it's deprecated)
  Formula/log4cxx.rb
Labels: automerge-skip, bottle unneeded

#70687 winetricks 20210206
  Formula/winetricks.rb
Labels: bottle unneeded

#70695 netcdf: update livecheck
  Formula/netcdf.rb
Labels: CI-syntax-only, livecheck

#70704 phpstan 0.12.74
  Formula/phpstan.rb
Labels: bottle unneeded, php

#70703 augustus: uses zlib from macos
  Formula/augustus.rb
Labels: CI-syntax-only, linux to homebrew-core

#70705 libphonenumber: add livecheck
  Formula/libphonenumber.rb
Labels: CI-syntax-only, livecheck

#70698 spotify-tui: add linux dependencies, use brewed openssl
  Formula/spotify-tui.rb
Labels: linux to homebrew-core, rust

#70707 angband: add livecheck
  Formula/angband.rb
Labels: CI-syntax-only, deprecated license, livecheck

#70525 maxwell 1.30.0
  Formula/maxwell.rb
Labels: 11-arm, bottle unneeded, java

#70732 nethack: update livecheck
  Formula/nethack.rb
Labels: CI-syntax-only, livecheck

#70762 exploitdb 2021-02-09
  Formula/exploitdb.rb
Labels: bottle unneeded

#70733 libmd 1.0.3 (new formula)
  .github/workflows/tests-linux.yml
  Formula/libmd.rb
Labels: automerge-skip, bottle unneeded, linux-only, new formula

#70777 liquibase 4.3.0
  Formula/liquibase.rb
Labels: bottle unneeded, java

#70779 jenkins 2.279
  Formula/jenkins.rb
Labels: bottle unneeded, java

#70719 libbsd 0.11.2
  Formula/libbsd.rb
Labels: bottle unneeded, linux-only

#70797 ophcrack: set expat path for linux only
  Formula/ophcrack.rb
Labels: linux to homebrew-core

#70806 prestodb 0.247
  Formula/prestodb.rb
Labels: bottle unneeded, java

#70825 workflows/triage: fix `no ARM bottle` regex
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip

#70830 lv: make workaround mac-only
  Formula/lv.rb
Labels: deprecated license, linux to homebrew-core

#70850 asciidoc: add livecheck
  Formula/asciidoc.rb
Labels: CI-syntax-only, livecheck, python

#70851 mlkit: add livecheck
  Formula/mlkit.rb
Labels: CI-syntax-only, deprecated license, livecheck, no ARM bottle

#70852 shntool: add livecheck
  Formula/shntool.rb
Labels: CI-syntax-only, livecheck

#70854 rxvt-unicode: add livecheck
  Formula/rxvt-unicode.rb
Labels: CI-syntax-only, livecheck

#70853 jenkins-lts 2.263.4
  Formula/jenkins-lts.rb
Labels: bottle unneeded, java

#70855 neovim: apply patch only to stable builds
  Formula/neovim.rb
Labels: CI-syntax-only, lua

#70857 picard-tools 2.25.0
  Formula/picard-tools.rb
Labels: bottle unneeded, java

#70866 istioctl: set platform-specific build paths
  Formula/istioctl.rb
Labels: go, linux to homebrew-core, no ARM bottle

#70848 cert_error_allowlist: add minio, libbladerf
  audit_exceptions/cert_error_allowlist.json
Labels: CI-syntax-only, automerge-skip

#70863 diff-so-fancy 1.4.0
  Formula/diff-so-fancy.rb
Labels: bottle unneeded

#69032 libdrm 2.4.104
  Formula/libdrm.rb
Labels: bottle unneeded, linux-only

#70868 libass: disable fontconfig only on Linux
  Formula/libass.rb
Labels: linux to homebrew-core

#70886 cimg 2.9.6
  Formula/cimg.rb
Labels: bottle unneeded

#70889 git-quick-stats 2.1.6
  Formula/git-quick-stats.rb
Labels: bottle unneeded

#70895 phoronix-test-suite 10.2.1
  Formula/phoronix-test-suite.rb
Labels: bottle unneeded

#70897 repo 2.12.1
  Formula/repo.rb
Labels: bottle unneeded, python

#70902 maxwell 1.31.0
  Formula/maxwell.rb
Labels: bottle unneeded, java

#66763 m4: patch bundled gnulib
  Formula/m4.rb
Labels: automerge-skip, bottle unneeded

#70908 exploitdb 2021-02-11
  Formula/exploitdb.rb
Labels: bottle unneeded

#70920 phpstan 0.12.75
  Formula/phpstan.rb
Labels: bottle unneeded, php

#70904 mysqltuner: contains deprecated SPDX licenses
  Formula/mysqltuner.rb
Labels: bottle unneeded, needs response

#70944 mdxmini: remove dead homepage URL
  Formula/mdxmini.rb
Labels: automerge-skip, bottle unneeded

#70910 Clarify update guidelines
  CONTRIBUTING.md
Labels: CI-syntax-only, automerge-skip

#70973 exploitdb 2021-02-12
  Formula/exploitdb.rb
Labels: bottle unneeded

#70968 metabase 0.37.9
  Formula/metabase.rb
Labels: bottle unneeded, java, nodejs

#70939 ocp: update livecheck
  Formula/ocp.rb
Labels: CI-syntax-only, livecheck

#70986 patchelf: update livecheck
  Formula/patchelf.rb
Labels: CI-syntax-only, automerge-skip, livecheck

#70987 rethinkdb: update livecheck
  Formula/rethinkdb.rb
Labels: CI-syntax-only, livecheck, no ARM bottle

#70988 rtptools: update livecheck
  Formula/rtptools.rb
Labels: CI-syntax-only, livecheck

#70989 tasksh: update livecheck
  Formula/tasksh.rb
Labels: CI-syntax-only, livecheck

#70990 vramsteg: update livecheck
  Formula/vramsteg.rb
Labels: CI-syntax-only, livecheck, missing license

#70991 zlib: update livecheck
  Formula/zlib.rb
Labels: CI-syntax-only, livecheck

#70992 mpw: update livecheck
  Formula/mpw.rb
Labels: CI-syntax-only, deprecated license, livecheck

#70971 fcl: add head url.
  Formula/fcl.rb
Labels: no ARM bottle

#71010 scalaenv 0.1.8
  Formula/scalaenv.rb
Labels: bottle unneeded
