Repository Homebrew/homebrew-core, pull requests merged in 2021-06, with the labels that each got.

#77336 gnu-getopt: upstream Linux fix
  Formula/gnu-getopt.rb
Labels: CI-syntax-only, linux to homebrew-core

#77584 vtk: align with linux version
  Formula/vtk.rb
Labels: linux to homebrew-core, python

#78437 libepoxy: depend on freeglut on Linux, disable macOS flags on Linux
  Formula/libepoxy.rb
Labels: linux to homebrew-core

#78490 dieharder: add livecheck
  Formula/dieharder.rb
Labels: CI-syntax-only, livecheck, missing license

#78498 checkstyle 8.43
  Formula/checkstyle.rb
Labels: bottle unneeded, bump-formula-pr, java

#78496 basex 9.5.2
  Formula/basex.rb
Labels: bottle unneeded, bump-formula-pr, java

#78542 openjdk: depend on gcc on Linux
  Formula/openjdk.rb
Labels: CI-syntax-only, linux to homebrew-core

#78545 ckan: add reason for `depends_on arch: :x86_64`
  Formula/ckan.rb
Labels: CI-syntax-only

#78546 lgogdownloader: add livecheck
  Formula/lgogdownloader.rb
Labels: CI-syntax-only, livecheck, missing license

#78558 exploitdb 2021-06-02
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#78438 libre: add sysroot only on macOS, fix test on Linux
  Formula/libre.rb
Labels: missing license

#76864 jenv: install fish function symlinks
  Formula/jenv.rb
Labels: bottle unneeded

#76059 at-spi2-core: new formula (Linux-only)
  .github/workflows/linux-pr-tests.yml
  Formula/at-spi2-core.rb
Labels: automerge-skip, linux to homebrew-core, linux-only

#75916 avahi: new formula (Linux-only)
  .github/workflows/linux-pr-tests.yml
  Formula/avahi.rb
Labels: automerge-skip, linux to homebrew-core, linux-only

#78590 zeek: update `inreplace` comment
  Formula/zeek.rb
Labels: CI-syntax-only, python

#78584 `PULL_REQUEST_TEMPLATE.md`: make some steps explicit
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CI-syntax-only, automerge-skip, maintainer feedback

#78631 spigot: uses ncurses from macOS
  Formula/spigot.rb
Labels: CI-syntax-only, linux to homebrew-core

#78636 randomize-lines: add livecheck
  Formula/randomize-lines.rb
Labels: CI-syntax-only, deprecated license, livecheck

#78642 kerl 2.1.2
  Formula/kerl.rb
Labels: bottle unneeded

#78644 exploitdb 2021-06-03
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#78653 flyway 7.9.2
  Formula/flyway.rb
Labels: bottle unneeded, bump-formula-pr, java

#78702 composer 2.1.1
  Formula/composer.rb
Labels: bottle unneeded

#78669 vtk@8.2: add Linux dependencies
  Formula/vtk@8.2.rb
Labels: CI-syntax-only, formula deprecated, legacy, linux to homebrew-core, python

#78663 git: set openssl flags on Linux/macOS
  Formula/git.rb
Labels: linux to homebrew-core

#78667 libscrypt: add linux install support
  Formula/libscrypt.rb
Labels: linux to homebrew-core

#78701 phpmyadmin 5.1.1
  Formula/phpmyadmin.rb
Labels: bottle unneeded, missing license, php

#78714 clang-format: make keg-only on Linux
  Formula/clang-format.rb
Labels: CI-syntax-only, linux to homebrew-core

#78730 snapcraft: update livecheck
  Formula/snapcraft.rb
Labels: CI-syntax-only, livecheck, python

#78731 pbc: add livecheck
  Formula/pbc.rb
Labels: CI-syntax-only, deprecated license, livecheck

#78733 bazel: add livecheck
  Formula/bazel.rb
Labels: CI-syntax-only, java, livecheck

#78734 fswatch: add livecheck
  Formula/fswatch.rb
Labels: CI-syntax-only, livecheck

#78735 storj-uplink: add livecheck
  Formula/storj-uplink.rb
Labels: CI-syntax-only, go, livecheck

#78736 bats-core: fix test in Linux
  Formula/bats-core.rb
Labels: CI-syntax-only, linux to homebrew-core

#78737 folly: depend on gcc on Linux
  Formula/folly.rb
Labels: CI-syntax-only, linux to homebrew-core

#78761 exploitdb 2021-06-04
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#78797 exploitdb 2021-06-05
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#78749 man-db: define paths to various folders
  Formula/man-db.rb
Labels: linux to homebrew-core

#78769 minizip: use workaround only on macOS to fix Linux build
  Formula/minizip.rb
Labels: linux to homebrew-core

#78664 hidapi: install hidtest only on macOS
  Formula/hidapi.rb
Labels: linux to homebrew-core

#78818 gdb: remove conflicts_with
  Formula/gdb.rb
Labels: CI-syntax-only, no ARM bottle, python

#78819 makeself: Updated project website
  Formula/makeself.rb
Labels: CI-syntax-only

#78815 opusfile: change stable URL and test resource
  Formula/opusfile.rb
  audit_exceptions/cert_error_allowlist.json
Labels: automerge-skip

#78812 fdroidserver: fix zlib path, appnope is macOS only
  Formula/fdroidserver.rb
Labels: linux to homebrew-core, python, rust

#78813 gawk: skip make check if no cmp command is installed
  Formula/gawk.rb
Labels: linux to homebrew-core

#78854 argus-clients: add livecheck
  Formula/argus-clients.rb
Labels: CI-syntax-only, livecheck, missing license

#78846 subversion: upstream Linux fix
  Formula/subversion.rb
Labels: java, linux to homebrew-core, perl, ruby

#78816 at-spi2-atk: new formula (Linux-only)
  .github/workflows/linux-pr-tests.yml
  Formula/at-spi2-atk.rb
Labels: automerge-skip, linux to homebrew-core, linux-only

#78862 libffcall: update license
  Formula/libffcall.rb
Labels: CI-syntax-only, license, no ARM bottle

#78865 packr: fix test
  Formula/packr.rb
Labels: go

#78876 composer 2.1.2
  Formula/composer.rb
Labels: bottle unneeded

#76538 gcc: align with linux version
  Formula/gcc.rb
Labels: linux to homebrew-core

#78888 gcc@10: align with linux version
  Formula/gcc@10.rb
Labels: CI-syntax-only, legacy, linux to homebrew-core, no ARM bottle

#78889 gcc@9: align with linux version
  Formula/gcc@9.rb
Labels: CI-syntax-only, legacy, linux to homebrew-core, no ARM bottle

#78898 terrascan: fix test
  Formula/terrascan.rb
Labels: go

#78939 cabal-install: add ARM bootstrap artefact
  Formula/cabal-install.rb
Labels: CI-syntax-only, haskell, no ARM bottle

#78943 pandoc: depend on `llvm` for the build on ARM
  Formula/pandoc.rb
Labels: CI-force-arm, haskell, no ARM bottle

#78904 fltk: add head url and install steps
  Formula/fltk.rb
Labels: CI-syntax-only, license

#78996 exiftags: add livecheck
  Formula/exiftags.rb
Labels: CI-syntax-only, livecheck, missing license

#79001 exploitdb 2021-06-09
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#78974 sysstat 12.5.4
  Formula/sysstat.rb
Labels: bottle unneeded, bump-formula-pr, linux-only

#78945 haskell-stack: depend on `llvm` for build on ARM
  Formula/haskell-stack.rb
Labels: CI-force-arm, haskell, no ARM bottle

#79040 ssed: add livecheck
  Formula/ssed.rb
Labels: CI-syntax-only, livecheck

#78893 gcc@6: align with linux version
  Formula/gcc@6.rb
Labels: CI-syntax-only, legacy, linux to homebrew-core, no ARM bottle

#78892 gcc@7: align with linux version
  Formula/gcc@7.rb
Labels: CI-syntax-only, legacy, linux to homebrew-core, no ARM bottle

#78890 gcc@8: align with linux version
  Formula/gcc@8.rb
Labels: CI-syntax-only, legacy, linux to homebrew-core, no ARM bottle

#79041 phpstan 0.12.89
  Formula/phpstan.rb
Labels: bottle unneeded, bump-formula-pr, php

#79066 hledger: depend on llvm for build on ARM
  Formula/hledger.rb
Labels: CI-syntax-only, haskell, no ARM bottle

#79070 dgraph: deprecate
  Formula/dgraph.rb
Labels: CI-syntax-only, formula deprecated, go

#79074 dgraph: remove livecheck
  Formula/dgraph.rb
Labels: CI-syntax-only, formula deprecated, go, livecheck

#79080 go@1.14: remove livecheck
  Formula/go@1.14.rb
Labels: CI-syntax-only, formula deprecated, legacy, livecheck, no ARM bottle

#79081 gcc@4.9: remove livecheck
  Formula/gcc@4.9.rb
Labels: CI-syntax-only, formula deprecated, legacy, livecheck, missing license

#79082 libu2f-host: remove livecheck
  Formula/libu2f-host.rb
Labels: CI-syntax-only, deprecated license, formula deprecated, livecheck

#79083 node@10: remove livecheck
  Formula/node@10.rb
Labels: CI-syntax-only, formula deprecated, legacy, livecheck, no ARM bottle

#79079 dnsmasq: update urls to avoid redirections
  Formula/dnsmasq.rb
Labels: CI-syntax-only

#79008 cdrtools: update homepage
  Formula/cdrtools.rb
Labels: CI-syntax-only, missing license

#79114 exploitdb 2021-06-10
  Formula/exploitdb.rb
Labels: bottle unneeded, bump-formula-pr

#78814 elfutils (new formula)
  .github/workflows/linux-pr-tests.yml
  Formula/elfutils.rb
Labels: automerge-skip, linux to homebrew-core

#79096 ed: do not prefix with g on Linux
  Formula/ed.rb
Labels: linux to homebrew-core

#79143 less: fix head build
  Formula/less.rb
Labels: CI-syntax-only, perl

#79167 lsof: update homepage
  Formula/lsof.rb
Labels: CI-syntax-only, automerge-skip

#79174 suricata: update urls to avoid redirections
  Formula/suricata.rb
Labels: CI-syntax-only, livecheck, python, rust

#79175 jumanpp: update homepage to use https
  Formula/jumanpp.rb
Labels: CI-syntax-only

#79176 raptor: update urls to https
  Formula/raptor.rb
Labels: CI-syntax-only, missing license

#79177 jhiccup: update homepage
  Formula/jhiccup.rb
Labels: CI-syntax-only, bottle unneeded, missing license

#79178 sysbench: add head url.
  Formula/sysbench.rb
Labels: no ARM bottle

#79199 cacli: fix sha
  Formula/cacli.rb
Labels: go

#79221 dmalloc: add livecheck
  Formula/dmalloc.rb
Labels: CI-syntax-only, livecheck

#79242 libirecovery: upstream Linux fix
  Formula/libirecovery.rb
Labels: CI-syntax-only, linux to homebrew-core

#79240 hypre: upstream Linux fix
  Formula/hypre.rb
Labels: linux to homebrew-core

#79227 libfuse 3.10.4
  Formula/libfuse.rb
Labels: bottle unneeded, bump-formula-pr, linux-only

#75927 gtk+3: upstream Linux fixes
  Formula/gtk+3.rb
Labels: CI-syntax-only, linux to homebrew-core

#79235 qwt: add livecheck
  Formula/qwt.rb
Labels: CI-syntax-only, livecheck

#79263 kcov: add Linux dependencies
  Formula/kcov.rb
Labels: CI-syntax-only, deprecated license, linux to homebrew-core

#79259 gcc@4.9: align with Linux version
  Formula/gcc@4.9.rb
Labels: formula deprecated, legacy, linux to homebrew-core, missing license

#79264 mysql@5.7: add workaround for linux build
  Formula/mysql@5.7.rb
Labels: CI-syntax-only, legacy, linux to homebrew-core

#79286 crc32c: upstream Linux fix
  Formula/crc32c.rb
Labels: linux to homebrew-core

#79283 calc: upstream Linux fix
  Formula/calc.rb
Labels: CI-syntax-only, linux to homebrew-core

#79285 apachetop: upstream Linux fix
  Formula/apachetop.rb
Labels: CI-syntax-only, linux to homebrew-core

#79281 bitrise: upstream Linux fix
  Formula/bitrise.rb
Labels: CI-syntax-only, go, linux to homebrew-core

#79280 adios2: upstream Linux fix
  Formula/adios2.rb
Labels: linux to homebrew-core, python

#79276 libtorrent-rasterbar: upstream Linux fix
  Formula/libtorrent-rasterbar.rb
Labels: linux to homebrew-core, python

#79258 bochs: add livecheck
  Formula/bochs.rb
Labels: CI-syntax-only, livecheck, missing license

#79290 liblzf: add livecheck
  Formula/liblzf.rb
Labels: CI-syntax-only, livecheck, missing license

#79271 gollum: update homepage
  Formula/gollum.rb
Labels: CI-syntax-only, go

#79277 gupnp: upstream Linux fix
  Formula/gupnp.rb
Labels: linux to homebrew-core, python

#79284 cogl: upstream Linux fix
  Formula/cogl.rb
Labels: license, linux to homebrew-core

#79267 pyenv: depend on Python 3.9 for test on Linux
  Formula/pyenv.rb
Labels: CI-syntax-only, linux to homebrew-core

#79275 gperftools: upstream Linux fix
  Formula/gperftools.rb
Labels: linux to homebrew-core

#79334 gcc@6: remove wrongly commited unless OS.mac?
  Formula/gcc@6.rb
Labels: CI-syntax-only, legacy, linux to homebrew-core, no ARM bottle

#79315 poco: set rpath for m1 support
  Formula/poco.rb
Labels: CI-force-arm, no ARM bottle

#79318 source-to-image: m1-support set arch to arm64 or amd64 depending on H…
  Formula/source-to-image.rb
Labels: CI-force-arm, go, no ARM bottle

#79330 editorconfig: m1-support add rpath and build out of tree
  Formula/editorconfig.rb
Labels: CI-force-arm, no ARM bottle

#79336 x264: update livecheck `url`
  Formula/x264.rb
Labels: CI-syntax-only, livecheck

#79335 dolt: align homepage with stable URL
  Formula/dolt.rb
Labels: CI-syntax-only, go

#79311 bibclean: add livecheck block
  Formula/bibclean.rb
Labels: CI-syntax-only, deprecated license, livecheck

#79387 exim: update livecheck
  Formula/exim.rb
Labels: CI-syntax-only, livecheck

#79384 bash: update livecheck
  Formula/bash.rb
Labels: CI-syntax-only, livecheck

#79392 x264: update livecheck
  Formula/x264.rb
Labels: CI-syntax-only, livecheck

#79395 mmctl: revert upgrade to 6.0.0
  Formula/mmctl.rb
Labels: CI-syntax-only, go

#79397 go@1.10: workaround permission issues on Linux
  Formula/go@1.10.rb
Labels: CI-syntax-only, formula disabled, legacy, linux to homebrew-core, no ARM bottle

#79405 jbig2dec: update livecheck
  Formula/jbig2dec.rb
Labels: CI-syntax-only, livecheck

#79426 liboping: add livecheck
  Formula/liboping.rb
Labels: CI-syntax-only, deprecated license, livecheck

#79398 lapack: make keg-only on Linux
  Formula/lapack.rb
Labels: CI-syntax-only, linux to homebrew-core

#79431 gcsfuse: fix separator on Linux
  Formula/gcsfuse.rb
Labels: go, linux to homebrew-core

#79434 libgnomecanvas: use x11 flags for test on Linux
  Formula/libgnomecanvas.rb
Labels: linux to homebrew-core, missing license

#79432 gtkmm: use x11 flags for test on Linux
  Formula/gtkmm.rb
Labels: linux to homebrew-core

#79433 libglade: use x11 flags for test on Linux
  Formula/libglade.rb
Labels: linux to homebrew-core, missing license

#79436 man-db: add alternative test for Linux
  Formula/man-db.rb
Labels: linux to homebrew-core

#79437 neko: add linux-only dependencies
  Formula/neko.rb
Labels: linux to homebrew-core

#79435 libomp: make keg only on Linux, fix test for gcc-5
  Formula/libomp.rb
Labels: linux to homebrew-core

#79438 haskell-language-server: remove LLVM dependency
  Formula/haskell-language-server.rb
Labels: automerge-skip, bottle unneeded, haskell

#77457 workflows/tests: set test-bot arguments.
  .github/workflows/tests.yml
Labels: CI-force-arm, CI-test-bot-fail-fast, CI-test-bot-skip-recursive-dependents, automerge-skip, stale

#79460 grt: add to `github_prerelease_allowlist`
  audit_exceptions/github_prerelease_allowlist.json
Labels: automerge-skip

#79458 workflows/tests: fix if conditions
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip

#79457 getxbook: add livecheck
  Formula/getxbook.rb
Labels: CI-syntax-only, livecheck

#78878 ammonite-repl: add version
  Formula/ammonite-repl.rb
Labels: CI-syntax-only, java

#79489 vifm: add head
  Formula/vifm.rb
Labels: CI-syntax-only

#79475 ode: fix test on Linux
  Formula/ode.rb
Labels: linux to homebrew-core, missing license

#79520 luajit-openresty: specify `version`
  Formula/luajit-openresty.rb
Labels: CI-syntax-only

#79519 libident: add livecheck
  Formula/libident.rb
Labels: CI-syntax-only, livecheck, missing license, no ARM bottle

#79522 llvm@11: update livecheck
  Formula/llvm@11.rb
Labels: CI-syntax-only, legacy, livecheck, python

#79477 postgresql: adjust flags for Linux, fix shim paths
  Formula/postgresql.rb
Labels: linux to homebrew-core, perl

#79472 nginx: remove non-portable tar options
  Formula/nginx.rb
Labels: linux to homebrew-core

#79527 launchctl-completion: add license
  Formula/launchctl-completion.rb
Labels: CI-syntax-only

#79529 apm-bash-completion: add license
  Formula/apm-bash-completion.rb
Labels: CI-syntax-only, license

#79543 operator-sdk: add livecheck
  Formula/operator-sdk.rb
Labels: CI-syntax-only, go, livecheck

#79473 nspr: disable workaround on Linux
  Formula/nspr.rb
Labels: linux to homebrew-core

#79574 alsa-lib 1.2.5.1
  Formula/alsa-lib.rb
Labels: bottle unneeded, bump-formula-pr, linux-only

#79610 workflows/tests: update skip unbottled ARM ENV
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip

#79614 nacl: add livecheck
  Formula/nacl.rb
Labels: CI-syntax-only, livecheck, missing license, no ARM bottle
