Repository Homebrew/homebrew-core, pull requests merged in 2022-02, with the labels that each got.

#94189 colima: add service
  Formula/colima.rb
Labels: go, macos-only, CI-no-bottles

#94231 flat_namespace_allowlist: add `xmlrpc-c`
  audit_exceptions/flat_namespace_allowlist.json
Labels: CI-syntax-only, automerge-skip

#94218 plotutils: fix erroneous use of the `-flat_namespace` flag
  Formula/plotutils.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#94194 fits: disable on Linux
  Formula/fits.rb
Labels: java, macos-only

#94264 colima: remove service block
  Formula/colima.rb
Labels: go, CI-syntax-only, macos-only

#94087 autobump: track more formulae
  .github/workflows/autobump.yml
Labels: CI-syntax-only, automerge-skip, workflows

#94211 ice: add dependencies, fix Linux build
  Formula/ice.rb
Labels: CI-no-bottles, no Linux bottle, long build

#94344 git: macOS pre-10.13 requires brewed zlib
  Formula/git.rb
Labels: bottle unneeded, CI-syntax-only, CI-no-bottles

#94539 ffmpegthumbnailer: fix test
  Formula/ffmpegthumbnailer.rb
Labels: license, CI-no-bottles

#94644 terminalimageviewer: requires Catalina minimum
  Formula/terminalimageviewer.rb
Labels: CI-syntax-only

#94646 molten-vk: mark as macOS-only
  Formula/molten-vk.rb
Labels: CI-syntax-only, macos-only

#94661 sonarqube-lts: update livecheck
  Formula/sonarqube-lts.rb
Labels: java, livecheck, CI-syntax-only

#94702 node: don't enable LTO on Mojave
  Formula/node.rb
Labels: CI-syntax-only

#94706 ffmpeg: fix HEAD install
  Formula/ffmpeg.rb
Labels: CI-syntax-only

#94800 synced_versions_formulae: add `fb303`
  synced_versions_formulae.json
Labels: CI-syntax-only, automerge-skip

#94810 proj@7: undeprecate
  Formula/proj@7.rb
Labels: legacy, CI-syntax-only

#94801 synced_versions_formulae: remove cross-toolchain formulae
  synced_versions_formulae.json
Labels: CI-syntax-only, automerge-skip

#94825 tests: show linkage and bottle output earlier
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#94557 Remove sonarqube-lts from the autobump list
  .github/workflows/autobump.yml
Labels: CI-syntax-only, automerge-skip, workflows

#93732 workflows/tests: set longer timeout for self-hosted Linux runner too
  .github/workflows/tests.yml
Labels: ready to merge, CI-syntax-only, automerge-skip, workflows

#94907 workflows/tests: error when `long build` is set without `CI-long-timeout`
  .github/workflows/tests.yml
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#94997 mapserver: fix Linux install
  Formula/mapserver.rb
Labels: python, ready to merge, no Linux bottle

#95062 spatialite-tools: fix build on Linux
  Formula/spatialite-tools.rb
Labels: ready to merge, CI-no-bottles, no Linux bottle

#95102 libewf: fix the branch name
  Formula/libewf.rb
Labels: CI-no-bottles

#95136 triage: add more `long build` formulae
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#95248 rdkit: use brewed catch2
  Formula/rdkit.rb
Labels: python, CI-no-bottles

#95266 rdkit: actually use Homebrew `catch2`
  Formula/rdkit.rb
Labels: python, ready to merge, CI-no-bottles

#95254 standardese: investigate failures
  Formula/standardese.rb
Labels: do not merge, CI-no-bottles, no Linux bottle

#95302 dotnet: ensure sources are cleaned up after install
  Formula/dotnet.rb
Labels: automerge-skip, CI-skip-recursive-dependents, CI-linux-self-hosted, CI-skip-dependents, CI-no-bottles, long build

#95334 dafny: fix Linux build
  Formula/dafny.rb
Labels: java, CI-no-bottles, no Linux bottle, dotnet

#95358 libtorrent-rasterbar: apply patch for Boost 1.78
  Formula/libtorrent-rasterbar.rb
Labels: python, ready to merge, CI-no-bottles

#95389 xmlsectool: Tweak test, `--listBlacklist` is deprecated
  Formula/xmlsectool.rb
Labels: java, CI-no-bottles

#95391 wiggle: fixes for Linux
  Formula/wiggle.rb
Labels: license, CI-no-bottles, no Linux bottle

#95444 collada-dom: fix Linux build
  Formula/collada-dom.rb
Labels: missing license, CI-no-bottles, no Linux bottle

#95449 standardese: fix Linux build
  Formula/standardese.rb
Labels: CI-no-bottles, no Linux bottle

#95447 uhd: fix Linux build
  Formula/uhd.rb
Labels: python, CI-no-bottles, no Linux bottle

#95415 weighttp: build with autotools
  Formula/weighttp.rb
Labels: CI-no-fail-fast, CI-no-bottles, no Linux bottle

#95473 thrift: exclude building py3 lib
  Formula/thrift.rb
Labels: CI-no-bottles

#95466 skaffold: add livecheck
  Formula/skaffold.rb
Labels: go, livecheck, CI-syntax-only

#95549 gdb: mark as Intel-only
  Formula/gdb.rb
Labels: python, no ARM bottle

#95548 qemu: fix FD12FLOPPY url
  Formula/qemu.rb
Labels: CI-no-bottles

#95588 mold: remove no-longer-needed xxhash dependency
  Formula/mold.rb
Labels: CI-no-bottles

#95650 jless: update homepage
  Formula/jless.rb
Labels: rust

#95737 Stop service if it is present on system (it may be spinning)
  cmd/postgresql-upgrade-database.rb
Labels: automerge-skip

#95440 workflows/tests: always test dependents unless requested otherwise
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#95446 lgogdownloader: fix Linux build
  Formula/lgogdownloader.rb
Labels: ready to merge, CI-no-bottles, no Linux bottle

#95849 netcdf: fix livecheck and resource URL
  Formula/netcdf.rb
Labels: livecheck, CI-no-bottles, long build

#95741 cassowary: fix source url
  Formula/cassowary.rb
Labels: go, ready to merge, CI-no-fail-fast, CI-no-bottles
