Repository Homebrew/homebrew-core, pull requests merged in 2022-08, with the labels that each got.

#107054 bazaar: deprecate
  Formula/bazaar.rb
Labels: formula disabled, missing license, CI-syntax-only, macos-only

#106660 atk: fix glib-utils
  Formula/atk.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#105614 ghostscript: fix builds pre-High Sierra
  Formula/ghostscript.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-no-bottles, long build

#107229 augustus: deprecate
  Formula/augustus.rb
Labels: formula deprecated, CI-syntax-only, boost

#107231 traefik@1: deprecate
  Formula/traefik@1.rb
Labels: go, nodejs, legacy, formula disabled, CI-syntax-only

#107252 libbluray: improve test
  Formula/libbluray.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#107449 gcc: fix comment
  Formula/gcc.rb
Labels: CI-syntax-only

#107454 autobump: remove `pocsuite3`
  .github/workflows/autobump.yml
Labels: CI-syntax-only, automerge-skip, workflows

#107562 .github/workflows: migrate to python@3.10
  .github/workflows/triage.yml
Labels: automerge-skip, workflows

#107482 llvm@13: remove `gcc` dependency
  Formula/llvm@13.rb
Labels: legacy, CI-syntax-only, CI-no-bottles

#107651 jpeg-xl: don't match `-base` tags in livecheck
  Formula/jpeg-xl.rb
Labels: livecheck, CI-syntax-only

#107673 lynx: add Fossies mirror
  Formula/lynx.rb
Labels: deprecated license, CI-no-bottles

#107698 statik: deprecate
  Formula/statik.rb
Labels: python, formula deprecated, CI-syntax-only

#107154 ksh: deprecate
  Formula/ksh.rb
Labels: formula deprecated, CI-no-bottles

#107695 python@3.9: avoid shelling out to `brew`
  Formula/python@3.9.rb
Labels: legacy, CI-skip-recursive-dependents, CI-no-bottles

#107662 libpython-tabulate: use Python's `libexec/"bin"`
  Formula/libpython-tabulate.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#107664 numpy: use Python's `libexec/"bin"`
  Formula/numpy.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#107663 libxml2: use explicitly versioned Python in test
  Formula/libxml2.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, icu4c

#107730 protobuf@3: use Python's `libexec/"bin`
  Formula/protobuf@3.rb
Labels: legacy, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#107731 py3cairo: use Python's `libexec/"bin`
  Formula/py3cairo.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#107733 pygobject3: use Python's `libexec/"bin"`
  Formula/pygobject3.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#107735 six: use Python's `libexec/"bin"`
  Formula/six.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#107511 jpeg: make keg-only
  Formula/jpeg.rb
Labels: ready to merge, automerge-skip, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#107660 libcython: use Python's `libexec/"bin"` directory
  Formula/libcython.rb
Labels: ready to merge, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#107732 pybind11: use Python's `libexec/"bin"`
  Formula/pybind11.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#107734 pyqt@5: use Python's `libexec/"bin"`
  Formula/pyqt@5.rb
Labels: python, legacy, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, long build

#106658 gsettings-desktop-schemas: fix build glib-utils
  Formula/gsettings-desktop-schemas.rb
Labels: CI-no-bottles, long build

#107770 swift: override default swiftpm modulecache
  Formula/swift.rb
Labels: python, ready to merge, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, long build, icu4c

#107867 gitfs: fix test failure
  Formula/gitfs.rb
Labels: python, CI-no-bottles

#107868 pillow: remove `setuptools` workaround
  Formula/pillow.rb
Labels: CI-no-bottles

#107884 gauche: update test
  Formula/gauche.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#105651 sdl2_net: update homepage and livecheck
  Formula/sdl2_net.rb
Labels: livecheck, CI-syntax-only

#108041 mapserver: fix test
  Formula/mapserver.rb
Labels: python, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#108046 gdcm: fix test
  Formula/gdcm.rb
Labels: python, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#108040 gdal: fix test
  Formula/gdal.rb
Labels: python, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#108101 mold: update test
  Formula/mold.rb
Labels: CI-no-bottles

#108171 mpd: add comment documenting workaround removal
  Formula/mpd.rb
Labels: CI-syntax-only, boost, icu4c, ffmpeg

#106155 Update github actions to use composite action created before
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#107875 julia: test build
  Formula/julia.rb
Labels: perl, no ARM bottle, CI-no-bottles, no Linux bottle

#108234 dsda-doom: fix formatting of `caveats`.
  Formula/dsda-doom.rb
Labels: CI-syntax-only

#108283 spidermonkey: fix build with new setuptools
  Formula/spidermonkey.rb
Labels: rust, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, icu4c

#108365 workflows/tests: split summary and bottle result again
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#108376 workflows/tests: use summary action for dependent tests
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#106277 molten-vk: add HEAD support
  Formula/molten-vk.rb
Labels: macos-only

#108407 kubecm: update build ldflags
  Formula/kubecm.rb
Labels: go, CI-no-bottles

#108494 pypi_formula_mappings: add enex2notion
  pypi_formula_mappings.json
Labels: automerge-skip

#108440 afflib: fix `python3` reference.
  Formula/afflib.rb
Labels: python, ready to merge, missing license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#108441 alot: fix `python3` references.
  Formula/alot.rb
Labels: python, ready to merge, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#108478 ansible-lint: fix `python3` reference.
  Formula/ansible-lint.rb
Labels: python, rust, ready to merge, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#108479 ansible: fix `python3` references.
  Formula/ansible.rb
Labels: python, rust, ready to merge, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#108421 x86_64-linux-gnu-binutils: make keg only on Linux
  Formula/x86_64-linux-gnu-binutils.rb
Labels: ready to merge, CI-syntax-only

#108562 SFML: fix build on high_sierra
  Formula/sfml.rb
Labels: CI-no-bottles

#108566 todoman: remove libpython-tabulate dependency
  Formula/todoman.rb
Labels: python

#108581 guichan: use http for fixedfont.bmp resource to make curl happy
  Formula/guichan.rb
Labels: missing license, CI-no-bottles

#108280 lasso: depend on `libxml2`
  Formula/lasso.rb
Labels: ready to merge, CI-no-bottles

#108504 astrometry-net: fix `python3` references.
  Formula/astrometry-net.rb
Labels: python, ready to merge, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#108493 workflows/tests: collapse some output in the summary
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#108635 graphicsmagick: disable jpeg-xl support, which seems to require unreleased version of libjxl
  Formula/graphicsmagick.rb
Labels: CI-no-bottles

#108665 glibc: don't try to link to libgd
  Formula/glibc.rb
Labels: linux-only, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#108777 ghorg: change desc
  Formula/ghorg.rb
Labels: go, CI-syntax-only, CI-no-bottles

#109056 gcc@5: drop glibc dependency
  Formula/gcc@5.rb
Labels: legacy, missing license, CI-syntax-only, CI-no-bottles

#108681 zlib: don't build with glibc@2.13
  Formula/zlib.rb
Labels: ready to merge, CI-skip-recursive-dependents, CI-linux-self-hosted, CI-no-fail-fast, CI-no-bottles

#109111 CODEOWNERS: remove myself from .github
  CODEOWNERS
Labels: automerge-skip

#109173 krb5: disable gettext
  Formula/krb5.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#109133 git: use linux-headers@5.15
  Formula/git.rb
Labels: CI-no-bottles

#109165 webkitgtk: add build dependency on `gobject-introspection`
  Formula/webkitgtk.rb
Labels: ruby, perl, linux-only, CI-no-bottles, icu4c

#109186 binutils: remove texinfo dependency
  Formula/binutils.rb
Labels: CI-skip-dependents, CI-no-bottles

#109189 libnsl: remove gettext dependency
  Formula/libnsl.rb
Labels: linux-only, CI-no-bottles

#109108 GitHub Workflows security hardening
  .github/workflows/dispatch-rebottle.yml
Labels: CI-syntax-only, automerge-skip, workflows

#109075 postgresql@14: fix data directory migration caveat
  Formula/postgresql@14.rb
Labels: legacy, perl, formula deprecated, CI-no-bottles, icu4c

#109222 glibc: only depend on linux-headers at build time.
  Formula/glibc.rb
Labels: linux-only, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#106665 poppler: fixes High Sierra build
  Formula/poppler.rb
Labels: CI-no-bottles

#109302 salt: deprecate
  Formula/salt.rb
Labels: python, formula deprecated, CI-syntax-only, CI-no-bottles

#107808 tre: add livecheck and license
  Formula/tre.rb
Labels: CI-syntax-only
