Repository Homebrew/homebrew-core, pull requests merged in 2022-03, with the labels that each got.

#96129 erlang@21: remove livecheck
  Formula/erlang@21.rb
Labels: legacy, livecheck, formula deprecated, CI-syntax-only, no ARM bottle

#96173 vespa-cli 7.552.18
  Formula/vespa-cli.rb
Labels: go, bump-formula-pr

#96132 workflows/publish-commit-bottles: allow running on self-hosted
  .github/workflows/publish-commit-bottles.yml
Labels: automerge-skip, workflows

#96197 charmcraft: use craft-cli commit since tag was modified
  Formula/charmcraft.rb
Labels: python, rust, CI-no-bottles

#96250 libarchive: update livecheck
  Formula/libarchive.rb
Labels: livecheck, CI-syntax-only

#96251 bib-tool: Fix deprecated license for bib-tool
  Formula/bib-tool.rb
Labels: CI-syntax-only, license

#96253 sonarqube: update livecheck
  Formula/sonarqube.rb
Labels: java, livecheck, CI-syntax-only

#96401 gmt: update 6.3.0_2 bottle.
  Formula/gmt.rb
Labels: CI-syntax-only

#96402 sbcl: update 2.1.9 bottle.
  Formula/sbcl.rb
Labels: CI-syntax-only

#96377 sdl12-compat: fix test on Linux
  Formula/sdl12-compat.rb
Labels: CI-no-fail-fast, CI-no-bottles, no Linux bottle

#96510 mergepbx: deprecate
  Formula/mergepbx.rb
Labels: formula deprecated, CI-syntax-only, deprecated license

#95472 aubio: fix build on linux
  Formula/aubio.rb
Labels: python, test failure, missing license, automerge-skip, CI-no-bottles, no Linux bottle

#96554 libreplaygain: add license
  Formula/libreplaygain.rb
Labels: CI-syntax-only, license

#96549 minimodem: add license
  Formula/minimodem.rb
Labels: CI-syntax-only, license

#96557 easy-tag: add license, update homepage
  Formula/easy-tag.rb
Labels: CI-syntax-only, license, no Linux bottle

#96543 cvsync: add license
  Formula/cvsync.rb
Labels: CI-syntax-only, license, no Linux bottle

#96544 template-glib: add license
  Formula/template-glib.rb
Labels: CI-syntax-only, license, no Linux bottle

#96581 sfst: fix build/test on Linux
  Formula/sfst.rb
Labels: CI-no-bottles, no Linux bottle

#96607 workflows/tests: don't run dependent tests on cancel
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#96658 fsh: deprecate
  Formula/fsh.rb
Labels: formula deprecated, CI-syntax-only, deprecated license, CI-no-bottles, no Linux bottle

#96682 gistit: fix build for Linux
  Formula/gistit.rb
Labels: CI-no-bottles, no Linux bottle

#96708 giza: hardcode the tests run
  Formula/giza.rb
Labels: CI-no-bottles

#96847 e2fsprogs: allow -flat_namespace
  audit_exceptions/flat_namespace_allowlist.json
Labels: automerge-skip

#96970 docui: use go@1.17 and deprecate
  Formula/docui.rb
Labels: go, formula deprecated, CI-no-fail-fast, CI-no-bottles

#96948 antibody: use go@1.17 and deprecate
  Formula/antibody.rb
Labels: go, formula deprecated, CI-no-fail-fast, CI-no-bottles

#97078 publish: fix build on Linux
  Formula/publish.rb
Labels: swift, CI-no-bottles, no Linux bottle

#97100 pulp: add livecheck, update homepage and license
  Formula/pulp.rb
Labels: nodejs, livecheck, CI-syntax-only, license

#97155 kubeprod: use go@1.17 and deprecate
  Formula/kubeprod.rb
Labels: go, formula deprecated, CI-no-fail-fast, CI-no-bottles

#97153 kubeless: use go@1.17 and deprecate
  Formula/kubeless.rb
Labels: go, formula deprecated, CI-no-fail-fast, CI-no-bottles

#97211 xcodegen: fix build on Linux
  Formula/xcodegen.rb
Labels: swift, CI-no-bottles, no Linux bottle

#97210 xclogparser: fix build on Linux
  Formula/xclogparser.rb
Labels: swift, CI-no-bottles, no Linux bottle

#97208 xcbeautify: fix build on Linux
  Formula/xcbeautify.rb
Labels: swift, CI-no-bottles, no Linux bottle

#97308 odin: fix build on Linux
  Formula/odin.rb
Labels: no ARM bottle, CI-no-bottles, no Linux bottle

#97300 ircii: fix build on Linux
  Formula/ircii.rb
Labels: CI-no-bottles, no Linux bottle

#97317 clutter: fix build on Linux
  Formula/clutter.rb
Labels: deprecated license, CI-no-bottles, no Linux bottle

#97318 gerbv: fix test on Linux
  Formula/gerbv.rb
Labels: CI-no-bottles, no Linux bottle

#97359 synfig: fix build on Linux
  Formula/synfig.rb
Labels: ready to merge, perl, CI-no-bottles, no Linux bottle

#97182 CONTRIBUTING: update Lima guide
  CONTRIBUTING.md
Labels: automerge-skip

#97466 Tests: set the default timeout to 90 minutes
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#97467 Upgrade actions/github-script@v6
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#97550 siril: fix build on Linux
  Formula/siril.rb
Labels: perl, CI-no-bottles, no Linux bottle

#97632 rich-cli: add rich alias
  Aliases/rich
Labels: automerge-skip

#97741 ship: deprecate
  Formula/ship.rb
Labels: go, nodejs, formula deprecated, CI-no-bottles, no Linux bottle

#97786 gource: installing from --head requires pcre2
  Formula/gource.rb
Labels: CI-syntax-only, CI-no-bottles

#97883 msktutil: fix build on Linux
  Formula/msktutil.rb
Labels: deprecated license, CI-no-bottles, no Linux bottle

#97878 lockrun: fix test on Linux
  Formula/lockrun.rb
Labels: missing license, CI-no-bottles, no Linux bottle

#97911 minipro: add `head`
  Formula/minipro.rb
Labels: CI-no-bottles

#97927 universal_binary_allowlist: remove `gitversion`
  audit_exceptions/universal_binary_allowlist.json
Labels: automerge-skip
