Repository Homebrew/homebrew-core, pull requests merged in 2022-11, with the labels that each got.

#114717 numpy@1.16: disable
  Formula/numpy@1.16.rb
Labels: legacy, formula disabled, CI-syntax-only, macos-only

#114724 apache-pulsar and libpulsar are no longer in sync
  synced_versions_formulae.json
Labels: automerge-skip

#114714 lightning: depend on x86_64
  Formula/lightning.rb
Labels: deprecated license, no ARM bottle, CI-no-bottles

#114807 gandi.cli: deprecate
  Formula/gandi.cli.rb
Labels: python, formula deprecated, CI-syntax-only

#114757 sollya: combine `test do` blocks
  Formula/sollya.rb
Labels: CI-no-bottles

#114738 clair: update sha
  Formula/clair.rb
Labels: go, checksum mismatch, CI-no-fail-fast

#114937 tor: Fix build failure
  Formula/tor.rb
Labels: CI-no-bottles

#114940 cabocha: add mirror
  Formula/cabocha.rb
Labels: missing license, CI-no-fail-fast, CI-no-bottles

#115052 ahcpd: update URL
  Formula/ahcpd.rb
Labels: CI-no-bottles

#114933 drill: update sha
  Formula/drill.rb
Labels: upstream issue, rust, checksum mismatch, ready to merge, CI-no-fail-fast, CI-no-bottles

#114604 creduce: use llvm@15 for HEAD
  Formula/creduce.rb
Labels: perl, CI-syntax-only, no ARM bottle, CI-no-bottles

#114379 chisel: fix build and test
  Formula/chisel.rb
Labels: ready to merge, macos-only

#115192 ucg: depend on x86_64
  Formula/ucg.rb
Labels: CI-syntax-only

#115294 cpu_features: depend on x86_64
  Formula/cpu_features.rb
Labels: no ARM bottle

#115221 xlearn: depend on x86_64
  Formula/xlearn.rb
Labels: CI-syntax-only, no ARM bottle

#115368 tcc: restrict to Catalina
  Formula/tcc.rb
Labels: CI-syntax-only

#114100 workflows: run tests on 13-arm64
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#115733 jenkins-lts: fix homepage URL
  Formula/jenkins-lts.rb
Labels: java, CI-syntax-only, CI-no-bottles

#115928 z3: fix test on Ventura
  Formula/z3.rb
Labels: CI-skip-recursive-dependents, CI-no-bottles

#116009 hunspell: update dictionary link
  Formula/hunspell.rb
Labels: CI-syntax-only

#116187 workflows/triage: update legacy label
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#116156 httrack: add license
  Formula/httrack.rb
Labels: CI-syntax-only, license

#116200 workflows/triage: update CI-linux-self-hosted formulae
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#116251 sblim-sfcc: add license
  Formula/sblim-sfcc.rb
Labels: CI-syntax-only, license

#116184 vtk@8.2: disable
  Formula/vtk@8.2.rb
Labels: python, legacy, formula deprecated, CI-syntax-only, boost, icu4c

#116372 apollo-cli: deprecate
  Formula/apollo-cli.rb
Labels: nodejs, formula deprecated, CI-syntax-only, CI-no-bottles

#116385 gcsfuse: add livecheck
  Formula/gcsfuse.rb
Labels: go, livecheck, CI-syntax-only, linux-only

#115661 libnghttp2, nghttp2 1.51.0
  Formula/libnghttp2.rb
  Formula/nghttp2.rb
Labels: CI-linux-self-hosted, CI-no-fail-fast, long build

#116512 acpica: update livecheck
  Formula/acpica.rb
Labels: livecheck, CI-syntax-only

#116511 molecule: remove jsonschema references from pypi_formula_mappings.json
  Formula/molecule.rb
  pypi_formula_mappings.json
Labels: python, automerge-skip, python-3.11-migration

#116513 poetry: remove jsonschema references from pypi_formula_mappings.json
  Formula/poetry.rb
  pypi_formula_mappings.json
Labels: python, automerge-skip, CI-no-bottles, python-3.11-migration

#116618 workflows: remove `HOMEBREW_CHANGE_ARCH_TO_ARM`
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#116650 Correct ponylang website address
  Formula/ponyc.rb
Labels: CI-syntax-only

#116670 fluxctl: deprecate
  Formula/fluxctl.rb
Labels: go, formula deprecated

#116654 xmltoman: fix test
  Formula/xmltoman.rb
Labels: perl, deprecated license, CI-no-bottles

#116847 workflows: migrate to actions/cache@v3
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/publish-commit-bottles.yml
Labels: CI-syntax-only, automerge-skip, workflows

#116960 libbluray: update 1.3.4 bottle.
  Formula/libbluray.rb
Labels: CI-syntax-only

#116923 tests.yml: run CI on Intel Ventura
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#116992 git-lfs: update homepage
  Formula/git-lfs.rb
Labels: go, ruby, CI-syntax-only

#115601 `openssl@1.1`: add deprecation date
  Formula/openssl@1.1.rb
Labels: formula deprecated, CI-syntax-only, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles
