Repository Homebrew/homebrew-core, pull requests merged in 2022-12, with the labels that each got.

#117122 beast: update license
  Formula/beast.rb
Labels: java, CI-syntax-only

#117078 emscripten: fix Linux test when `sdl12-compat` is installed
  Formula/emscripten.rb
Labels: nodejs, python, java, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles, long build

#117174 compface: deprecate
  Formula/compface.rb
Labels: formula deprecated, missing license, CI-syntax-only, CI-no-bottles

#117212 libgnomecanvas: add license
  Formula/libgnomecanvas.rb
Labels: formula deprecated, CI-syntax-only, license, no Linux bottle

#117213 vfuse: add license
  Formula/vfuse.rb
Labels: CI-syntax-only, license, macos-only

#117214 liboauth: add license
  Formula/liboauth.rb
Labels: CI-syntax-only, license

#117208 xmlformat: add license
  Formula/xmlformat.rb
Labels: CI-syntax-only, license

#117209 xmount: add license
  Formula/xmount.rb
Labels: CI-syntax-only, license, linux-only

#117210 zip: add license
  Formula/zip.rb
Labels: CI-syntax-only, license

#117221 fabric-completion: add license
  Formula/fabric-completion.rb
Labels: CI-syntax-only, license

#117249 zelda-roth-se: add license
  Formula/zelda-roth-se.rb
Labels: CI-syntax-only, license

#117246 vrpn: add license
  Formula/vrpn.rb
Labels: CI-syntax-only, license

#117247 dps8m: add license
  Formula/dps8m.rb
Labels: CI-syntax-only, license

#117251 libquicktime: add license
  Formula/libquicktime.rb
Labels: CI-syntax-only, license

#117250 vert: add license
  Formula/vert.rb
Labels: go, formula disabled, CI-syntax-only, license

#117248 globe: add license
  Formula/globe.rb
Labels: CI-syntax-only, license

#117252 vorbis-tools: add license
  Formula/vorbis-tools.rb
Labels: CI-syntax-only, license

#117253 liblzf: add license
  Formula/liblzf.rb
Labels: CI-syntax-only, license

#117254 mecab-unidic-extended: add license
  Formula/mecab-unidic-extended.rb
Labels: CI-syntax-only, license

#117255 zbackup: add license
  Formula/zbackup.rb
Labels: formula disabled, CI-syntax-only, license

#117257 tnftpd: add license
  Formula/tnftpd.rb
Labels: CI-syntax-only, license

#117256 known_hosts: deprecate
  Formula/known_hosts.rb
Labels: formula deprecated, missing license, CI-syntax-only, license

#117258 bookloupe: add license
  Formula/bookloupe.rb
Labels: CI-syntax-only, license

#117267 libusb-compat: add license
  Formula/libusb-compat.rb
Labels: CI-syntax-only, license

#117535 jupyterlab: update license
  Formula/jupyterlab.rb
Labels: nodejs, python, CI-syntax-only, license

#117536 libmikmod: add license
  Formula/libicns.rb
Labels: CI-syntax-only, license

#117537 hevea: add license
  Formula/hevea.rb
Labels: ocaml, CI-syntax-only, license

#117538 pktanon: add license
  Formula/pktanon.rb
Labels: CI-syntax-only, license, boost

#117539 libiptcdata: add license
  Formula/libiptcdata.rb
Labels: CI-syntax-only, license

#117540 crm114: add license
  Formula/crm114.rb
Labels: CI-syntax-only, license

#117541 mdf2iso: add license
  Formula/mdf2iso.rb
Labels: CI-syntax-only, license

#117543 widelands: add license
  Formula/widelands.rb
Labels: lua, CI-syntax-only, license, boost, icu4c

#117545 daemonlogger: add license
  Formula/daemonlogger.rb
Labels: CI-syntax-only, license

#117546 libb64: add license
  Formula/libb64.rb
Labels: CI-syntax-only, license

#117547 lpc21isp: add license
  Formula/lpc21isp.rb
Labels: CI-syntax-only, license

#117696 git-annex: use `ghc@9.2` to build ARM
  Formula/git-annex.rb
Labels: haskell, CI-no-bottles

#117694 dhall-lsp-server: use `ghc@9.2` to build
  Formula/dhall-lsp-server.rb
Labels: haskell, CI-no-bottles

#117693 dhall-json: use `ghc@9.2` to build
  Formula/dhall-json.rb
Labels: haskell, CI-no-bottles

#117692 dhall-bash: use `ghc@9.2` to build
  Formula/dhall-bash.rb
Labels: haskell, CI-no-bottles

#117691 dhall: use `ghc@9.2` to build
  Formula/dhall.rb
Labels: haskell, CI-no-bottles

#117683 hadolint: use `ghc@9.2` to build
  Formula/hadolint.rb
Labels: haskell, CI-no-bottles

#117685 postgrest: use `ghc@9.2` to build
  Formula/postgrest.rb
Labels: haskell, CI-no-bottles

#117686 purescript: use `ghc@9.2` to build
  Formula/purescript.rb
Labels: haskell, CI-no-bottles

#117687 taskell: use `ghc@9.2` to build
  Formula/taskell.rb
Labels: haskell, CI-no-bottles

#117695 dhall-yaml: use `ghc@9.2` to build
  Formula/dhall-yaml.rb
Labels: haskell, CI-no-bottles

#117688 stylish-haskell: add support for building with GHC 9.4
  Formula/stylish-haskell.rb
Labels: haskell, CI-no-bottles

#117689 pandoc-crossref: add support for building with GHC 9.4
  Formula/pandoc-crossref.rb
Labels: haskell, CI-no-bottles

#117690 futhark: add support for building with GHC 9.4
  Formula/futhark.rb
Labels: haskell, CI-no-bottles

#117680 cryptol: use `ghc@9.2` to build
  Formula/cryptol.rb
Labels: haskell, ready to merge, CI-no-fail-fast, CI-no-bottles

#117726 nethacked: disable
  Formula/nethacked.rb
Labels: livecheck, formula disabled, CI-syntax-only

#117770 haskell-stack: use `ghc@9.2` to build
  Formula/haskell-stack.rb
Labels: haskell, ready to merge, CI-no-bottles

#117836 wasm-micro-runtime: update license and test
  Formula/wasm-micro-runtime.rb
Labels: license, CI-no-bottles

#117928 sccache: fix head branch to main
  Formula/sccache.rb
Labels: rust, CI-no-bottles

#117895 kubernetes-cli@1.22: disable formula
  Formula/kubernetes-cli@1.22.rb
Labels: go, legacy, formula disabled, CI-no-bottles

#118122 dosbox-x: update livecheck
  Formula/dosbox-x.rb
Labels: livecheck, CI-syntax-only

#118256 workflows/triage: "long build" for `envoy` and `libtensorflow`
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#118346 upx: add license
  Formula/upx.rb
Labels: CI-syntax-only, license, no ARM bottle

#118413 autocorrect: make rust a build dependency
  Formula/autocorrect.rb
Labels: rust

#118320 qt: fix linux test
  Formula/qt.rb
Labels: nodejs, ready to merge, perl, CI-skip-recursive-dependents, CI-linux-self-hosted, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles, no Linux bottle, icu4c, ffmpeg

#118445 gst-devtools & friends: add to synced_versions
  synced_versions_formulae.json
Labels: automerge-skip

#118540 CODEOWNERS: add formulae from #113512
  CODEOWNERS
Labels: CI-syntax-only, automerge-skip

#118590 iso-codes: migrate to `python@3.11`
  Formula/iso-codes.rb
Labels: CI-no-bottles, python-3.11-migration

#118668 ruby: Build HEAD using Rust, and Homebrew's Bison
  Formula/ruby.rb
Labels: rust, CI-skip-dependents, CI-no-bottles

#118749 ISSUE_TEMPLATE/bug: nudge people to discussions.
  .github/ISSUE_TEMPLATE/bug.yml
Labels: automerge-skip

#118828 libmspub: fix Linux build
  Formula/libmspub.rb
Labels: CI-no-bottles, boost, icu4c

#118852 traefik@1: remove livecheck
  Formula/traefik@1.rb
Labels: go, nodejs, legacy, livecheck, formula disabled, CI-syntax-only

#118897 ccextractor: disable
  Formula/ccextractor.rb
Labels: formula disabled, CI-syntax-only

#118958 bullet: migrate to python@3.11
  Formula/bullet.rb
Labels: CI-no-bottles, python-3.11-migration

#118961 clblas: migrate to python@3.11
  Formula/clblas.rb
Labels: CI-no-bottles, boost, python-3.11-migration

#118980 cppcheck: migrate to python@3.11
  Formula/cppcheck.rb
Labels: CI-no-bottles, python-3.11-migration

#119016 lc0: migrate to python@3.11
  Formula/lc0.rb
Labels: CI-no-bottles, python-3.11-migration

#119021 libgit2-glib: migrate to python@3.11
  Formula/libgit2-glib.rb
Labels: CI-no-bottles, python-3.11-migration

#119033 libvirt: migrate to python@3.11
  Formula/libvirt.rb
Labels: perl, CI-no-bottles, python-3.11-migration

#119046 mavsdk: migrate to python@3.11
  Formula/mavsdk.rb
Labels: CI-no-bottles, python-3.11-migration

#119053 monetdb: migrate to python@3.11
  Formula/monetdb.rb
Labels: CI-no-bottles, python-3.11-migration

#119058 nanomsgxx: migrate to python@3.11
  Formula/nanomsgxx.rb
Labels: python-3.11-migration

#119060 ncspot: migrate to python@3.11
  Formula/ncspot.rb
Labels: rust, CI-no-bottles, python-3.11-migration

#119068 onnxruntime: migrate to python@3.11
  Formula/onnxruntime.rb
Labels: CI-no-bottles, python-3.11-migration

#119069 open-adventure: migrate to python@3.11
  Formula/open-adventure.rb
Labels: CI-no-bottles, python-3.11-migration

#119071 openmsx: migrate to python@3.11
  Formula/openmsx.rb
Labels: deprecated license, CI-no-bottles, python-3.11-migration

#119072 opentsdb: migrate to python@3.11
  Formula/opentsdb.rb
Labels: java, deprecated license, no ARM bottle, CI-no-bottles, no Linux bottle, python-3.11-migration

#119076 ppsspp: migrate to python@3.11
  Formula/ppsspp.rb
Labels: CI-no-bottles, python-3.11-migration

#119089 qpid-proton: migrate to python@3.11
  Formula/qpid-proton.rb
Labels: CI-no-bottles, python-3.11-migration

#119091 rabbitmq: migrate to python@3.11
  Formula/rabbitmq.rb
Labels: CI-no-bottles, python-3.11-migration

#119093 recode: migrate to python@3.11
  Formula/recode.rb
Labels: CI-no-bottles, python-3.11-migration

#119102 samba: migrate to python@3.11
  Formula/samba.rb
Labels: perl, CI-no-bottles, python-3.11-migration

#119104 serialosc: migrate to python@3.11
  Formula/serialosc.rb
Labels: CI-no-bottles, python-3.11-migration

#119106 shaderc: migrate to python@3.11
  Formula/shaderc.rb
Labels: CI-no-bottles, python-3.11-migration

#119108 simple-tiles: migrate to python@3.11
  Formula/simple-tiles.rb
Labels: CI-no-bottles, python-3.11-migration

#119121 spirv-tools: migrate to python@3.11
  Formula/spirv-tools.rb
Labels: CI-no-bottles, python-3.11-migration

#119123 stone-soup: migrate to python@3.11
  Formula/stone-soup.rb
Labels: lua, CI-no-bottles, python-3.11-migration

#119120 spice-gtk: migrate to python@3.11
  Formula/spice-gtk.rb
Labels: CI-no-bottles, python-3.11-migration

#119122 spot: migrate to python@3.11
  Formula/spot.rb
Labels: CI-no-bottles, python-3.11-migration

#119128 talloc: migrate to python@3.11
  Formula/talloc.rb
Labels: CI-no-bottles, python-3.11-migration

#119126 suil: migrate to python@3.11
  Formula/suil.rb
Labels: CI-no-bottles, python-3.11-migration

#118956 at-spi2-atk: migrate to python@3.11
  Formula/at-spi2-atk.rb
Labels: linux-only, CI-no-bottles, python-3.11-migration

#119134 tsduck: migrate to python@3.11
  Formula/tsduck.rb
Labels: java, CI-no-bottles, python-3.11-migration

#119135 udis86: migrate to python@3.11
  Formula/udis86.rb
Labels: CI-no-bottles, python-3.11-migration

#119140 varnish: migrate to python@3.11
  Formula/varnish.rb
Labels: CI-no-bottles, python-3.11-migration

#119143 vineyard: migrate to python@3.11
  Formula/vineyard.rb
Labels: CI-no-bottles, boost, python-3.11-migration

#119129 tbb: migrate to python@3.11
  Formula/tbb.rb
Labels: CI-requeued, CI-no-fail-fast, CI-no-bottles, python-3.11-migration

#119219 gitbucket: brew style --fix
  Formula/gitbucket.rb
Labels: java, CI-syntax-only

#119217 mikutter: uses `libxml2` and `libxslt`
  Formula/mikutter.rb
Labels: ruby, CI-no-bottles

#119220 Revert "CODEOWNERS: add formulae from #113512 (#118540)"
  CODEOWNERS
Labels: automerge-skip

#119278 afflib: add license
  Formula/afflib.rb
Labels: python, CI-syntax-only, license

#119247 crystal: use `on_system` blocks in resource
  Formula/crystal.rb
Labels: automerge-skip, CI-no-bottles

#119277 amtterm: update license
  Formula/amtterm.rb
Labels: CI-syntax-only, license

#119149 webkitgtk: migrate to python@3.11
  Formula/webkitgtk.rb
Labels: ruby, perl, linux-only, CI-no-bottles, icu4c, python-3.11-migration

#119246 vtk: use `on_arm` blocks
  Formula/vtk.rb
Labels: python, CI-syntax-only, CI-no-bottles, boost

#119301 gstreamer: add to `synced_versions`
  synced_versions_formulae.json
Labels: CI-syntax-only, automerge-skip

#118046 CI: schedule an online check for all formulae
  .github/workflows/scheduled.yml
Labels: workflows

#119346 scheduled: set github token
  .github/workflows/scheduled.yml
Labels: automerge-skip, workflows

#119350 faust: use upstream patch
  Formula/faust.rb
Labels: CI-no-bottles

#119379 density: deprecate
  Formula/density.rb
Labels: formula deprecated, CI-syntax-only

#118967 chakra: migrate to python@3.11
  Formula/chakra.rb
Labels: no ARM bottle, CI-no-bottles, icu4c, python-3.11-migration

#119392 mtoc: deprecate
  Formula/mtoc.rb
Labels: formula deprecated, missing license, CI-syntax-only, macos-only

#119433 caffe: deprecate
  Formula/caffe.rb
Labels: formula deprecated, CI-syntax-only, boost

#119057 mxnet: migrate to python@3.11
  Formula/mxnet.rb
Labels: CI-requeued, CI-no-bottles, python-3.11-migration

#119469 discount: update livecheck
  Formula/discount.rb
Labels: livecheck, CI-syntax-only

#117343 node: migrate to python@3.11
  Formula/node.rb
Labels: in progress, ready to merge, CI-no-bottles, long build, icu4c, python-3.11-migration

#119139 v8: migrate to python@3.11
  Formula/v8.rb
Labels: CI-no-bottles, long build, python-3.11-migration
