Repository Homebrew/homebrew-core, pull requests merged in 2022-05, with the labels that each got.

#100546 spirv-headers: add livecheck
  Formula/spirv-headers.rb
Labels: livecheck, CI-syntax-only

#100579 click: add livecheck
  Formula/click.rb
Labels: rust, livecheck, CI-syntax-only

#100622 jpegoptim: update license
  Formula/jpegoptim.rb
Labels: CI-syntax-only

#100632 libcython: add livecheck
  Formula/libcython.rb
Labels: livecheck, CI-syntax-only

#100667 grokj2k: min Catalina requirement
  Formula/grokj2k.rb
Labels: perl, CI-syntax-only, CI-no-bottles

#100426 arrayfire: fix build on Linux
  Formula/arrayfire.rb
Labels: ready to merge, CI-no-fail-fast, CI-no-bottles, no Linux bottle

#100787 gcc@5: Fix glibc installation logic
  Formula/gcc@5.rb
Labels: legacy, missing license, CI-syntax-only

#100781 mongodb-atlas-cli: add head
  Formula/mongodb-atlas-cli.rb
Labels: go, CI-syntax-only

#100779 mongocli: add head, livecheck
  Formula/mongocli.rb
Labels: go, livecheck, CI-syntax-only

#100936 nagios: fix build on Linux
  Formula/nagios.rb
Labels: ready to merge, deprecated license, CI-no-fail-fast, CI-no-bottles, no Linux bottle

#101173 osm2pgrouting: fix build on Linux
  Formula/osm2pgrouting.rb
Labels: CI-no-bottles, no Linux bottle

#101175 ola: fix build on Linux
  Formula/ola.rb
Labels: python, CI-no-bottles, no Linux bottle

#101187 pioneer: fix build on Linux
  Formula/pioneer.rb
Labels: CI-no-bottles, no Linux bottle

#101193 stdman: fix test on Linux
  Formula/stdman.rb
Labels: CI-no-bottles, no Linux bottle

#101196 ttygif: fix test on Linux
  Formula/ttygif.rb
Labels: CI-no-bottles, no Linux bottle

#101200 gnu-cobol: fix shim references on Linux
  Formula/gnu-cobol.rb
Labels: CI-no-bottles, no Linux bottle

#101246 tz: fix test on Linux
  Formula/tz.rb
Labels: go, CI-no-bottles, no Linux bottle

#101245 gpg-tui: fix test on Linux
  Formula/gpg-tui.rb
Labels: rust, CI-no-bottles, no Linux bottle

#101244 supermodel: fix build on Linux
  Formula/supermodel.rb
Labels: missing license, CI-no-bottles, no Linux bottle

#101251 minizinc: remove comment for already removed patch
  Formula/minizinc.rb
Labels: CI-syntax-only

#101176 allegro: fix build on Linux
  Formula/allegro.rb
Labels: ready to merge, CI-no-bottles, no Linux bottle

#101358 grafana-agent: fix checksum
  Formula/grafana-agent.rb
Labels: go, CI-no-fail-fast

#101482 platformio: add head
  Formula/platformio.rb
Labels: python, CI-syntax-only

#101568 Formula: fix curl mirror URL
  Formula/curl.rb
Labels: CI-syntax-only

#101620 sslmate: fix build on Linux
  Formula/sslmate.rb
Labels: python, ready to merge, perl, CI-no-bottles, no Linux bottle

#101702 pulledpork: fix build on Linux
  Formula/pulledpork.rb
Labels: perl, CI-no-bottles, no Linux bottle

#101791 bash-language-server: fix test
  Formula/bash-language-server.rb
Labels: nodejs, CI-no-bottles

#101953 vcpkg: fix typo in caveats section
  Formula/vcpkg.rb
Labels: CI-syntax-only

#101988 xmrig: change head branch to `dev`
  Formula/xmrig.rb
Labels: CI-syntax-only, CI-no-bottles

#102040 colima: remove macos-only restriction.
  Formula/colima.rb
Labels: go, no Linux bottle

#101432 csound: build on Linux
  Formula/csound.rb
Labels: python, java, CI-no-bottles, no Linux bottle

#100640 Expand synced_versions_formulae.json
  Formula/boost-bcp.rb
  Formula/boost-mpi.rb
  Formula/boost-python3.rb
  synced_versions_formulae.json
Labels: stale, CI-syntax-only, automerge-skip

#102326 webfs: fix build on Linux
  Formula/webfs.rb
Labels: ready to merge, missing license, CI-no-bottles, no Linux bottle

#98504 doxygen: replace variables in man pages
  Formula/doxygen.rb
Labels: CI-requeued, stale, ready to merge, CI-no-fail-fast

#102514 flix: add livecheck
  Formula/flix.rb
Labels: java, livecheck, CI-syntax-only

#102538 sbcl: add livecheck
  Formula/sbcl.rb
Labels: livecheck, CI-syntax-only

#102573 man-db: update test
  Formula/man-db.rb
Labels: CI-no-fail-fast, CI-no-bottles
