Repository Homebrew/homebrew-core, pull requests merged in 2022-04, with the labels that each got.

#98421 rgf: fix build on Linux
  Formula/rgf.rb
Labels: CI-no-bottles, no Linux bottle

#98440 projectm: fix build on Linux
  Formula/projectm.rb
Labels: ready to merge, CI-no-bottles, no Linux bottle

#98180 opencbm: fix build on Linux
  Formula/opencbm.rb
Labels: ready to merge, CI-no-bottles, no Linux bottle

#98450 qsoas: fix build on Linux
  Formula/qsoas.rb
Labels: ruby, CI-no-bottles, no Linux bottle

#98541 openshift-cli: re-enable
  Formula/openshift-cli.rb
Labels: go, CI-no-bottles

#98551 bind: remove libjson flag, SDKROOT fix
  Formula/bind.rb
Labels: CI-no-bottles

#98634 wy60: fix build on Linux
  Formula/wy60.rb
Labels: missing license, CI-no-bottles, no Linux bottle

#98633 typespeed: fix build on Linux
  Formula/typespeed.rb
Labels: deprecated license, CI-no-bottles, no Linux bottle

#98632 tcpstat: fix build on Linux
  Formula/tcpstat.rb
Labels: CI-no-bottles, no Linux bottle

#98631 slashem: fix build on Linux
  Formula/slashem.rb
Labels: missing license, CI-no-bottles, no Linux bottle

#98629 le: fix build on Linux
  Formula/le.rb
Labels: deprecated license, CI-no-bottles, no Linux bottle

#98628 gnuski: fix build on Linux
  Formula/gnuski.rb
Labels: missing license, CI-no-bottles, no Linux bottle

#98627 glkterm: fix build on Linux
  Formula/glkterm.rb
Labels: missing license, CI-no-bottles, no Linux bottle

#98626 epic5: fix build on Linux
  Formula/epic5.rb
Labels: CI-no-bottles, no Linux bottle

#98590 mongodb-atlas-cli: add mongodb-atlas alias
  Aliases/mongodb-atlas
Labels: automerge-skip

#98573 Update Homebrew discussion links
  .github/ISSUE_TEMPLATE/config.yml
  Formula/julia.rb
Labels: CI-syntax-only, automerge-skip

#98675 README: update discussions.
  README.md
Labels: CI-syntax-only, automerge-skip

#98762 ansible@2.8: update 2.8.20_2 bottle.
  Formula/ansible@2.8.rb
Labels: python, legacy, rust, formula deprecated, CI-syntax-only, no ARM bottle

#98827 duo_unix: remove livecheck
  Formula/duo_unix.rb
Labels: livecheck, CI-syntax-only

#99055 kmod: update homepage
  Formula/kmod.rb
Labels: livecheck, CI-syntax-only, linux-only

#98863 tgif: fix build on Linux
  Formula/tgif.rb
Labels: CI-no-fail-fast, CI-no-bottles, no Linux bottle

#99058 grafana-agent: update deprecated flags in test
  Formula/grafana-agent.rb
Labels: go, automerge-skip, CI-no-bottles

#98756 fontconfig: add python@3.9 as build dependency on Mojave and below
  Formula/fontconfig.rb
Labels: CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#99211 polynote: fix build on Linux
  Formula/polynote.rb
  audit_exceptions/github_prerelease_allowlist.json
Labels: python, java, automerge-skip, CI-no-bottles, no Linux bottle

#98855 julius: fix build on Linux
  Formula/julius.rb
Labels: no ARM bottle, CI-no-bottles, no Linux bottle

#96907 observerward: add observer_ward alias
  Aliases/observer_ward
Labels: automerge-skip, bump-formula-pr

#99512 dotnet: add livecheck
  Formula/dotnet.rb
Labels: livecheck, CI-syntax-only

#99553 tractorgen: update homepage, stable
  Formula/tractorgen.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#99558 zsh-you-should-use: improve caveat
  Formula/zsh-you-should-use.rb
Labels: CI-syntax-only

#99716 versioned_dependencies_conflicts_allowlist: remove `anjuta` and `gjs`
  audit_exceptions/versioned_dependencies_conflicts_allowlist.json
Labels: automerge-skip

#99579 libmarpa: pkgconfig support for --HEAD build
  Formula/libmarpa.rb
Labels: CI-syntax-only

#98175 djview4: fix build on Linux
  Formula/djview4.rb
Labels: ready to merge, CI-no-fail-fast, CI-no-bottles, no Linux bottle

#99597 cataclysm: fix build on Linux
  Formula/cataclysm.rb
Labels: ready to merge, CI-no-bottles, no Linux bottle

#99990 netcdf: update livecheck
  Formula/netcdf.rb
Labels: livecheck, CI-syntax-only

#98483 biber: update test resource
  Formula/biber.rb
Labels: ready to merge, perl, CI-linux-self-hosted, CI-no-fail-fast, CI-no-bottles

#99475 triage: add more `long build` formulae
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#99474 autobump: track more formulae
  .github/workflows/autobump.yml
Labels: CI-syntax-only, automerge-skip, workflows

#100073 mvtools: patch build issues on apple silicon
  Formula/mvtools.rb
Labels: deprecated license, no ARM bottle, CI-no-bottles

#99966 gti: add license
  Formula/gti.rb
Labels: CI-syntax-only, license

#99959 clipsafe: add license
  Formula/clipsafe.rb
Labels: perl, CI-syntax-only, license

#100177 mupen64plus: update 2.5_1 bottle.
  Formula/mupen64plus.rb
Labels: CI-syntax-only, deprecated license, no ARM bottle

#98499 workflows/tests: add test ephemeral runner
  .github/workflows/tests.yml
Labels: do not merge, automerge-skip, workflows

#98171 zlib 1.2.12
  Formula/zlib.rb
Labels: CI-issue, CI-syntax-only, automerge-skip, bump-formula-pr, CI-linux-wheezy, CI-no-fail-fast

#100295 sevenzip: add livecheck
  Formula/sevenzip.rb
Labels: livecheck, CI-syntax-only

#100441 bbftp-client: fix build on Linux
  Formula/bbftp-client.rb
Labels: CI-no-fail-fast, CI-no-bottles, no Linux bottle
