Repository Homebrew/homebrew-core, pull requests merged in 2022-10, with the labels that each got.

#112136 publish-commit-bottles: use large GitHub runner
  .github/workflows/publish-commit-bottles.yml
Labels: CI-syntax-only, automerge-skip, workflows

#112117 nwchem: fix python3 reference
  Formula/nwchem.rb
Labels: python, ready to merge, CI-no-bottles

#112116 jailkit: fix python3 reference
  Formula/jailkit.rb
Labels: python, ready to merge, CI-no-bottles

#112109 z3: fix head branch.
  Formula/z3.rb
Labels: CI-no-bottles

#112225 zig: remove `odie`
  Formula/zig.rb
Labels: CI-syntax-only

#112297 pla: fix build on Linux
  Formula/pla.rb
Labels: CI-no-bottles, no Linux bottle

#112298 supermodel: fix build on Linux
  Formula/supermodel.rb
Labels: CI-no-bottles, no Linux bottle

#110496 subversion: fix `python3` references.
  Formula/subversion.rb
Labels: java, ruby, perl, CI-no-fail-fast, CI-no-bottles

#112351 caf: drop GCC dependency
  Formula/caf.rb
Labels: CI-no-bottles

#112375 CONTRIBUTING: update container version
  CONTRIBUTING.md
Labels: automerge-skip

#110116 libtorch: fix `python3` reference.
  Formula/libtorch.rb
Labels: ready to merge, CI-no-fail-fast, CI-no-bottles, long build

#112702 ldid: linux compatibility
  Formula/ldid.rb
Labels: CI-no-fail-fast, CI-no-bottles, no Linux bottle

#112699 jj: remove Linux-only `gcc` dependency
  Formula/jj.rb
Labels: rust, CI-no-bottles

#112840 ksh: Fix deprecation message
  Formula/ksh.rb
Labels: formula deprecated, CI-syntax-only

#112966 mpfr: update test
  Formula/mpfr.rb
Labels: CI-skip-dependents, CI-no-bottles

#112929 libsndfile: update python to `uses_from_macos`
  Formula/libsndfile.rb
Labels: CI-no-fail-fast, CI-no-bottles, long build

#113046 workflows: fix python@3.10 exception for legacy label
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#113305 workflows: support ephemeral 13-arm64
  .github/workflows/dispatch-build-bottle.yml
  cmd/determine-rebottle-runners.rb
Labels: automerge-skip

#113649 clamav: create DB directory in post-install
  Formula/clamav.rb
Labels: rust, CI-no-bottles

#113742 openldap: use `groff` to build on Ventura
  Formula/openldap.rb
Labels: CI-no-bottles

#113764 luarocks: test with `luajit`
  Formula/luarocks.rb
Labels: lua, CI-no-bottles

#113766 openldap: avoid hardcoding details of the `Makefile`
  Formula/openldap.rb
Labels: CI-skip-dependents, CI-no-bottles

#113768 zsh: depend on texinfo for macOS Ventura
  Formula/zsh.rb
Labels: CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#113767 ksh: rename to `ksh93`
  Formula/ksh.rb
  formula_renames.json
Labels: automerge-skip

#113785 xalan-c: Deprecate package due to upstream retirement
  Formula/xalan-c.rb
Labels: formula deprecated, CI-no-bottles

#113824 yasm: fix test for ARM
  Formula/yasm.rb
Labels: missing license, CI-no-bottles

#113823 pstree: update mirror
  Formula/pstree.rb
Labels: missing license, CI-no-bottles

#113856 xvid: deparallelize
  Formula/xvid.rb
Labels: CI-skip-recursive-dependents, CI-no-bottles

#113506 workflows: fix Linux logs path for upload
  .github/workflows/tests.yml
Labels: do not merge, automerge-skip, CI-linux-self-hosted, workflows

#113885 openjdk: patch for macOS Ventura
  Formula/openjdk.rb
Labels: CI-long-timeout, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, long build

#113895 libvpx: patch for macOS Ventura
  Formula/libvpx.rb
Labels: CI-skip-recursive-dependents, CI-no-bottles

#113898 libvpx: adjust patch for macOS Ventura
  Formula/libvpx.rb
Labels: CI-skip-dependents, CI-no-bottles

#113916 mold: fix test on ARM Ventura
  Formula/mold.rb
Labels: CI-no-bottles

#114039 openjdk@8: depend on x86_64
  Formula/openjdk@8.rb
Labels: legacy, CI-syntax-only, no ARM bottle

#114037 groff: depend on texinfo on Ventura
  Formula/groff.rb
Labels: perl, CI-skip-recursive-dependents, CI-no-bottles

#114038 awscli: use Homebrew groff on macOS Ventura
  Formula/awscli.rb
Labels: python, rust, CI-no-bottles
