Repository Homebrew/homebrew-core, pull requests merged in 2022-07, with the labels that each got.

#104834 llvm@7: disable
  Formula/llvm@7.rb
Labels: python, legacy, formula disabled, CI-syntax-only

#104903 klee: fix ARM build
  Formula/klee.rb
Labels: python, ready to merge, no ARM bottle, CI-no-bottles

#105002 triage: add labels for boost, icu4c, ffmpeg dependents
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#104833 libetonyek: don't hardcode mdds version number
  Formula/libetonyek.rb
Labels: missing license, CI-no-bottles, boost

#104993 alpine: move to new upstream website
  Formula/alpine.rb
Labels: CI-no-fail-fast, CI-no-bottles

#105087 workflows: remove wheezy references
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#105003 ci: Add GitHub token permissions for workflows
  .github/workflows/autobump.yml
  .github/workflows/autopublish.yml
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/publish-commit-bottles.yml
  .github/workflows/recreate-linux-runners.yml
  .github/workflows/remove-disabled-formulae.yml
  .github/workflows/tests.yml
  .github/workflows/triage.yml
Labels: automerge-skip, workflows

#105084 git-annex: remove gsasl and quvi dependencies
  Formula/git-annex.rb
Labels: haskell, no ARM bottle, CI-no-bottles

#105292 mu: use new lispdir build option
  Formula/mu.rb
Labels: CI-no-bottles

#105259 gobo: fix build on Linux
  Formula/gobo.rb
Labels: CI-no-bottles, no Linux bottle

#105315 terminalimageviewer: remove `assert_equal`
  Formula/terminalimageviewer.rb
Labels: CI-no-bottles

#105378 crystal: avoid unchecksummed download
  Formula/crystal.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#105389 cava: remove unnecessary parentheses.
  Formula/cava.rb
Labels: bottle unneeded, CI-syntax-only, CI-no-bottles

#105509 xdg-ninja: fix dependent formula on macos.
  Formula/xdg-ninja.rb
Labels: CI-no-bottles

#105570 help2man: fix build pre mojave
  Formula/help2man.rb
Labels: perl

#105658 libpcl: update urls, license
  Formula/libpcl.rb
Labels: livecheck, license, no ARM bottle, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#105715 CODEOWNERS: add `protobuf` dependents
  CODEOWNERS
Labels: CI-syntax-only, automerge-skip

#105736 qt@5: remove outdated caveat
  Formula/qt@5.rb
Labels: nodejs, legacy, CI-syntax-only, icu4c

#105784 libpython-tabulate: add livecheck
  Formula/libpython-tabulate.rb
Labels: livecheck, CI-syntax-only

#105805 crystal: restrict linux builds to x86-64 #105566
  Formula/crystal.rb
Labels: CI-no-bottles

#105812 protobuf@3.6: disable
  Formula/protobuf@3.6.rb
Labels: python, legacy, formula disabled, no Linux bottle

#105819 bedops: update license
  Formula/bedops.rb
Labels: CI-syntax-only, license

#105864 CODEOWNERS: remove `protobuf` dependents
  CODEOWNERS
Labels: automerge-skip

#105799 luajit: incorporate feedback from #104765
  Formula/luajit.rb
Labels: CI-syntax-only

#105886 mpw: remove livecheck
  Formula/mpw.rb
Labels: livecheck, formula disabled, CI-syntax-only

#105851 gcc@6: fix flat namespace usage
  Formula/gcc@6.rb
Labels: legacy, ready to merge, no ARM bottle, CI-no-bottles

#105855 gcc@7: fix flat namespace usage
  Formula/gcc@7.rb
Labels: legacy, ready to merge, no ARM bottle, CI-no-bottles

#105857 gcc@8: fix flat namespace usage
  Formula/gcc@8.rb
Labels: legacy, ready to merge, no ARM bottle, CI-no-bottles

#106061 spdylay: remove old hack
  Formula/spdylay.rb
Labels: formula deprecated

#106051 llvm: remove old compat
  Formula/llvm.rb
Labels: python, CI-long-timeout, CI-linux-self-hosted, CI-skip-dependents, long build

#106099 lz4: add HTTP mirrors
  Formula/lz4.rb
Labels: CI-syntax-only

#106079 grafana-agent: remove deprecated fields in test
  Formula/grafana-agent.rb
Labels: go, CI-no-bottles

#106184 mypy: fix bottle block
  Formula/mypy.rb
Labels: python, CI-syntax-only

#106198 rizin: put head back to dev instead of stable
  Formula/rizin.rb
Labels: CI-no-bottles

#106229 tfenv: depend on grep formula when using macos
  Formula/tfenv.rb
Labels: CI-no-bottles

#105507 appstream-glib: fix remove unneeded dependency
  Formula/appstream-glib.rb
Labels: CI-no-bottles

#106318 gegl: fix since glib-utils
  Formula/gegl.rb
Labels: CI-no-bottles

#106471 qt: depends on `openssl@1.1`
  Formula/qt.rb
Labels: nodejs, perl, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, long build, icu4c, ffmpeg

#106445 blastem: migrate to python@3.10
  Formula/blastem.rb
Labels: no ARM bottle, CI-no-bottles

#106490 glooctl: fix bottle block
  Formula/glooctl.rb
Labels: go, CI-syntax-only

#106589 freeciv: depend on sqlite
  Formula/freeciv.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, icu4c

#106588 ffmpeg@2.8: depend on xz
  Formula/ffmpeg@2.8.rb
Labels: legacy, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#106587 cherrytree: depend on sqlite
  Formula/cherrytree.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#106591 fceux: depend on mesa-glu on Linux
  Formula/fceux.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, ffmpeg

#106594 mgba: depend on sqlite
  Formula/mgba.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, ffmpeg

#106593 msc-generator: depend on mesa on Linux
  Formula/msc-generator.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#106596 ntopng: depend on sqlite
  Formula/ntopng.rb
Labels: lua, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#106575 libxml2: fix installation of Python bindings
  Formula/libxml2.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, icu4c

#106605 dura: add service
  Formula/dura.rb
Labels: rust, CI-no-bottles

#106592 libchamplain: depend on sqlite
  Formula/libchamplain.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#106626 winexe: deprecate
  Formula/winexe.rb
Labels: perl, formula deprecated, CI-syntax-only, deprecated license, CI-no-fail-fast, CI-no-bottles, no Linux bottle

#106667 hut: remove coreutils dependency
  Formula/hut.rb
Labels: go, CI-no-bottles

#106595 mikutter: depend on xz
  Formula/mikutter.rb
Labels: ruby, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#106718 ledger: uses `libedit`
  Formula/ledger.rb
Labels: python, CI-no-bottles, boost

#106720 creduce: move patch to `stable` block
  Formula/creduce.rb
Labels: perl, CI-syntax-only, no ARM bottle

#106743 creduce: point to the right `clang-format` for `HEAD`
  Formula/creduce.rb
Labels: perl, no ARM bottle, CI-no-bottles

#106668 gexiv2: fix glib-utils
  Formula/gexiv2.rb
Labels: CI-no-bottles

#106850 docker-machine-driver-vultr: deprecate
  Formula/docker-machine-driver-vultr.rb
Labels: go, formula deprecated, CI-syntax-only

#106849 phplint: deprecate
  Formula/phplint.rb
Labels: php, formula deprecated, missing license, CI-no-bottles

#106858 bitcoin: remove "--disable-dependency-tracking"
  Formula/bitcoin.rb
Labels: CI-no-bottles, boost

#106721 libxcrpyt: overwrite conflicts with `glibc`
  Formula/libxcrypt.rb
Labels: CI-syntax-only

#106879 node@12: add python to PATH for npm on macOS
  Formula/node@12.rb
Labels: legacy, formula deprecated, CI-no-bottles, icu4c

#106980 xgboost: remove `numpy` and `scipy`
  Formula/xgboost.rb
Labels: CI-no-bottles
