Repository Homebrew/homebrew-core, pull requests merged in 2022-01, with the labels that each got.

#92333 formulae*: update synced_versions_formulae list
  synced_versions_formulae.json
Labels: CI-syntax-only, automerge-skip

#89982 openjdk@8: depend on awk
  Formula/openjdk@8.rb
Labels: legacy, CI-force-arm, no ARM bottle, CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#92397 oscats: fix -flat_namespace issue
  Formula/oscats.rb
Labels: missing license, CI-no-bottles, no Linux bottle

#92413 maven-shell: add livecheck
  Formula/maven-shell.rb
Labels: livecheck, CI-syntax-only

#92428 immudb: add service
  Formula/immudb.rb
Labels: go, CI-no-bottles

#92436 libhid: fix incorrect `-flat_namespace` usage on Big Sur
  Formula/libhid.rb
Labels: deprecated license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#92328 autobump: track more java formulae
  .github/workflows/autobump.yml
Labels: java, automerge-skip, workflows

#90318 fauna-shell: avoid stalling CI runs
  Formula/fauna-shell.rb
Labels: nodejs, ready to merge, CI-no-bottles

#92467 yafc: add libbsd on linux
  Formula/yafc.rb
Labels: missing license, no Linux bottle

#92504 gauche: update livecheck
  Formula/gauche.rb
Labels: livecheck, CI-syntax-only

#92515 mosh: add livecheck
  Formula/mosh.rb
Labels: livecheck, CI-syntax-only

#92525 winetricks: add livecheck
  Formula/winetricks.rb
Labels: livecheck, CI-syntax-only

#92526 flatbuffers: add livecheck
  Formula/flatbuffers.rb
Labels: livecheck, CI-syntax-only

#92555 workflows/tests: warn when label count query fails
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#92527 polipo: disable
  Formula/polipo.rb
Labels: formula disabled

#92572 mpd: add livecheck
  Formula/mpd.rb
Labels: livecheck, CI-syntax-only

#92528 keptn: add livecheck
  Formula/keptn.rb
Labels: go, livecheck, CI-syntax-only

#92647 libtasn1: run `make check`
  Formula/libtasn1.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#92635 mpdas: add livecheck
  Formula/mpdas.rb
Labels: livecheck, CI-syntax-only, no Linux bottle

#92656 asuka: Fix test
  Formula/asuka.rb
Labels: rust, CI-no-bottles

#92688 vips: fix build on Linux
  Formula/vips.rb
Labels: CI-no-bottles, no Linux bottle

#92782 scrcpy: fix build on Linux
  Formula/scrcpy.rb
Labels: CI-no-bottles, no Linux bottle

#92807 gnuradio: allow -flat_namespace flag
  audit_exceptions/flat_namespace_allowlist.json
Labels: automerge-skip

#92769 autobump: track more formulae
  .github/workflows/autobump.yml
Labels: go, CI-syntax-only, automerge-skip, workflows

#92798 mono: update conflicts
  Formula/mono.rb
Labels: python, CI-syntax-only, no ARM bottle, no Linux bottle

#92851 beansdb: disable
  Formula/beansdb.rb
Labels: formula disabled, CI-no-bottles

#92853 cosi: disable
  Formula/cosi.rb
Labels: go, formula disabled, deprecated license, CI-no-bottles

#92907 percona-server: equal sign is required for datadir
  Formula/percona-server.rb
Labels: CI-syntax-only

#88835 neopop-sdl: update `head` URL
  Formula/neopop-sdl.rb
Labels: stale, no ARM bottle, CI-no-fail-fast, CI-no-bottles, no Linux bottle

#92944 regina-rexx: add license
  Formula/regina-rexx.rb
Labels: CI-syntax-only, license

#92921 nut: add livecheck
  Formula/nut.rb
Labels: livecheck, CI-syntax-only

#92888 chmlib: Support Apple Silicon
  Formula/chmlib.rb
Labels: no ARM bottle, CI-no-bottles

#92994 libsbol: Fix build and linkage
  Formula/libsbol.rb
Labels: CI-no-bottles, no Linux bottle

#93097 jolie: fix broken test
  Formula/jolie.rb
Labels: java, CI-no-bottles

#93098 open-mesh: add livecheck, license
  Formula/open-mesh.rb
Labels: livecheck, CI-syntax-only, license

#93059 CONTRIBUTING: add section on dealing with CI failures
  CONTRIBUTING.md
Labels: CI-syntax-only, automerge-skip

#93172 openal-soft: add livecheck
  Formula/openal-soft.rb
Labels: livecheck, CI-syntax-only

#93240 dnsprobe: fix typo
  Formula/dnsprobe.rb
Labels: go, formula deprecated, CI-syntax-only

#93250 openclonk: add livecheck
  Formula/openclonk.rb
Labels: livecheck, CI-syntax-only, no Linux bottle

#93203 haruhi-dl: deprecate
  Formula/haruhi-dl.rb
Labels: python, formula deprecated, CI-syntax-only, no Linux bottle

#93275 tests: get debug output for failed API queries
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#93281 synced_versions_formulae: add `fbthrift`
  synced_versions_formulae.json
Labels: CI-syntax-only, automerge-skip

#93296 libswiften: disable
  Formula/libswiften.rb
Labels: lua, formula disabled, missing license, no Linux bottle

#93314 libgdata: fix test on Monterey
  Formula/libgdata.rb
Labels: CI-no-bottles, no Linux bottle

#93327 workflows: remove `HOMEBREW_RELOCATE_RPATHS`
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#93326 epsilon: regenerate `configure`
  Formula/epsilon.rb
Labels: license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#93323 gobject-introspection: fix doctemplates error
  Formula/gobject-introspection.rb
Labels: python, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#93341 workflows/tests: show `brew linkage` output
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#93338 libgda: patch incorrect -flat_namespace usage
  Formula/libgda.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, no Linux bottle

#93396 stdman: change description to strip C++ version
  Formula/stdman.rb
Labels: CI-no-bottles, no Linux bottle

#93425 lighttpd: update `livecheck` URL
  Formula/lighttpd.rb
Labels: livecheck, CI-syntax-only

#93416 sheldon: fix build for Linux
  Formula/sheldon.rb
Labels: rust, CI-no-bottles, no Linux bottle

#93472 workflows/tests: fix GraphQL query errors
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#93543 arkade: add livecheck
  Formula/arkade.rb
Labels: go, livecheck, CI-syntax-only

#93601 languagetool: add service to run languagetool-server
  Formula/languagetool.rb
Labels: java, CI-no-bottles

#93613 rarian: regenerate `configure`
  Formula/rarian.rb
Labels: license, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#93641 dafny: update livecheck
  Formula/dafny.rb
Labels: java, livecheck, CI-syntax-only, no ARM bottle, no Linux bottle, dotnet

#93642 direvent: update license
  Formula/direvent.rb
Labels: CI-syntax-only, license

#93660 ipsumdump: improve test
  Formula/ipsumdump.rb
Labels: CI-no-bottles, no Linux bottle

#93708 numpy: downgrade setuptools
  Formula/numpy.rb
Labels: python, CI-no-fail-fast, CI-no-bottles, long build

#93683 rpm: fix build on Apple Silicon
  Formula/rpm.rb
Labels: lua, ready to merge, no ARM bottle, CI-no-fail-fast, CI-no-bottles

#93862 osm: add livecheck and head
  Formula/osm.rb
Labels: go, livecheck, CI-syntax-only

#93921 jq: update `livecheck`
  Formula/jq.rb
Labels: livecheck, CI-syntax-only

#93939 pdfpc: fix ARM build
  Formula/pdfpc.rb
Labels: ready to merge, no ARM bottle, CI-no-bottles, no Linux bottle

#93943 pdfpc: skip test on Linux
  Formula/pdfpc.rb
Labels: no ARM bottle, CI-no-bottles, no Linux bottle

#93895 watchman: build with Homebrew `googletest`
  Formula/watchman.rb
Labels: python, rust, linux, CI-no-fail-fast, CI-no-bottles

#93961 blink1: fixes for Linux
  Formula/blink1.rb
Labels: ready to merge, CI-no-bottles, no Linux bottle

#93963 simple-scan: fix build with Meson 0.60+.
  Formula/simple-scan.rb
Labels: ready to merge, CI-no-bottles, no Linux bottle

#93962 evince: fix build with newer Meson
  Formula/evince.rb
Labels: python, ready to merge, CI-no-bottles, no Linux bottle

#93974 simple-scan: skip test on Linux
  Formula/simple-scan.rb
Labels: CI-no-bottles, no Linux bottle

#93985 pyenv: update livecheck
  Formula/pyenv.rb
Labels: livecheck, CI-syntax-only

#94026 aerc: add `head`
  Formula/aerc.rb
Labels: go, CI-syntax-only

#94067 workflows/tests: always upload logs
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#94001 heartbeat: skip test on Linux
  Formula/heartbeat.rb
Labels: go, CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#94084 workflows: try to fix autobump
  .github/workflows/autobump.yml
Labels: automerge-skip, workflows

#94130 workflows/dispatch-build-bottle: always upload logs
  .github/workflows/dispatch-build-bottle.yml
Labels: CI-syntax-only, automerge-skip, workflows

#94132 libxslt: patch `configure` directly
  Formula/libxslt.rb
Labels: ready to merge, CI-skip-recursive-dependents, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#94145 xray: add livecheck
  Formula/xray.rb
Labels: go, livecheck, CI-syntax-only

#94095 czmq: remove macOS dependency
  Formula/czmq.rb
Labels: automerge-skip, CI-no-bottles, no Linux bottle
