Repository Homebrew/homebrew-core, pull requests merged in 2023-02, with the labels that each got.

#121985 formulae: disable
  Formula/googler.rb
  Formula/haruhi-dl.rb
Labels: python, formula disabled, CI-syntax-only

#121984 abnfgen: use https
  Formula/abnfgen.rb
Labels: missing license, CI-no-bottles

#122131 aide: fix HEAD build
  Formula/aide.rb
Labels: CI-syntax-only

#122171 liquibase: update livecheck
  Formula/liquibase.rb
Labels: java, livecheck, CI-syntax-only

#122174 felinks: use `libidn2` on HEAD
  Formula/felinks.rb
Labels: CI-syntax-only

#122241 macvim: add livecheck
  Formula/macvim.rb
Labels: lua, python, ruby, livecheck, CI-syntax-only, macos-only

#122316 soplex: add livecheck
  Formula/soplex.rb
Labels: livecheck, CI-syntax-only, boost

#122328 jpeg-turbo: add livecheck
  Formula/jpeg-turbo.rb
Labels: livecheck, CI-syntax-only

#122333 vecx: deprecate
  Formula/vecx.rb
Labels: formula deprecated, CI-syntax-only, deprecated license

#122334 guichan: deprecate
  Formula/guichan.rb
Labels: formula deprecated, missing license, CI-syntax-only

#122344 workflows: add `directory` when pushing the bottle commits
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
Labels: CI-syntax-only, automerge-skip, workflows

#122416 workflows: add `HOMEBREW_NO_INSTALL_FROM_API`
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/publish-commit-bottles.yml
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#122447 libming: deprecate
  Formula/libming.rb
Labels: perl, formula deprecated, CI-syntax-only

#122448 plod: use https
  Formula/plod.rb
Labels: missing license, CI-no-bottles

#122459 git-appraise: fix test; build bottle on Ventura
  Formula/git-appraise.rb
Labels: go, CI-no-bottles

#122542 pax-construct: deprecate
  Formula/pax-construct.rb
Labels: formula deprecated, CI-no-bottles

#122606 octant: deprecate
  Formula/octant.rb
Labels: go, nodejs, formula deprecated, CI-syntax-only

#122610 scalapack: update homepage, stable urls
  Formula/scalapack.rb
Labels: CI-no-bottles

#120184 podman: remove unstartable macOS service
  Formula/podman.rb
Labels: go, rust, automerge-skip, CI-no-bottles

#122667 atuin: specify bin in test #2
  Formula/atuin.rb
Labels: rust, CI-skip-dependents, CI-no-bottles

#122714 spades: update livecheck
  Formula/spades.rb
Labels: python, livecheck, CI-syntax-only, no ARM bottle

#122796 gerbil-scheme: update license
  Formula/gerbil-scheme.rb
Labels: CI-syntax-only, license

#122896 cabextract: update license
  Formula/cabextract.rb
Labels: CI-syntax-only, license

#122897 mawk: update license
  Formula/mawk.rb
Labels: CI-syntax-only, license

#122918 rbenv: fix head build and install manpage
  Formula/rbenv.rb
Labels: ruby, CI-no-bottles

#122726 workflows/tests: remove any leftover bottles dir
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#122938 pypi_formula_mappings: added ansible@6
  pypi_formula_mappings.json
Labels: CI-syntax-only, automerge-skip

#122937 aardvark_shell_utils: deprecate
  Formula/aardvark_shell_utils.rb
Labels: formula deprecated, CI-syntax-only

#122944 uutils-coreutils: only symlink `hashsum` on Linux
  Formula/uutils-coreutils.rb
Labels: rust

#122943 google-sql-tool: deprecate
  Formula/google-sql-tool.rb
Labels: java, formula deprecated, missing license, CI-syntax-only

#123050 lua-language-server: update repo owner
  Formula/lua-language-server.rb
Labels: CI-no-bottles

#123000 workflows/triage.yml: include freetype|ztsd into long-build and CI-linux-self-hosted lists
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#123144 bench: use `ghc@9.2` to build
  Formula/bench.rb
Labels: haskell, CI-no-bottles

#123154 sonarqube: update livecheck
  Formula/sonarqube.rb
Labels: java, livecheck, CI-syntax-only

#123155 gnome-recipes: add comment for libsoup 3 support
  Formula/gnome-recipes.rb
Labels: missing license, CI-syntax-only

#123157 guile@2: re-deprecate
  Formula/guile@2.rb
Labels: legacy, formula deprecated, missing license, CI-syntax-only

#123158 libelf: disable on Linux in 3 months
  Formula/libelf.rb
Labels: CI-syntax-only, macos-only

#123204 kvazaar: specify test resource
  Formula/kvazaar.rb
Labels: CI-syntax-only

#123218 kyua: deprecate
  Formula/kyua.rb
Labels: lua, formula deprecated, CI-syntax-only

#123330 omega-rpg: deprecate
  Formula/omega-rpg.rb
Labels: formula deprecated, missing license, CI-syntax-only

#123331 wbox: deprecate
  Formula/wbox.rb
Labels: formula deprecated, missing license, CI-syntax-only

#123393 krew: style improvements
  Formula/krew.rb
Labels: go, CI-no-bottles

#123394 docker-slim: update homepage and repo info
  Formula/docker-slim.rb
Labels: go, CI-syntax-only

#123445 ykclient: re-deprecate on 2023-07-29
  Formula/pam_yubico.rb
  Formula/ykclient.rb
Labels: formula deprecated, CI-syntax-only

#123452 narwhal: deprecate
  Formula/narwhal.rb
Labels: formula deprecated, CI-syntax-only

#123458 scrollkeeper: deprecate
  Formula/scrollkeeper.rb
Labels: perl, formula deprecated, CI-syntax-only

#123443 cmu-sphinxbase: deprecate
  Formula/cmu-sphinxbase.rb
Labels: formula deprecated, CI-syntax-only

#123478 coffeescript: update HEAD branch to main
  Formula/coffeescript.rb
Labels: nodejs, CI-syntax-only

#123518 dcmtk: update livecheck
  Formula/dcmtk.rb
Labels: livecheck, missing license, CI-syntax-only

#123562 go-jsonnet: add livecheck to ignore `-pre*` releases
  Formula/go-jsonnet.rb
Labels: go, livecheck, CI-syntax-only

#123553 gradle@7: update `livecheck`
  Formula/gradle@7.rb
Labels: legacy, java, livecheck, CI-syntax-only

#123582 mp3val: remove patch
  Formula/mp3val.rb
Labels: ready to merge, CI-no-bottles

#123623 pmtiles: add `livecheck`
  Formula/pmtiles.rb
Labels: go, livecheck, CI-syntax-only

#123664 uwsgi: add reference to `pcre2` issue
  Formula/uwsgi.rb
Labels: python, perl, CI-syntax-only

#123635 workflows/triage: "long build" for `aws-sdk-cpp`
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#123688 gtk-vnc: update livecheck
  Formula/gtk-vnc.rb
Labels: livecheck, CI-syntax-only

#123690 go@1.17: update homepage, remove livecheck
  Formula/go@1.17.rb
Labels: go, legacy, livecheck, formula deprecated, CI-syntax-only

#123728 fish: add `rust` for HEAD build
  Formula/fish.rb
Labels: rust, CI-no-bottles

#123738 qt: add temporary dependency on `ffmpeg`
  Formula/qt.rb
Labels: nodejs, ready to merge, perl, CI-syntax-only, icu4c, ffmpeg

#123954 theharvester: update test
  Formula/theharvester.rb
Labels: python, CI-no-bottles

#123971 k3d: backport support for Go 1.20
  Formula/k3d.rb
Labels: go, CI-no-bottles

#124013 onscripter: remove livecheck
  Formula/onscripter.rb
Labels: lua, livecheck, formula deprecated, CI-syntax-only

#124031 poac: reflect organization name change
  Formula/poac.rb
Labels: CI-syntax-only, boost

#124035 lockrun: specify license
  Formula/lockrun.rb
Labels: CI-syntax-only, license

#123969 erigon: update issue ref blocking Go 1.20
  Formula/erigon.rb
Labels: go, CI-syntax-only, CI-no-fail-fast, CI-no-bottles

#124235 tty-share: use std_go_args
  Formula/tty-share.rb
Labels: go, CI-no-bottles

#124290 pax-construct: remove livecheck
  Formula/pax-construct.rb
Labels: formula deprecated, CI-syntax-only, CI-skip-livecheck

#124384 gzrt: replace deprecated `Utils.gzip` method
  Formula/gzrt.rb
Labels: CI-no-bottles

#124318 postgresql@15: fix native language support
  Formula/postgresql@15.rb
Labels: perl, formula deprecated, CI-syntax-only, icu4c

#124341 Refactor use of OpenStruct in postgresql-upgrade-database cmd
  cmd/postgresql-upgrade-database.rb
Labels: automerge-skip

#124437 bitcoin-core: update gcc fails_with block
  Formula/bitcoin.rb
Labels: CI-no-bottles, boost
