Repository Homebrew/homebrew-core, pull requests merged in 2023-01, with the labels that each got.

#119495 nest: update caveat reference to `python@3.11`
  Formula/nest.rb
Labels: python, CI-syntax-only

#118979 cp2k: migrate to python@3.11
  Formula/cp2k.rb
Labels: CI-requeued, CI-no-fail-fast, CI-no-bottles, long build, python-3.11-migration

#119534 sshfs: deprecate
  Formula/sshfs.rb
Labels: formula deprecated, CI-syntax-only, linux-only

#119541 irssi: update license
  Formula/irssi.rb
Labels: perl, CI-syntax-only, license

#119543 specify default head branches for gitlab projects
  Formula/ascii.rb
  Formula/cvs-fast-export.rb
  Formula/intercal.rb
  Formula/libidn2.rb
  Formula/lilypond.rb
  Formula/mdds.rb
  Formula/mutt.rb
  Formula/pdfgrep.rb
Labels: CI-syntax-only

#119552 golo: deprecate
  Formula/golo.rb
Labels: java, livecheck, formula deprecated, CI-no-bottles

#119565 netcdf: add `libxml2` dependency
  Formula/netcdf.rb
Labels: CI-no-bottles

#119601 libcpuid: apply patch only to stable
  Formula/libcpuid.rb
Labels: CI-syntax-only, no ARM bottle

#119614 zorba: remove Linux bottle
  Formula/zorba.rb
Labels: java, CI-syntax-only, no Linux bottle, icu4c

#119600 openttd: add `icu4c` and `zlib` dependency on Linux
  Formula/openttd.rb
Labels: ready to merge, CI-no-bottles, icu4c

#119672 aliases: add libdwarf for dwarfutils
  Aliases/libdwarf
Labels: automerge-skip

#119847 workflows/triage: use self-hosted for `python@3.11`
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#120019 sccache: add livecheck
  Formula/sccache.rb
Labels: rust, livecheck, CI-syntax-only

#120020 certstrap: add livecheck
  Formula/certstrap.rb
Labels: go, livecheck, CI-syntax-only

#120043 vert.x: deprecate
  Formula/vert.x.rb
Labels: java, formula deprecated, CI-syntax-only

#120005 artifactory: deprecate
  .github/workflows/autobump.yml
  Formula/artifactory.rb
Labels: java, formula deprecated, CI-syntax-only, automerge-skip

#120065 curaengine: remove `livecheck`
  Formula/curaengine.rb
Labels: livecheck, formula deprecated, CI-syntax-only

#120064 vert.x: remove `livecheck`
  Formula/vert.x.rb
Labels: java, livecheck, formula deprecated, CI-syntax-only

#120063 ruff: add throttle comment
  Formula/ruff.rb
Labels: rust, CI-syntax-only

#120076 libvnc: remove `livecheck`
  Formula/libvnc.rb
Labels: livecheck, formula disabled, CI-syntax-only

#120069 artifactory: remove `livecheck`
  Formula/artifactory.rb
Labels: java, livecheck, formula deprecated, CI-syntax-only

#120067 sonarqube: update livecheck
  Formula/sonarqube.rb
Labels: java, livecheck, CI-syntax-only

#120197 workflows/triage: "skip recursive" for ca-certs
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#120177 CODEOWNERS: add formulae for icu4c 72.1 #113512
  CODEOWNERS
Labels: automerge-skip

#120122 krb5: make `bison` build-only dependency
  Formula/krb5.rb
Labels: ready to merge, CI-linux-self-hosted, CI-no-fail-fast, CI-no-bottles, long build

#120259 mpd: fix build with boost 1.81.0
  Formula/mpd.rb
Labels: ready to merge, automerge-skip, CI-no-bottles, boost, icu4c, ffmpeg

#120264 liblcf: set `CMAKE_INSTALL_RPATH`
  Formula/liblcf.rb
Labels: ready to merge, CI-no-bottles, icu4c

#120295 brpc: fix url
  Formula/brpc.rb
Labels: CI-syntax-only

#120267 manticoresearch: add livecheck
  Formula/manticoresearch.rb
Labels: ready to merge, livecheck, CI-syntax-only, automerge-skip, boost, icu4c

#120360 streamlink: fix test when `ffmpeg` is installed
  Formula/streamlink.rb
Labels: python, CI-no-bottles

#120384 workflows/triage: "long build" for xz
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#120403 autobump: add aptos
  .github/workflows/autobump.yml
Labels: CI-syntax-only, automerge-skip, workflows

#120500 restund: remove livecheck
  Formula/restund.rb
Labels: livecheck, formula deprecated, CI-syntax-only

#120501 xml2: remove livecheck
  Formula/xml2.rb
Labels: livecheck, formula deprecated, CI-syntax-only

#120483 workflows/triage: "long build" for libomp
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#119766 swift-format: remove patch
  Formula/swift-format.rb
Labels: swift, CI-no-bottles

#120593 scheduled: do not test disabled or deprecated
  .github/workflows/scheduled.yml
Labels: automerge-skip, workflows

#120626 gtk-mac-integration: specify default branch for `head` build
  Formula/gtk-mac-integration.rb
Labels: CI-syntax-only, macos-only

#120629 tiger-vnc: add livecheck
  Formula/tiger-vnc.rb
Labels: livecheck, CI-syntax-only

#120639 libswiften: remove livecheck
  Formula/libswiften.rb
Labels: lua, livecheck, formula disabled, missing license, CI-syntax-only, no Linux bottle, boost

#120654 pypi_formula_mappings(sgr): cleanup jsonschema
  pypi_formula_mappings.json
Labels: CI-syntax-only, automerge-skip

#120703 cpufetch: only apply patches to stable
  Formula/cpufetch.rb
Labels: CI-syntax-only

#120697 metals: add livecheck
  Formula/metals.rb
Labels: java, livecheck, CI-syntax-only

#120681 Revert "CODEOWNERS: add formulae for icu4c 72.1 #113512 (#120177)"
  CODEOWNERS
Labels: CI-syntax-only, automerge-skip

#120777 workflows/recreate: bump `setup-gcloud`
  .github/workflows/recreate-linux-runners.yml
Labels: CI-syntax-only, automerge-skip, workflows

#120813 rqlite: update homepage
  Formula/rqlite.rb
Labels: go, CI-syntax-only

#120915 simdutf: minimum Catalina
  Formula/simdutf.rb
Labels: no Linux bottle, icu4c

#120920 socket_vmnet: minimum Catalina
  Formula/socket_vmnet.rb
Labels: CI-syntax-only, macos-only

#120972 gtksourceviewmm: deprecate
  Formula/gtksourceviewmm.rb
Labels: formula deprecated, CI-syntax-only

#120952 at-spi2-core: make `gettext` build-only dependency
  Formula/at-spi2-core.rb
Labels: linux-only, CI-no-bottles

#120961 glibmm: let `meson` handle build steps
  Formula/glibmm.rb
Labels: CI-no-bottles

#120962 libsigc++: let `meson` handle build steps
  Formula/libsigc++.rb
Labels: CI-no-bottles

#120968 grt: let `cmake` handle build steps
  Formula/grt.rb
Labels: CI-no-bottles

#120970 libvdpau: let `meson` handle build steps
  Formula/libvdpau.rb
Labels: CI-no-bottles

#120948 anjuta: remove `gnome-themes-standard` dependency
  Formula/anjuta.rb
Labels: python, perl, formula disabled, CI-syntax-only

#120953 spirv-tools,shaderc: add conflicts_with
  Formula/shaderc.rb
  Formula/spirv-tools.rb
Labels: ready to merge, CI-syntax-only

#120988 gtkextra: deprecate
  Formula/gtkextra.rb
Labels: formula deprecated, CI-syntax-only

#120989 gtk-chtheme: deprecate
  Formula/gtk-chtheme.rb
Labels: formula deprecated, missing license, CI-syntax-only

#120990 gbdfed: deprecate
  Formula/gbdfed.rb
Labels: formula deprecated, missing license, CI-syntax-only

#120991 gqview: deprecate
  Formula/gqview.rb
Labels: formula deprecated, missing license, CI-syntax-only

#120992 gerbv, gkrellm, xsane: add reference to GTK3/GTK4 issue
  Formula/gerbv.rb
  Formula/gkrellm.rb
  Formula/xsane.rb
Labels: CI-syntax-only

#121017 phrase-cli: add alias from phrase
  Aliases/phrase
Labels: automerge-skip

#121046 gpa: add HEAD
  Formula/gpa.rb
Labels: missing license, CI-no-bottles

#121056 tomcat@8: add future disable date
  Formula/tomcat@8.rb
Labels: legacy, java, formula deprecated, CI-syntax-only

#121173 caffe: remove livecheck
  Formula/caffe.rb
Labels: livecheck, formula deprecated, CI-syntax-only, boost

#121175 libcouchbase@2: deprecate
  Formula/libcouchbase@2.rb
Labels: legacy, formula deprecated, CI-syntax-only

#121210 xsw: deprecate
  Formula/xsw.rb
Labels: formula deprecated, CI-syntax-only, deprecated license

#121201 luarocks: remove `lua@5.1` test dependency
  Formula/luarocks.rb
Labels: lua, CI-no-bottles

#121208 yelp-tools: update deprecated implied `meson setup`
  Formula/yelp-tools.rb
Labels: python, CI-no-bottles

#121221 gtksourceviewmm: remove livecheck
  Formula/gtksourceviewmm.rb
Labels: livecheck, formula deprecated, CI-syntax-only

#121223 gifski: add reference to FFmpeg 5 issue
  Formula/gifski.rb
Labels: rust, CI-syntax-only, ffmpeg

#121055 bibtexconv: update homepage
  Formula/bibtexconv.rb
Labels: CI-syntax-only

#121249 zenity: add `gettext` build dependency
  Formula/zenity.rb
Labels: CI-no-bottles

#121318 twtxt: depend on six formula
  Formula/twtxt.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121317 recon-ng: move python deps to homebrew deps
  Formula/recon-ng.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121316 dstack: depend on python-typing-extensions, remove unneeded python deps
  Formula/dstack.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121429 libcouchbase@2: fix homepage URL
  Formula/libcouchbase@2.rb
Labels: legacy, formula deprecated, CI-syntax-only

#121454 gnome-common: deprecate
  Formula/gnome-common.rb
  Formula/libpinyin.rb
Labels: CI-requeued, ready to merge, CI-issue, CI-syntax-only, CI-no-fail-fast, CI-no-bottles

#121504 ghc: use gnu-sed for Catalina
  Formula/ghc.rb
Labels: CI-syntax-only, CI-build-dependents-from-source

#121541 global: depend on pygments formula
  Formula/global.rb
Labels: python, CI-no-bottles

#121537 aws-sam-cli: depend on python-typing-extensions
  Formula/aws-sam-cli.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121538 cfn-lint: depend on python-typing-extensions
  Formula/cfn-lint.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121539 pylint: depend on python-typing-extensions
  Formula/pylint.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121543 theharvester: depend on pygments
  Formula/theharvester.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121544 iredis: depend on pygments
  Formula/iredis.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121545 pwntools: depend on pygments
  Formula/pwntools.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121546 grip: depend on pygments
  Formula/grip.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121547 name-that-hash: depend on pygments
  Formula/name-that-hash.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121406 workflows/remove-disabled-formulae: adapt to setup-homebrew changes
  .github/workflows/remove-disabled-formulae.yml
Labels: CI-syntax-only, automerge-skip, workflows

#121619 workflows: remove workspace hacks
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/publish-commit-bottles.yml
Labels: CI-syntax-only, automerge-skip, workflows

#121662 search-that-hash: depend on pygments
  Formula/search-that-hash.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121663 pywhat: depend on pygments
  Formula/pywhat.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121664 pyvim: depend on pygments
  Formula/pyvim.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-no-bottles

#121665 ptpython: depend on pygments
  Formula/ptpython.rb
  pypi_formula_mappings.json
Labels: python, automerge-skip, CI-no-bottles

#121668 litecli: depend on pygments
  Formula/litecli.rb
  pypi_formula_mappings.json
Labels: python, automerge-skip, CI-no-bottles

#121670 httpie: depend on pygments
  Formula/httpie.rb
  pypi_formula_mappings.json
Labels: python, automerge-skip, CI-no-bottles

#112955 Replace deprecated set-output with GITHUB_OUTPUT
  .github/workflows/dispatch-build-bottle.yml
  .github/workflows/dispatch-rebottle.yml
  .github/workflows/tests.yml
  cmd/determine-rebottle-runners.rb
Labels: automerge-skip

#121782 lepton: deprecate for archived repo
  Formula/lepton.rb
Labels: formula deprecated, no ARM bottle

#121833 aespipe: update livecheck
  Formula/aespipe.rb
Labels: livecheck, missing license, CI-syntax-only
