Repository Homebrew/homebrew-core, pull requests merged in 2024-09, with the labels that each got.

#183077 xml-tooling-c: add indirect `zlib` dep
  Formula/x/xml-tooling-c.rb
Labels: ready to merge, CI-no-bottles, boost

#183084 libgedit-amtk 5.9.0 libgedit-gfls 0.2.0
  .github/autobump.txt
  Formula/lib/libgedit-amtk.rb
  Formula/lib/libgedit-gfls.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#183082 libcyaml 1.4.2
  .github/autobump.txt
  Formula/lib/libcyaml.rb
Labels: bump-formula-pr, CI-skip-recursive-dependents, CI-published-bottle-commits, autobump

#180236 gismo 24.08.0
  .github/autobump.txt
  Formula/g/gismo.rb
Labels: ready to merge, livecheck, bump-formula-pr, CI-published-bottle-commits, autobump

#183078 man-db 2.13.0
  Formula/m/man-db.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#183090 boost: backport Boost.Compute fix follow up
  Formula/b/boost.rb
Labels: CI-skip-dependents, icu4c, CI-published-bottle-commits, long dependent tests

#183075 arrayfire: build with latest boost
  Formula/a/arrayfire.rb
Labels: CI-no-bottles, no Linux bottle, boost

#183081 lammps 20240829
  Formula/l/lammps.rb
Labels: homepage, CI-published-bottle-commits

#183074 poac: make `nlohmann-json` a build dependency
  Formula/p/poac.rb
Labels: CI-no-bottles

#183072 gnome_devel_allowlist: add libxml2 2.13
  audit_exceptions/gnome_devel_allowlist.json
Labels: CI-syntax-only, automerge-skip

#183071 mbedtls 3.6.1
  Formula/m/mbedtls.rb
Labels: CI-skip-recursive-dependents, CI-published-bottle-commits, long dependent tests

#183093 leela-zero: add `zlib` dep
  Formula/l/leela-zero.rb
Labels: CI-no-bottles, boost

#183092 katago: remove `boost`, use `eigen` backend on Linux
  Formula/k/katago.rb
Labels: CI-published-bottle-commits

#183079 libpcap 1.10.5
  .github/autobump.txt
  Formula/lib/libpcap.rb
Labels: bump-formula-pr, CI-skip-recursive-dependents, CI-published-bottle-commits, autobump

#183103 utf8proc: add HEAD
  Formula/u/utf8proc.rb
Labels: CI-syntax-only

#183096 tectonic: backport fix for newer Rust
  Formula/t/tectonic.rb
Labels: rust, CI-no-bottles, icu4c

#183063 fizz: add copy of FindSodium.cmake to libexec
  Formula/f/fbthrift.rb
  Formula/f/fizz.rb
Labels: CI-published-bottle-commits

#182965 libssh 0.11.1
  .github/autobump.txt
  Formula/lib/libssh.rb
Labels: bump-formula-pr, CI-skip-recursive-dependents, CI-published-bottle-commits, autobump, CI-no-fail-fast-deps, long dependent tests

#183108 mysql: use `protobuf`, avoid some upstream brew build logic
  Formula/m/mysql.rb
Labels: icu4c, CI-published-bottle-commits

#183125 autobump: `sort -u`
  .github/autobump.txt
Labels: CI-syntax-only, automerge-skip, autobump

#183095 gensio 2.8.6
  .github/autobump.txt
  Formula/g/gensio.rb
  Formula/s/ser2net.rb
Labels: go, python, bump-formula-pr, CI-published-bottle-commits, autobump

#183067 navidrome 0.52.5
  .github/autobump.txt
  Formula/n/navidrome.rb
Labels: CI-no-fail-fast, CI-published-bottle-commits, autobump

#183137 viddy 1.1.0
  Formula/v/viddy.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#183148 knot-resolver: update livecheck
  Formula/k/knot-resolver.rb
Labels: lua, livecheck, CI-syntax-only

#183155 jerryscript: declare indirect deps with linkage
  Formula/j/jerryscript.rb
Labels: CI-no-bottles

#183153 partio: use modern cmake syntax
  Formula/p/partio.rb
Labels: python, CI-no-bottles

#183149 nestopia-ue: declare indirect deps with linkage
  Formula/n/nestopia-ue.rb
Labels: CI-no-bottles

#183147 fltk: declare indirect deps with linkage
  Formula/f/fltk.rb
Labels: CI-no-bottles

#183140 qrcp 0.11.3
  .github/autobump.txt
  Formula/q/qrcp.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits, autobump

#183141 instead 3.5.2
  .github/autobump.txt
  Formula/i/instead.rb
Labels: lua, bump-formula-pr, CI-published-bottle-commits, autobump

#183094 certifi 2024.8.30
  .github/autobump.txt
  Formula/c/certifi.rb
Labels: ready to merge, bump-formula-pr, CI-published-bottle-commits, autobump, CI-no-fail-fast-deps, long dependent tests

#183159 autobump: Update renamed formulae
  .github/autobump.txt
Labels: CI-syntax-only, automerge-skip, autobump

#182715 bigloo: fix build
  Formula/b/bigloo.rb
Labels: java, no ARM bottle, CI-no-bottles

#183152 openfast: use modern cmake syntax
  Formula/o/openfast.rb
Labels: CI-no-bottles

#183073 dwarfs: build with GCC 11
  Formula/d/dwarfs.rb
Labels: ready to merge, boost, CI-published-bottle-commits

#183161 wget2: clean up dependencies
  Formula/w/wget2.rb
Labels: ready to merge, CI-published-bottle-commits

#183162 quazip: fix test
  Formula/q/quazip.rb
Labels: CI-no-bottles

#183181 lefthook 1.7.15
  Formula/l/lefthook.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#183069 CODEOWNERS: add `linux_only_gcc_dependency_allowlist`
  CODEOWNERS
Labels: CI-syntax-only, automerge-skip

#183184 openliberty-microprofile4 24.0.0.8
  Formula/o/openliberty-microprofile4.rb
Labels: java, bump-formula-pr, CI-published-bottle-commits

#183185 openliberty-webprofile8 24.0.0.8
  Formula/o/openliberty-webprofile8.rb
Labels: java, bump-formula-pr, CI-published-bottle-commits

#183183 openliberty-jakartaee8 24.0.0.8
  Formula/o/openliberty-jakartaee8.rb
Labels: java, bump-formula-pr, CI-published-bottle-commits

#183187 sstp-client 1.0.20
  Formula/s/sstp-client.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#183192 meilisearch 1.10.1
  Formula/m/meilisearch.rb
Labels: rust, CI-published-bottle-commits

#183193 apify-cli 0.20.6
  Formula/a/apify-cli.rb
Labels: nodejs, bump-formula-pr, CI-published-bottle-commits

#183202 tmux: fix for macOS 15
  Formula/t/tmux.rb
Labels: CI-no-bottles

#183204 progressline 0.2.2
  Formula/p/progressline.rb
Labels: swift, bump-formula-pr, CI-published-bottle-commits

#183138 grizzly 0.4.6 (new formula)
  .github/autobump.txt
  Formula/g/grizzly.rb
Labels: go, new formula, ready to merge, CI-published-bottle-commits, autobump

#183166 pyupgrade 3.17.0 (new formula)
  .github/autobump.txt
  Formula/p/pyupgrade.rb
Labels: new formula, CI-published-bottle-commits, autobump

#183165 dra 0.6.1 (new formula)
  .github/autobump.txt
  Formula/d/dra.rb
Labels: new formula, CI-published-bottle-commits, autobump

#183168 fierce 1.6.0 (new formula)
  .github/autobump.txt
  Formula/f/fierce.rb
Labels: new formula, CI-published-bottle-commits, autobump

#183205 xmlto: build with clang 16
  Formula/x/xmlto.rb
Labels: CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#180989 ircd-irc2: add license, replace usage of nameser_def.h
  Formula/i/ircd-irc2.rb
Labels: license, CI-published-bottle-commits

#183151 libfido2: use modern cmake syntax
  Formula/lib/libfido2.rb
Labels: ready to merge, CI-no-bottles

#183150 isl 0.27
  .github/autobump.txt
  Aliases/isl@0.27
  Formula/i/isl.rb
Labels: ready to merge, bump-formula-pr, CI-published-bottle-commits, autobump, CI-no-fail-fast-deps, long dependent tests

#183028 various formulae: use `audit_result` kwarg
  Formula/d/deadfinder.rb
  Formula/d/dnsmasq.rb
  Formula/l/licensed.rb
  Formula/m/mold.rb
  Formula/n/netcdf-cxx.rb
  Formula/n/nghttp2.rb
  Formula/o/open-mpi.rb
  Formula/o/opencascade.rb
  Formula/q/qt.rb
  Formula/v/vnstat.rb
  Formula/w/wemux.rb
  Formula/x/xinit.rb
Labels: brew, CI-syntax-only, CI-linux-self-hosted, CI-skip-dependents, CI-no-bottles, long build, CI-linux-self-hosted-deps, long dependent tests

#183206 protobuf: upstream fix for macOS 15
  Formula/p/protobuf.rb
Labels: CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#183207 azion 1.37.0
  Formula/a/azion.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#183222 mihomo 1.18.8
  .github/autobump.txt
  Formula/m/mihomo.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits, autobump

#183219 doc8 1.1.2
  .github/autobump.txt
  Formula/d/doc8.rb
Labels: python, bump-formula-pr, CI-published-bottle-commits, autobump

#183220 chrony 4.6
  .github/autobump.txt
  Formula/c/chrony.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#183208 zabbix-cli 3.0.0
  .github/autobump.txt
  Formula/z/zabbix-cli.rb
Labels: python, bump-formula-pr, CI-published-bottle-commits, autobump

#183221 libffcall 2.5
  .github/autobump.txt
  Formula/lib/libffcall.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#183228 mesheryctl 0.7.91
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#183209 ghostscript: avoid neon on clang 16
  Formula/g/ghostscript.rb
Labels: CI-skip-recursive-dependents, CI-no-fail-fast, CI-published-bottle-commits

#183231 odin 2024-09
  Formula/o/odin.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#182806 libchaos: patch in support for Xcode 15 (LLVM 16)
  Formula/lib/libchaos.rb
Labels: ready to merge, CI-no-bottles

#183247 pyupgrade: Fix `desc` stanza
  Formula/p/pyupgrade.rb
Labels: python, CI-syntax-only

#183267 trimage: disable
  Formula/t/trimage.rb
Labels: python, formula disabled, CI-syntax-only

#181011 bbtools: fix build
  Formula/b/bbtools.rb
Labels: java, ready to merge, CI-syntax-only, CI-no-fail-fast, CI-no-bottles

#183268 packetry 0.2.2
  Formula/p/packetry.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#183252 autobump: add protobuf
  .github/autobump.txt
Labels: ready to merge, CI-syntax-only, autobump

#183249 rttr: use modern cmake syntax
  Formula/r/rttr.rb
Labels: ready to merge, CI-no-fail-fast, CI-no-bottles

#183248 open-babel: declare indirect deps with linkage
  Formula/o/open-babel.rb
Labels: python, ready to merge, CI-no-bottles

#183246 libsvg-cairo: declare indirect deps with linkage
  Formula/lib/libsvg-cairo.rb
Labels: ready to merge, license, CI-no-bottles

#183250 r: declare indirect deps with linkage
  Formula/r/r.rb
Labels: CI-no-bottles

#183243 cminpack 1.3.9
  .github/autobump.txt
  Formula/c/cminpack.rb
Labels: ready to merge, CI-published-bottle-commits, autobump

#183251 lightning 2.2.3
  .github/autobump.txt
  Formula/l/lightning.rb
Labels: CI-published-bottle-commits, autobump

#183269 vulkan 1.3.295
  Formula/v/vulkan-headers.rb
  Formula/v/vulkan-loader.rb
  Formula/v/vulkan-profiles.rb
  Formula/v/vulkan-tools.rb
  Formula/v/vulkan-utility-libraries.rb
  Formula/v/vulkan-validationlayers.rb
Labels: CI-no-fail-fast, CI-published-bottle-commits

#183285 mesheryctl 0.7.92
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#183244 workflows/tests: add message about deps test being skipped
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#183283 libshumate: drop unused dependencies
  Formula/lib/libshumate.rb
Labels: ready to merge, CI-no-bottles

#183284 sbom-tool: remove `icu4c` dep
  Formula/s/sbom-tool.rb
Labels: ready to merge, CI-no-bottles, dotnet

#183294 ruby-build 20240903
  Formula/r/ruby-build.rb
Labels: CI-published-bottle-commits

#183300 tmux: scope patch to stable block
  Formula/t/tmux.rb
Labels: CI-published-bottle-commits

#183293 attr: fix test
  Formula/a/attr.rb
Labels: linux-only, CI-skip-dependents, CI-no-bottles

#183311 Replace remaining deprecated SPDX identifiers
  Formula/i/intercal.rb
  Formula/n/net-snmp.rb
Labels: CI-syntax-only, CI-no-bottles

#183310 vespa-cli 8.403.12
  Formula/v/vespa-cli.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#183322 tilt 0.33.20
  Formula/t/tilt.rb
Labels: go, nodejs, bump-formula-pr, CI-published-bottle-commits

#183332 dalfox 2.9.3
  Formula/d/dalfox.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#183333 viddy 1.1.1
  Formula/v/viddy.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#183324 lightning: add upstream patch for fixing `missing mprotect call if NDEBUG is not defined`
  Formula/l/lightning.rb
Labels: CI-published-bottle-commits

#183057 libblastrampoline 5.11.0 (new formula)
  Formula/j/julia.rb
  Formula/lib/libblastrampoline.rb
Labels: new formula, notability, CI-no-fail-fast, CI-published-bottle-commits, CI-skip-new-formulae

#183365 docbook2x: update license
  Formula/d/docbook2x.rb
Labels: perl, CI-syntax-only, license

#183361 libspiro 20240902
  .github/autobump.txt
  Formula/lib/libspiro.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#175258 argus-clients 5.0.0
  .github/autobump.txt
  Formula/a/argus-clients.rb
Labels: ready to merge, license, bump-formula-pr, CI-no-fail-fast, CI-published-bottle-commits, autobump

#183363 wxwidgets: fix for macOS 16
  Formula/w/wxwidgets.rb
Labels: CI-published-bottle-commits

#183358 luajit: fix for clang 16
  Formula/l/luajit.rb
Labels: CI-no-bottles

#183396 tundra: update livecheck
  Formula/t/tundra.rb
Labels: livecheck, CI-syntax-only

#183296 wush 0.1.2 (new formula)
  Formula/w/wush.rb
Labels: go, new formula, CI-published-bottle-commits

#183286 gumbo-parser 0.12.1
  Formula/g/gumbo-parser.rb
Labels: maintainer feedback, ready to merge, CI-published-bottle-commits

#183408 metis: add mirror
  Formula/m/metis.rb
Labels: CI-syntax-only

#183411 libxmlb: fix `rewrite_shebang` call
  Formula/lib/libxmlb.rb
Labels: CI-no-fail-fast, CI-skip-dependents, CI-no-bottles

#183407 libheif: force off gdk-pixbuf
  Formula/lib/libheif.rb
Labels: CI-skip-recursive-dependents, CI-no-bottles

#183414 xmlstarlet: compatibility with old C
  Formula/x/xmlstarlet.rb
Labels: CI-skip-recursive-dependents, CI-no-bottles

#183420 sox: fix for recent clang
  Formula/s/sox.rb
Labels: CI-no-bottles

#183425 llama.cpp: use simpler test on Intel Monterey
  Formula/l/llama.cpp.rb
Labels: CI-no-bottles

#183426 python-packaging: undisable
  Formula/p/python-packaging.rb
Labels: maintainer feedback, CI-skip-dependents, CI-no-bottles

#183419 solidity 0.8.27
  Formula/s/solidity.rb
Labels: boost, CI-published-bottle-commits

#182894 mesa 24.2.1
  Formula/m/mesa.rb
Labels: CI-published-bottle-commits, CI-linux-self-hosted-deps

#183440 coin3d: add livecheck and autobump
  .github/autobump.txt
  Formula/c/coin3d.rb
Labels: livecheck, CI-syntax-only, automerge-skip, autobump

#183362 mubeng 0.15.3
  .github/autobump.txt
  Formula/m/mubeng.rb
Labels: go, ready to merge, bump-formula-pr, CI-no-fail-fast, CI-published-bottle-commits, autobump

#183445 libiconv: work-around for old C
  Formula/lib/libiconv.rb
Labels: macos-only, CI-no-bottles, 15

#183446 zsh-autocomplete 24.09.04
  Formula/z/zsh-autocomplete.rb
Labels: CI-published-bottle-commits

#183448 fnlfmt 0.3.2
  .github/autobump.txt
  Formula/f/fnlfmt.rb
Labels: lua, bump-formula-pr, CI-published-bottle-commits, autobump

#183450 pcapplusplus 24.09
  .github/autobump.txt
  Formula/p/pcapplusplus.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#183458 iprint: update license and urls
  Formula/i/iprint.rb
Labels: formula disabled, CI-syntax-only, license

#183424 kosli-cli 2.10.14
  Formula/k/kosli-cli.rb
Labels: go, CI-no-fail-fast, CI-published-bottle-commits, 14

#183454 libfixbuf: declare indirect deps with linkage and add test
  Formula/lib/libfixbuf.rb
Labels: CI-no-bottles

#183449 luajit 2.1.1725453128
  Formula/l/luajit.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#183422 libsvm: fix symlink
  Formula/lib/libsvm.rb
Labels: CI-published-bottle-commits

#183167 cairo 1.18.2
  Formula/c/cairo.rb
Labels: bump-formula-pr, CI-skip-recursive-dependents, CI-published-bottle-commits, CI-no-fail-fast-deps, long dependent tests

#183455 glab 1.46.0
  Formula/g/glab.rb
Labels: go, bump-formula-pr, CI-no-fail-fast, CI-published-bottle-commits

#183476 yazi 0.3.3
  .github/autobump.txt
  Formula/y/yazi.rb
Labels: rust, ready to merge, bump-formula-pr, CI-published-bottle-commits, autobump

#183477 wasm-tools 1.216.0
  Formula/w/wasm-tools.rb
Labels: rust, CI-published-bottle-commits

#183447 expat 2.6.3
  Formula/e/expat.rb
Labels: bump-formula-pr, CI-skip-recursive-dependents, CI-published-bottle-commits, CI-no-fail-fast-deps, long dependent tests

#183478 mesheryctl 0.7.93
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#183022 alpscore: test with `cmake` and workaround CMake-built HDF5
  Formula/a/alpscore.rb
Labels: CI-no-bottles, boost

#183452 innotop: declare indirect deps with linkage
  Formula/i/innotop.rb
Labels: perl, CI-no-bottles

#183502 kubecolor 0.4.0
  Formula/k/kubecolor.rb
Labels: go, CI-published-bottle-commits

#181076 minipro: update sha
  Formula/m/minipro.rb
Labels: upstream issue, checksum mismatch, CI-no-fail-fast, CI-published-bottle-commits, CI-checksum-change-confirmed

#183523 mariadb@11.1: remove livecheck
  Formula/m/mariadb@11.1.rb
Labels: legacy, java, livecheck, formula disabled, CI-syntax-only

#183519 mise 2024.9.0
  Formula/m/mise.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#183513 cffi 1.17.1
  .github/autobump.txt
  Formula/c/cffi.rb
Labels: bump-formula-pr, CI-skip-recursive-dependents, CI-published-bottle-commits, autobump, CI-no-fail-fast-deps, long dependent tests

#183498 rust: move `cargo` bash completion
  Formula/r/rust.rb
Labels: CI-build-dependents-from-source, long build, CI-published-bottle-commits, long dependent tests

#183522 pypy3.9: deprecate
  .github/autobump.txt
  Formula/p/pypy3.9.rb
Labels: formula deprecated, CI-syntax-only, autobump

#183514 mongo-orchestration 0.9.0
  .github/autobump.txt
  Formula/m/mongo-orchestration.rb
Labels: python, bump-formula-pr, CI-published-bottle-commits, autobump

#183525 rbspy 0.25.0
  Formula/r/rbspy.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#183524 assimp: update license
  Formula/a/assimp.rb
Labels: CI-syntax-only, license

#183552 viddy 1.1.2
  Formula/v/viddy.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#183546 sane-backends: patch for clang 16
  Formula/s/sane-backends.rb
Labels: CI-skip-recursive-dependents, CI-published-bottle-commits, 15

#183558 bind: depend on jemalloc
  Formula/b/bind.rb
Labels: CI-published-bottle-commits, 15

#183566 tor: add mirror
  Formula/t/tor.rb
Labels: CI-no-bottles, 15

#183571 ahoy 2.2.0
  .github/autobump.txt
  Formula/a/ahoy.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits, autobump

#183579 silk 3.23.0
  .github/autobump.txt
  Formula/s/silk.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#183580 yaf 2.16.0
  .github/autobump.txt
  Formula/y/yaf.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#183578 nbdime 4.0.2
  .github/autobump.txt
  Formula/n/nbdime.rb
Labels: python, bump-formula-pr, CI-published-bottle-commits, autobump

#183575 iputils 20240905
  .github/autobump.txt
  Formula/i/iputils.rb
Labels: linux-only, bump-formula-pr, CI-published-bottle-commits, autobump

#183091 aider 0.54.8
  .github/autobump.txt
  Formula/a/aider.rb
Labels: python, rust, ready to merge, CI-published-bottle-commits, autobump

#183576 libfixbuf 2.5.0
  .github/autobump.txt
  Formula/lib/libfixbuf.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump
