Repository Homebrew/homebrew-core, pull requests merged in 2025-08, with the labels that each got.

#231947 gradle@7: deprecate
  Formula/g/gradle@7.rb
Labels: legacy, java, formula deprecated, CI-no-bottles

#231861 secretspec 0.3.1 (new formula)
  Formula/s/secretspec.rb
Labels: new formula, rust, ready to merge, CI-no-fail-fast, CI-published-bottle-commits, CI-skip-new-formulae

#231991 incus 6.15
  Formula/i/incus.rb
Labels: go, CI-published-bottle-commits

#231858 llvm: Rebase clang-cl patch
  Formula/l/llvm.rb
Labels: python, long build, CI-published-bottle-commits

#231994 ortp 5.4.33
  Formula/o/ortp.rb
Labels: CI-published-bottle-commits

#231899 dbhash lemon sqldiff sqlite-analyzer sqlite-rsync sqlite 3.50.4
  Formula/d/dbhash.rb
  Formula/l/lemon.rb
  Formula/s/sqldiff.rb
  Formula/s/sqlite-analyzer.rb
  Formula/s/sqlite-rsync.rb
  Formula/s/sqlite.rb
Labels: CI-skip-recursive-dependents, CI-published-bottle-commits, CI-no-fail-fast-deps, long dependent tests

#232013 unciv 4.17.11
  Formula/u/unciv.rb
Labels: java, CI-published-bottle-commits

#231969 bb-cli 1.3.3 (new formula)
  Formula/b/bb-cli.rb
Labels: new formula, php, CI-published-bottle-commits, CI-skip-new-formulae

#232033 fakesteak 0.2.4 (new formula)
  Formula/f/fakesteak.rb
Labels: new formula, CI-published-bottle-commits

#230400 tcl-tk: use current build with tcltls
  Formula/t/tcl-tk.rb
Labels: CI-published-bottle-commits

#232058 glances: revision bump
  Formula/g/glances.rb
Labels: python, rust, CI-published-bottle-commits

#232074 errcheck 1.9.0 (new formula)
  Formula/e/errcheck.rb
Labels: go, new formula, CI-published-bottle-commits

#232073 [ab]*: fix pathname
  Formula/a/ali.rb
  Formula/a/apko.rb
  Formula/a/arkade.rb
  Formula/a/ascii.rb
  Formula/a/austin.rb
  Formula/b/bartib.rb
  Formula/b/bettercap.rb
  Formula/b/binsider.rb
  Formula/b/bottom.rb
  Formula/b/bower-mail.rb
  Formula/b/bzt.rb
Labels: CI-no-bottles

#232075 mame rom-tools 0.279
  Formula/m/mame.rb
  Formula/r/rom-tools.rb
Labels: long build, CI-published-bottle-commits

#232076 runme 3.15.1
  Formula/r/runme.rb
Labels: go, CI-published-bottle-commits

#232104 polaris 10.1.0
  Formula/p/polaris.rb
Labels: go, CI-published-bottle-commits

#232108 atomist-cli: deprecate
  Formula/a/atomist-cli.rb
Labels: nodejs, formula deprecated, CI-syntax-only

#232124 avro-cpp: improve patch and comment
  Formula/a/avro-cpp.rb
Labels: boost, CI-published-bottle-commits

#232110 [efg]*: fix pathname
  Formula/e/empty.rb
  Formula/f/falcoctl.rb
  Formula/f/fastgron.rb
  Formula/f/fierce.rb
  Formula/f/flawz.rb
  Formula/f/fricas.rb
  Formula/f/frizbee.rb
  Formula/g/ggh.rb
  Formula/g/gimmecert.rb
  Formula/g/gitea-mcp-server.rb
  Formula/g/gitu.rb
  Formula/g/gnmic.rb
  Formula/g/gobuster.rb
  Formula/g/gptscript.rb
  Formula/g/gtop.rb
Labels: CI-no-fail-fast, CI-no-bottles, CI-test-bot-no-concurrent-downloads

#232131 dra: fix pathname
  Formula/d/dra.rb
Labels: rust, CI-no-bottles, CI-test-bot-no-concurrent-downloads

#232129 tidy-html5: fix pathname and cmake
  Formula/t/tidy-html5.rb
Labels: CI-no-bottles

#232125 dromeaudio: deprecate
  Formula/d/dromeaudio.rb
Labels: formula deprecated, CI-syntax-only

#232134 lhasa 0.5.0
  Formula/l/lhasa.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#232117 [tu]*: fix pathname
  Formula/t/talisman.rb
  Formula/t/tbls.rb
  Formula/t/tern.rb
  Formula/t/tfk8s.rb
  Formula/t/tfproviderlint.rb
  Formula/t/tfupdate.rb
  Formula/t/toxiproxy.rb
  Formula/t/tradcpp.rb
  Formula/t/travis.rb
  Formula/t/tunnel.rb
  Formula/t/twtxt.rb
  Formula/u/uhubctl.rb
  Formula/u/usage.rb
Labels: CI-no-fail-fast, CI-no-bottles, CI-test-bot-no-concurrent-downloads

#232126 qhull: fix pathname and cmake
  Formula/q/qhull.rb
Labels: CI-skip-dependents, CI-no-bottles

#232150 o*: fix pathname
  Formula/o/openfga.rb
  Formula/o/opensca-cli.rb
  Formula/o/ory-hydra.rb
  Formula/o/overtls.rb
  Formula/o/ovsx.rb
  Formula/o/oxker.rb
Labels: CI-no-fail-fast, CI-no-bottles, CI-test-bot-no-concurrent-downloads

#232151 p*: fix pathname
  Formula/p/pacmc.rb
  Formula/p/parsedmarc.rb
  Formula/p/pidof.rb
  Formula/p/pkg-config-wrapper.rb
  Formula/p/plakar.rb
  Formula/p/policy-engine.rb
  Formula/p/prestodb.rb
  Formula/p/python-markdown.rb
Labels: CI-no-fail-fast, CI-no-bottles, CI-test-bot-no-concurrent-downloads

#232132 d*: fix pathname
  Formula/d/dart-sdk.rb
  Formula/d/deadfinder.rb
  Formula/d/docker-buildx.rb
  Formula/d/docker-compose.rb
  Formula/d/docker-machine.rb
  Formula/d/dory.rb
Labels: CI-linux-self-hosted, CI-no-fail-fast, CI-no-bottles, CI-test-bot-no-concurrent-downloads

#232120 [vwx]*: fix pathname
  Formula/v/veilid.rb
  Formula/v/vfox.rb
  Formula/v/vsce.rb
  Formula/v/vttest.rb
  Formula/w/wzprof.rb
  Formula/x/xcode-kotlin.rb
  Formula/x/xq.rb
Labels: CI-no-fail-fast, CI-no-bottles, CI-test-bot-no-concurrent-downloads

#232113 [qrs]*: fix pathname
  Formula/r/ratchet.rb
  Formula/r/rattler-build.rb
  Formula/r/regula.rb
  Formula/r/rojo.rb
  Formula/r/rpm.rb
  Formula/s/s3ql.rb
  Formula/s/safety.rb
  Formula/s/scw.rb
Labels: CI-no-fail-fast, CI-no-bottles, long build, CI-test-bot-no-concurrent-downloads

#232152 xmodmap: fix pathname and sleep test
  Formula/x/xmodmap.rb
Labels: CI-no-bottles, CI-test-bot-no-concurrent-downloads

#232163 xterm: add `pkgconf` build dependency
  Formula/x/xterm.rb
Labels: CI-published-bottle-commits

#232176 prefligit: add shell completions
  Formula/p/prefligit.rb
Labels: rust, CI-published-bottle-commits, CI-test-bot-no-concurrent-downloads

#232178 certgraph 0.1.1
  Formula/c/certgraph.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#232162 unzip: avoid using `macosx` target on Linux
  Formula/u/unzip.rb
Labels: CI-published-bottle-commits

#232209 cruft: fix test
  Formula/c/cruft.rb
Labels: python, CI-no-bottles

#232215 jasper: modernise CMake invocation
  Formula/j/jasper.rb
Labels: CI-skip-recursive-dependents, CI-no-bottles, long dependent tests

#232206 misc formulae: declare missing conflicts
  Formula/a/arp-scan-rs.rb
  Formula/a/arp-scan.rb
  Formula/b/btcli.rb
  Formula/b/btpd.rb
  Formula/k/kahip.rb
  Formula/m/mcp-toolbox.rb
  Formula/n/nova-fairwinds.rb
  Formula/o/open-simh.rb
  Formula/r/remarshal.rb
  Formula/s/sox.rb
  Formula/s/sox_ng.rb
  Formula/y/yaml2json.rb
Labels: CI-syntax-only, CI-no-bottles

#232227 redis: update livecheck
  Formula/r/redis.rb
Labels: livecheck, CI-syntax-only

#232228 vet: update homepage
  Formula/v/vet.rb
Labels: go, CI-syntax-only, homepage

#232229 bash-preexec 0.6.0
  Formula/b/bash-preexec.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#232232 Update CA certificate loading documentation
  Formula/c/ca-certificates.rb
  Formula/o/openssl@3.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#232263 misc: disable
  Formula/c/coda-cli.rb
  Formula/g/git-ssh.rb
  Formula/g/gmail-backup.rb
  Formula/k/ksync.rb
  Formula/l/linklint.rb
  Formula/lib/libolm.rb
  Formula/lib/libsignal-protocol-c.rb
  Formula/m/mahout.rb
  Formula/m/moz-git-tools.rb
  Formula/p/pgtune.rb
Labels: formula deprecated, formula disabled, CI-syntax-only

#232260 lstr 0.2.1 (new formula)
  Formula/l/lstr.rb
Labels: new formula, rust, CI-published-bottle-commits

#232259 rulesync 0.55.0 (new formula)
  Formula/r/rulesync.rb
Labels: nodejs, new formula, CI-published-bottle-commits

#232264 apache-flink@1 1.20.2
  Formula/a/apache-flink@1.rb
Labels: legacy, java, CI-published-bottle-commits, CI-test-bot-no-concurrent-downloads

#232268 mcp-proxy 0.8.2 (new formula)
  Formula/m/mcp-proxy.rb
  pypi_formula_mappings.json
Labels: python, new formula, CI-published-bottle-commits

#232270 mcptools 0.7.1 (new formula)
  Formula/m/mcptools.rb
Labels: go, new formula, CI-published-bottle-commits

#230870 mysql@8.4 mysql-client@8.4 8.4.6
  Formula/m/mysql-client@8.4.rb
  Formula/m/mysql@8.4.rb
Labels: legacy, ready to merge, CI-published-bottle-commits

#232333 kubernetes-cli@1.30: remove livecheck
  Formula/k/kubernetes-cli@1.30.rb
Labels: go, legacy, livecheck, formula disabled, CI-syntax-only

#232332 node@18: remove livecheck
  Formula/n/node@18.rb
Labels: legacy, livecheck, formula deprecated, CI-syntax-only, long build, icu4c

#232335 pyside@2: remove livecheck
  Formula/p/pyside@2.rb
Labels: python, legacy, livecheck, formula disabled, CI-syntax-only

#232336 task@2: remove livecheck
  Formula/t/task@2.rb
Labels: legacy, livecheck, formula disabled, CI-syntax-only

#232349 libgcrypt 1.11.2
  Formula/lib/libgcrypt.rb
Labels: bump-formula-pr, CI-skip-recursive-dependents, CI-published-bottle-commits, CI-no-fail-fast-deps, long dependent tests

#232379 libcroco: disable
  Formula/lib/libcroco.rb
Labels: formula deprecated, formula disabled, CI-syntax-only

#232383 mesheryctl 0.8.126
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#232411 oxen: disable autobump
  Formula/o/oxen.rb
Labels: rust, CI-no-bottles

#225813 pyrefly 0.26.1 (new formula)
  Formula/p/pyrefly.rb
Labels: new formula, rust, ready to merge, CI-published-bottle-commits

#232434 rage: Fix incomplete URL substring sanitization
  Formula/r/rage.rb
Labels: rust, CI-no-bottles

#232436 curl: Fix missing regular expression anchor
  Formula/c/curl.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#232435 iccdev 2.2.50 (renamed formula)
  Formula/i/iccdev.rb
  formula_renames.json
Labels: CI-published-bottle-commits

#232455 odin 2025-08
  Formula/o/odin.rb
Labels: CI-published-bottle-commits

#232498 workflows/manage-pull-request-labels: fix comment
  .github/workflows/manage-pull-request-labels.yml
Labels: CI-syntax-only, automerge-skip, workflows

#232431 php@8.2: Fix incomplete string escaping or encoding
  Formula/p/php@8.2.rb
Labels: legacy, formula deprecated, icu4c, CI-published-bottle-commits

#232432 php@8.3: Fix incomplete string escaping or encoding
  Formula/p/php@8.3.rb
Labels: legacy, formula deprecated, icu4c, CI-published-bottle-commits

#232291 manifold 3.2.1 (new formula)
  Formula/m/manifold.rb
Labels: new formula, CI-no-fail-fast, CI-published-bottle-commits

#232384 rggen 0.35.2 (new formula)
  Formula/r/rggen.rb
Labels: new formula, ruby, CI-no-fail-fast, CI-published-bottle-commits

#231814 libcaption: build as shared library
  Formula/lib/libcaption.rb
Labels: CI-published-bottle-commits

#232570 go@1.23 1.23.12
  Formula/g/go@1.23.rb
Labels: go, legacy, CI-published-bottle-commits

#232572 mac 11.30
  Formula/m/mac.rb
Labels: CI-published-bottle-commits

#232574 triage: remove `percona-server` from `long build` list
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#232576 passt 2025_08_05.309eefd
  Formula/p/passt.rb
Labels: linux-only, bump-formula-pr, CI-published-bottle-commits

#225846 percona-server 8.4.5-5
  Formula/p/percona-server.rb
Labels: ready to merge, CI-no-fail-fast, long build, icu4c, CI-published-bottle-commits

#232575 tidy-viewer 1.6.0
  Formula/t/tidy-viewer.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#232569 go 1.24.6
  Formula/g/garble.rb
  Formula/g/go.rb
  Formula/s/staticcheck.rb
Labels: no long build conflict, CI-published-bottle-commits

#232587 unciv 4.17.12
  Formula/u/unciv.rb
Labels: java, CI-published-bottle-commits

#232568 percona-server@8.0 8.0.42-33
  Formula/p/percona-server@8.0.rb
Labels: legacy, ready to merge, CI-no-fail-fast, icu4c, CI-published-bottle-commits

#232614 llama.cpp: fix typo
  Formula/l/llama.cpp.rb
Labels: CI-syntax-only

#232627 autocorrect 2.14.3
  Formula/a/autocorrect.rb
Labels: rust, CI-published-bottle-commits

#232679 gravitino: add livecheck
  Formula/g/gravitino.rb
Labels: nodejs, java, livecheck, CI-syntax-only

#232681 clipper2: add livecheck
  Formula/c/clipper2.rb
Labels: livecheck, CI-syntax-only

#232676 determine-rebottle-runners: add `-dispatch` tag to runner names
  cmd/determine-rebottle-runners.rb
Labels: CI-syntax-only, automerge-skip

#232699 wayback 0.20.1 (new formula)
  Formula/w/wayback.rb
Labels: go, new formula, CI-published-bottle-commits

#228217 gbox 0.0.19 (new formula)
  Formula/g/gbox.rb
Labels: go, new formula, CI-published-bottle-commits

#232735 zrok 1.1.0
  Formula/z/zrok.rb
Labels: go, nodejs, CI-published-bottle-commits

#232682 protoc-gen-grpc-java: build with `gradle@8`
  Formula/p/protoc-gen-grpc-java.rb
Labels: java, ready to merge, CI-no-fail-fast, CI-no-bottles

#232767 freeswitch: use `ffmpeg` and `pcre2` on HEAD
  Formula/f/freeswitch.rb
Labels: lua, CI-no-bottles, ffmpeg

#232723 adaptivecpp 25.02.0
  Formula/a/adaptivecpp.rb
  Formula/s/shamrock.rb
Labels: python, boost, CI-published-bottle-commits

#232757 swiftdraw 0.23.1
  Formula/s/swiftdraw.rb
Labels: swift, bump-formula-pr, CI-no-fail-fast, CI-published-bottle-commits

#232785 polyml 5.9.2
  Formula/p/polyml.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#232794 protoc-gen-grpc-java: revision bump (abseil 20250127.1)
  Formula/p/protoc-gen-grpc-java.rb
Labels: java, ready to merge, CI-published-bottle-commits

#232829 msolve 0.9.0 (new formula)
  Formula/m/msolve.rb
Labels: new formula, CI-published-bottle-commits

#232861 fdroidcl: fix fragile test
  Formula/f/fdroidcl.rb
Labels: go, CI-no-bottles

#232773 root: remove `pcre` dependency
  Formula/r/root.rb
Labels: python, CI-no-bottles, long build

#232885 limine: add livecheck
  Formula/l/limine.rb
Labels: livecheck, CI-syntax-only

#232888 tkdiff: migrate to `tcl-tk@9`
  Formula/t/tkdiff.rb
Labels: CI-published-bottle-commits

#232472 netatalk: make SQLite backend available
  Formula/n/netatalk.rb
Labels: perl, CI-published-bottle-commits, meson

#232889 synced_versions_formulae: remove cross-GCC formulae
  synced_versions_formulae.json
Labels: CI-syntax-only, automerge-skip

#232902 cdi 2.5.3
  Formula/c/cdi.rb
Labels: CI-published-bottle-commits

#230365 mesa 25.2
  Formula/m/mesa.rb
Labels: rust, prerelease-testing, CI-no-fail-fast, CI-published-bottle-commits, meson, CI-linux-self-hosted-deps

#232905 mesheryctl 0.8.127
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#232916 prjtrellis: update test url to resolve ssl issue
  Formula/p/prjtrellis.rb
Labels: python, CI-no-bottles, boost

#232915 macvim: update test to fix pathname issue
  Formula/m/macvim.rb
Labels: lua, python, ruby, macos-only, CI-no-bottles

#232914 tika: move resource version check to install block
  Formula/t/tika.rb
Labels: java, CI-no-bottles

#226858 gambit-scheme 4.9.7 gerbil-scheme 0.18.1
  Formula/g/gambit-scheme.rb
  Formula/g/gerbil-scheme.rb
Labels: CI-no-fail-fast, long build, CI-published-bottle-commits, linux-arm

#232937 osm-gps-map: patch in support for libsoup 3
  Formula/o/osm-gps-map.rb
Labels: CI-published-bottle-commits

#232939 tiger-vnc: add issue ref for fltk 1.4
  Formula/t/tiger-vnc.rb
Labels: CI-syntax-only

#232935 mesheryctl 0.8.128
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#232951 icemon: backport support for Qt 6
  Formula/i/icemon.rb
Labels: CI-published-bottle-commits

#232963 suil: use `qt` on Linux
  Formula/s/suil.rb
Labels: CI-published-bottle-commits, meson

#232967 openssl@3.0: deprecate on 2026-09-07
  Formula/o/openssl@3.0.rb
Labels: legacy, formula deprecated, CI-syntax-only

#232968 wxmaxima: backport support for wxWidgets 3.3
  Formula/w/wxmaxima.rb
Labels: CI-published-bottle-commits

#232970 cobo-cli 0.0.7
  Formula/c/cobo-cli.rb
Labels: python, rust, ready to merge, bump-formula-pr, CI-published-bottle-commits

#232949 qt: apply Arch Linux patches for assimp 6
  Formula/f/f3d.rb
  Formula/q/qt.rb
Labels: CI-linux-self-hosted, CI-no-fail-fast, long build, CI-published-bottle-commits, long dependent tests

#233008 mac 11.33
  Formula/m/mac.rb
Labels: CI-published-bottle-commits

#233018 libunicode: drop linux bottle
  Formula/lib/libunicode.rb
Labels: CI-no-bottles, no Linux bottle

#233024 afsctool: Specify the HEAD branch
  Formula/a/afsctool.rb
Labels: CI-syntax-only, macos-only

#233001 whisperkit-cli: generate completions
  Formula/w/whisperkit-cli.rb
Labels: swift, macos-only, shell-completion, CI-published-bottle-commits

#233007 moor 2.0.1 (new formula)
  Formula/m/moor.rb
Labels: go, new formula, CI-published-bottle-commits

#233004 kuzu: drop runtime versioned GCC
  Formula/k/kuzu.rb
Labels: CI-published-bottle-commits

#233026 or-tools: use upstream patch instead of `inreplace`
  Formula/o/or-tools.rb
Labels: ready to merge, CI-no-bottles

#232962 moor: renamed from moar
  Formula/m/moar.rb
  Formula/m/moarvm.rb
  Formula/m/moor.rb
  Formula/r/rakudo-star.rb
  formula_renames.json
Labels: go, CI-syntax-only, automerge-skip, CI-skip-dependents

#233040 choose: remove conflicts
  Formula/c/choose-gui.rb
  Formula/c/choose-rust.rb
  Formula/c/choose.rb
Labels: CI-syntax-only, CI-skip-dependents

#233046 terraform: remove conflicts
  Formula/t/tenv.rb
  Formula/t/terraform.rb
  Formula/t/tfenv.rb
Labels: CI-syntax-only

#233043 fastbit: remove conflicts
  Formula/f/fastbit.rb
  Formula/i/iniparser.rb
Labels: CI-syntax-only

#233048 zorba: remove conflicts
  Formula/x/xqilla.rb
  Formula/z/zorba.rb
Labels: CI-syntax-only

#233047 wownero: remove conflicts
  Formula/m/monero.rb
  Formula/w/wownero.rb
Labels: CI-syntax-only, boost

#233032 percona-xtrabackup: try to remove workaround
  Formula/p/percona-xtrabackup.rb
Labels: perl, CI-no-fail-fast, CI-skip-dependents, CI-no-bottles, icu4c, CI-skip-livecheck

#233064 macpine 1.1.1
  Formula/m/macpine.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#233065 aqtinstall: use Homebrew `zstd`
  Formula/a/aqtinstall.rb
Labels: python, CI-published-bottle-commits

#233066 ratarmount: ensure linkage to `zstd`
  Formula/r/ratarmount.rb
Labels: python, linux-only, CI-published-bottle-commits

#232918 k9s: v0.50.9 git revision update
  Formula/k/k9s.rb
Labels: go, upstream issue, checksum mismatch, CI-published-bottle-commits

#233081 determine-rebottle-runners: add a missing `-dispatch` tag
  cmd/determine-rebottle-runners.rb
Labels: CI-syntax-only, automerge-skip

#233082 opensca-cli 3.0.8
  Formula/o/opensca-cli.rb
Labels: go, CI-published-bottle-commits

#233083 workflows: use `xargs -t`
  .github/workflows/autobump.yml
  .github/workflows/tests.yml
Labels: CI-syntax-only, automerge-skip, workflows

#233085 gphoto2 2.5.32
  Formula/g/gphoto2.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#233086 logcheck 1.4.6
  Formula/l/logcheck.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#233084 bnfc 2.9.6
  Formula/b/bnfc.rb
Labels: haskell, java, bump-formula-pr, CI-published-bottle-commits

#231535 dvr-scan: switch to pypi source, enable autobump
  Formula/d/dvr-scan.rb
  pypi_formula_mappings.json
Labels: python, test failure, brew, switch-to-pypi-source, linux, CI-no-fail-fast, ffmpeg, CI-published-bottle-commits

#233094 ruby-build 20250811
  Formula/r/ruby-build.rb
Labels: CI-published-bottle-commits

#227251 openvino 2025.2.0
  Formula/o/openvino.rb
Labels: build failure, linux, CI-no-fail-fast, long build, CI-published-bottle-commits, CI-no-fail-fast-deps

#233102 gstreamer: remove Linux workaround
  Formula/g/gstreamer.rb
Labels: python, rust, ready to merge, long build, ffmpeg, CI-published-bottle-commits, meson

#233134 moor 2.0.2
  Formula/m/moor.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#233122 electric 1.1.0 (new formula)
  Formula/e/electric.rb
Labels: new formula, erlang, CI-published-bottle-commits

#233152 freeradius-server: revision bump (openssl 3.5.2)
  Formula/f/freeradius-server.rb
Labels: python, perl, CI-published-bottle-commits

#233177 vespa-cli 8.562.17
  Formula/v/vespa-cli.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#233203 alive2 21.0
  Formula/a/alive2.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#233237 zrok 1.1.2
  Formula/z/zrok.rb
Labels: go, nodejs, CI-published-bottle-commits

#233238 pieces-cli 1.17.0
  Formula/p/pieces-cli.rb
Labels: python, rust, bump-formula-pr, CI-published-bottle-commits

#233253 meilisearch 1.17.1
  Formula/m/meilisearch.rb
Labels: rust, CI-published-bottle-commits
