Repository Homebrew/homebrew-core, pull requests merged in 2025-07, with the labels that each got.

#228640 qalculate-gtk qalculate-qt 5.6.0
  Formula/q/qalculate-gtk.rb
  Formula/q/qalculate-qt.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#228720 astro: revert to 1.34.1
  Formula/a/astro.rb
Labels: go, CI-syntax-only, CI-version-downgrade

#228749 ibex 2.9.1
  Formula/i/ibex.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#228770 riff 3.4.0
  Formula/r/riff.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#228615 codex 0.2.0 (TypeScript -> Rust)
  Formula/c/codex.rb
Labels: rust, CI-published-bottle-commits

#228771 evernote2md 0.22.0
  Formula/e/evernote2md.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#228792 azure-cli: update `no_autobump` reason
  Formula/a/azure-cli.rb
Labels: python, rust, CI-syntax-only, autobump

#228811 blueprint-compiler 0.18.0
  Formula/b/blueprint-compiler.rb
Labels: bump-formula-pr, CI-published-bottle-commits, meson

#228878 legba: remove cmake 4 workaround
  Formula/l/legba.rb
Labels: rust, CI-no-bottles

#228874 yapf: enable autobump, add head
  Formula/y/yapf.rb
Labels: python, CI-syntax-only, autobump

#228879 dcadec: disable
  Formula/d/dcadec.rb
Labels: formula deprecated, formula disabled, CI-syntax-only

#228859 mbedtls 3.6.4
  Formula/m/mbedtls.rb
Labels: CI-published-bottle-commits

#228873 gi-docgen 2025.4
  Formula/g/gi-docgen.rb
Labels: python, bump-formula-pr, CI-published-bottle-commits

#228880 macvim: update cask name in conflicts
  Formula/m/macvim.rb
Labels: lua, python, ruby, macos-only, CI-no-bottles

#228882 frugal: disable
  Formula/f/frugal.rb
Labels: go, formula deprecated, formula disabled, CI-syntax-only

#228881 bitwarden-cli: remove workarounds
  Formula/b/bitwarden-cli.rb
Labels: nodejs, CI-no-fail-fast, CI-published-bottle-commits

#228916 dsda-doom: Replace dumb with libopenmpt.
  Formula/d/dsda-doom.rb
Labels: CI-published-bottle-commits

#228918 dumb: deprecate
  Formula/d/dumb.rb
Labels: formula deprecated, CI-syntax-only

#228927 unciv 4.17.2
  Formula/u/unciv.rb
Labels: java, CI-published-bottle-commits

#228941 lefthook 1.11.16
  Formula/l/lefthook.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#228992 eiffelstudio 25.02.98732
  Formula/e/eiffelstudio.rb
Labels: CI-published-bottle-commits

#228993 mongosh 2.5.5
  Formula/m/mongosh.rb
Labels: nodejs, ready to merge, CI-published-bottle-commits

#228908 glances: remove `six` formula
  Formula/g/glances.rb
  pypi_formula_mappings.json
Labels: CI-published-bottle-commits

#228914 gitmoji: fix prefix replacement
  Formula/g/gitmoji.rb
Labels: nodejs, CI-published-bottle-commits

#229062 rich-cli 1.8.1
  Formula/r/rich-cli.rb
Labels: python, bump-formula-pr, CI-published-bottle-commits

#229049 hyper-mcp 0.1.4
  Formula/h/hyper-mcp.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#228955 pytr 0.4.2 (new formula)
  .github/autobump.txt
  Formula/p/pytr.rb
  pypi_formula_mappings.json
Labels: python, new formula, CI-published-bottle-commits, autobump

#229064 saxon 12.8
  Formula/s/saxon.rb
Labels: java, CI-published-bottle-commits

#229060 koka 3.1.3
  Formula/k/koka.rb
Labels: haskell, CI-published-bottle-commits

#229099 trailscraper: enable autobump
  Formula/t/trailscraper.rb
Labels: python, CI-syntax-only

#228520 arcade-learning-environment: fix missing pypi deps
  Formula/a/arcade-learning-environment.rb
Labels: python, ready to merge, CI-published-bottle-commits

#229029 zeromq: enable drafts
  Formula/z/zeromq.rb
Labels: CI-published-bottle-commits, long dependent tests

#229108 eiffelstudio: update livecheck
  Formula/e/eiffelstudio.rb
Labels: livecheck, CI-syntax-only

#229137 unciv 4.17.3
  Formula/u/unciv.rb
Labels: java, CI-published-bottle-commits

#229065 readline 8.3
  Formula/r/readline.rb
Labels: ready to merge, CI-published-bottle-commits, CI-no-fail-fast-deps, long dependent tests

#229136 execline: add head
  Formula/e/execline.rb
Labels: CI-syntax-only

#229143 dalfox 2.12.0
  Formula/d/dalfox.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#229167 sevenzip 25.00
  Formula/s/sevenzip.rb
Labels: CI-published-bottle-commits

#229166 libgphoto2 2.5.32
  Formula/lib/libgphoto2.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#229164 fonttools: add lxml dependency
  Formula/f/fonttools.rb
  pypi_formula_mappings.json
Labels: CI-published-bottle-commits

#229196 hasura-cli 2.48.1
  Formula/h/hasura-cli.rb
Labels: go, nodejs, formula deprecated, bump-formula-pr, CI-published-bottle-commits

#229199 tcpflow: update livecheck
  Formula/t/tcpflow.rb
Labels: livecheck, CI-syntax-only, boost

#229209 kubernetes-cli@1.32 1.32.6
  Formula/k/kubernetes-cli@1.32.rb
Labels: go, legacy, formula disabled, bump-formula-pr, CI-published-bottle-commits

#229130 glances 4.3.2
  Formula/g/glances.rb
  pypi_formula_mappings.json
Labels: automerge-skip, CI-published-bottle-commits

#229251 monetdb 11.53.9
  Formula/m/monetdb.rb
Labels: CI-published-bottle-commits

#229303 kuzco 1.4.1
  Formula/k/kuzco.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#229312 moar 1.32.3
  Formula/m/moar.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#229327 tkdiff 6.0
  Formula/t/tkdiff.rb
Labels: CI-published-bottle-commits

#229341 dnstwist: bump python resources
  Formula/d/dnstwist.rb
Labels: python, CI-published-bottle-commits

#229347 streamrip: bump python resources
  Formula/s/streamrip.rb
Labels: python, ffmpeg, CI-published-bottle-commits

#229349 sigstore: bump python resources
  Formula/s/sigstore.rb
Labels: python, rust, CI-published-bottle-commits

#229351 vdirsyncer: bump python resources
  Formula/v/vdirsyncer.rb
Labels: python, CI-published-bottle-commits

#229352 fprettify: bump python resources
  Formula/f/fprettify.rb
Labels: python, CI-published-bottle-commits

#229348 slither-analyzer: bump python resources
  Formula/s/slither-analyzer.rb
Labels: python, rust, CI-published-bottle-commits

#229353 keepkey-agent: bump python resources
  Formula/k/keepkey-agent.rb
Labels: python, CI-published-bottle-commits

#229363 publish-commit-bottles: render force-push warning using Caution blockquote
  .github/workflows/publish-commit-bottles.yml
Labels: CI-syntax-only, workflows

#229391 mesheryctl 0.8.115
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#229410 go 1.24.5
  Formula/g/garble.rb
  Formula/g/go.rb
  Formula/s/staticcheck.rb
Labels: ready to merge, no long build conflict, CI-published-bottle-commits

#229423 git 2.50.1
  Formula/g/git-credential-libsecret.rb
  Formula/g/git-gui.rb
  Formula/g/git-svn.rb
  Formula/g/git.rb
Labels: CI-published-bottle-commits

#229433 mdp 1.0.16
  Formula/m/mdp.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#229471 plakar 1.0.2 (new formula)
  Formula/p/plakar.rb
Labels: go, new formula, CI-published-bottle-commits

#227751 trezor-agent: bump python resources
  Formula/t/trezor-agent.rb
Labels: python, CI-no-fail-fast, CI-published-bottle-commits

#229542 gh 2.75.0
  Formula/g/gh.rb
Labels: go, CI-published-bottle-commits

#229524 codex 0.4.0
  Formula/c/codex.rb
Labels: rust, CI-published-bottle-commits

#229543 workflows: discourage bottle block modification with a comment
  .github/workflows/triage.yml
  cmd/check-bottle-modification.rb
Labels: CI-syntax-only, workflows

#229562 workflows: set `HOMEBREW_DISABLE_LOAD_FORMULA` for `pull_request_target` workflows
  .github/workflows/automerge-triggers.yml
  .github/workflows/clean-up-closed-prs.yml
  .github/workflows/manage-pull-request-labels.yml
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#229564 workflows/triage: run `check-bottle-block` job in container
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#229567 check-bottle-modification: fix regex false positive
  cmd/check-bottle-modification.rb
Labels: CI-syntax-only, automerge-skip

#229550 sui 1.51.3
  Formula/s/sui.rb
Labels: rust, CI-published-bottle-commits

#229569 scdoc: don't clobber environment `LDFLAGS`
  Formula/s/scdoc.rb
Labels: CI-no-bottles

#229599 sing-box: update build tags
  Formula/s/sing-box.rb
Labels: go, CI-published-bottle-commits

#229607 mesheryctl 0.8.118
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#229648 squid 7.1
  Formula/s/squid.rb
Labels: CI-published-bottle-commits

#229647 gnuplot: fix source checksum
  Formula/g/gnuplot.rb
Labels: lua, checksum mismatch, CI-published-bottle-commits, CI-checksum-change-confirmed

#229663 glab 1.62.0
  Formula/g/glab.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#229658 uchardet: use relocatable rpath
  Formula/u/uchardet.rb
Labels: CI-skip-dependents, CI-no-bottles

#229657 wireshark: use relocatable rpath
  Formula/w/wireshark.rb
Labels: lua, CI-published-bottle-commits

#229664 plakar: add `service`
  Formula/p/plakar.rb
Labels: go, CI-published-bottle-commits

#229629 min-lang 0.46.0 (new formula)
  Formula/m/min-lang.rb
Labels: new formula, CI-published-bottle-commits

#229729 automerge-triggers.yml: fix overly broad permissions
  .github/workflows/automerge-triggers.yml
Labels: CI-syntax-only, automerge-skip, workflows

#229730 Avoid 0.0.0.0
  Formula/k/knot.rb
  Formula/l/launch_socket_server.rb
  Formula/v/varnish.rb
Labels: CI-published-bottle-commits

#229403 execstack 20130503 (new formula)
  Formula/e/execstack.rb
Labels: new formula, CI-published-bottle-commits

#229742 lefthook 1.12.2
  Formula/l/lefthook.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#229754 usage 2.2.0
  Formula/u/usage.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#229710 hsd: rebuild (node 24.4.0)
  Formula/h/hsd.rb
Labels: nodejs, CI-published-bottle-commits

#229758 Enable Bash completions for formulae using `:click` (3/18)
  Formula/c/cf2tf.rb
  Formula/c/cfn-flip.rb
  Formula/c/cfripper.rb
  Formula/c/check-jsonschema.rb
  Formula/c/cloudsplaining.rb
Labels: python, CI-published-bottle-commits

#229761 Enable Bash completions for formulae using `:click` (4/18)
  Formula/c/cobo-cli.rb
  Formula/c/codecov-cli.rb
  Formula/c/compiledb.rb
  Formula/c/conda-lock.rb
  Formula/c/cookiecutter.rb
Labels: python, CI-published-bottle-commits

#229764 Enable Bash completions for formulae using `:click` (5/18)
  Formula/d/datasette.rb
  Formula/d/djlint.rb
  Formula/d/dnsgen.rb
  Formula/d/dooit.rb
  Formula/e/ecs-deploy.rb
Labels: python, CI-published-bottle-commits

#229774 Enable Bash completions for formulae using `:click` (13/18)
  Formula/p/platformio.rb
  Formula/p/policy_sentry.rb
  Formula/p/posting.rb
  Formula/p/proselint.rb
  Formula/r/rasterio.rb
Labels: python, CI-published-bottle-commits

#229777 Enable Bash completions for formulae using `:click` (16/18)
  Formula/s/sigma-cli.rb
  Formula/s/snakefmt.rb
  Formula/s/sqlfluff.rb
  Formula/s/sqlite-utils.rb
  Formula/s/subliminal.rb
Labels: python, CI-published-bottle-commits

#229776 Enable Bash completions for formulae using `:click` (15/18)
  Formula/s/semgrep.rb
  Formula/s/sgr.rb
  Formula/s/shallow-backup.rb
  Formula/s/shodan.rb
  Formula/s/shub.rb
Labels: python, CI-published-bottle-commits

#229768 Enable Bash completions for formulae using `:click` (8/18)
  Formula/h/harlequin.rb
  Formula/h/hatch.rb
  Formula/h/homeassistant-cli.rb
  Formula/h/http-prompt.rb
  Formula/i/iredis.rb
Labels: python, CI-published-bottle-commits

#229798 readline 8.3.1
  Formula/r/readline.rb
Labels: ready to merge, CI-skip-dependents, CI-published-bottle-commits, long dependent tests

#229836 qsv 6.0.0
  Formula/q/qsv.rb
Labels: rust, CI-published-bottle-commits

#229757 Enable Bash completions for formulae using `:click` (2/18)
  Formula/b/beancount.rb
  Formula/b/bilix.rb
  Formula/b/bump-my-version.rb
  Formula/c/cekit.rb
Labels: python, long build, CI-published-bottle-commits

#229849 fzy 1.1
  Formula/f/fzy.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#229850 miniprot 0.18
  Formula/m/miniprot.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#229848 fish-lsp 1.0.10
  Formula/f/fish-lsp.rb
Labels: nodejs, bump-formula-pr, CI-published-bottle-commits

#229773 Enable Bash completions for formulae using `:click` (12/18)
  Formula/o/otterdog.rb
  Formula/p/pgcli.rb
  Formula/p/pip-tools.rb
  Formula/p/pipenv.rb
  Formula/p/pipgrip.rb
Labels: python, CI-published-bottle-commits

#229870 lima-additional-guestagents 1.2.0
  Formula/l/lima-additional-guestagents.rb
  synced_versions_formulae.json
Labels: CI-published-bottle-commits

#229871 tl-expected 1.2.0
  Formula/t/tl-expected.rb
Labels: CI-published-bottle-commits

#229827 ncurses: update CFLAGS when building with gcc>=15
  Formula/n/ncurses.rb
Labels: CI-skip-dependents, CI-no-bottles

#229873 neovim 0.11.3
  Formula/n/neovim.rb
Labels: lua, bump-formula-pr, CI-published-bottle-commits

#229883 cmd/check-bottle-modification: ignore merge commits
  cmd/check-bottle-modification.rb
Labels: CI-syntax-only, automerge-skip

#229866 stormy 0.2.1 (new formula)
  Formula/s/stormy.rb
Labels: go, new formula, CI-published-bottle-commits

#229872 bash: depend on readline
  Formula/b/bash.rb
Labels: CI-published-bottle-commits

#229890 tokei: add head
  Formula/t/tokei.rb
Labels: rust, CI-syntax-only

#229252 cxxopts: build an `:all` bottle
  Formula/c/cxxopts.rb
Labels: CI-published-bottle-commits

#229935 workflows/publish-commit-bottles: remove `master` branch handling
  .github/workflows/publish-commit-bottles.yml
Labels: CI-syntax-only, automerge-skip, workflows

#229933 codequery 1.0.1
  Formula/c/codequery.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#229727 pgslice 0.7.0 (new formula)
  Formula/p/pgslice.rb
Labels: new formula, ruby, CI-published-bottle-commits, CI-skip-new-formulae

#227978 kafkactl-azure-plugin: 1.3.0 (new formula)
  Formula/k/kafkactl-azure-plugin.rb
Labels: go, new formula, CI-published-bottle-commits, CI-skip-new-formulae

#229977 bash: avoid using `strchrnul` on macOS 15 and older
  Formula/b/bash.rb
Labels: ready to merge, CI-published-bottle-commits

#230014 runme 3.15.0
  Formula/r/runme.rb
Labels: go, CI-published-bottle-commits

#230047 gwyddion: update homepage, livecheck
  Formula/g/gwyddion.rb
Labels: livecheck, CI-syntax-only, homepage

#230050 ktlint 1.7.0
  Formula/k/ktlint.rb
Labels: java, CI-published-bottle-commits

#230054 workflows/triage: add missing `--repo` flag
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#230065 nixfmt 1.0.0 (new formula)
  Formula/n/nixfmt.rb
Labels: haskell, new formula, CI-published-bottle-commits

#230093 unciv 4.17.5
  Formula/u/unciv.rb
Labels: java, CI-published-bottle-commits

#230091 rbtools 5.3
  Formula/r/rbtools.rb
Labels: python, CI-published-bottle-commits, autosquash

#229990 kafkactl-aws-plugin: 1.3.0 (new formula)
  Formula/k/kafkactl-aws-plugin.rb
Labels: go, new formula, CI-published-bottle-commits, CI-skip-new-formulae

#230173 glab 1.63.0
  Formula/g/glab.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#230174 sui 1.52.1
  Formula/s/sui.rb
Labels: rust, CI-published-bottle-commits

#230197 ruby-build 20250716
  Formula/r/ruby-build.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#230109 fakeroot: add fixes for macOS
  Formula/f/fakeroot.rb
Labels: CI-published-bottle-commits

#230092 git-annex: update build flags to enable p2http
  Formula/g/git-annex.rb
Labels: haskell, CI-published-bottle-commits

#230264 spirv-cross 1.4.321.0
  Formula/s/spirv-cross.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#230265 spirv-headers 1.4.321.0
  Formula/s/spirv-headers.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#230267 zsh-fast-syntax-highlighting 1.56
  Formula/z/zsh-fast-syntax-highlighting.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#230268 mesheryctl 0.8.120
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#230269 wasi-libc 26
  Formula/w/wasi-libc.rb
Labels: CI-published-bottle-commits

#230266 usage 2.2.2
  Formula/u/usage.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#230263 aider 0.85.2
  Formula/a/aider.rb
Labels: python, rust, CI-published-bottle-commits

#230204 pkgconf: Add mirror from fossies.
  Formula/p/pkgconf.rb
Labels: CI-skip-dependents, CI-no-bottles

#230323 mvfst 2025.07.14.00
  Formula/m/mvfst.rb
  synced_versions_formulae.json
Labels: CI-published-bottle-commits

#230325 damask-grid: add livecheck
  Formula/d/damask-grid.rb
Labels: livecheck, CI-syntax-only

#230124 burrow 1.9.4 (new formula)
  Formula/b/burrow.rb
Labels: go, new formula, CI-published-bottle-commits

#230347 pkgconf: fix HTTP mirror
  Formula/p/pkgconf.rb
Labels: CI-skip-dependents, CI-no-bottles

#230355 misc: disable
  Formula/a/apidoc.rb
  Formula/c/crunchy-cli.rb
  Formula/g/gitless.rb
Labels: formula deprecated, formula disabled, CI-syntax-only

#230354 six: deprecate, disable in 3 months
  Formula/s/six.rb
Labels: formula disabled, CI-syntax-only

#230381 vespa-cli 8.551.21
  Formula/v/vespa-cli.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#230383 apify-cli 0.21.9
  Formula/a/apify-cli.rb
Labels: nodejs, bump-formula-pr, CI-published-bottle-commits

#230436 gh 2.76.0
  Formula/g/gh.rb
Labels: go, CI-published-bottle-commits

#230435 xml2rfc 3.30.0
  Formula/x/xml2rfc.rb
Labels: python, bump-formula-pr, CI-published-bottle-commits

#230432 cmocka 1.1.8
  Formula/c/cmocka.rb
Labels: CI-published-bottle-commits

#230433 flow-control 0.4.0
  Formula/f/flow-control.rb
Labels: bump-formula-pr, CI-published-bottle-commits, zig

#230429 mac 11.21
  Formula/m/mac.rb
Labels: CI-published-bottle-commits

#230477 bind: avoid deprecated funcs on all macOS
  Formula/b/bind.rb
Labels: CI-published-bottle-commits

#230496 unciv 4.17.6
  Formula/u/unciv.rb
Labels: java, CI-published-bottle-commits

#230553 zrok 1.0.7
  Formula/z/zrok.rb
Labels: go, nodejs, CI-published-bottle-commits
