Repository Homebrew/homebrew-core, pull requests merged in 2025-06, with the labels that each got.

#225343 healpix: update homepage
  Formula/h/healpix.rb
Labels: CI-syntax-only, homepage

#225369 lume: add service, improve test PID handling
  Formula/l/lume.rb
Labels: swift, macos-only, CI-published-bottle-commits

#225376 jq 1.8.0
  .github/autobump.txt
  Formula/j/jq.rb
Labels: automerge-skip, bump-formula-pr, CI-published-bottle-commits, autobump, CI-no-fail-fast-deps

#225108 wcurl: merge into curl
  Formula/c/curl.rb
  Formula/w/wcurl.rb
  formula_renames.json
Labels: CI-skip-recursive-dependents, CI-published-bottle-commits

#225396 dexter 0.6.0
  Formula/d/dexter.rb
Labels: ruby, CI-published-bottle-commits

#225333 git-cola: add git-gui (gitk) dependency
  Formula/g/git-cola.rb
Labels: python, CI-no-bottles

#225413 openldap: Enable the sssvlv module (server side sort)
  Formula/o/openldap.rb
Labels: CI-published-bottle-commits

#225451 cheapglk 1.0.7
  Formula/c/cheapglk.rb
Labels: CI-published-bottle-commits

#225453 dcfldd 1.9.3
  Formula/d/dcfldd.rb
Labels: CI-published-bottle-commits

#225450 odin 2025-06
  Formula/o/odin.rb
Labels: CI-published-bottle-commits

#225452 nx 21.0.4 (new formula)
  Formula/n/nx.rb
Labels: nodejs, new formula, CI-published-bottle-commits

#225535 nb 7.20.0
  Formula/n/nb.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#224970 phrase-cli 2.42.0
  Formula/p/phrase-cli.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#225550 nx 21.1.2
  Formula/n/nx.rb
Labels: nodejs, bump-formula-pr, CI-published-bottle-commits

#225462 blueprint-compiler 0.16.0 (new formula)
  Formula/b/blueprint-compiler.rb
Labels: new formula, CI-published-bottle-commits, meson

#225569 git-cliff 2.9.1
  Formula/g/git-cliff.rb
Labels: rust, CI-published-bottle-commits

#225473 logcheck 1.4.5
  Formula/l/logcheck.rb
Labels: CI-no-fail-fast, CI-published-bottle-commits

#225583 chadwick 0.10.0
  Formula/c/chadwick.rb
Labels: repo-location-update, CI-published-bottle-commits

#225175 claude-squad 1.0.3 (new formula)
  Formula/c/claude-squad.rb
Labels: go, new formula, CI-published-bottle-commits

#225607 libgig 4.5.0
  Formula/lib/libgig.rb
Labels: CI-published-bottle-commits

#225648 oq: revision bump (jq 1.8.0)
  Formula/o/oq.rb
Labels: CI-published-bottle-commits

#225663 fricas 1.3.12
  Formula/f/fricas.rb
Labels: CI-published-bottle-commits

#225678 python-gdbm@3.12 python-tk@3.12 python@3.12 3.12.11
  Formula/p/python-gdbm@3.12.rb
  Formula/p/python-tk@3.12.rb
  Formula/p/python@3.12.rb
Labels: legacy, bump-formula-pr, CI-published-bottle-commits

#225649 texi2html: scope gettext dep for macos and rebottle for attestation
  Formula/t/texi2html.rb
Labels: CI-no-fail-fast, CI-published-bottle-commits

#223398 jetty: 12.0.22
  Formula/j/jetty.rb
Labels: java, CI-published-bottle-commits

#225714 glab 1.59.0
  Formula/g/glab.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#225729 gradle@7 7.6.5
  .github/autobump.txt
  Formula/g/gradle@7.rb
Labels: legacy, java, CI-published-bottle-commits, autobump

#225779 glab 1.59.2
  Formula/g/glab.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#225760 mesa 25.1.2
  Formula/m/mesa.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits, meson

#225792 python-tk@3.9 python@3.9 3.9.23
  Formula/p/python-tk@3.9.rb
  Formula/p/python@3.9.rb
Labels: legacy, bump-formula-pr, CI-published-bottle-commits

#225801 aider 0.84.0
  Formula/a/aider.rb
Labels: python, rust, CI-published-bottle-commits

#225758 dbus: update caveats
  Formula/d/dbus.rb
Labels: CI-syntax-only, meson

#225828 ohdear-cli 4.3.1
  Formula/o/ohdear-cli.rb
Labels: php, bump-formula-pr, CI-published-bottle-commits

#225472 lzsa 1.4.1 (new formula)
  Formula/l/lzsa.rb
Labels: new formula, CI-published-bottle-commits

#225897 flow-cli 2.2.17
  Formula/f/flow-cli.rb
Labels: go, CI-published-bottle-commits

#225907 java-service-wrapper 3.6.2
  Formula/j/java-service-wrapper.rb
Labels: java, CI-published-bottle-commits

#225895 toml-bombadil 4.2.0 (new formula)
  Formula/t/toml-bombadil.rb
Labels: new formula, rust, CI-published-bottle-commits

#225950 brotli: add livecheck
  Formula/b/brotli.rb
Labels: livecheck, CI-syntax-only, long dependent tests

#225954 samply 0.13.1 (new formula)
  .github/autobump.txt
  Formula/s/samply.rb
Labels: new formula, rust, CI-published-bottle-commits, autobump

#225955 sql-lint 1.0.2
  .github/autobump.txt
  Formula/s/sql-lint.rb
Labels: nodejs, bump-formula-pr, CI-published-bottle-commits, autobump

#225956 atmos 1.178.0
  Formula/a/atmos.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#225960 vcpkg 2025.06.02
  Formula/v/vcpkg.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#226020 claude-squad 1.0.5
  Formula/c/claude-squad.rb
Labels: go, CI-published-bottle-commits

#226021 nx 21.1.3
  Formula/n/nx.rb
Labels: nodejs, CI-published-bottle-commits

#226005 credo 1.7.12 (new formula)
  .github/autobump.txt
  Formula/c/credo.rb
Labels: new formula, CI-published-bottle-commits, autobump

#226006 htmlhint 1.5.0 (new formula)
  .github/autobump.txt
  Formula/h/htmlhint.rb
Labels: nodejs, new formula, CI-published-bottle-commits, autobump

#226041 podman-tui release v1.6.1
  Formula/p/podman-tui.rb
Labels: go, CI-published-bottle-commits

#225702 tsnet-serve 1.2.2 (new formula)
  .github/autobump.txt
  Formula/t/tsnet-serve.rb
Labels: go, new formula, CI-published-bottle-commits, autobump, CI-skip-new-formulae

#225882 mongo-c-driver 2.0.1 mongo-c-driver@1 1.30.4 (new formula)
  Aliases/mongo-c-driver@2
  Formula/f/fastnetmon.rb
  Formula/m/mongo-c-driver.rb
  Formula/m/mongo-c-driver@1.rb
  Formula/m/mongo-cxx-driver.rb
  Formula/s/syslog-ng.rb
  Formula/t/treefrog.rb
Labels: new formula, CI-published-bottle-commits, alias

#226033 sqruff 0.25.28 (new formula)
  .github/autobump.txt
  Formula/s/sqruff.rb
Labels: new formula, rust, CI-published-bottle-commits, autobump

#226059 gibo 3.0.14
  Formula/g/gibo.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#226058 formulae: revision bumps for mongo-c-driver@1 dep update
  Formula/f/fastnetmon.rb
  Formula/m/mongo-cxx-driver.rb
  Formula/s/syslog-ng.rb
  Formula/t/treefrog.rb
Labels: ready to merge, CI-published-bottle-commits

#225942 xk6: The version command is fixed and tested
  Formula/x/xk6.rb
Labels: go, superseded, automerge-skip, no push access

#212057 openjdk 24.0.1
  Aliases/openjdk@24
  Formula/o/openjdk.rb
Labels: help wanted, automerge-skip, CI-no-fail-fast, CI-build-dependents-from-source, CI-published-bottle-commits, alias, CI-no-fail-fast-deps, long dependent tests

#225072 btcli 9.5.1 (new formula)
  Formula/b/btcli.rb
  pypi_formula_mappings.json
Labels: python, new formula, rust, ready to merge, CI-published-bottle-commits

#226063 ares 0.11.0
  .github/autobump.txt
  Formula/a/ares.rb
Labels: CI-no-fail-fast, CI-published-bottle-commits, autobump

#225983 mesheryctl 0.8.100
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#226124 miniupnpc: allow building from head
  Formula/m/miniupnpc.rb
Labels: CI-syntax-only

#226134 dexter 0.6.1
  Formula/d/dexter.rb
Labels: ruby, CI-published-bottle-commits

#226076 k*: add no_autobump!
  Formula/k/kaitai-struct-compiler.rb
  Formula/k/kalign.rb
  Formula/k/kanif.rb
  Formula/k/karn.rb
  Formula/k/kawa.rb
  Formula/k/kconf.rb
  Formula/k/kdoctor.rb
  Formula/k/keepassc.rb
  Formula/k/keepkey-agent.rb
  Formula/k/keptn.rb
  Formula/k/kertish-dos.rb
  Formula/k/kettle.rb
  Formula/k/keystone.rb
  Formula/k/keyutils.rb
  Formula/k/khard.rb
  Formula/k/khiva.rb
  Formula/k/killswitch.rb
  Formula/k/kimwitu++.rb
  Formula/k/kitchen-completion.rb
  Formula/k/klavaro.rb
  Formula/k/knock.rb
  Formula/k/koka.rb
  Formula/k/kommit.rb
  Formula/k/kona.rb
  Formula/k/kondo.rb
  Formula/k/kopia.rb
  Formula/k/kore.rb
  Formula/k/kosli-cli.rb
  Formula/k/kqwait.rb
  Formula/k/kstart.rb
  Formula/k/ksync.rb
  Formula/k/kt-connect.rb
  Formula/k/ktlint.rb
  Formula/k/ktmpl.rb
  Formula/k/kubeaudit.rb
  Formula/k/kubectx.rb
  Formula/k/kubernetes-cli@1.29.rb
  Formula/k/kubesess.rb
  Formula/k/kumo.rb
  Formula/k/kustomizer.rb
  Formula/k/kuzco.rb
  Formula/k/kuzu.rb
  Formula/k/kyoto-cabinet.rb
  Formula/k/kyoto-tycoon.rb
  Formula/k/kytea.rb
Labels: CI-syntax-only

#226101 goplus: rename to `xgo` and remove formula
  .github/autobump.txt
  Formula/g/goplus.rb
  formula_renames.json
Labels: ready to merge, CI-syntax-only, autobump

#226147 pymol: allow numpy 2
  Formula/p/pymol.rb
Labels: python, CI-published-bottle-commits

#226149 xgo: add shell completion support
  Formula/x/xgo.rb
Labels: go, shell-completion, CI-published-bottle-commits

#226155 abpoa 1.5.4 (new formula)
  Formula/a/abpoa.rb
Labels: new formula, CI-published-bottle-commits

#225924 dvisvgm 3.5 (new formula)
  .github/autobump.txt
  Formula/d/dvisvgm.rb
Labels: new formula, ready to merge, CI-published-bottle-commits, autobump

#226132 swc 1.11.31
  Formula/s/swc.rb
Labels: rust, brew, CI-published-bottle-commits

#226169 java-service-wrapper: fix test failure under openjdk@24
  Formula/j/java-service-wrapper.rb
Labels: java, CI-no-bottles

#225048 osx-trash 0.7.1 (new formula)
  Formula/o/osx-trash.rb
Labels: new formula, macos-only, CI-no-fail-fast, CI-published-bottle-commits

#226220 osx-trash: add keg_only
  Formula/o/osx-trash.rb
Labels: macos-only, CI-no-bottles

#226223 gitup 0.5.2
  Formula/g/gitup.rb
Labels: python, CI-published-bottle-commits

#226225 ortp 5.4.21
  Formula/o/ortp.rb
Labels: CI-published-bottle-commits

#226246 px 3.6.11
  Formula/p/px.rb
Labels: python, bump-formula-pr, CI-published-bottle-commits

#226263 terramaid 2.5.0
  Formula/t/terramaid.rb
Labels: go, CI-published-bottle-commits

#226213 q*: add no_autobump!
  Formula/q/qalculate-gtk.rb
  Formula/q/qalculate-qt.rb
  Formula/q/qdbm.rb
  Formula/q/qhull.rb
  Formula/q/qjson.rb
  Formula/q/qodem.rb
  Formula/q/qp.rb
  Formula/q/qprint.rb
  Formula/q/qrencode.rb
  Formula/q/qrupdate.rb
  Formula/q/qscintilla2.rb
  Formula/q/qsoas.rb
  Formula/q/qstat.rb
  Formula/q/qt-libiodbc.rb
  Formula/q/qt-mariadb.rb
  Formula/q/qt-mysql.rb
  Formula/q/qt-percona-server.rb
  Formula/q/qt-postgresql.rb
  Formula/q/qt-unixodbc.rb
  Formula/q/qt.rb
  Formula/q/qt@5.rb
  Formula/q/qtads.rb
  Formula/q/quartz-wm.rb
  Formula/q/quex.rb
  Formula/q/quickjs.rb
  Formula/q/quran.rb
  Formula/q/qwt-qt5.rb
  Formula/q/qwt.rb
Labels: CI-syntax-only

#226294 gitlab-runner: remove `-B gobuildid` ldflag
  Formula/g/gitlab-runner.rb
Labels: go, CI-published-bottle-commits

#226314 octobuild 1.8.0
  Formula/o/octobuild.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#226293 tun2proxy 0.7.10 (new formula)
  .github/autobump.txt
  Formula/t/tun2proxy.rb
Labels: new formula, rust, CI-published-bottle-commits, autobump

#226300 mesheryctl: update ldflags
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#226303 u*: add no_autobump!
  Formula/u/ubertooth.rb
  Formula/u/ucg.rb
  Formula/u/uchardet.rb
  Formula/u/ucl.rb
  Formula/u/ucommon.rb
  Formula/u/ucon64.rb
  Formula/u/ucspi-tcp.rb
  Formula/u/udis86.rb
  Formula/u/udp2raw-multiplatform.rb
  Formula/u/udptunnel.rb
  Formula/u/udunits.rb
  Formula/u/ufbt.rb
  Formula/u/uftp.rb
  Formula/u/uggconv.rb
  Formula/u/uhdm.rb
  Formula/u/uhubctl.rb
  Formula/u/ulfius.rb
  Formula/u/ultralist.rb
  Formula/u/um.rb
  Formula/u/umlet.rb
  Formula/u/umockdev.rb
  Formula/u/umple.rb
  Formula/u/unac.rb
  Formula/u/unciv.rb
  Formula/u/unifdef.rb
  Formula/u/unittest-cpp.rb
  Formula/u/unittest.rb
  Formula/u/uniutils.rb
  Formula/u/unixodbc.rb
  Formula/u/unnethack.rb
  Formula/u/unoconv.rb
  Formula/u/unp.rb
  Formula/u/unpaper.rb
  Formula/u/unrtf.rb
  Formula/u/unum.rb
  Formula/u/unyaffs.rb
  Formula/u/unzip.rb
  Formula/u/up.rb
  Formula/u/upscaledb.rb
  Formula/u/uptoc.rb
  Formula/u/upx.rb
  Formula/u/urh.rb
  Formula/u/urlfinder.rb
  Formula/u/urlview.rb
  Formula/u/uru.rb
  Formula/u/urweb.rb
  Formula/u/usage.rb
  Formula/u/utftex.rb
  Formula/u/uthash.rb
  Formula/u/utimer.rb
  Formula/u/uudeview.rb
  Formula/u/uvw.rb
Labels: CI-syntax-only

#226363 g3log 2.5
  Formula/g/g3log.rb
Labels: CI-published-bottle-commits

#226084 sprocket 0.13.0 (new formula)
  .github/autobump.txt
  Formula/s/sprocket.rb
Labels: new formula, rust, CI-published-bottle-commits, autobump

#226367 gh 2.74.1
  Formula/g/gh.rb
Labels: go, CI-published-bottle-commits

#226366 mapcidr 1.1.94
  Formula/m/mapcidr.rb
Labels: go, CI-published-bottle-commits

#226386 mender-artifact: Install shell completions
  Formula/m/mender-artifact.rb
Labels: go, shell-completion, CI-published-bottle-commits

#226388 gcc@14 14.3.0
  Formula/g/gcc@14.rb
Labels: legacy, long build, CI-published-bottle-commits

#226307 y*: add no_autobump!
  Formula/y/yacas.rb
  Formula/y/yafc.rb
  Formula/y/yajl.rb
  Formula/y/yamcha.rb
  Formula/y/yamdi.rb
  Formula/y/yaml-cpp.rb
  Formula/y/yank.rb
  Formula/y/yapf.rb
  Formula/y/yarn-completion.rb
  Formula/y/yarn.rb
  Formula/y/yasm.rb
  Formula/y/yatas.rb
  Formula/y/yaze-ag.rb
  Formula/y/yazpp.rb
  Formula/y/yconalyzer.rb
  Formula/y/ydcv.rb
  Formula/y/yder.rb
  Formula/y/yelp-tools.rb
  Formula/y/yetris.rb
  Formula/y/yh.rb
  Formula/y/yj.rb
  Formula/y/ykclient.rb
  Formula/y/ykdl.rb
  Formula/y/ykpers.rb
  Formula/y/youtube-dl.rb
  Formula/y/yubikey-agent.rb
  Formula/y/yuicompressor.rb
  Formula/y/yydecode.rb
Labels: CI-syntax-only

#226308 z*: add no_autobump!
  Formula/z/z.rb
  Formula/z/z80asm.rb
  Formula/z/z80dasm.rb
  Formula/z/zanata-client.rb
  Formula/z/zbar.rb
  Formula/z/zboy.rb
  Formula/z/zebra.rb
  Formula/z/zelda-roth-se.rb
  Formula/z/zero-install.rb
  Formula/z/zimfw.rb
  Formula/z/zimg.rb
  Formula/z/zinit.rb
  Formula/z/zip.rb
  Formula/z/zita-convolver.rb
  Formula/z/zmqpp.rb
  Formula/z/zns.rb
  Formula/z/zopfli.rb
  Formula/z/zorba.rb
  Formula/z/zork.rb
  Formula/z/zpaq.rb
  Formula/z/zplug.rb
  Formula/z/zrepl.rb
  Formula/z/zrok.rb
  Formula/z/zsdx.rb
  Formula/z/zsh-async.rb
  Formula/z/zsh-autopair.rb
  Formula/z/zsh-completions.rb
  Formula/z/zsh-f-sy-h.rb
  Formula/z/zsh-fast-syntax-highlighting.rb
  Formula/z/zsh-git-prompt.rb
  Formula/z/zsh-history-substring-search.rb
  Formula/z/zsh-navigation-tools.rb
  Formula/z/zsh-syntax-highlighting.rb
  Formula/z/zsh-system-clipboard.rb
  Formula/z/zsh.rb
  Formula/z/zssh.rb
  Formula/z/zsxd.rb
  Formula/z/zsync.rb
  Formula/z/zug.rb
  Formula/z/zurl.rb
  Formula/z/zxcc.rb
  Formula/z/zyre.rb
  Formula/z/zzuf.rb
  Formula/z/zzz.rb
Labels: CI-syntax-only

#226448 mesheryctl 0.8.102
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#216453 packcc: update sha
  Formula/p/packcc.rb
Labels: upstream issue, checksum mismatch, ready to merge, CI-published-bottle-commits, CI-checksum-change-confirmed, linux-arm-bottling

#226445 sui 1.50.1
  Formula/s/sui.rb
Labels: rust, CI-published-bottle-commits

#226446 ruby-build 20250610
  Formula/r/ruby-build.rb
Labels: CI-published-bottle-commits

#226572 Tweak GitHub Actions workflows
  .github/workflows/actionlint.yml
  .github/workflows/autobump.yml
  .github/workflows/cache.yml
  .github/workflows/remove-disabled-packages.yml
  .github/workflows/scheduled.yml
  .github/workflows/tests.yml
Labels: automerge-skip, workflows

#226571 unciv 4.16.15
  Formula/u/unciv.rb
Labels: java, CI-published-bottle-commits

#226575 meilisearch 1.15.1
  Formula/m/meilisearch.rb
Labels: rust, CI-published-bottle-commits

#226582 ldcli 1.15.3 (new formula)
  .github/autobump.txt
  Formula/l/ldcli.rb
Labels: new formula, CI-published-bottle-commits, autobump, CI-skip-new-formulae

#226586 gitwatch 0.3
  .github/autobump.txt
  Formula/g/gitwatch.rb
Labels: CI-published-bottle-commits, autobump

#226588 mm-common 1.0.7
  Formula/m/mm-common.rb
Labels: python, bump-formula-pr, CI-published-bottle-commits, meson

#226594 desed 1.2.2 (new formula)
  Formula/d/desed.rb
Labels: new formula, rust, CI-published-bottle-commits

#226755 meilisearch 1.15.2
  Formula/m/meilisearch.rb
Labels: rust, CI-published-bottle-commits

#226754 mesheryctl 0.8.103
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#226762 btcli 9.6.0
  Formula/b/btcli.rb
Labels: python, rust, CI-published-bottle-commits

#226763 certbot 4.1.1
  .github/autobump.txt
  Formula/c/certbot.rb
Labels: python, bump-formula-pr, CI-published-bottle-commits, autobump

#226634 python-gdbm@3.13 python-tk@3.13 python@3.13 python-freethreading 3.13.5
  Formula/p/python-freethreading.rb
  Formula/p/python-gdbm@3.13.rb
  Formula/p/python-tk@3.13.rb
  Formula/p/python@3.13.rb
Labels: bump-formula-pr, CI-published-bottle-commits, CI-linux-self-hosted-deps, CI-no-fail-fast-deps, long dependent tests

#226811 telegram-downloader 0.19.0
  Formula/t/telegram-downloader.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#226827 tilt 0.35.0
  Formula/t/tilt.rb
Labels: go, nodejs, bump-formula-pr, CI-published-bottle-commits

#226830 zrok 1.0.6
  Formula/z/zrok.rb
Labels: go, nodejs, CI-published-bottle-commits

#226840 octobuild 1.8.1
  Formula/o/octobuild.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#226856 puzzles 20250613
  Formula/p/puzzles.rb
Labels: CI-published-bottle-commits

#226859 swiftly 1.0.1
  .github/autobump.txt
  Formula/s/swiftly.rb
Labels: CI-published-bottle-commits, autobump

#226864 lammps 20240829-update3
  Formula/l/lammps.rb
Labels: CI-published-bottle-commits

#226888 moar 1.31.10
  Formula/m/moar.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#226899 various: remove, move, and add `no_autobump!`
  Formula/a/abpoa.rb
  Formula/a/adamstark-audiofile.rb
  Formula/b/bash.rb
  Formula/b/bcftools.rb
  Formula/b/blastem.rb
  Formula/b/blueprint-compiler.rb
  Formula/b/breseq.rb
  Formula/b/btcli.rb
  Formula/c/calabash.rb
  Formula/c/clang-include-graph.rb
  Formula/c/claude-squad.rb
  Formula/c/clojure-lsp.rb
  Formula/c/cmix.rb
  Formula/e/elf2uf2-rs.rb
  Formula/f/fastk.rb
  Formula/f/flye.rb
  Formula/f/foxglove-cli.rb
  Formula/f/frege.rb
  Formula/g/glibc@2.13.rb
  Formula/g/glibc@2.17.rb
  Formula/g/gradle@7.rb
  Formula/h/htslib.rb
  Formula/h/http_load.rb
  Formula/j/jq.rb
  Formula/j/jwt-hack.rb
  Formula/k/kraken2.rb
  Formula/l/lzsa.rb
  Formula/lib/libbsc.rb
  Formula/lib/liblcf.rb
  Formula/lib/libpq@16.rb
  Formula/lib/libtatsu.rb
  Formula/lib/libtpms.rb
  Formula/lib/libzdb.rb
  Formula/m/macpine.rb
  Formula/m/maeparser.rb
  Formula/m/mesa.rb
  Formula/m/mingw-w64.rb
  Formula/m/mint.rb
  Formula/m/mongo-c-driver@1.rb
  Formula/n/nx.rb
  Formula/o/osx-trash.rb
  Formula/p/pangene.rb
  Formula/p/perbase.rb
  Formula/p/polypolish.rb
  Formula/p/poppler-qt5.rb
  Formula/p/poppler.rb
  Formula/r/ropebwt3.rb
  Formula/s/samtools.rb
  Formula/s/sql-lint.rb
  Formula/s/squashfs.rb
  Formula/s/stringtie.rb
  Formula/t/tabixpp.rb
  Formula/t/tea.rb
  Formula/t/toml-bombadil.rb
  Formula/t/trimal.rb
  Formula/u/urx.rb
  Formula/z/zebra.rb
  Formula/z/zsh-history-enquirer.rb
Labels: CI-syntax-only

#226898 goenv 2.2.25
  .github/autobump.txt
  Formula/g/goenv.rb
Labels: CI-published-bottle-commits, autobump

#226903 px 3.6.12
  Formula/p/px.rb
Labels: python, bump-formula-pr, CI-published-bottle-commits

#226912 quran: update test
  Formula/q/quran.rb
Labels: go, CI-no-bottles

#226921 service-weaver: deprecate
  Formula/s/service-weaver.rb
Labels: go, formula deprecated, CI-no-bottles

#226897 cmake cmake-docs 4.0.3
  .github/autobump.txt
  Formula/c/cmake-docs.rb
  Formula/c/cmake.rb
Labels: CI-skip-recursive-dependents, CI-published-bottle-commits, autobump, long dependent tests

#226929 nb 7.20.1
  Formula/n/nb.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#226936 ghalint 1.5.1 (new formula)
  .github/autobump.txt
  Formula/g/ghalint.rb
Labels: go, new formula, CI-published-bottle-commits, autobump

#226937 diagram 1.0.6 (new formula)
  .github/autobump.txt
  Formula/d/diagram.rb
Labels: go, new formula, CI-published-bottle-commits, autobump

#226943 mpremote 1.25.0 (new formula)
  .github/autobump.txt
  Formula/m/mpremote.rb
  synced_versions_formulae.json
Labels: python, new formula, CI-published-bottle-commits, autobump

#226949 unciv 4.16.16
  Formula/u/unciv.rb
Labels: java, CI-published-bottle-commits

#226966 pieces-cli 1.15.2
  Formula/p/pieces-cli.rb
Labels: python, rust, bump-formula-pr, CI-published-bottle-commits

#225397 act_runner 0.2.11 (new formula)
  Formula/a/act_runner.rb
Labels: go, new formula, CI-published-bottle-commits

#226969 puzzles 20250615
  Formula/p/puzzles.rb
Labels: CI-published-bottle-commits

#226982 yt-dlp: update test
  Formula/y/yt-dlp.rb
Labels: python, CI-no-bottles

#226944 mcp-inspector 0.14.2 (new formula)
  .github/autobump.txt
  Formula/m/mcp-inspector.rb
Labels: new formula, ready to merge, CI-published-bottle-commits, autobump

#226958 triage: update formulae tests
  .github/workflows/triage.yml
Labels: CI-syntax-only, automerge-skip, workflows

#227014 determine-rebottle-runners: fix typechecking error
  cmd/determine-rebottle-runners.rb
Labels: automerge-skip

#226385 mender-artifact: missing file system tools dependencies
  Formula/m/mender-artifact.rb
Labels: go

#226959 xk6: Added missing gosec and govulncheck dependencies
  Formula/x/xk6.rb
Labels: go, workflows, CI-build-dependents-from-source

#226780 picotool: fix HEAD build
  Formula/p/picotool.rb
Labels: CI-syntax-only, CI-no-bottles

#226926 python@3.13: fix os.getlogin
  Formula/p/python@3.13.rb
Labels: CI-skip-recursive-dependents, CI-published-bottle-commits, CI-linux-self-hosted-deps, CI-no-fail-fast-deps, long dependent tests

#227049 automerge: block automerge with 'maintainer feedback` label
  .github/workflows/automerge.yml
Labels: automerge-skip, workflows

#227083 findomain: add rust 1.87 build patch
  Formula/f/findomain.rb
Labels: rust, CI-no-bottles

#227082 ffsend: add rust 1.87 build patch
  Formula/f/ffsend.rb
Labels: rust, CI-no-bottles

#227085 kalker: add rust 1.87 build patch
  Formula/k/kalker.rb
Labels: rust, CI-no-bottles

#227084 kubeshark 52.7.8
  Formula/k/kubeshark.rb
Labels: go, superseded, automerge-skip, no push access

#227087 websocat: bump traitobject to build against rust 1.87
  Formula/w/websocat.rb
Labels: rust, CI-no-bottles

#227086 scryer-prolog: add rust 1.87 build patch
  Formula/s/scryer-prolog.rb
Labels: rust, CI-no-bottles

#227113 gobackup 2.15.3
  Formula/g/gobackup.rb
Labels: go, nodejs, CI-published-bottle-commits

#227114 deprecate: gorilla-cli
  Formula/g/gorilla-cli.rb
Labels: python, formula deprecated, CI-published-bottle-commits

#227101 html2text 2.3.0
  Formula/h/html2text.rb
Labels: repo-location-update, homepage, CI-published-bottle-commits

#227161 m4: fix mirror URL
  Formula/m/m4.rb
Labels: CI-syntax-only

#227167 glab 1.60.0
  Formula/g/glab.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#227187 gwyddion: add autoconf 2.72 compatibility
  Formula/g/gwyddion.rb
Labels: CI-no-bottles

#227151 moodle-dl 2.3.13 (new formula)
  .github/autobump.txt
  Formula/m/moodle-dl.rb
  pypi_formula_mappings.json
Labels: python, new formula, ready to merge, ffmpeg, CI-published-bottle-commits, autobump

#227214 jjui 0.8.11
  Formula/j/jjui.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#227115 chawan 0.2.0 (new formula)
  .github/autobump.txt
  Formula/c/chawan.rb
Labels: new formula, ready to merge, CI-published-bottle-commits, autobump

#227235 mesheryctl 0.8.105
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits
