Repository Homebrew/homebrew-core, pull requests merged in 2025-01, with the labels that each got.

#202888 inko: add livecheck
  Formula/i/inko.rb
Labels: rust, ruby, livecheck, CI-syntax-only

#202887 kapacitor 1.7.6
  Formula/k/kapacitor.rb
Labels: go, rust, ready to merge, CI-published-bottle-commits

#202873 mlton 20241230
  .github/autobump.txt
  Formula/m/mlton.rb
Labels: ready to merge, bump-formula-pr, CI-published-bottle-commits, autobump

#202878 influxdb@1: add rust 1.83 build patch
  Formula/i/influxdb@1.rb
Labels: go, legacy, rust, ready to merge, CI-published-bottle-commits

#202880 influxdb 2.7.11
  Formula/i/influxdb.rb
Labels: go, rust, ready to merge, CI-published-bottle-commits

#202897 formulae: allow building on linux arm64
  Formula/b/bic.rb
  Formula/b/bigloo.rb
  Formula/d/dnscrypt-wrapper.rb
  Formula/g/gcc@9.rb
  Formula/g/gdbgui.rb
  Formula/lib/libpcl.rb
  Formula/o/openjdk@8.rb
  Formula/o/openslp.rb
Labels: no ARM bottle, CI-skip-dependents, CI-no-bottles, long build

#202877 neovide: avoid pre-built `skia`, unbundle libs on Linux
  Formula/n/neovide.rb
Labels: rust, icu4c, CI-published-bottle-commits

#202907 oniguruma 6.9.10
  Formula/o/oniguruma.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#202893 harper 0.14.0 (new formula)
  .github/autobump.txt
  Formula/h/harper.rb
Labels: new formula, rust, CI-published-bottle-commits, autobump

#202900 xc 0.8.5 (new formula)
  .github/autobump.txt
  Formula/x/xc.rb
Labels: go, new formula, CI-published-bottle-commits, autobump

#202902 serie 0.4.1 (new formula)
  .github/autobump.txt
  Formula/s/serie.rb
Labels: new formula, rust, automerge-skip, CI-published-bottle-commits, autobump

#202903 tiny 0.13.0 (new formula)
  .github/autobump.txt
  Formula/t/tiny.rb
Labels: new formula, rust, automerge-skip, CI-no-fail-fast, CI-published-bottle-commits, autobump

#202904 vue-language-server 2.2.0 (new formula)
  .github/autobump.txt
  Formula/v/vue-language-server.rb
Labels: nodejs, new formula, automerge-skip, CI-published-bottle-commits, autobump

#202928 neovim: remove `caveats`
  Formula/n/neovim.rb
Labels: lua, CI-syntax-only

#202927 onefetch 2.23.0
  Formula/o/onefetch.rb
Labels: rust, CI-published-bottle-commits

#202937 onefetch 2.23.1
  Formula/o/onefetch.rb
Labels: rust, CI-published-bottle-commits

#202876 mame rom-tools 0.273
  Formula/m/mame.rb
  Formula/r/rom-tools.rb
Labels: ready to merge, CI-no-fail-fast, long build, CI-published-bottle-commits

#202943 mise 2025.1.0
  Formula/m/mise.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#202948 squiid 1.2.0
  Formula/s/squiid.rb
Labels: rust, CI-published-bottle-commits

#202955 itstool: add livecheck
  Formula/i/itstool.rb
Labels: python, livecheck, CI-syntax-only

#202944 yewtube: fix flacky test
  Formula/y/yewtube.rb
Labels: python, CI-no-bottles, ffmpeg

#202957 z: remove old comment, use shell_output to test
  Formula/z/z.rb
Labels: CI-no-bottles

#202938 cargo-msrv 0.17.1 (new formula)
  .github/autobump.txt
  Formula/c/cargo-msrv.rb
Labels: new formula, rust, CI-published-bottle-commits, autobump

#202942 gh-ost 1.1.7 (new formula)
  .github/autobump.txt
  Formula/g/gh-ost.rb
Labels: go, new formula, CI-published-bottle-commits, autobump

#202947 rtabmap: add indirect dependency
  Formula/r/rtabmap.rb
Labels: CI-no-bottles, long build, boost

#200514 visp: test cmake functionality in test block
  Formula/v/visp.rb
Labels: CI-no-bottles, boost

#202965 a-b*: add click shell completions
  Formula/a/adr-viewer.rb
  Formula/a/airshare.rb
  Formula/a/apprise.rb
  Formula/a/aws-sam-cli.rb
  Formula/a/aws-sso-util.rb
  Formula/b/bilix.rb
  Formula/b/bump-my-version.rb
Labels: python, CI-published-bottle-commits

#202972 c*: add argcomplete/click shell completions
  Formula/c/c7n.rb
  Formula/c/censys.rb
  Formula/c/cfn-flip.rb
  Formula/c/cfripper.rb
  Formula/c/cloudsplaining.rb
  Formula/c/cobo-cli.rb
  Formula/c/codecov-cli.rb
  Formula/c/conda-lock.rb
Labels: python, CI-published-bottle-commits

#202956 gcc@11 gcc@12: apply same linux arm64 fix as gcc formula
  Formula/g/gcc@11.rb
  Formula/g/gcc@12.rb
Labels: legacy, ready to merge, CI-no-bottles, long build

#202963 csound: remove `faust` test due to Homebrew/homebrew-core#202599
  Formula/c/csound.rb
Labels: python, java, ready to merge, CI-no-bottles, no Linux bottle

#202975 maturin: fix strict linkage warning
  Formula/m/maturin.rb
Labels: rust, CI-published-bottle-commits

#194622 mysql mysql-client 9.1.0
  Aliases/mysql-client@9.1
  Aliases/mysql@9.1
  Formula/m/mysql-client.rb
  Formula/m/mysql.rb
Labels: bump-formula-pr, CI-published-bottle-commits

#202983 meilisearch 1.12.1
  Formula/m/meilisearch.rb
Labels: rust, CI-published-bottle-commits

#202973 d-f*: add argcomplete/click shell completions
  Formula/d/djlint.rb
  Formula/d/dnsgen.rb
  Formula/d/dooit.rb
  Formula/e/ecs-deploy.rb
  Formula/e/esphome.rb
  Formula/e/esptool.rb
  Formula/f/flintrock.rb
  Formula/f/fred.rb
Labels: python, CI-published-bottle-commits

#202945 faust: add indirect dependency
  Formula/f/faust.rb
Labels: ready to merge, CI-skip-dependents, CI-no-bottles, CI-no-fail-fast-deps

#203006 g-l*: add argcomplete/click shell completions
  Formula/g/gcalcli.rb
  Formula/g/ggshield.rb
  Formula/g/gptme.rb
  Formula/h/harlequin.rb
  Formula/h/http-prompt.rb
  Formula/k/khal.rb
  Formula/l/localstack.rb
Labels: python, shell-completion, CI-published-bottle-commits

#202964 faust: use LLVM 19, dynamically link to LLVM
  Formula/f/faust.rb
Labels: CI-published-bottle-commits

#202901 xmq 3.1.3 (new formula)
  Formula/x/xmq.rb
Labels: new formula, notability, CI-published-bottle-commits, CI-skip-new-formulae

#203024 s-w*: add argcomplete/click shell completions
  Formula/s/schemathesis.rb
  Formula/s/sigma-cli.rb
  Formula/s/snakefmt.rb
  Formula/s/ssh-mitm.rb
  Formula/s/subliminal.rb
  Formula/t/tmt.rb
  Formula/v/vdirsyncer.rb
  Formula/w/weaviate-cli.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203043 beancount: add shell completions
  Formula/b/beancount.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203044 compiledb: add click shell completions
  Formula/c/compiledb.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203045 euler-py: add click shell completions
  Formula/e/euler-py.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203046 goolabs: add click shell completions
  Formula/g/goolabs.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203048 langgraph-cli: add click shell completions
  Formula/l/langgraph-cli.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203047 iredis: add click shell completions
  Formula/i/iredis.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203049 litecli: add click shell completions
  Formula/l/litecli.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203051 a-b*: align bash completion name
  Formula/a/action-validator.rb
  Formula/a/asdf.rb
  Formula/a/aws-vault.rb
  Formula/b/bazel.rb
  Formula/b/bottom.rb
Labels: shell-completion, CI-published-bottle-commits

#203059 d-f*: align bash completion name
  Formula/d/dust.rb
  Formula/e/exercism.rb
  Formula/f/ffsend.rb
  Formula/f/fossil.rb
Labels: CI-published-bottle-commits

#203067 p-s*: align bash completion name
  Formula/p/pastel.rb
  Formula/r/rain.rb
  Formula/s/savana.rb
  Formula/s/sequoia-sq.rb
Labels: shell-completion, CI-published-bottle-commits

#203072 jo: align bash completion name, use shell_output
  Formula/j/jo.rb
Labels: shell-completion, CI-published-bottle-commits

#203073 sugarjar: align bash completion name
  Formula/s/sugarjar.rb
Labels: ruby, shell-completion, CI-published-bottle-commits

#203066 t-x*: align bash completion name
  Formula/t/tabiew.rb
  Formula/t/taskwarrior-tui.rb
  Formula/t/textidote.rb
  Formula/u/unar.rb
  Formula/x/xh.rb
Labels: shell-completion, CI-published-bottle-commits

#203068 m-n*: align bash completion name
  Formula/m/magic-wormhole.rb
  Formula/m/modman.rb
  Formula/n/nb.rb
  Formula/n/ninja.rb
  Formula/n/nnn.rb
  Formula/n/notmuch.rb
Labels: shell-completion, CI-published-bottle-commits

#203075 name-that-hash: add click shell completions
  Formula/n/name-that-hash.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203076 okta-awscli: add click shell completions
  Formula/o/okta-awscli.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203077 proselint: add click shell completions
  Formula/p/proselint.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203079 tartufo: add click shell completions
  Formula/t/tartufo.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203080 waybackpy: add click shell completions
  Formula/w/waybackpy.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203007 jj: resolve redirect to `jj-vcs` GH org.
  Formula/j/jj.rb
Labels: rust, CI-no-bottles, repo-location-update

#203078 shodan: add click shell completions
  Formula/s/shodan.rb
Labels: python, shell-completion, CI-published-bottle-commits

#203052 c*: align bash completion name
  Formula/c/chezmoi.rb
  Formula/c/cmdshelf.rb
  Formula/c/code-minimap.rb
  Formula/c/csview.rb
  Formula/c/cyme.rb
Labels: shell-completion, CI-published-bottle-commits

#203070 j-l*: align bash completion name
  Formula/j/john-jumbo.rb
  Formula/k/kubie.rb
  Formula/l/ledger.rb
  Formula/l/leiningen.rb
  Formula/l/lsd.rb
  Formula/l/lunchy.rb
Labels: shell-completion, CI-published-bottle-commits

#203081 libfuse@2: backport fix for Linux arm64
  Formula/lib/libfuse@2.rb
Labels: legacy, linux-only, CI-no-bottles

#203074 stripe-cli: use `generate_completions_from_executable` and add fish completion support
  Formula/s/stripe-cli.rb
Labels: go, shell-completion, CI-published-bottle-commits

#203092 liquidctl 1.14.0
  Formula/l/liquidctl.rb
Labels: python, bump-formula-pr, CI-published-bottle-commits

#203071 g-h*: align bash completion name
  Formula/g/git-flow.rb
  Formula/g/git-gerrit.rb
  Formula/g/git-machete.rb
  Formula/g/gopass.rb
  Formula/h/homeshick.rb
Labels: shell-completion, CI-published-bottle-commits

#203015 formulae: use `pkgconf` for test
  Formula/a/apache-arrow-glib.rb
  Formula/a/appstream-glib.rb
  Formula/c/cairo.rb
  Formula/g/gerbv.rb
  Formula/g/gom.rb
  Formula/g/gssdp.rb
  Formula/g/gtkglext.rb
  Formula/g/gwyddion.rb
  Formula/j/json-glib.rb
  Formula/lib/libdazzle.rb
  Formula/lib/libgee.rb
  Formula/lib/libgtop.rb
  Formula/lib/libjcat.rb
  Formula/lib/libosinfo.rb
  Formula/lib/libpeas.rb
  Formula/lib/libpeas@1.rb
  Formula/lib/libpinyin.rb
  Formula/lib/librest.rb
  Formula/lib/libxml++.rb
  Formula/lib/libxmlb.rb
  Formula/o/osm-gps-map.rb
Labels: ready to merge, CI-skip-dependents, CI-no-bottles, long build

#203050 tabiew 0.8.1
  .github/autobump.txt
  Formula/t/tabiew.rb
Labels: rust, ready to merge, CI-published-bottle-commits, autobump

#203113 sile: Revert upstreamed fix for building luautf8 with luajit
  Formula/s/sile.rb
Labels: lua, rust, icu4c, CI-published-bottle-commits

#203121 i2pd: use latest `boost`
  Formula/i/i2pd.rb
Labels: boost, CI-published-bottle-commits

#201007 uhd: backport support for Boost 1.87.0
  Formula/g/gnuradio.rb
  Formula/u/uhd.rb
Labels: python, boost, CI-published-bottle-commits

#203114 poppler poppler-qt5 25.01.0
  Formula/e/efl.rb
  Formula/g/gdal.rb
  Formula/p/pdfgrep.rb
  Formula/p/pdftoipe.rb
  Formula/p/poppler-qt5.rb
  Formula/p/poppler.rb
Labels: CI-published-bottle-commits

#203122 fastfec: disable on 2025-09-13
  Formula/f/fastfec.rb
Labels: formula disabled, CI-syntax-only, zig

#199676 aws-sdk-cpp: add `aws-crt-cpp` dependency
  Formula/a/apache-arrow.rb
  Formula/a/aws-sdk-cpp.rb
  Formula/s/s2n.rb
Labels: long build, CI-published-bottle-commits

#203082 a*: check pipe_output exit code
  Formula/a/aamath.rb
  Formula/a/ack.rb
  Formula/a/aescrypt.rb
  Formula/a/aespipe.rb
  Formula/a/afio.rb
  Formula/a/afuse.rb
  Formula/a/age.rb
  Formula/a/aha.rb
  Formula/a/aiven-client.rb
  Formula/a/aldo.rb
  Formula/a/align.rb
  Formula/a/analog.rb
Labels: CI-skip-dependents, CI-no-bottles

#203149 passenger: remove `pcre` dependency
  Formula/p/passenger.rb
Labels: ruby, CI-published-bottle-commits

#203156 vectorscan: add reference to PCRE2 issue
  Formula/v/vectorscan.rb
Labels: CI-syntax-only, boost

#203157 hyperscan: recommend `vectorscan` as replacement
  Formula/h/hyperscan.rb
Labels: formula deprecated, CI-syntax-only, no ARM bottle, boost

#203159 tilt 0.33.22
  Formula/t/tilt.rb
Labels: go, nodejs, bump-formula-pr, CI-published-bottle-commits

#203160 kubeshark 52.3.94
  Formula/k/kubeshark.rb
Labels: go, superseded, automerge-skip, no push access

#203148 xmq 3.2.0
  .github/autobump.txt
  Formula/x/xmq.rb
Labels: CI-published-bottle-commits, autobump

#203103 cyphernetes: remove goyacc dependency
  Formula/c/cyphernetes.rb
Labels: go, CI-published-bottle-commits

#202991 proxyfor 0.5.0 (new formula)
  Formula/p/proxyfor.rb
Labels: new formula, rust, CI-published-bottle-commits

#203086 a*: check pipe_output exit code (part 2)
  Formula/a/antlr.rb
  Formula/a/apache-opennlp.rb
  Formula/a/apache-spark.rb
  Formula/a/apgdiff.rb
  Formula/a/argon2.rb
  Formula/a/as-tree.rb
  Formula/a/ascii2binary.rb
  Formula/a/asmfmt.rb
  Formula/a/aspell.rb
  Formula/a/attr.rb
  Formula/a/autopep8.rb
  Formula/a/avanor.rb
  Formula/a/awk.rb
  Formula/a/aws-auth.rb
Labels: CI-skip-recursive-dependents, CI-no-bottles

#203090 b*: check pipe_output exit code
  Formula/b/b2sum.rb
  Formula/b/base16384.rb
  Formula/b/base91.rb
  Formula/b/basedpyright.rb
  Formula/b/bazel.rb
  Formula/b/bc-gh.rb
  Formula/b/bc.rb
  Formula/b/bcrypt.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles

#203091 b*: check pipe_output exit code (part 2)
  Formula/b/bigloo.rb
  Formula/b/bk.rb
  Formula/b/blahtexml.rb
  Formula/b/bootloadhid.rb
  Formula/b/boxes.rb
  Formula/b/bsdconv.rb
  Formula/b/btpd.rb
  Formula/b/bwidget.rb
Labels: CI-skip-dependents, CI-no-bottles

#203185 ly 0.9.9
  Formula/l/ly.rb
Labels: python, CI-published-bottle-commits

#203187 cdo 2.5.0
  Formula/c/cdo.rb
Labels: CI-published-bottle-commits

#203174 xmq: simplify install
  Formula/x/xmq.rb
Labels: CI-no-bottles

#203194 sile: 0.15.9
  Formula/s/sile.rb
Labels: lua, rust, icu4c, CI-published-bottle-commits

#203180 mas 1.9.0
  Formula/m/mas.rb
Labels: macos-only, CI-published-bottle-commits

#203208 boring 0.11.0
  Formula/b/boring.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#203212 fourstore: remove outdated comment
  Formula/f/fourstore.rb
Labels: CI-syntax-only

#203210 python@3.12 python@3.13: use "n/a" to force disable tkinter
  Formula/p/python@3.12.rb
  Formula/p/python@3.13.rb
Labels: CI-skip-dependents, CI-no-bottles, CI-linux-self-hosted-deps

#203219 xurls 2.6.0
  .github/autobump.txt
  Formula/x/xurls.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits, autobump

#203200 fswatch 1.18.0
  .github/autobump.txt
  Formula/f/fswatch.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#203199 cargo-expand 1.0.96
  .github/autobump.txt
  Formula/c/cargo-expand.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits, autobump

#203196 spectra 1.1.0
  .github/autobump.txt
  Formula/s/spectra.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#203195 winetricks 20250102
  .github/autobump.txt
  Formula/w/winetricks.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#203202 libxmp 4.6.1
  .github/autobump.txt
  Formula/lib/libxmp.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#203197 sdl2_ttf 2.24.0
  .github/autobump.txt
  Formula/s/sdl2_ttf.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#203223 gnu-getopt: update Linux keg_only message, test with shell_output
  Formula/g/gnu-getopt.rb
Labels: CI-skip-dependents, CI-no-bottles

#203224 util-macros: use std_configure_args, test with shell_output
  Formula/u/util-macros.rb
Labels: CI-no-bottles

#203228 templ 0.3.819
  .github/autobump.txt
  Formula/t/templ.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits, autobump

#203227 mosquitto: update test
  Formula/m/mosquitto.rb
Labels: CI-no-bottles

#203232 broot: run test on Linux
  Formula/b/broot.rb
Labels: rust, CI-no-bottles

#203220 opencl-icd-loader: remove `ninja` dependency
  Formula/o/opencl-icd-loader.rb
Labels: CI-no-bottles

#203230 gh-ost: add livecheck
  Formula/g/gh-ost.rb
Labels: go, livecheck, CI-syntax-only

#203229 swc 1.10.4
  Formula/s/swc.rb
Labels: rust, livecheck, CI-published-bottle-commits

#203234 ghcup: build with GHC 9.10
  Formula/g/ghcup.rb
Labels: haskell, CI-no-bottles

#203225 cproto 4.7x
  .github/autobump.txt
  Formula/c/cproto.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#203226 qcli 1.4
  .github/autobump.txt
  Formula/q/qcli.rb
Labels: bump-formula-pr, ffmpeg, CI-published-bottle-commits, autobump

#203201 libxmp-lite 4.6.1
  .github/autobump.txt
  Formula/lib/libxmp-lite.rb
Labels: bump-formula-pr, CI-published-bottle-commits, autobump

#203221 libngspice,ngspice: rebuild (libngspice ngspice 44)
  Formula/lib/libngspice.rb
  Formula/n/ngspice.rb
Labels: ready to merge, CI-no-fail-fast, CI-published-bottle-commits, CI-checksum-change-confirmed

#203239 dhall-lsp-server: patch for GHC 9.6
  Formula/d/dhall-lsp-server.rb
Labels: haskell, CI-no-bottles

#203243 allureofthestars: add workaround to build with GHC 9.10
  Formula/a/allureofthestars.rb
Labels: haskell, CI-no-bottles

#203240 ghc@9.4: deprecate
  Formula/g/ghc@9.4.rb
Labels: legacy, formula deprecated, CI-syntax-only, long build

#203218 bc 1.08.0
  .github/autobump.txt
  Formula/b/bc.rb
Labels: bump-formula-pr, CI-no-fail-fast, CI-published-bottle-commits, autobump

#203244 yozefu 0.0.2 (new formula)
  .github/autobump.txt
  Formula/y/yozefu.rb
Labels: new formula, rust, automerge-skip, CI-published-bottle-commits, autobump, CI-skip-new-formulae

#203248 vgt 1.0.0 (new formula)
  .github/autobump.txt
  Formula/v/vgt.rb
Labels: go, new formula, automerge-skip, CI-published-bottle-commits, autobump

#203265 fzf-make 0.54.0
  Formula/f/fzf-make.rb
Labels: rust, CI-published-bottle-commits

#203235 streamrip 2.0.5 (new formula)
  Formula/s/streamrip.rb
  pypi_formula_mappings.json
Labels: python, new formula, ready to merge, CI-published-bottle-commits

#203246 ghc@9.10 9.10.1 (new formula)
  Aliases/ghc@9.10
  Formula/g/ghc@9.10.rb
  style_exceptions/binary_bootstrap_formula_urls_allowlist.json
Labels: new formula, CI-no-fail-fast, long build, CI-published-bottle-commits, CI-skip-new-formulae

#203268 mesheryctl 0.8.4
  Formula/m/mesheryctl.rb
Labels: go, CI-published-bottle-commits

#203135 rqlite: set version, commit hash etc build flags
  Formula/r/rqlite.rb
Labels: go, CI-published-bottle-commits

#203025 zabbix-cli: add shell completions, use PyPI sdist
  Formula/z/zabbix-cli.rb
Labels: python, rust, switch-to-pypi-source, CI-no-fail-fast, shell-completion, CI-published-bottle-commits

#203198 rhino 1.8.0
  .github/autobump.txt
  Formula/r/rhino.rb
Labels: livecheck, CI-no-fail-fast, CI-published-bottle-commits, autobump

#203167 lnav: add PRQL support
  Formula/l/lnav.rb
Labels: rust, CI-published-bottle-commits

#203282 pandoc: build with `ghc@9.10`
  Formula/p/pandoc.rb
Labels: haskell, ready to merge, CI-no-bottles

#203283 darcs: backport support for GHC 9.10
  Formula/d/darcs.rb
Labels: haskell, ready to merge, CI-no-bottles

#203284 bench: backport support for GHC 9.10
  Formula/b/bench.rb
Labels: haskell, ready to merge, CI-no-bottles

#203285 cryptol: build with `ghc@9.10`
  Formula/c/cryptol.rb
Labels: haskell, ready to merge, CI-no-bottles

#203293 moar 1.31.0
  Formula/m/moar.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#203292 hadolint: backport support for GHC 9.8
  Formula/h/hadolint.rb
Labels: haskell, CI-no-bottles

#203296 fzf-make 0.55.0
  Formula/f/fzf-make.rb
Labels: rust, CI-published-bottle-commits

#203281 hopenpgp-tools: workaround to build with `ghc@9.8`
  Formula/h/hopenpgp-tools.rb
Labels: haskell, CI-no-bottles

#203294 fourmolu: build with `ghc@9.10`
  Formula/f/fourmolu.rb
Labels: haskell, ready to merge, CI-no-bottles

#203297 hledger: build with `ghc@9.10`
  Formula/h/hledger.rb
Labels: haskell, ready to merge, CI-no-bottles

#203245 openapi-tui 0.10.0 (new formula)
  .github/autobump.txt
  Formula/o/openapi-tui.rb
Labels: new formula, rust, automerge-skip, CI-no-fail-fast, CI-published-bottle-commits, autobump

#203307 stylish-haskell: add upstream ref for GHC 9.10 support
  Formula/s/stylish-haskell.rb
Labels: haskell, CI-syntax-only

#203301 koka: switch to Cabal to build with GHC 9.10
  Formula/k/koka.rb
Labels: haskell, ready to merge, CI-no-bottles

#203306 dhall-lsp-server: backport support for GHC 9.8
  Formula/d/dhall-lsp-server.rb
Labels: haskell, CI-no-bottles

#203279 dhall*: backport support for GHC 9.10
  Formula/d/dhall-bash.rb
  Formula/d/dhall-json.rb
  Formula/d/dhall-toml.rb
  Formula/d/dhall-yaml.rb
  Formula/d/dhall.rb
Labels: haskell, ready to merge, CI-no-fail-fast, CI-no-bottles

#203308 ormolu: build with `ghc@9.10`
  Formula/o/ormolu.rb
Labels: haskell, CI-no-bottles

#203310 haskell-language-server: switch `ghc` to `ghc@9.10`
  Formula/h/haskell-language-server.rb
Labels: haskell, CI-no-bottles, long build

#203318 mise 2025.1.1
  Formula/m/mise.rb
Labels: rust, bump-formula-pr, CI-published-bottle-commits

#203211 python@3.13: remove unused Linux dependencies
  Formula/p/python@3.13.rb
Labels: CI-skip-recursive-dependents, CI-skip-dependents, CI-no-bottles, CI-no-fail-fast-deps

#203339 echidna: add upstream ref for GHC 9.8
  Formula/e/echidna.rb
Labels: haskell, CI-syntax-only

#203358 vespa-cli 8.459.67
  Formula/v/vespa-cli.rb
Labels: go, bump-formula-pr, CI-published-bottle-commits

#203361 hlint: add upstream ref for GHC 9.10/9.12
  Formula/h/hlint.rb
Labels: haskell, CI-no-bottles
